export const GOVERNMENT_ENTITY_SUPPLEMENTS: Record<string, string[]> = {
  "agriculture-commissioner": [
    "The Agriculture Commissioner's authority is broad but divided across several regulatory systems. The Texas Department of Agriculture administers weights and measures, pesticide registration and enforcement, agricultural marketing, rural-development programs and major nutrition programs, but it does not serve as the state's sole regulator of farms, ranches or food businesses. Animal health is primarily overseen by the Texas Animal Health Commission, environmental permits can fall to the Texas Commission on Environmental Quality, water rights are governed through separate state institutions, and meat or food-safety questions may involve state health agencies or federal regulators. That division matters when a public dispute is described simply as an 'agriculture' issue: the elected commissioner may administer one program while another agency holds the actual permitting or enforcement power.",
    "Accountability can be traced through agency rules, grant and nutrition-program records, pesticide and measurement enforcement actions, appropriations, procurement records and the commissioner's statewide election. Federal funding also creates an additional layer of oversight because programs such as school meals and certain agricultural grants operate under federal statutes and agency agreements. The commissioner can advocate for agricultural policy and administer programs assigned by the Legislature, but cannot independently change tax law, rewrite federal program conditions or direct another agency outside the department's statutory authority. For readers evaluating a claim about the office, the useful question is not simply whether agriculture is involved, but which statute or program assigns the commissioner responsibility for the specific decision.",
  ],
  "land-commissioner": [
    "The General Land Office sits at the intersection of public land management, mineral revenue, coastal policy, veterans programs and disaster recovery. Its land and mineral work is constrained by constitutional and statutory trust duties, particularly where state assets generate revenue for public education. The commissioner can negotiate leases, manage records and administer programs within delegated authority, but does not own those public assets personally and cannot redirect trust revenue for an unrelated purpose. Coastal work also overlaps with federal agencies, local governments and environmental regulators, while disaster-recovery programs frequently depend on federal grant conditions. Separating those roles helps explain why the GLO may administer a program without controlling every permitting, funding or local reconstruction decision connected to it.",
    "The office is unusually document-rich for accountability purposes. Land patents, surveys, mineral leases, coastal plans, veterans-program records, procurement documents, disaster-recovery grant materials and legislative appropriations all provide ways to test claims about performance and authority. Revenue from state lands can be economically important, but the commissioner's discretion remains bounded by the Texas Constitution, the Natural Resources Code and program-specific statutes. In disaster recovery, for example, the office may allocate or administer federally supported funds under approved plans while federal agencies define eligibility requirements and local governments carry out projects. When evaluating delays or spending disputes, readers should distinguish the GLO's administrative role from federal approval, local execution and legislative funding decisions rather than assigning the entire chain to one elected official.",
  ],
  "railroad-commission": [
    "Despite its historic name, the Railroad Commission's modern authority is concentrated in oil and gas, intrastate pipelines, certain natural-gas utilities, surface mining and alternative-fuel safety. It does not regulate Texas railroads, and it does not serve as the state's general environmental agency. Drilling permits, well completion, production reporting, plugging obligations and many pipeline-safety matters can fall within commission jurisdiction, while air and water pollution controls may involve TCEQ, federal interstate pipeline rules may involve federal regulators, and electric-utility regulation largely belongs to the Public Utility Commission. The boundaries are important because an oilfield incident can trigger several legal regimes at once, with the commission responsible for one part of the response and another agency responsible for another.",
    "The three commissioners act through an elected multi-member commission rather than as a single executive administrator. Public meetings, rulemakings, enforcement dockets, permitting records, well and production databases, plugging programs, appropriations and campaign disclosures provide separate accountability channels. A commissioner can vote on rules, enforcement matters and agency policy within statutory authority, but cannot independently change the Natural Resources Code or take over federal jurisdiction. The commission's role in natural-gas utility rates is also narrower than the Public Utility Commission's role in much of the electric market. For readers assessing responsibility for energy policy, distinguishing upstream oil-and-gas regulation, pipeline safety, gas-utility jurisdiction, electric-market regulation and environmental permitting avoids attributing unrelated powers to the Railroad Commission simply because the dispute concerns energy.",
  ],
  "state-board-of-education": [
    "The State Board of Education is a statewide policymaking body, but it does not operate Texas school districts. Its most visible powers include adopting the Texas Essential Knowledge and Skills curriculum standards, acting on instructional-materials processes established by law, setting certain graduation requirements and exercising responsibilities connected to the Permanent School Fund. Local school boards hire superintendents, adopt local budgets and make many operational decisions; the Texas Education Agency administers statewide programs and accountability systems; and the Legislature can change the statutory framework governing both entities. That division is central to understanding disputes over curriculum, textbooks, testing, school finance or district operations, because the board's authority varies significantly by subject.",
    "The board's fifteen members are elected from districts, while the governor designates a chair from among them under state law. Its decisions are made collectively in public meetings rather than by individual members acting alone. Meeting agendas, recorded votes, proposed curriculum standards, instructional-material reviews, Permanent School Fund materials and Education Code provisions give readers primary records for evaluating claims about the board. The board can debate and adopt standards within its assigned jurisdiction, but it cannot appropriate state education funding, directly manage a local classroom or unilaterally rewrite statutes passed by the Legislature. When a controversy is described as a 'State Board of Education decision,' the useful check is whether the matter actually concerns board-adopted standards or materials, or instead belongs to TEA, a local district, the Legislature or another education authority.",
  ],
  "supreme-court": [
    "The Supreme Court of Texas is the state's court of last resort for civil and juvenile matters, but it does not function as a general supervisor that can decide any political dispute presented to it. Cases must fall within constitutional and statutory jurisdiction and satisfy procedural requirements for review. The court may interpret the Texas Constitution and statutes, review civil judgments, answer certain certified questions and exercise rulemaking or administrative authority assigned by law. Criminal cases generally terminate in the separate Court of Criminal Appeals, while federal constitutional or federal-law issues may ultimately be reviewable in the federal courts. That divided appellate structure is unusual enough that identifying the correct court is essential before attributing a Texas legal ruling to the 'state supreme court.'",
    "Judicial accountability is also different from executive accountability. The nine justices are elected statewide to six-year terms, but individual cases are decided through the judicial process rather than campaign platforms or legislative votes. Opinions, orders, briefs, oral-argument recordings, docket entries, procedural rules and judicial-administration records provide the primary evidence for what the court actually held or changed. A majority opinion establishes the court's judgment in a case; concurrences and dissents can explain competing reasoning without controlling the outcome. The court can invalidate government action that conflicts with controlling law, but it cannot appropriate money or enact a replacement statute. If lawmakers disagree with a statutory interpretation, they may be able to amend the statute prospectively, subject to constitutional limits and the facts of later cases.",
  ],
  "court-of-criminal-appeals": [
    "The Court of Criminal Appeals is Texas's highest court for criminal law, including discretionary criminal appeals and post-conviction habeas matters within its jurisdiction. It is separate from the Supreme Court of Texas, which handles civil and juvenile matters. The court also receives direct review in death-penalty cases under Texas law and may issue writs authorized by the Constitution and statutes. That does not mean every criminal case is automatically heard by the court: many cases end in the intermediate courts of appeals unless discretionary review is granted, and post-conviction claims follow specialized procedural rules. Federal habeas review is a separate process in the federal judiciary and should not be confused with state habeas proceedings before Texas courts.",
    "The nine judges are elected statewide, including a presiding judge, but the court's authority is exercised through cases, rules and judicial orders rather than executive directives. Opinions, petitions for discretionary review, habeas filings, oral arguments, docket information and the Code of Criminal Procedure provide primary records for evaluating a claim about the court. The judges can interpret criminal statutes and constitutional protections within cases properly before them, but cannot prosecute defendants, direct local district attorneys or rewrite a criminal statute outside the judicial process. When a conviction, sentence or procedural rule is disputed, readers should distinguish the trial court, intermediate court of appeals, Court of Criminal Appeals and any later federal review so responsibility is assigned to the institution that actually made the controlling decision.",
  ],
};

export function getGovernmentEntitySupplements(slug: string) {
  return GOVERNMENT_ENTITY_SUPPLEMENTS[slug] ?? [];
}
