export type KtrEvergreenFacebookPost = {
  category: string;
  title: string;
  message: string;
};

// Evergreen, discussion-first posts for KeepTXRed. These are intentionally
// phrased as questions or neutral historical/civic prompts so they can stand
// alone on Facebook without requiring an article link or asserting a disputed
// conclusion as fact.
export const KTR_EVERGREEN_FACEBOOK_POSTS: readonly KtrEvergreenFacebookPost[] = [
  { category: "Texas politics", title: "Local control", message: "Where should Texas draw the line between local control and statewide rules? What issue best shows the tension?" },
  { category: "Texas politics", title: "Property taxes", message: "What would make the biggest real-world difference to Texas property-tax bills: lower rates, tighter spending limits, higher exemptions, or something else?" },
  { category: "Texas politics", title: "School choice", message: "What should Texas parents have the most control over in their child’s education?" },
  { category: "Texas politics", title: "Border policy", message: "Which border-policy outcome should Texas leaders prioritize most: security, faster legal processing, trade efficiency, local costs, or something else?" },
  { category: "Texas politics", title: "Energy policy", message: "What should Texas prioritize most for long-term energy reliability: more natural gas, more nuclear, more renewables, more storage, or a broader mix?" },
  { category: "Texas politics", title: "State spending", message: "If Texas had to cut one area of state spending and protect another, what would you choose?" },
  { category: "Texas politics", title: "Election rules", message: "Which election rule matters most for public confidence: voter ID, paper records, faster counting, stronger audits, easier registration, or something else?" },
  { category: "Texas politics", title: "Legislative priorities", message: "If the Texas Legislature could pass only ONE major reform next session, what should it be?" },

  { category: "Constitution", title: "First Amendment", message: "Which First Amendment freedom do you think Americans take most for granted today?" },
  { category: "Constitution", title: "Second Amendment", message: "What should responsible gun ownership mean in practice beyond simply following the law?" },
  { category: "Constitution", title: "Tenth Amendment", message: "What issue is the best modern example of why the Tenth Amendment still matters?" },
  { category: "Constitution", title: "Federalism", message: "When Washington and Texas disagree, which kinds of decisions should clearly belong to the states?" },
  { category: "Constitution", title: "Originalism", message: "When judges interpret the Constitution, how much weight should the original public meaning carry versus modern circumstances?" },
  { category: "Constitution", title: "Electoral College", message: "Keep it, reform it, or replace it: what is your view of the Electoral College and why?" },
  { category: "Constitution", title: "Executive power", message: "Do presidents rely too much on executive orders today? Where should Congress draw the line?" },
  { category: "Constitution", title: "Privacy", message: "Which privacy protection needs the most attention today: phones, financial data, location tracking, cameras, or government databases?" },

  { category: "Texas history", title: "Alamo history", message: "What is one Alamo fact or story you think every Texan should know?" },
  { category: "Texas history", title: "Texas Republic", message: "Which part of the Republic of Texas era deserves more attention in Texas classrooms?" },
  { category: "Texas history", title: "Gonzales", message: "What does ‘Come and Take It’ mean to Texans today: history, attitude, political symbol, or all three?" },
  { category: "Texas history", title: "Sam Houston", message: "Which Sam Houston decision had the biggest long-term impact on Texas?" },
  { category: "Texas history", title: "Texas Rangers", message: "Which chapter of Texas Rangers history should be taught more fully — the celebrated parts, the controversial parts, or both?" },
  { category: "Texas history", title: "Spindletop", message: "How much of modern Texas was shaped by Spindletop and the oil boom that followed?" },
  { category: "Texas history", title: "Texas frontier", message: "Which Texas frontier story best captures the grit people still associate with the state?" },
  { category: "Texas history", title: "Texas courthouses", message: "Which Texas county courthouse is the most impressive you’ve seen?" },
  { category: "Texas history", title: "Texas monuments", message: "What Texas monument or landmark gives you the strongest sense of state history?" },
  { category: "Texas history", title: "Military Texans", message: "Which Texan from U.S. military history deserves to be better known nationally?" },

  { category: "Economy", title: "Texas economy", message: "What is the single biggest reason businesses keep moving to or expanding in Texas?" },
  { category: "Economy", title: "Small business", message: "What is the biggest obstacle facing a small Texas business right now: taxes, regulation, labor, insurance, rent, financing, or something else?" },
  { category: "Economy", title: "Inflation", message: "Which everyday expense has changed your household budget the most over the last few years?" },
  { category: "Economy", title: "Housing", message: "What is driving housing costs most where you live in Texas: land, construction, taxes, insurance, zoning, demand, or interest rates?" },
  { category: "Economy", title: "Deregulation", message: "Where has deregulation clearly helped consumers — and where do you think guardrails still matter?" },
  { category: "Economy", title: "Minimum wage", message: "Should wage policy be set nationally, by states, locally, or mostly by the market?" },
  { category: "Economy", title: "National debt", message: "If Washington got serious about the national debt, where would you start: spending cuts, entitlement reform, tax changes, growth, or all of the above?" },
  { category: "Economy", title: "Tariffs", message: "Are tariffs worth higher prices if they bring more manufacturing back to America? Where is your line?" },
  { category: "Economy", title: "Right to work", message: "What does worker freedom mean to you: the right to organize, the right not to join, both, or something else?" },
  { category: "Economy", title: "Gig economy", message: "For gig workers, what matters more: flexibility or traditional employee protections?" },

  { category: "Energy", title: "Texas grid", message: "What change would make you most confident in the Texas electric grid before the next major freeze or heat wave?" },
  { category: "Energy", title: "Oil and gas", message: "How should Texas balance oil-and-gas growth with land, water, and air concerns?" },
  { category: "Energy", title: "Nuclear power", message: "Should Texas build more nuclear power plants? Why or why not?" },
  { category: "Energy", title: "Wind and solar", message: "What role should wind and solar play in the Texas grid ten years from now?" },
  { category: "Energy", title: "Energy independence", message: "What does American energy independence actually require in 2026?" },
  { category: "Energy", title: "EV policy", message: "Should governments set EV adoption targets, or should consumers and the market decide the pace?" },
  { category: "Energy", title: "Transmission", message: "Texas is growing fast. What matters more for the grid right now: more generation or more transmission?" },
  { category: "Energy", title: "Emergency power", message: "After recent Texas weather disasters, what backup-power lesson do you think every household should take seriously?" },

  { category: "Education", title: "Civic education", message: "What is one thing every Texas high-school graduate should understand about the Constitution before receiving a diploma?" },
  { category: "Education", title: "Phonics", message: "Parents and teachers: what reading method have you seen work best for kids who are struggling?" },
  { category: "Education", title: "Life skills", message: "What practical life skill should every Texas public school teach before graduation?" },
  { category: "Education", title: "College alternatives", message: "For an 18-year-old today, when is trade school or an apprenticeship a better choice than a four-year degree?" },
  { category: "Education", title: "Homeschooling", message: "Families who homeschool: what was the biggest reason you chose it — and what surprised you afterward?" },
  { category: "Education", title: "Charter schools", message: "What should Texas measure when deciding whether a charter school is succeeding?" },
  { category: "Education", title: "Parents rights", message: "Which school decisions should always require meaningful parental input?" },
  { category: "Education", title: "Student debt", message: "What should young Texans know about college debt before signing their first student-loan paperwork?" },

  { category: "Family and community", title: "Family dinner", message: "How many nights a week does your family actually sit down for dinner together — and does it still matter?" },
  { category: "Family and community", title: "Chores", message: "What chore taught you the most responsibility when you were growing up?" },
  { category: "Family and community", title: "Grandparents", message: "What lesson, saying, recipe, or tradition did your grandparents pass down that you still keep?" },
  { category: "Family and community", title: "Manners", message: "Which old-fashioned manners should make a comeback?" },
  { category: "Family and community", title: "Volunteerism", message: "What local volunteer group in your Texas community deserves more recognition?" },
  { category: "Family and community", title: "Youth sports", message: "What should youth sports teach first: winning, discipline, teamwork, resilience, or something else?" },
  { category: "Family and community", title: "Digital childhood", message: "What is one phone or social-media rule you think more families should adopt?" },
  { category: "Family and community", title: "Community traditions", message: "What local tradition makes your Texas town feel like a real community?" },

  { category: "Media literacy", title: "Headline framing", message: "What is the fastest way you spot a headline that is trying to persuade instead of inform?" },
  { category: "Media literacy", title: "Primary sources", message: "Before sharing a political story, do you look for the original speech, bill, court filing, or data? Which source do you trust most?" },
  { category: "Media literacy", title: "Corrections", message: "Should news outlets make corrections as prominent as the original mistake?" },
  { category: "Media literacy", title: "Polls", message: "What makes you trust or distrust a political poll: sample size, wording, sponsor, methodology, track record, or something else?" },
  { category: "Media literacy", title: "Algorithms", message: "How much do you think social-media and search algorithms shape the political news people see?" },
  { category: "Media literacy", title: "Citizen journalism", message: "Has citizen journalism made local news better, worse, or simply faster?" },
  { category: "Media literacy", title: "Fact checks", message: "What should a trustworthy fact-check always show its readers?" },
  { category: "Media literacy", title: "Anonymous sources", message: "When should a news organization use anonymous sources — and when should readers be skeptical?" },

  { category: "Self reliance", title: "Texas homestead", message: "What self-reliance skill should every Texan know, even if they live in the suburbs?" },
  { category: "Self reliance", title: "Grid outage", message: "If the power went out for three days, what item would you be happiest you already had?" },
  { category: "Self reliance", title: "Water storage", message: "How much emergency water do you keep at home — if any?" },
  { category: "Self reliance", title: "Ham radio", message: "Any ham-radio operators here? What made you get licensed, and is it still worth learning?" },
  { category: "Self reliance", title: "Truck essentials", message: "What is one thing every Texan should keep in the truck year-round?" },
  { category: "Self reliance", title: "First aid", message: "What first-aid skill do you think everyone should know before an emergency happens?" },
  { category: "Self reliance", title: "Backyard food", message: "If you had to produce one food at home, would you choose a garden, fruit trees, chickens, or something else?" },
  { category: "Self reliance", title: "Storm prep", message: "What is the Texas storm-prep purchase you made once and have never regretted?" },

  { category: "Foreign policy", title: "China", message: "What China-related issue should concern Americans most: trade, Taiwan, technology, supply chains, military power, or something else?" },
  { category: "Foreign policy", title: "Deterrence", message: "What does ‘peace through strength’ require in practice today?" },
  { category: "Foreign policy", title: "Defense manufacturing", message: "Should Texas push harder to bring defense manufacturing and critical supply chains into the state?" },
  { category: "Foreign policy", title: "Foreign aid", message: "What conditions should Congress attach to U.S. foreign aid?" },
  { category: "Foreign policy", title: "Navy", message: "How important is U.S. naval power to everyday American economic security?" },
  { category: "Foreign policy", title: "Trade", message: "Which products or industries are too strategically important for America to depend heavily on foreign suppliers?" },
  { category: "Foreign policy", title: "Cybersecurity", message: "Which part of U.S. infrastructure worries you most in a major cyberattack: power, water, banking, hospitals, communications, or transportation?" },
  { category: "Foreign policy", title: "Intervention", message: "What test should the United States meet before committing troops to a foreign conflict?" },

  { category: "Texas culture", title: "High school football", message: "What is the best Texas high-school football tradition in your town?" },
  { category: "Texas culture", title: "Stockyards", message: "Fort Worth Stockyards fans: what is the one thing a first-time visitor should not miss?" },
  { category: "Texas culture", title: "Texas BBQ", message: "Brisket debate: bark, smoke ring, tenderness, seasoning, or fat render — what matters most?" },
  { category: "Texas culture", title: "Honky tonks", message: "What Texas honky-tonk belongs on every country-music fan’s bucket list?" },
  { category: "Texas culture", title: "Texas brands", message: "What independent Texas brand has earned your loyalty?" },
  { category: "Texas culture", title: "Rodeo", message: "What is your favorite rodeo tradition or event?" },
  { category: "Texas culture", title: "Texas trucks", message: "What makes a truck a ‘Texas truck’ to you: capability, ranch use, road trips, style, or just attitude?" },
  { category: "Texas culture", title: "Texas museums", message: "Which Texas museum has the one artifact or exhibit every Texan should see?" },
  { category: "Texas culture", title: "A&M traditions", message: "Aggies: which Texas A&M tradition best explains the school to somebody who has never been there?" },
  { category: "Texas culture", title: "Sunday drive", message: "What historic Texas town makes the best Sunday drive destination?" },
  { category: "Texas culture", title: "Roughneck history", message: "Do you have a roughneck, refinery, pipeline, or oilfield story in your family?" },
  { category: "Texas culture", title: "Western films", message: "What classic Western do you think every Texan should watch at least once?" },
  { category: "Texas culture", title: "Chuckwagon", message: "What old-school Texas or trail recipe still deserves a place at the table today?" },

  { category: "Faith and civic life", title: "Religious liberty", message: "Where do you think the hardest modern religious-liberty questions are showing up: schools, workplaces, healthcare, public spaces, or elsewhere?" },
  { category: "Faith and civic life", title: "Church history", message: "What historic Texas church or congregation has the most interesting story in your area?" },
  { category: "Faith and civic life", title: "Service", message: "Which faith-based charity or local ministry in Texas is doing work more people should know about?" },
  { category: "Faith and civic life", title: "Stewardship", message: "What does good stewardship of Texas land and natural resources look like to you?" },
  { category: "Faith and civic life", title: "Founding ideas", message: "Which idea from the American founding — liberty, self-government, religious freedom, property rights, civic duty — matters most today?" },
  { category: "Faith and civic life", title: "Western civilization", message: "Which book, speech, law, or historical event best explains the Western idea of individual liberty?" },
] as const;
