import { describe, expect, it } from "vitest";
import { classifySportsText, sportsKindForText } from "@/lib/sports-taxonomy";

describe("sports taxonomy", () => {
  it("classifies team, league, city and sport from a pro story", () => {
    const result = classifySportsText("Houston Texans NFL injury report from NRG Stadium in Houston");
    expect(result.teams).toContain("texans"); expect(result.leagues).toContain("nfl"); expect(result.topics).toContain("football"); expect(result.topics).toContain("injuries"); expect(result.cities).toContain("houston"); expect(sportsKindForText("Houston Texans NFL injury report")).toBe("sports-nfl");
  });
  it("recognizes college recruiting and NIL coverage", () => { const result = classifySportsText("Texas Longhorns recruiting collective discusses NIL revenue sharing in Austin"); expect(result.teams).toContain("longhorns"); expect(result.leagues).toContain("cfb"); expect(result.topics).toEqual(expect.arrayContaining(["recruiting", "nil", "college"])); });
  it("recognizes Texas sports business and policy stories", () => { const text = "Texas lawmakers debate sports betting legislation in Dallas"; const result = classifySportsText(text); expect(result.topics).toContain("business-policy"); expect(result.isSports).toBe(true); expect(sportsKindForText(text)).toBe("sports-policy"); });
  it("recognizes motorsports without requiring a team", () => { const text = "Formula 1 returns to Circuit of the Americas in Austin as COTA prepares for race weekend"; const result = classifySportsText(text); expect(result.topics).toContain("motorsports"); expect(result.cities).toContain("austin"); expect(sportsKindForText(text)).toBe("sports-motorsports"); });
  it("supports cross-posting stories that mention multiple teams", () => { const result = classifySportsText("The Houston Astros and Texas Rangers meet in another Lone Star Series matchup"); expect(result.teams.sort()).toEqual(["astros", "rangers"]); expect(result.topics).toEqual(expect.arrayContaining(["baseball", "rivalries"])); });
  it("does not turn generic university coverage into college sports", () => { const tamu = classifySportsText("Texas A&M professors challenge classroom restrictions in federal court"); const tech = classifySportsText("Texas Tech researchers publish a new water study for West Texas communities"); expect(tamu.teams).not.toContain("texas-am"); expect(tamu.isSports).toBe(false); expect(tech.teams).not.toContain("texas-tech"); expect(tech.isSports).toBe(false); });
  it("does not confuse Texas A&M system campuses with the Aggies", () => { const result = classifySportsText("Texas A&M-Texarkana opens a sports complex with a 6,000-seat football stadium"); expect(result.teams).not.toContain("texas-am"); expect(result.topics).toEqual(expect.arrayContaining(["football", "stadiums"])); expect(result.isSports).toBe(true); });
  it("does not treat resident Texans or political recruiting language as sports", () => { const residents = classifySportsText("Texans across the state are preparing for tax-free weekend"); const politics = classifySportsText("Texas lawmakers recruit rivals for a new policy coalition"); expect(residents.teams).not.toContain("texans"); expect(residents.isSports).toBe(false); expect(politics.topics).toEqual(expect.arrayContaining(["recruiting", "business-policy"])); expect(politics.isSports).toBe(false); });
  it("does not infer a team from a venue-only entertainment story", () => { const result = classifySportsText("Ringling returns to Houston with an animal-free circus at NRG Stadium"); expect(result.teams).not.toContain("texans"); expect(result.isSports).toBe(false); });
  it("recognizes an ambiguous Rangers headline when baseball context is present", () => { const text = "Rangers Win Fourth Straight Behind deGrom as AL West Race Tightens"; const result = classifySportsText(text); expect(result.teams).toContain("rangers"); expect(result.leagues).toContain("mlb"); expect(result.topics).toContain("baseball"); expect(result.isSports).toBe(true); });
  it("does not confuse the Texas Rangers law-enforcement agency with the MLB club", () => { const text = "Texas Police vs. Sheriff vs. Constable vs. DPS vs. Texas Rangers: Who Does What?"; const result = classifySportsText(text); expect(result.teams).not.toContain("rangers"); expect(result.leagues).not.toContain("mlb"); expect(result.isSports).toBe(false); expect(sportsKindForText(text)).toBeNull(); });
  it("keeps city-specific NBA and athletics stories in Sports", () => { const camp = classifySportsText("NBA Rookie Kingston Flemings Comes Home to San Antonio for a Basketball Camp"); const tomball = classifySportsText("Tomball ISD Plans Athletic Upgrades as Extreme Heat Reshapes Texas Sports"); expect(camp.leagues).toContain("nba"); expect(camp.cities).toContain("san antonio"); expect(camp.isSports).toBe(true); expect(tomball.isSports).toBe(true); });
  it("does not turn co-branded university merchandise into college sports", () => { const result = classifySportsText("Buc-ee's and Texas A&M Put Two Texas Icons on the Same Shirt"); expect(result.teams).not.toContain("texas-am"); expect(result.isSports).toBe(false); });
  it("does not treat media ethics stories as Sports just because World Cup tickets are mentioned", () => { const result = classifySportsText("Houston anchor returns to KPRC after complimentary World Cup tickets review found no influence on journalism or reporting"); expect(result.teams).toEqual([]); expect(result.isSports).toBe(false); });
  it("does not classify school security from an incidental athletic-event adjective", () => { const result = classifySportsText("HISD adds armed officers and game-day rules as students return; security includes athletic-event entry rules in Houston"); expect(result.isSports).toBe(false); });
  it("recognizes Spurs arena funding as team-linked Sports policy", () => { const result = classifySportsText("San Antonio council debates Spurs arena funding and ballot questions"); expect(result.teams).toContain("spurs"); expect(result.leagues).toContain("nba"); expect(result.topics).toContain("stadiums"); expect(result.isSports).toBe(true); });
});
