import type {TexasEquityGrowthResult} from "@/types/equity/TexasEquityGrowth";
export const formatEquityCurrency=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
export const explainCurrentEquity=(r:TexasEquityGrowthResult)=>`Your current estimated home equity is ${formatEquityCurrency(r.currentEquity.equityAmount)} (${(r.currentEquity.equityPercentage*100).toFixed(1)}% ownership).`;
export const explainFutureEquity=(r:TexasEquityGrowthResult)=>`After ${r.input.projectionYears} years, projected equity could grow to ${formatEquityCurrency(r.futureProjection.futureEquity)}.`;
export const explainAppreciationGrowth=(r:TexasEquityGrowthResult)=>`Estimated property appreciation contributes approximately ${formatEquityCurrency(r.wealthAnalysis.appreciationGain)}.`;
export const explainPrincipalReduction=(r:TexasEquityGrowthResult)=>`Mortgage principal reduction contributes approximately ${formatEquityCurrency(r.wealthAnalysis.principalReduction)}.`;
export const explainAnnualGrowth=(r:TexasEquityGrowthResult)=>`Projected equity growth averages approximately ${formatEquityCurrency(r.wealthAnalysis.annualEquityGrowth)} per year.`;
export function calculateEquityGrowthScore(r:TexasEquityGrowthResult){let score=50;if(r.wealthAnalysis.totalEquityGrowth>100000)score+=20;if(r.wealthAnalysis.totalEquityGrowth>250000)score+=15;if(r.futureProjection.futureEquity>r.input.currentHomeValue*.5)score+=10;if(r.currentEquity.equityPercentage>.3)score+=5;return Math.min(100,score)}
export const explainOwnershipMilestone=(r:TexasEquityGrowthResult)=>{const p=r.futureProjection.futureHomeValue?r.futureProjection.futureEquity/r.futureProjection.futureHomeValue:0;return p>=.75?"You are projected to have a very strong ownership position.":p>=.5?"You are projected to build significant home ownership.":p>=.25?"You are steadily building homeowner equity.":"You are in the early stages of building equity."};
export const generateEquityRecommendation=(r:TexasEquityGrowthResult)=>calculateEquityGrowthScore(r)>=85?"Your home is projected to become a significant wealth-building asset.":calculateEquityGrowthScore(r)>=70?"Your property shows strong potential for long-term equity growth.":"Your equity position is developing.";
export const generateEquitySEODescription=(location="Texas")=>`Use this ${location} home equity calculator to estimate current equity, future home value, appreciation growth, and long-term homeowner wealth.`;
