import type {TexasHomeAffordabilityResult} from "@/types/homeAffordability/TexasHomeAffordability";
export const formatAffordabilityCurrency=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
export const explainMaximumAffordability=(r:TexasHomeAffordabilityResult)=>`Based on your income and debt profile, your estimated maximum home price is ${formatAffordabilityCurrency(r.homePriceAnalysis.maximumHomePrice)}.`;
export const explainComfortableAffordability=(r:TexasHomeAffordabilityResult)=>`A more comfortable purchase range is approximately ${formatAffordabilityCurrency(r.homePriceAnalysis.comfortableHomePrice)}.`;
export const explainDebtRatios=(r:TexasHomeAffordabilityResult)=>`Your projected housing debt ratio is approximately ${Math.round(r.paymentAnalysis.futureDebtRatio*100)}%.`;
export const explainAffordabilityScore=(r:TexasHomeAffordabilityResult)=>r.score.rating==="excellent"?"Your financial profile appears strong.":r.score.rating==="comfortable"?"This purchase appears reasonably aligned.":r.score.rating==="stretch"?"This purchase may reduce financial flexibility.":"This purchase may create significant budget pressure.";
export const generateAffordabilityRecommendation=(r:TexasHomeAffordabilityResult)=>r.score.rating==="excellent"?"Your profile supports a strong home purchase position.":r.score.rating==="comfortable"?"Your estimated purchase range appears balanced.":r.score.rating==="stretch"?"Consider a lower purchase price or additional savings.":"Consider improving debt and savings before buying.";
export const calculateBuyerReadinessScore=(r:TexasHomeAffordabilityResult)=>Math.min(100,r.score.score+(r.input.buyer.downPayment>=r.homePriceAnalysis.maximumHomePrice*.2?5:0)+(r.paymentAnalysis.currentDebtRatio<.15?5:0));
export const generateAffordabilitySEODescription=(location="Texas")=>`Use this ${location} home affordability calculator to estimate how much house you can afford based on income, debts, mortgage rates, property taxes, and insurance.`;
