import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "What is a Class A CDL in Texas?", answer: "A Class A CDL generally authorizes a combination of vehicles with a gross combination weight rating of 26,001 pounds or more when the vehicle or vehicles being towed have a gross vehicle weight rating above 10,000 pounds." },
  { question: "What is a Class B CDL in Texas?", answer: "A Class B CDL generally authorizes a single vehicle rated at 26,001 pounds or more, including that vehicle towing a unit rated at 10,000 pounds or less, and certain large passenger vehicles." },
  { question: "When is a Class C CDL required?", answer: "A Class C CDL is generally required for a vehicle that does not meet Class A or B weight thresholds but is designed to transport 16 to 23 people including the driver, or carries hazardous materials requiring placards." },
  { question: "Does a higher CDL class automatically include every endorsement?", answer: "No. A Class A holder may operate lesser vehicle classes, but passenger, school bus, tanker, hazardous-materials, and double or triple trailer operations may require separate endorsements and may still be limited by restrictions." },
];

function CdlClassesPage() {
  return (
    <main>
      <HubBreadcrumbs current="Texas CDL Classes Explained" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Commercial driver licensing</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight sm:text-5xl">Texas CDL Classes Explained: Class A, B and C</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Use vehicle weight ratings, trailer ratings, passenger capacity, and cargo—not a job title—to determine which Texas commercial driver license class applies.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/dmv/cdl" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Complete Texas CDL guide</a><a href="/dmv/cdl-endorsements" className="rounded-md border px-5 py-3 text-sm font-semibold">CDL endorsements</a></div></div></section>
      <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
        <section><h2 className="text-3xl font-bold">The ratings that determine CDL class</h2><p className="mt-4">Texas DPS uses the vehicle manufacturer's gross vehicle weight rating, the combined ratings of a power unit and trailer, passenger design capacity, and hazardous-materials use. Actual scale weight can matter in enforcement, but choosing a license class normally begins with the ratings shown on the vehicle and trailer certification labels.</p></section>
        <section><h2 className="text-3xl font-bold">Texas CDL class comparison</h2><div className="mt-6 overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-4 py-3">Class</th><th className="px-4 py-3">Core rule</th><th className="px-4 py-3">Typical vehicles</th></tr></thead><tbody className="divide-y"><tr><td className="px-4 py-3 font-bold">A</td><td className="px-4 py-3">Combination rated at least 26,001 pounds with a towed unit above 10,000 pounds</td><td className="px-4 py-3">Tractor-trailers, heavy truck-and-trailer combinations</td></tr><tr><td className="px-4 py-3 font-bold">B</td><td className="px-4 py-3">Single vehicle rated at least 26,001 pounds, towing 10,000 pounds or less</td><td className="px-4 py-3">Straight trucks, large buses, dump trucks</td></tr><tr><td className="px-4 py-3 font-bold">C</td><td className="px-4 py-3">Outside Class A or B, but regulated by passenger capacity or placarded hazardous materials</td><td className="px-4 py-3">Certain small buses, vans, and hazmat vehicles</td></tr></tbody></table></div></section>
        <section><h2 className="text-3xl font-bold">Class A CDL</h2><p className="mt-4">Class A covers the heaviest combinations. The key is that the combination reaches 26,001 pounds or more and the towed unit is rated above 10,000 pounds. A properly endorsed and unrestricted Class A holder may generally operate Class B and C vehicles, but not motorcycles.</p><p className="mt-4">Common Class A restrictions arise when the skills test is completed without a manual transmission, full air brakes, or a tractor-trailer connection. The tested vehicle can therefore affect the authority printed on the license.</p></section>
        <section><h2 className="text-3xl font-bold">Class B CDL</h2><p className="mt-4">Class B is built around a heavy single vehicle. It may tow a unit rated at 10,000 pounds or less. Many straight trucks and buses fall here, although passenger service also requires the appropriate endorsement and testing.</p></section>
        <section><h2 className="text-3xl font-bold">Class C CDL</h2><p className="mt-4">Class C applies when a commercial vehicle does not meet Class A or B weight thresholds but is designed for 16 to 23 occupants including the driver, or transports hazardous materials that require placarding. The correct endorsement is still required.</p></section>
        <section><h2 className="text-3xl font-bold">Commercial versus non-commercial Class A and B</h2><p className="mt-4">Texas also issues non-commercial Class A and B licenses to some drivers who operate heavy vehicles but qualify for a CDL exemption or are not engaged in CDL-regulated operation. Recreational vehicles used personally, certain farm operations, emergency vehicles, and other narrow categories may fit this structure. Never assume that a CDL exemption means a standard Class C license is sufficient.</p></section>
        <section className="rounded-xl border bg-muted/20 p-6"><h2 className="text-2xl font-bold">Before applying</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>Record the GVWR of the power unit and each trailer.</li><li>Confirm the GCWR and the rating of the towed unit.</li><li>Check passenger design capacity.</li><li>Determine whether hazardous materials require placards.</li><li>Identify needed endorsements and likely restrictions.</li><li>Confirm whether an exemption applies to the operation, not merely the employer.</li></ul></section>
        <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
        <p className="border-t pt-8 text-sm text-muted-foreground">Confirm the current class, endorsement, permit, medical, and testing rules with Texas DPS before operating a commercial vehicle.</p>
      </article>
    </main>
  );
}

export const Route = createFileRoute("/dmv/cdl-classes")({
  head: () => { const seo = buildSeo({ title: "Texas CDL Classes Explained: Class A, B and C", description: "Compare Texas Class A, Class B and Class C commercial driver licenses using vehicle weight, trailer, passenger and hazardous-material rules.", path: "/dmv/cdl-classes", type: "article", keywords: "Texas CDL classes, Class A CDL Texas, Class B CDL Texas, Class C CDL Texas" }); return { meta: seo.meta, links: seo.links, scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas CDL Classes Explained", url: `${SITE_URL}/dmv/cdl-classes` }) }, { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) }] }; },
  component: CdlClassesPage,
});