import { createFileRoute, Link, notFound } from '@tanstack/react-router';
import { supabase } from '@/integrations/supabase/client';
import { SITE_URL } from '@/lib/bills';
import { publicBillPath } from '@/lib/bill-public-path';

const db = supabase as any;
export const Route = createFileRoute('/texas-legislature/sessions/$sessionSlug')({
  loader: async ({ params }) => { const match = /^(\d+)([a-z0-9]+)$/i.exec(params.sessionSlug); if (!match) throw notFound(); const { data: session, error } = await db.from('legislative_sessions').select('*').eq('legislature_number', Number(match[1])).eq('session_code', match[2].toUpperCase()).maybeSingle(); if (error) throw error; if (!session) throw notFound(); const { data: bills, error: billsError } = await db.from('bills').select('*').eq('legislature_number', session.legislature_number).eq('session_code', session.session_code).order('last_action_date', { ascending: false }).limit(100); if (billsError) throw billsError; return { session, bills: bills ?? [] }; },
  head: ({ loaderData }) => { if (!loaderData) return {}; const canonical = `${SITE_URL}/texas-legislature/sessions/${loaderData.session.legislature_number}${loaderData.session.session_code.toLowerCase()}`; return { meta: [{ title: `${loaderData.session.session_name} | KeepTXRed` }, { name: 'description', content: `Bills, committees, dates, and official records for the ${loaderData.session.session_name}.` }], links: [{ rel: 'canonical', href: canonical }], scripts: [{ type: 'application/ld+json', children: JSON.stringify({ '@context': 'https://schema.org', '@graph': [{ '@type': ['Event','CollectionPage'], name: loaderData.session.session_name, startDate: loaderData.session.start_date, endDate: loaderData.session.end_date, url: canonical, location: { '@type': 'AdministrativeArea', name: 'Texas' }, organizer: { '@type': 'GovernmentOrganization', name: 'Texas Legislature', url: 'https://capitol.texas.gov/' } }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL }, { '@type': 'ListItem', position: 2, name: 'Texas Legislature', item: `${SITE_URL}/texas-legislature` }, { '@type': 'ListItem', position: 3, name: 'Sessions', item: `${SITE_URL}/texas-legislature/sessions` }, { '@type': 'ListItem', position: 4, name: loaderData.session.session_name, item: canonical }] }] }) }] }; }, component: SessionPage,
});
function SessionPage() { const { session, bills } = Route.useLoaderData(); return <main className="mx-auto max-w-6xl px-4 py-10"><nav className="text-sm text-muted-foreground"><Link to="/">Home</Link> / <Link to="/texas-legislature">Texas Legislature</Link> / <Link to="/texas-legislature/sessions">Sessions</Link> / {session.session_name}</nav><header className="mt-6 rounded-2xl border bg-card p-8"><h1 className="text-4xl font-bold">{session.session_name}</h1><p className="mt-3 text-muted-foreground">{[session.start_date, session.end_date].filter(Boolean).join(' – ')}</p></header><section className="mt-8 rounded-xl border bg-card p-6"><h2 className="text-2xl font-bold">Legislation</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{bills.map((bill: any) => <a key={bill.id} href={publicBillPath(bill)} className="rounded-lg border p-4 hover:border-primary"><strong className="text-primary">{bill.bill_identifier}</strong><p className="mt-2">{bill.caption}</p><p className="mt-2 text-sm text-muted-foreground">{bill.current_status_label}</p></a>)}</div></section></main>; }
