import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "What does financial responsibility mean in Texas?", answer: "It means a driver must be able to pay for injuries and property damage caused in a crash. Most drivers satisfy the requirement with auto liability insurance." },
  { question: "Is insurance the only way to prove financial responsibility?", answer: "No. Texas law recognizes certain alternatives, including qualifying deposits, surety bonds, and self-insurance arrangements, but these options have strict eligibility and documentation requirements." },
  { question: "What happens if I drive without financial responsibility?", answer: "A driver can face citations, fines, license or registration consequences, towing, and personal liability for crash damages. Repeat violations can bring more serious penalties." },
  { question: "What is an SR-22?", answer: "An SR-22 is a certificate filed by an insurer showing that the driver maintains required liability coverage. It may be required after certain convictions, suspensions, or other enforcement actions." },
];

function FinancialResponsibilityPage() { return <main>
  <HubBreadcrumbs current="Texas Financial Responsibility Law" />
  <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Proof you can pay for a crash</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Financial Responsibility Law</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">Learn how liability insurance, proof of coverage, TexasSure, SR-22 filings, and limited legal alternatives fit together.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/vehicles/auto-insurance-requirements" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Auto insurance requirements</a><a href="https://www.tdi.texas.gov/consumer/auto-insurance.html" rel="noreferrer" className="rounded-md border px-5 py-3 text-sm font-semibold">Texas insurance resources</a></div></div></section>
  <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
    <section><h2 className="text-3xl font-bold">The core Texas rule</h2><p className="mt-4">A driver must be able to pay for bodily injury and property damage caused by a motor-vehicle crash. Most people meet that duty by carrying at least the minimum liability insurance required by Texas law.</p></section>
    <section><h2 className="text-3xl font-bold">Common proof of financial responsibility</h2><ul className="mt-5 list-disc space-y-3 pl-6"><li>Current auto liability insurance card, paper or accepted electronic form.</li><li>Insurance information verified through the TexasSure system.</li><li>Qualifying certificate, bond, deposit, or self-insurance evidence authorized by law.</li><li>SR-22 certificate when specifically required as a condition of reinstatement or continued driving privilege.</li></ul></section>
    <section><h2 className="text-3xl font-bold">When proof may be requested</h2><p className="mt-4">Be prepared to show proof during a traffic stop, after a crash, during vehicle registration, and at an emissions or commercial inspection station. A mismatch in VIN, effective dates, named insured, or vehicle information can delay verification even when a policy exists.</p></section>
    <section><h2 className="text-3xl font-bold">SR-22 filings</h2><p className="mt-4">An SR-22 is not a separate insurance policy. It is a filing made by an insurer to certify qualifying coverage. A lapse or cancellation can be reported to the state and may trigger renewed suspension or other consequences. Drivers should confirm the exact filing period and reinstatement conditions before changing insurers.</p></section>
    <section><h2 className="text-3xl font-bold">Alternatives to ordinary liability insurance</h2><p className="mt-4">Texas law allows limited alternatives such as certain surety bonds, deposits, or self-insurance. These options are not simple substitutes for an insurance card. They can require substantial assets, formal approval, and specific certificates. Most individual drivers will find a liability policy more practical.</p></section>
    <section className="rounded-xl border bg-muted/20 p-6"><h2 className="text-2xl font-bold">Avoid a coverage gap</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>Pay renewal premiums before the due date.</li><li>Confirm the new policy is active before canceling the old one.</li><li>Update vehicles, drivers, addresses, and lienholders promptly.</li><li>Keep proof available even when TexasSure should verify coverage.</li><li>Do not drive a newly purchased vehicle until coverage is confirmed.</li><li>Track SR-22 requirements separately from the policy expiration date.</li></ul></section>
    <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
    <p className="border-t pt-8 text-sm text-muted-foreground">Financial-responsibility, reinstatement, SR-22, insurance, bond, and self-insurance rules can change. Confirm your specific requirements with Texas DPS, TxDMV, TDI, the court, and your insurer.</p>
  </article>
</main>; }

export const Route = createFileRoute("/vehicles/financial-responsibility")({ head: () => { const seo = buildSeo({ title: "Texas Financial Responsibility Law: Insurance, Proof and SR-22", description: "Texas financial responsibility guide covering liability insurance, proof of coverage, TexasSure, SR-22 filings, penalties and legal alternatives.", path: "/vehicles/financial-responsibility", type: "article", keywords: "Texas financial responsibility law, Texas proof of insurance, TexasSure, SR-22 Texas, driving without insurance Texas" }); return { meta:seo.meta, links:seo.links, scripts:[{ type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Texas Financial Responsibility Law", url:`${SITE_URL}/vehicles/financial-responsibility` }) }, { type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item)=>({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) }] }; }, component: FinancialResponsibilityPage });