import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "Do most Texas passenger vehicles still need a safety inspection?", answer: "No. Since January 1, 2025, most non-commercial vehicles no longer need an annual comprehensive safety inspection, although equipment laws and registration requirements still apply." },
  { question: "Do commercial vehicles still need inspections?", answer: "Yes. Commercial vehicles generally remain subject to an annual commercial safety inspection statewide." },
  { question: "Do emissions counties still require testing?", answer: "Yes. Qualifying vehicles registered in designated emissions counties must still pass emissions testing before registration." },
  { question: "Does ending the safety inspection mean unsafe equipment is legal?", answer: "No. Drivers must still comply with laws governing lights, brakes, tires, mirrors, windshields, seat belts, exhaust systems, and other equipment." },
];

function VehicleInspectionsPage() { return <main>
  <HubBreadcrumbs current="Texas Vehicle Inspections" />
  <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Post-2025 inspection rules</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Vehicle Inspections</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">See which vehicles still require commercial safety inspections or emissions tests, what changed in 2025, and which equipment rules still apply to every driver.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.dps.texas.gov/section/vehicle-inspection" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Official DPS inspection information</a><a href="/vehicles/inspections-emissions" className="rounded-md border px-5 py-3 text-sm font-semibold">Emissions testing guide</a></div></div></section>
  <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
    <section><h2 className="text-3xl font-bold">What changed on January 1, 2025</h2><p className="mt-4">Texas ended the annual comprehensive safety inspection for most non-commercial vehicles. The change did not eliminate emissions testing, commercial vehicle inspections, roadside equipment enforcement, or the inspection-program replacement fee collected with many registrations.</p></section>
    <section><h2 className="text-3xl font-bold">Who still needs an inspection?</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Commercial vehicles</h3><p className="mt-2 text-muted-foreground">Annual commercial safety inspection remains required statewide, with emissions testing added when applicable.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Emissions-county vehicles</h3><p className="mt-2 text-muted-foreground">Qualifying gasoline vehicles must pass the applicable emissions test before registration.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Special regulated vehicles</h3><p className="mt-2 text-muted-foreground">Certain buses, government fleets, rebuilt vehicles, or other regulated operations may have separate inspection or certification requirements.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Most personal vehicles</h3><p className="mt-2 text-muted-foreground">No annual safety inspection, but the vehicle must remain legally equipped and roadworthy.</p></div></div></section>
    <section><h2 className="text-3xl font-bold">Equipment laws still apply</h2><p className="mt-4">A vehicle can still be stopped or cited for defective lights, unsafe tires, inadequate brakes, obstructed windshields, missing mirrors, illegal tint, excessive exhaust noise, seat-belt problems, or other equipment violations. The absence of an annual inspection does not create immunity from roadside enforcement or civil liability.</p></section>
    <section><h2 className="text-3xl font-bold">Inspection and registration timing</h2><p className="mt-4">When an inspection is required, complete it early enough for the result to reach the state database before registration. Keep the Vehicle Inspection Report until registration is complete. A missing electronic record, failed test, incorrect VIN, or expired result can delay renewal.</p></section>
    <section><h2 className="text-3xl font-bold">Failed commercial or emissions inspections</h2><p className="mt-4">Review the failure report, repair the listed problems, retain receipts, and confirm retest rules with the station. Do not assume a cleared dashboard warning light or disconnected battery means the vehicle is ready; emissions readiness monitors may need time and normal driving to reset.</p></section>
    <section className="rounded-xl border bg-muted/20 p-6"><h2 className="text-2xl font-bold">Annual safety check you should still do</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>Tire tread, pressure, age, and damage.</li><li>Brake performance and warning lights.</li><li>Headlights, brake lights, turn signals, and plate lights.</li><li>Wipers, windshield damage, mirrors, and washer fluid.</li><li>Seat belts and child-restraint anchors.</li><li>Fluid leaks, steering, suspension, battery, and exhaust condition.</li></ul></section>
    <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
  </article>
</main>; }

export const Route = createFileRoute("/vehicles/inspections")({ head: () => { const seo = buildSeo({ title: "Texas Vehicle Inspections: 2026 Safety and Commercial Rules", description: "Texas vehicle inspection guide explaining the 2025 safety-inspection change, commercial inspections, emissions testing and equipment laws.", path: "/vehicles/inspections", type: "article", keywords: "Texas vehicle inspection, Texas safety inspection 2026, commercial vehicle inspection Texas, Texas inspection law" }); return { meta:seo.meta, links:seo.links, scripts:[{ type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Texas Vehicle Inspections", url:`${SITE_URL}/vehicles/inspections` }) }, { type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item)=>({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) }] }; }, component: VehicleInspectionsPage });