import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const permitTypes = [
  ["Vehicle Transit Permit", "For a qualifying private-party sale when the seller keeps the Texas plates. It is free, valid for five calendar days, and authorizes one trip between the stated origin, destination, and listed intermediate points."],
  ["Temporary Registration Plate — One Trip", "Issued by a county tax office or TxDMV Regional Service Center for one trip by an eligible unregistered vehicle. The underlying one-trip authority is valid for 15 calendar days and generally applies only to an unladen vehicle."],
  ["Temporary Registration Plate — 30 Days", "Issued in person for eligible passenger vehicles, motorcycles, private buses, trailers, semitrailers, and qualifying light commercial vehicles. Form VTR-66, identification, insurance, and applicable emissions documentation may be required."],
  ["72-Hour Permit", "Temporary commercial registration for qualifying commercial vehicles and buses. A valid USDOT number is required. The permit fee is $25 plus the current processing and handling charge."],
  ["144-Hour Permit", "Temporary commercial registration for qualifying commercial vehicles and buses. A valid USDOT number is required. The permit fee is $50 plus the current processing and handling charge."],
] as const;

const faq = [
  { question: "Did Texas eliminate paper temporary tags?", answer: "Texas eliminated most dealer-issued paper temporary tags on July 1, 2025. Dealers now generally issue metal plates at delivery, and county offices or TxDMV Regional Service Centers issue metal Temporary Registration Plates for one-trip and 30-day temporary registration." },
  { question: "Can I still print a Vehicle Transit Permit after a private sale?", answer: "Yes. A qualifying private-sale buyer may still obtain the paper Vehicle Transit Permit online when the seller keeps the Texas plates. It is valid for five calendar days and one trip." },
  { question: "How much does a Texas one-trip permit cost?", answer: "TxDMV lists a $5 permit fee plus a non-refundable $4.75 processing and handling charge. Since July 1, 2025, the county or Regional Service Center issues a metal Temporary Registration Plate rather than the former paper display permit." },
  { question: "How much does a Texas 30-day permit cost?", answer: "TxDMV lists a $25 permit fee plus a non-refundable $4.75 processing and handling charge. The temporary registration is now represented by a metal Temporary Registration Plate with expiration stickers." },
  { question: "Can a temporary permit replace normal registration?", answer: "No. Temporary registration is limited to specific qualifying circumstances and cannot be used as a substitute for completing ordinary title and registration requirements." },
  { question: "Do I need insurance for a temporary permit?", answer: "Most applicants must show liability insurance meeting Texas minimum limits. TxDMV generally does not require insurance for trailers and semitrailers." },
  { question: "Can I use a Texas temporary permit outside Texas?", answer: "Some Texas temporary permits authorize operation only in Texas. Before leaving the state, verify whether every state on the route will recognize the permit or temporary registration plate." },
];

function TemporaryTagsPage() {
  return (
    <main>
      <HubBreadcrumbs current="Texas Temporary Tags and Permits" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas temporary vehicle registration</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Temporary Tags and Temporary Permits Guide</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Understand Texas temporary registration after the July 1, 2025 metal-plate transition. Compare Vehicle Transit Permits, one-trip and 30-day Temporary Registration Plates, and 72-hour or 144-hour commercial permits.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/register-your-vehicle/temporary-permits" target="_blank" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Open official TxDMV permit page</a><a href="/find-my-dmv" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Find a county or TxDMV office</a><a href="/vehicles/title-transfer" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Title transfer guide</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><div className="rounded-xl border border-amber-300 bg-amber-50 p-6 text-amber-950"><h2 className="text-xl font-bold">Texas dealers no longer print ordinary buyer paper tags</h2><p className="mt-2 leading-relaxed">House Bill 718 took effect July 1, 2025. Texas dealers generally issue metal general-issue plates when delivering a vehicle. Metal Buyer Provisional Plates may be used when the required plate type is temporarily unavailable, and Out-of-State Buyer Plates may be used for qualifying non-Texas buyers.</p></div><div className="mt-12"><h2 className="text-3xl font-bold">Which temporary authority do you need?</h2><div className="mt-7 space-y-4">{permitTypes.map(([title, text]) => <article key={title} className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></article>)}</div></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">What changed under HB 718</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Dealer sales</h3><p className="mt-3 leading-relaxed text-muted-foreground">Dealers generally issue metal plates at delivery instead of printing a buyer temporary tag. Buyers should keep the dealer's Buyer’s Receipt in the vehicle until registration is complete and the windshield sticker is received.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">One-trip and 30-day permits</h3><p className="mt-3 leading-relaxed text-muted-foreground">County tax offices and TxDMV Regional Service Centers now issue metal Temporary Registration Plates with expiration stickers for these transactions. The plates must be securely displayed on the rear of the vehicle rather than placed in a window.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Private-party sales</h3><p className="mt-3 leading-relaxed text-muted-foreground">The paper Vehicle Transit Permit remains available when a seller removes the Texas plates. It is limited to one qualifying vehicle, one trip, and five calendar days.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Commercial temporary permits</h3><p className="mt-3 leading-relaxed text-muted-foreground">Paper 72-hour and 144-hour permits remain available for qualifying commercial vehicles. They require a valid USDOT number and are valid only in Texas.</p></article></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Documents and information to prepare</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{["Vehicle identification number","Current government-issued photo identification","Proof of Texas-compliant liability insurance","Completed Form VTR-66 for a 30-day permit","USDOT number for a 72-hour or 144-hour permit","Proof of required emissions inspection for a 30-day permit in an emissions county","Origin, destination, and intermediate points for trip-limited authority","Payment accepted by the issuing office"].map((item) => <div key={item} className="rounded-xl border bg-card p-5 font-medium">{item}</div>)}</div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Important limits and common mistakes</h2><div className="mt-7 space-y-5"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Do not treat a permit as renewable registration</h3><p className="mt-2 leading-relaxed text-muted-foreground">Temporary authority exists for limited movement or short-term operation. Complete the required title and registration transaction instead of repeatedly relying on permits.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Match the permit to the vehicle and trip</h3><p className="mt-2 leading-relaxed text-muted-foreground">Vehicle weight, commercial use, cargo, salvage status, route, and destination can make a vehicle ineligible. A one-trip permit generally cannot be used for a laden commercial vehicle or a trip that begins and ends outside Texas.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Carry the required receipt</h3><p className="mt-2 leading-relaxed text-muted-foreground">Keep the permit receipt and supporting documents in the vehicle. Metal Temporary Registration Plates must be secured to the rear and display the required expiration stickers.</p></article></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></section>
      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-2xl font-bold">Related Texas vehicle resources</h2><div className="mt-5 flex flex-wrap gap-3"><a href="/vehicles/registration" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Vehicle registration</a><a href="/vehicles/renewal" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Registration renewal</a><a href="/vehicles/title-transfer" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Title transfer</a><a href="/vehicles/plates" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">License plates</a><a href="/find-my-dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Office finder</a><a href="/dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">DMV and DPS hub</a></div></div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground"><p>Temporary-registration rules depend on vehicle type, weight, use, title status, inspection status, route, and issuing office. Confirm current eligibility, display rules, forms, fees, and acceptable payment with TxDMV or the county tax assessor-collector before operating the vehicle.</p></div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/temporary-tags")({
  head: () => {
    const seo = buildSeo({ title: "Texas Temporary Tags & Permits: HB 718 Metal Plate Rules", description: "Texas temporary vehicle registration guide covering HB 718 metal plates, Vehicle Transit Permits, one-trip, 30-day, 72-hour, and 144-hour permits.", path: "/vehicles/temporary-tags", type: "article", keywords: "Texas temporary tags, Texas temporary permit, Texas temporary registration plate, HB 718 Texas, Vehicle Transit Permit, Texas one trip permit, Texas 30 day permit" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Temporary Tags and Temporary Permits Guide", description: "Current Texas temporary vehicle registration rules after the HB 718 metal-plate transition.", mainEntityOfPage: `${SITE_URL}/vehicles/temporary-tags`, publisher: { "@type": "Organization", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV & Driver Services", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Texas Temporary Tags and Permits", item: `${SITE_URL}/vehicles/temporary-tags` }] }) },
    ] };
  },
  component: TemporaryTagsPage,
});