import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const buyerChecklist = [
  ["Check the title and VIN", "Match the VIN on the vehicle to the original title, confirm the seller is the titled owner, review lien information, and use TxDMV Title Check or an NMVTIS report before paying."],
  ["Document the transaction", "Record the buyer and seller names and addresses, sale date, price, mileage, VIN, and payment terms. Keep copies of the signed title, Form 130-U, bill of sale, lien release, and payment record."],
  ["Complete the title assignment", "The seller should sign the title, enter the sale date and odometer disclosure when required, and avoid leaving blank fields or creating an open title."],
  ["Apply within 30 days", "The buyer generally files the assigned title and Form 130-U at the county tax assessor-collector within 30 calendar days and pays title, registration, local, and motor-vehicle tax amounts."],
] as const;

const sellerChecklist = [
  "Confirm payment before releasing the vehicle and original title",
  "Provide a properly assigned title and signed Form 130-U",
  "Remove or retain the license plates when appropriate",
  "File the TxDMV Vehicle Transfer Notification within 30 days",
  "Keep the buyer's contact information, VIN, price, date, and document copies",
  "Cancel insurance only after possession and responsibility have transferred",
] as const;

const faq = [
  { question: "How long does a Texas buyer have to transfer the title?", answer: "The buyer generally must apply for title within 30 calendar days after the sale. Delinquent-transfer penalties can apply after the deadline." },
  { question: "Should the seller go to the county tax office with the buyer?", answer: "TxDMV recommends accompanying the buyer when possible so the seller can confirm that the title application is actually filed." },
  { question: "What should a Texas seller give the buyer?", answer: "The seller should provide the properly assigned original title and a signed Form 130-U showing the sales price. A lien release and other transaction-specific documents may also be required." },
  { question: "Why should the seller file a Vehicle Transfer Notification?", answer: "When filed within 30 days, it updates the state record to show the vehicle as sold and helps protect the seller from later parking-ticket and toll liability." },
  { question: "How much sales tax applies to a private-party vehicle purchase?", answer: "Texas motor-vehicle sales tax is generally 6.25%. For many private-party used-vehicle purchases, tax is based on the greater of the actual price or 80% of the standard presumptive value unless a qualifying exception or certified appraisal applies." },
  { question: "Can the seller keep the Texas license plates?", answer: "Yes. A seller may remove and retain eligible plates for future transfer, transfer them to another qualifying vehicle, or deface and dispose of them to prevent fraudulent use." },
  { question: "How can a buyer drive the vehicle if the seller removes the plates?", answer: "A qualifying private-sale buyer may obtain one five-day Vehicle Transit Permit for the sale. The permit does not replace the title-transfer and registration requirements." },
];

function BuyingSellingPage() {
  return <main>
    <HubBreadcrumbs current="Buying or Selling a Vehicle in Texas" />
    <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas private vehicle transactions</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Buying or Selling a Vehicle in Texas</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Use a safer Texas private-sale process, verify the title and VIN, complete Form 130-U, understand taxes and plates, meet the 30-day title deadline, and protect both sides with complete records.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle" target="_blank" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Open official TxDMV instructions</a><a href="/vehicles/title-transfer" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Title-transfer guide</a><a href="/find-my-dmv" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Find a county tax office</a></div></div></section>
    <section className="mx-auto max-w-5xl px-4 py-14"><div className="rounded-xl border border-amber-300 bg-amber-50 p-6 text-amber-950"><h2 className="text-xl font-bold">Do not buy an open title</h2><p className="mt-2 leading-relaxed">The person selling the vehicle should be the titled owner or an authorized representative. Blank assignments, skipped owners, altered titles, unresolved liens, and mismatched VINs can create tax, ownership, fraud, and registration problems.</p></div><h2 className="mt-12 text-3xl font-bold">Buyer checklist</h2><div className="mt-7 space-y-4">{buyerChecklist.map(([title,text]) => <article key={title} className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></article>)}</div></section>
    <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Seller protection checklist</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{sellerChecklist.map((item) => <div key={item} className="rounded-xl border bg-card p-5 font-medium">{item}</div>)}</div><div className="mt-8 rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Vehicle Transfer Notification</h3><p className="mt-3 leading-relaxed text-muted-foreground">File the notification within 30 days of the sale. It does not transfer ownership by itself, but it updates the TxDMV record to show the vehicle as sold and can protect the seller from qualifying parking-ticket and toll liability.</p></div></div></section>
    <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Taxes, plates, insurance, and inspections</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Private-party tax</h3><p className="mt-3 leading-relaxed text-muted-foreground">The buyer generally pays 6.25% motor-vehicle sales tax at the county office. Standard presumptive value rules can cause tax to be calculated on 80% of the vehicle's state value when that amount exceeds the reported price.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Plates and transit permit</h3><p className="mt-3 leading-relaxed text-muted-foreground">The seller may remove the plates. A qualifying buyer can obtain one five-day Vehicle Transit Permit to move the vehicle while completing the title and registration process.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Insurance</h3><p className="mt-3 leading-relaxed text-muted-foreground">Proof of liability insurance is generally required to register the vehicle. A buyer without proof may be able to apply for title only, but may not lawfully drive an uninsured vehicle.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Inspection records</h3><p className="mt-3 leading-relaxed text-muted-foreground">Commercial vehicles still require a commercial safety inspection. Vehicles registered in emissions counties must satisfy emissions requirements, and the county may request a Vehicle Inspection Report when no current record appears electronically.</p></article></div></section>
    <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></div></section>
    <section className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-2xl font-bold">Related Texas vehicle resources</h2><div className="mt-5 flex flex-wrap gap-3"><a href="/vehicles/title-transfer" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Title transfer</a><a href="/vehicles/temporary-tags" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Temporary permits</a><a href="/vehicles/plates" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">License plates</a><a href="/vehicles/bonded-titles" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Missing-title options</a><a href="/dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">DMV hub</a></div></section>
    <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground"><p>Transaction facts can change the required forms, tax treatment, inspection requirements, and title remedy. Confirm the current title record, lien status, forms, taxes, fees, and county procedures before exchanging money or possession.</p></div></section>
  </main>;
}

export const Route = createFileRoute("/vehicles/buying-selling")({
  head: () => { const seo = buildSeo({ title: "Buying or Selling a Vehicle in Texas: Private-Sale Checklist", description: "Texas private vehicle sale guide for titles, Form 130-U, taxes, VIN checks, plates, Vehicle Transfer Notifications, insurance, and the 30-day deadline.", path: "/vehicles/buying-selling", type: "article", keywords: "buying a used car in Texas, selling a car in Texas, Texas private vehicle sale, Form 130-U, Vehicle Transfer Notification, Texas car sales tax" }); return { meta: seo.meta, links: seo.links, scripts: [
    { type: "application/ld+json", children: JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Buying or Selling a Vehicle in Texas", description:"Texas private-sale checklist covering title verification, documents, taxes, plates, deadlines, and seller protection.", mainEntityOfPage:`${SITE_URL}/vehicles/buying-selling`, publisher:{ "@type":"Organization", name:"Keep TX Red", url:`${SITE_URL}/` } }) },
    { type: "application/ld+json", children: JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item) => ({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) },
    { type: "application/ld+json", children: JSON.stringify({ "@context":"https://schema.org", "@type":"BreadcrumbList", itemListElement:[{ "@type":"ListItem", position:1, name:"Home", item:`${SITE_URL}/` },{ "@type":"ListItem", position:2, name:"Texas DMV & Driver Services", item:`${SITE_URL}/dmv` },{ "@type":"ListItem", position:3, name:"Buying or Selling a Vehicle in Texas", item:`${SITE_URL}/vehicles/buying-selling` }] }) },
  ] }; },
  component: BuyingSellingPage,
});