import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "How do I check whether a Texas personalized plate message is available?", answer: "Use the current TxDMV or authorized specialty-plate vendor search tool. Availability can change until an order is accepted and processed." },
  { question: "Can Texas reject a personalized plate message?", answer: "Yes. TxDMV may reject combinations that violate formatting rules, conflict with existing plates, create enforcement confusion, or fall within prohibited content standards." },
  { question: "Are personalized plates transferable?", answer: "Some plates may be transferred to another eligible vehicle or retained for future use, subject to plate type, ownership, registration, and TxDMV rules." },
  { question: "Do personalized plates replace normal registration fees?", answer: "No. Personalized or specialty plate charges are generally added to ordinary registration and any other applicable vehicle fees." },
];

function PersonalizedPlatesPage() { return <main>
  <HubBreadcrumbs current="Texas Personalized License Plates" />
  <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Custom Texas plates</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Personalized License Plates</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">Choose a plate design and custom message, check availability, understand review rules, and complete ordering, renewal, transfer, and replacement steps.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/license-plates/specialty-license-plates" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Official TxDMV plate options</a><a href="/vehicles/plates" className="rounded-md border px-5 py-3 text-sm font-semibold">Texas plate guide</a></div></div></section>
  <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
    <section><h2 className="text-3xl font-bold">How personalized plates work</h2><p className="mt-4">Texas offers personalized messages on eligible general-issue and specialty plate designs. Character limits, spaces, symbols, and available combinations vary by plate. A message shown as available during a search is not guaranteed until the application passes review and is accepted.</p></section>
    <section><h2 className="text-3xl font-bold">Ordering steps</h2><ol className="mt-5 list-decimal space-y-3 pl-6"><li>Select an eligible plate design.</li><li>Check the current character and formatting limits.</li><li>Search the requested message and alternatives.</li><li>Review the total plate charge and normal registration costs.</li><li>Submit through the authorized online, county, or mail process for that plate.</li><li>Wait for approval and manufacturing.</li><li>Follow pickup or delivery instructions and install the plates promptly.</li></ol></section>
    <section><h2 className="text-3xl font-bold">Why a message may be rejected</h2><p className="mt-4">Texas reviews custom combinations for duplication, legibility, law-enforcement confusion, prohibited content, misleading official meaning, and compliance with the selected plate format. Spelling tricks, numbers, spacing, and implied meanings may be considered as a whole.</p></section>
    <section><h2 className="text-3xl font-bold">Renewal, transfer, and replacement</h2><p className="mt-4">Personalized plate rights depend on keeping the plate current and following the applicable renewal rules. Before selling a vehicle, determine whether the plate can be removed, retained, transferred to another eligible vehicle, or must be surrendered. Lost or damaged plates require a replacement process and may not preserve the same message in every circumstance.</p></section>
    <section className="rounded-xl border bg-muted/20 p-6"><h2 className="text-2xl font-bold">Before ordering</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>Confirm the plate fits your vehicle class.</li><li>Check the full annual and initial cost.</li><li>Choose several acceptable message alternatives.</li><li>Review whether the plate supports transfer or retention.</li><li>Verify county pickup and production timing.</li><li>Do not dispose of current plates until instructed.</li></ul></section>
    <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
  </article>
</main>; }

export const Route = createFileRoute("/vehicles/personalized-plates")({ head: () => { const seo = buildSeo({ title: "Texas Personalized License Plates: Availability and Ordering", description: "Learn how to order Texas personalized plates, check message availability, understand review rules, fees, renewal, transfer and replacement.", path: "/vehicles/personalized-plates", type: "article", keywords: "Texas personalized license plates, custom plates Texas, vanity plates Texas, Texas specialty plates" }); return { meta:seo.meta, links:seo.links, scripts:[{ type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Texas Personalized License Plates", url:`${SITE_URL}/vehicles/personalized-plates` }) }, { type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item)=>({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) }] }; }, component: PersonalizedPlatesPage });