import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const emissionsCounties = ["Brazoria", "Collin", "Dallas", "Denton", "El Paso", "Ellis", "Fort Bend", "Galveston", "Harris", "Johnson", "Kaufman", "Montgomery", "Parker", "Rockwall", "Tarrant", "Travis", "Williamson"] as const;

const faq = [
  { question: "Does Texas still require annual vehicle safety inspections?", answer: "Since January 1, 2025, Texas no longer requires comprehensive safety inspections for most non-commercial vehicles. Commercial vehicles still require an annual commercial safety inspection, and qualifying vehicles registered in emissions counties still require emissions testing." },
  { question: "Which Texas counties require emissions testing?", answer: `Emissions testing currently applies in ${emissionsCounties.join(", ")}. Bexar County begins emissions testing on November 1, 2026.` },
  { question: "Which vehicles need an emissions test?", answer: "DPS generally requires gasoline-powered vehicles that are two through 24 model years old and registered in an emissions county to receive an annual OBDII emissions test. Electric-only vehicles and certain other vehicles are exempt." },
  { question: "How much does a Texas emissions inspection cost?", answer: "DPS lists maximum station charges of $18.50 in the Dallas-Fort Worth and Houston-area emissions counties and $11.50 in El Paso, Travis, and Williamson counties. Confirm the current charge with the inspection station." },
  { question: "What happens if my vehicle fails emissions testing?", answer: "The vehicle must generally be repaired and pass a retest before registration can be completed. Ask the station for the Vehicle Inspection Report, diagnostic trouble codes, retest rules, and information about any repair assistance or waiver program for which you may qualify." },
  { question: "Does a new Texas resident need an inspection before registration?", answer: "A new resident registering a qualifying vehicle in an emissions county must obtain the required emissions test before completing title and registration. Most non-commercial vehicles outside emissions counties no longer need a safety inspection." },
];

function InspectionsEmissionsPage() {
  return (
    <main>
      <HubBreadcrumbs current="Texas Vehicle Inspections and Emissions" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas registration requirements</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Vehicle Inspections and Emissions Testing</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Understand the post-2025 inspection rules, emissions counties, vehicle exemptions, testing costs, commercial inspections, registration timing, failed tests, and Bexar County's November 2026 change.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.dps.texas.gov/section/vehicle-inspection" target="_blank" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Open official DPS inspection information</a><a href="/vehicles/renewal" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Registration renewal guide</a><a href="/find-my-dmv" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Find an office</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><div className="rounded-xl border border-amber-300 bg-amber-50 p-6 text-amber-950"><h2 className="text-xl font-bold">The 2025 change did not eliminate emissions testing</h2><p className="mt-2 leading-relaxed">Texas ended comprehensive annual safety inspections for most non-commercial vehicles on January 1, 2025. Emissions testing remains mandatory for qualifying vehicles registered in designated counties, and commercial vehicles still require annual safety inspections statewide.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Most personal vehicles</h3><p className="mt-3 leading-relaxed text-muted-foreground">No annual safety inspection unless another specific rule applies. Registration and legal equipment requirements still remain.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Emissions-county vehicles</h3><p className="mt-3 leading-relaxed text-muted-foreground">Qualifying gasoline vehicles generally need an annual emissions test before registration renewal.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Commercial vehicles</h3><p className="mt-3 leading-relaxed text-muted-foreground">Annual commercial safety inspection remains required in every Texas county, plus emissions testing when applicable.</p></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Texas emissions counties</h2><p className="mt-4 leading-relaxed text-muted-foreground">The following 17 counties currently require emissions testing for qualifying vehicles. Bexar County joins the program on November 1, 2026.</p><div className="mt-7 grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">{emissionsCounties.map((county) => <div key={county} className="rounded-lg border bg-card px-4 py-3 font-semibold">{county} County</div>)}<div className="rounded-lg border border-dashed border-primary bg-primary/5 px-4 py-3 font-semibold">Bexar County — starts Nov. 1, 2026</div></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Which vehicles generally need emissions testing?</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Generally tested</h3><ul className="mt-4 space-y-2 text-muted-foreground">{["Gasoline-powered vehicle","Registered in an emissions county","Two through 24 model years old","Used primarily in the affected county","Due for annual registration or initial Texas registration"].map((item) => <li key={item}>• {item}</li>)}</ul></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Common exemptions</h3><ul className="mt-4 space-y-2 text-muted-foreground">{["Electric-only vehicles","Vehicles newer than the testing age threshold","Vehicles older than 24 model years","Diesel-powered vehicles under the emissions program","Qualifying vehicles primarily operated outside the affected county","Other statutory or program exemptions"].map((item) => <li key={item}>• {item}</li>)}</ul></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Testing process, costs, and registration timing</h2><div className="mt-7 space-y-5"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">1. Visit a certified emissions station</h3><p className="mt-2 leading-relaxed text-muted-foreground">Bring the vehicle and proof of financial responsibility. The station generally performs an OBDII test and checks emissions-control components required by the program.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">2. Pay the station charge</h3><p className="mt-2 leading-relaxed text-muted-foreground">DPS currently lists maximum charges of $18.50 in Dallas-Fort Worth and Houston-area counties and $11.50 in El Paso, Travis, and Williamson counties. Commercial inspections may cost up to $40.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">3. Complete registration</h3><p className="mt-2 leading-relaxed text-muted-foreground">Inspection results are transmitted electronically. After a passing result is recorded, complete registration through TxT, TxDMV, a participating location, or the county tax assessor-collector as eligible.</p></article></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">If the vehicle fails</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Use the inspection report</h3><p className="mt-3 leading-relaxed text-muted-foreground">Review the Vehicle Inspection Report and diagnostic trouble codes. A lit check-engine light, incomplete readiness monitors, emissions-control failure, or communication problem can prevent a passing result.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Repair and retest</h3><p className="mt-3 leading-relaxed text-muted-foreground">Repair the underlying issue, complete any required drive cycle, and return for retesting. Keep receipts because they may be needed for assistance, waiver, or dispute procedures.</p></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Inspection program replacement fee</h2><p className="mt-4 leading-relaxed text-muted-foreground">Although most non-commercial safety inspections ended, Texas retained the former state inspection-related amount as an inspection program replacement fee collected with registration. DPS states the standard amount is $7.50, while qualifying new vehicles receiving two years of initial registration are charged $16.75. Commercial vehicles that still pay for a safety inspection are exempt from this replacement fee.</p></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></section>
      <section className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-2xl font-bold">Related Texas vehicle resources</h2><div className="mt-5 flex flex-wrap gap-3"><a href="/vehicles/registration" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Vehicle registration</a><a href="/vehicles/renewal" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Registration renewal</a><a href="/vehicles/buying-selling" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Buying and selling</a><a href="/find-my-dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Office finder</a><a href="/dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">DMV and DPS hub</a></div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground"><p>Inspection rules, county participation, testing fees, exemptions, waiver programs, and registration procedures can change. Confirm current requirements with Texas DPS, TxDMV, TCEQ, and your county tax assessor-collector.</p></div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/inspections-emissions")({
  head: () => {
    const seo = buildSeo({ title: "Texas Vehicle Inspections & Emissions Testing: 2026 Guide", description: "Texas vehicle inspection and emissions rules after the 2025 safety-inspection change. See emissions counties, exemptions, fees, failed-test steps, commercial rules, and Bexar County's 2026 start.", path: "/vehicles/inspections-emissions", type: "article", keywords: "Texas vehicle inspection, Texas emissions testing, emissions counties Texas, Texas safety inspection 2026, Bexar County emissions test, Texas commercial vehicle inspection" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Vehicle Inspections and Emissions Testing", description: "Texas safety inspection, emissions testing, county, exemption, fee, and registration guidance.", mainEntityOfPage: `${SITE_URL}/vehicles/inspections-emissions`, publisher: { "@type": "Organization", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV & Driver Services", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Texas Vehicle Inspections and Emissions", item: `${SITE_URL}/vehicles/inspections-emissions` }] }) },
    ] };
  },
  component: InspectionsEmissionsPage,
});