import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const steps = [
  ["1. Confirm the title brand", "Check whether the vehicle is salvage, nonrepairable, owner-retained, rebuilt, or another branded-title category before buying parts or beginning repairs. Use TxDMV Title Check and an NMVTIS history report when available."],
  ["2. Obtain the proper salvage title", "A Texas salvage vehicle generally must first be issued a Salvage Vehicle Title. TxDMV instructs applicants to submit Form VTR-441, ownership evidence, identification, any lien release, and the required fee."],
  ["3. Rebuild and document the work", "Keep receipts for major component parts, record where parts came from, and complete the Rebuilt Vehicle Statement, Form VTR-61. Do not use parts that create an ownership, theft, or nonrepairable-vehicle problem."],
  ["4. Complete required inspections", "The vehicle must satisfy the inspections required for its vehicle type and county before registration. Rebuilt vehicles are also subject to anti-theft and roadworthiness requirements."],
  ["5. Apply for rebuilt title and registration", "Take the salvage title, Form 130-U, Form VTR-61, identification, insurance, inspection evidence when applicable, and county-required documents to the county tax assessor-collector."],
] as const;

const faq = [
  { question: "Can a vehicle with a Texas salvage title be driven on public roads?", answer: "No. A salvage or nonrepairable vehicle may not be operated on public roads. A salvage vehicle must be rebuilt, inspected, titled with the appropriate rebuilt brand, insured, and registered before legal road use." },
  { question: "What is a rebuilt salvage title in Texas?", answer: "It is a Texas title issued after a vehicle previously branded salvage has been rebuilt to roadworthiness and completed the required title, inspection, and registration process. The title remains permanently branded Rebuilt Salvage." },
  { question: "What forms are normally used to title a rebuilt vehicle?", answer: "The core forms are usually Application for Texas Title and/or Registration, Form 130-U, and Rebuilt Vehicle Statement, Form VTR-61. Obtaining the initial salvage or nonrepairable title generally uses Form VTR-441." },
  { question: "How much is a Texas salvage title application?", answer: "TxDMV currently lists an $8 salvage-title fee, with an additional $2 when the title is lost. County title, registration, inspection, tax, and local fees may apply later when applying for rebuilt title and registration." },
  { question: "Can a Texas nonrepairable vehicle be rebuilt and registered?", answer: "Generally no. A nonrepairable vehicle is intended only for parts or scrap and cannot be legally rebuilt for normal Texas road registration. Do not assume a vehicle can return to the road merely because repairs are physically possible." },
  { question: "Can a salvage vehicle receive a 30-day temporary permit?", answer: "No. TxDMV says a 30-day temporary registration plate may not be issued to a vehicle that has been issued a salvage or nonrepairable title." },
];

function SalvageRebuiltTitlesPage() {
  return (
    <main>
      <HubBreadcrumbs current="Texas Salvage and Rebuilt Titles" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas branded vehicle titles</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Salvage and Rebuilt Vehicle Title Guide</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Understand Texas salvage, nonrepairable, owner-retained, and rebuilt-title rules, including forms, inspections, fees, documentation, road-use restrictions, and the county title process.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle/title-check-look-before-you-buy/salvage-brands" target="_blank" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Open official TxDMV salvage guidance</a><a href="/vehicles/title-transfer" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Title transfer guide</a><a href="/find-my-dmv" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Find a county tax office</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><div className="rounded-xl border border-red-300 bg-red-50 p-6 text-red-950"><h2 className="text-xl font-bold">A salvage vehicle is not road legal yet</h2><p className="mt-2 leading-relaxed">A Texas salvage or nonrepairable vehicle may not be driven on public roads. A salvage vehicle must complete the rebuild, inspection, title, insurance, and registration process first. A nonrepairable vehicle generally cannot be returned to ordinary road use.</p></div><div className="mt-12"><h2 className="text-3xl font-bold">Texas rebuilt-title process</h2><div className="mt-7 space-y-4">{steps.map(([title, text]) => <article key={title} className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></article>)}</div></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Know the title brands</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Salvage</h3><p className="mt-3 leading-relaxed text-muted-foreground">The vehicle has damage or missing major parts and the estimated repair cost exceeds the applicable value threshold. It may be rebuilt, but it cannot be registered for road use until the rebuilt-title process is complete.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Nonrepairable</h3><p className="mt-3 leading-relaxed text-muted-foreground">The vehicle is considered suitable only for parts or scrap. It cannot be rebuilt and registered for ordinary road use in Texas.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Owner retained</h3><p className="mt-3 leading-relaxed text-muted-foreground">An insurer declared the vehicle a total loss, but the owner retained possession. Later transfers may carry a prior-owner-retained brand.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Rebuilt salvage</h3><p className="mt-3 leading-relaxed text-muted-foreground">A previously salvage-branded vehicle has been rebuilt and approved through the required title and inspection process. The rebuilt brand remains part of the vehicle history.</p></article></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Documents commonly required</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{["Texas Salvage Vehicle Title","Application for Texas Title and/or Registration, Form 130-U","Rebuilt Vehicle Statement, Form VTR-61","Government-issued photo identification","Proof of liability insurance","Inspection or emissions evidence when applicable","Receipts and ownership records for major component parts","Lien release when a recorded lien has been paid","County title, registration, tax, and fee payment"].map((item) => <div key={item} className="rounded-xl border bg-card p-5 font-medium">{item}</div>)}</div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Inspection and parts documentation</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Inspection rules</h3><p className="mt-3 leading-relaxed text-muted-foreground">Inspection requirements depend on vehicle type and county. Commercial vehicles continue to require commercial inspection. Noncommercial vehicles in emissions counties must satisfy applicable emissions requirements before registration.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Parts and receipts</h3><p className="mt-3 leading-relaxed text-muted-foreground">Form VTR-61 identifies repairs and major component parts. Keep detailed receipts showing the seller, date, description, and vehicle-identification information when applicable. Missing or questionable documentation can delay or prevent titling.</p></article></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Before buying a rebuilt vehicle</h2><div className="mt-7 space-y-4">{["Run TxDMV Title Check and obtain an NMVTIS vehicle-history report.","Match the VIN on the dashboard, door label, title, and sales documents.","Ask for repair invoices, parts receipts, photos, inspection records, and the prior salvage title.","Arrange an independent structural, mechanical, electrical, airbag, and flood-damage inspection.","Confirm insurance availability and coverage before purchasing.","Expect the rebuilt brand to affect financing, resale value, trade-in value, and warranty options."].map((item) => <div key={item} className="rounded-xl border bg-card p-5">{item}</div>)}</div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-2xl font-bold">Related Texas vehicle resources</h2><div className="mt-5 flex flex-wrap gap-3"><a href="/vehicles/title-transfer" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Title transfer</a><a href="/vehicles/registration" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Vehicle registration</a><a href="/vehicles/temporary-tags" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Temporary permits</a><a href="/vehicles/plates" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">License plates</a><a href="/find-my-dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Find an office</a><a href="/dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">DMV and DPS hub</a></div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground"><p>Salvage and rebuilt-title transactions are document-sensitive. Confirm current forms, inspection requirements, fees, title eligibility, parts documentation, and county procedures with TxDMV and the county tax assessor-collector before buying, repairing, transporting, or applying for title.</p></div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/salvage-rebuilt-titles")({
  head: () => {
    const seo = buildSeo({ title: "Texas Salvage & Rebuilt Titles: Forms, Inspections and Rules", description: "Texas salvage and rebuilt vehicle title guide covering Form VTR-61, Form VTR-441, inspections, fees, nonrepairable vehicles, title brands, and registration.", path: "/vehicles/salvage-rebuilt-titles", type: "article", keywords: "Texas salvage title, Texas rebuilt title, rebuilt salvage Texas, VTR-61, VTR-441, nonrepairable vehicle Texas, prior salvage title" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Salvage and Rebuilt Vehicle Title Guide", description: "Texas salvage, nonrepairable, owner-retained, and rebuilt vehicle title requirements.", mainEntityOfPage: `${SITE_URL}/vehicles/salvage-rebuilt-titles`, publisher: { "@type": "Organization", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV & Driver Services", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Texas Salvage and Rebuilt Titles", item: `${SITE_URL}/vehicles/salvage-rebuilt-titles` }] }) },
    ] };
  },
  component: SalvageRebuiltTitlesPage,
});