import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const steps = [
  ["1. Confirm you may qualify", "You generally must be a Texas resident or military member stationed in Texas, possess the complete vehicle, and lack acceptable ownership documents. Junked, nonrepairable, or otherwise untitling-eligible vehicles do not qualify."],
  ["2. Apply for a TxDMV eligibility review", "Submit Form VTR-130-SOF, supporting ownership evidence, acceptable photo identification, lien releases when required, and the $15 administrative fee to the TxDMV Regional Service Center serving your county."],
  ["3. Complete any required VIN inspection", "A vehicle with no Texas title or registration record generally requires Form VTR-68-A from an authorized auto-theft investigator. TxDMV does not perform this inspection."],
  ["4. Receive the bond determination", "If approved, TxDMV issues Form VTR-130-ND showing the required surety-bond amount. Texas sets the bond at one and one-half times the vehicle value determined through SPV, a recognized reference guide, or an eligible appraisal."],
  ["5. Buy the surety bond", "Purchase the vehicle surety bond from an insurance agency or another business licensed to sell surety bonds in Texas. The determination notice is valid for one year."],
  ["6. File at the county tax office", "Within 30 days after buying the bond, submit the original bond determination, surety bond, Form 130-U, ownership evidence, required VIN inspection, identification, insurance for registration, and transaction-specific documents to the county tax assessor-collector."],
] as const;

const faq = [
  { question: "What is a Texas bonded title?", answer: "A bonded title is a Texas certificate of title issued after an applicant proves eligibility and purchases a surety bond that protects prior owners, lienholders, and other parties who may later establish a valid ownership claim." },
  { question: "How much is the Texas bonded-title surety bond?", answer: "TxDMV sets the required bond amount at one and one-half times the vehicle's determined value. The premium paid to the surety company is not the full bond amount and varies by provider and applicant risk." },
  { question: "What form starts the Texas bonded-title process?", answer: "Use the Bonded Title Application or Tax Collector Hearing Statement of Fact, Form VTR-130-SOF, and submit it to the TxDMV Regional Service Center serving your county with supporting evidence, identification, and the $15 administrative fee." },
  { question: "Can I get a bonded title when the vehicle has a lien?", answer: "A recorded lien that is less than 10 years old generally requires an original lien release or letter of no interest. Without it, TxDMV says the applicant is not eligible for the bonded-title process and may need legal advice or a court order." },
  { question: "How long do I have to purchase the bond?", answer: "The TxDMV bond-determination notice is valid for one year. If you do not purchase the bond during that period, a new determination and bond may be required." },
  { question: "How quickly must I file after purchasing the bond?", answer: "TxDMV instructs applicants to take the required documents to the county tax office within 30 days after purchasing the surety bond." },
  { question: "Does a bonded title erase ownership disputes?", answer: "No. The bond protects people who may have a valid ownership or lien claim. A bonded title does not guarantee that no prior claim exists, so buyers should still investigate the vehicle's history before purchasing." },
];

function BondedTitlesPage() {
  return (
    <main>vehicles.bonded-titles.tsx
      <HubBreadcrumbs current="Texas Bonded Titles" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas vehicle ownership</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Bonded Title Guide</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Learn how to pursue a Texas bonded title when ownership documents are missing, incomplete, or incorrect. Follow the TxDMV eligibility review, appraisal, surety-bond, VIN-inspection, and county filing process.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle/bought-a-vehicle-with-no-title" target="_blank" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Open official TxDMV instructions</a><a href="/find-my-dmv" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Find a regional or county office</a><a href="/vehicles/title-transfer" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Title-transfer guide</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><div className="rounded-xl border border-amber-300 bg-amber-50 p-6 text-amber-950"><h2 className="text-xl font-bold">Do not buy a vehicle without checking the title first</h2><p className="mt-2 leading-relaxed">A bonded title is a limited remedy for missing or defective ownership evidence—not a substitute for a properly assigned title. Verify the VIN, seller identity, lien status, theft history, and title brands before paying for a vehicle.</p></div><div className="mt-12"><h2 className="text-3xl font-bold">Texas bonded-title process</h2><div className="mt-7 space-y-4">{steps.map(([title, text]) => <article key={title} className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></article>)}</div></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Documents commonly required</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{["Form VTR-130-SOF","Bill of sale, invoice, canceled check, or other ownership evidence","Acceptable government-issued photo identification","Original lien release or letter of no interest when required","Form VTR-68-A when no Texas vehicle record exists","Form VTR-130-ND issued by TxDMV","Original vehicle surety bond","Form 130-U","Proof of liability insurance when registering","Weight certificate for certain trucks or commercial vehicles","Payment for title, registration, taxes, and county fees"].map((item) => <div key={item} className="rounded-xl border bg-card p-5 font-medium">{item}</div>)}</div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">How TxDMV determines the bond amount</h2><p className="mt-4 max-w-4xl leading-relaxed text-muted-foreground">The required surety bond equals 1.5 times the value assigned by TxDMV. The department generally starts with standard presumptive value, then may use a recognized vehicle-value guide or Form VTR-125 appraisal when necessary.</p><div className="mt-7 grid gap-5 md:grid-cols-3"><article className="rounded-xl border bg-card p-6"><h3 className="font-semibold">Older vehicles</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">For an appraisal below $4,000 on a vehicle at least 25 years old, TxDMV sets the value at $4,000.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="font-semibold">Trailers under 20 feet</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">TxDMV permits an established trailer value of $4,000 instead of an appraisal.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="font-semibold">Trailers 20 feet or longer</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">TxDMV permits an established trailer value of $7,000 instead of an appraisal.</p></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Bonded title vs. other ownership remedies</h2><div className="mt-7 grid gap-5 md:grid-cols-3"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Certified copy of title</h3><p className="mt-3 leading-relaxed text-muted-foreground">Use this when you are the recorded owner and the Texas title was lost or destroyed. It is usually simpler than a bonded title.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Tax assessor-collector hearing</h3><p className="mt-3 leading-relaxed text-muted-foreground">A person denied title may request a county hearing under Texas Transportation Code §501.052. Ask the county tax office for filing requirements.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Court order</h3><p className="mt-3 leading-relaxed text-muted-foreground">A court proceeding may be necessary when ownership is disputed, a required lien release cannot be obtained, or the vehicle is not eligible for the bonded-title process.</p></article></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></section>
      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-2xl font-bold">Related Texas vehicle resources</h2><div className="mt-5 flex flex-wrap gap-3"><a href="/vehicles/title-transfer" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Title transfer</a><a href="/vehicles/salvage-rebuilt-titles" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Salvage and rebuilt titles</a><a href="/vehicles/registration" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Vehicle registration</a><a href="/vehicles/temporary-tags" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Temporary permits</a><a href="/dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">DMV and DPS hub</a></div></div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground"><p>Bonded-title eligibility and required evidence depend on the vehicle record and transaction. Confirm current forms, lien requirements, valuation, inspection, bond, tax, title, and registration requirements with TxDMV, the surety provider, and your county tax assessor-collector.</p></div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/bonded-titles")({
  head: () => {
    const seo = buildSeo({ title: "Texas Bonded Title Guide: Forms, Bond Amount & Process", description: "Learn the Texas bonded-title process, including Form VTR-130-SOF, eligibility, VIN inspection, vehicle valuation, surety bond, Form 130-U, fees, and county filing.", path: "/vehicles/bonded-titles", type: "article", keywords: "Texas bonded title, Texas title bond, VTR-130-SOF, vehicle without title Texas, Texas surety bond title, VTR-130-ND, VTR-68-A" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Bonded Title Guide", description: "Texas bonded-title eligibility, forms, vehicle valuation, surety-bond, VIN-inspection, and county filing guidance.", mainEntityOfPage: `${SITE_URL}/vehicles/bonded-titles`, publisher: { "@type": "Organization", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV & Driver Services", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Texas Bonded Titles", item: `${SITE_URL}/vehicles/bonded-titles` }] }) },
    ] };
  },
  component: BondedTitlesPage,
});
