import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "How do I replace a lost Texas vehicle title?", answer: "Apply for a certified copy using Form VTR-34 through a TxDMV Regional Service Center. All recorded owners must sign, identification is required, and an original lien release may be needed when a lien remains on record." },
  { question: "How much does a certified copy of title cost?", answer: "TxDMV lists a $2 mail-in fee and a $5.45 in-person fee. Confirm current payment methods and convenience charges before applying." },
  { question: "Can a county tax office correct a title error?", answer: "Yes. Contact the county tax assessor-collector. Errors made by TxDMV or the county may be corrected without charge; errors based on information supplied in the application generally require a new application and fee." },
  { question: "How do I add or remove a lien?", answer: "Use Form 130-U and the required ownership or lien documents at the county tax office. An additional lien generally also requires Form VTR-267." },
];

function Page() {
  return <main>
    <HubBreadcrumbs current="Liens, Duplicate Titles & Corrected Titles" />
    <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas vehicle titles</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Liens, Duplicate Titles & Corrected Titles</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Replace a lost title, correct a name or vehicle-data error, add or release a lien, and understand which transaction belongs with TxDMV or your county tax office.</p></div></section>
    <section className="mx-auto max-w-5xl px-4 py-14 space-y-12">
      <section><h2 className="text-3xl font-bold">Certified copy of title</h2><p className="mt-4 leading-relaxed text-muted-foreground">Texas calls a replacement title a certified copy of title. Complete Form VTR-34, obtain signatures from every recorded owner, include current government-issued photo identification, and provide an original lien release when a paid lien still appears in the title record.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h3 className="font-semibold">Apply by mail</h3><p className="mt-2 text-sm text-muted-foreground">TxDMV lists a $2 mail-in fee. Use the address and payment instructions printed on the current form.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-semibold">Apply in person</h3><p className="mt-2 text-sm text-muted-foreground">Visit a TxDMV Regional Service Center. Appointments are encouraged. TxDMV lists a $5.45 in-person fee plus any card convenience charge.</p></div></div><p className="mt-4 text-sm text-muted-foreground">A 30-day waiting period generally applies after the most recent title was issued.</p></section>
      <section><h2 className="text-3xl font-bold">Correcting a Texas title</h2><p className="mt-4 leading-relaxed text-muted-foreground">Start with the county tax assessor-collector that handles title transactions. Bring the title, identification, supporting evidence, and a corrected Form 130-U when requested. If TxDMV or the county caused the error, correction may be free. If the title reflects information supplied on the original application, a new application and title fee normally apply.</p></section>
      <section><h2 className="text-3xl font-bold">Adding or removing a lien</h2><div className="mt-6 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-4 py-3">Transaction</th><th className="px-4 py-3">Typical documents</th></tr></thead><tbody className="divide-y"><tr><td className="px-4 py-3 font-semibold">Add a lien</td><td className="px-4 py-3">Current title and Form 130-U</td></tr><tr><td className="px-4 py-3 font-semibold">Add another lien</td><td className="px-4 py-3">Current title, Form 130-U, and Form VTR-267</td></tr><tr><td className="px-4 py-3 font-semibold">Remove a paper lien</td><td className="px-4 py-3">Released title or original lien release and county title application</td></tr><tr><td className="px-4 py-3 font-semibold">Remove an electronic lien</td><td className="px-4 py-3">Lienholder submits the electronic release; request a printed title if needed</td></tr></tbody></table></div><p className="mt-4 text-sm text-muted-foreground">Texas title fees are generally $28 or $33 depending on the county, plus any local or processing charges.</p></section>
      <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
    </section>
    <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground">Confirm forms, fees, lien status, signatures, identification requirements, and office procedures with TxDMV or the county tax assessor-collector before filing.</div></section>
  </main>;
}

export const Route = createFileRoute("/vehicles/liens-duplicate-corrected-titles")({
  head: () => { const seo = buildSeo({ title: "Texas Duplicate Titles, Lien Releases & Title Corrections", description: "How to replace a lost Texas title, correct title errors, add or remove a lien, and use Forms VTR-34, 130-U, and VTR-267.", path: "/vehicles/liens-duplicate-corrected-titles", type: "article", keywords: "Texas duplicate title, VTR-34, Texas lien release, corrected vehicle title, VTR-267" }); return { meta: seo.meta, links: seo.links, scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Liens, Duplicate Titles & Corrected Titles", url: `${SITE_URL}/vehicles/liens-duplicate-corrected-titles` }) }, { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) }] }; },
  component: Page,
});