import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const steps = [
  ["Confirm insurance", "Texas requires liability coverage of at least $30,000 per injured person, $60,000 per accident, and $25,000 for property damage. Some out-of-state policies may qualify, but confirm with your insurer before visiting the county office."],
  ["Complete any required inspection", "Most non-commercial vehicles no longer need an annual safety inspection. Commercial vehicles still do, and vehicles registered in an emissions county must pass emissions testing before registration."],
  ["Prepare Form 130-U", "Complete the Application for Texas Title and/or Registration. New residents who keep the out-of-state title can select Registration Purposes Only when permitted."],
  ["Visit the county tax office", "Bring proof of ownership, identification, insurance, inspection evidence when applicable, Form 130-U, and payment for tax, registration, title, county, processing, and plate charges."],
  ["Apply for a Texas driver license", "Vehicle registration is handled through the county tax office. Driver licenses and identification cards are handled separately by the Texas Department of Public Safety."],
] as const;

const emissionsCounties = ["Brazoria", "Collin", "Dallas", "Denton", "El Paso", "Ellis", "Fort Bend", "Galveston", "Harris", "Johnson", "Kaufman", "Montgomery", "Parker", "Rockwall", "Tarrant", "Travis", "Williamson"] as const;

const faq = [
  { question: "How long does a new Texas resident have to register a vehicle?", answer: "TxDMV generally requires a new resident to register a vehicle within 30 days after moving to Texas. Delays can result in penalties or added complications." },
  { question: "Do I have to surrender my out-of-state title?", answer: "Not always. Texas allows Registration Purposes Only in some situations. Complete Form 130-U and check the appropriate box if you are keeping the out-of-state title." },
  { question: "How much is the Texas new-resident vehicle tax?", answer: "A qualifying vehicle that was previously registered in the new resident's name outside Texas is generally subject to a $90 new-resident tax instead of the 6.25% use tax." },
  { question: "Do new residents need a Texas vehicle inspection?", answer: "Commercial vehicles still need a safety inspection. Non-commercial vehicles in designated emissions counties need a passing emissions inspection before registration." },
  { question: "Can I register before getting a Texas driver license?", answer: "Yes. Vehicle registration and driver licensing are separate transactions. Register through the county tax office, then apply for a Texas driver license through DPS." },
  { question: "What if the vehicle is leased?", answer: "A qualifying new resident who leased the vehicle outside Texas before moving may still owe the $90 new-resident tax. The county may require lease and lessor documentation." },
  { question: "Do active-duty military members get more time?", answer: "Texas motor vehicle tax guidance generally gives active-duty military personnel 60 calendar days for certain tax payments, but registration and residency facts can affect the result. Confirm with the county tax office." },
];

function VehicleNewResidentsPage() {
  return (
    <main>
      <HubBreadcrumbs current="Vehicle Registration for New Texas Residents" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Moving to Texas</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Vehicle Registration for New Texas Residents</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Follow the Texas sequence for insurance, inspections, title or registration paperwork, taxes, county fees, plates, and your separate DPS driver-license appointment.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://texasdefined.com/moving-to-texas" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Open the moving checklist</a><a href="/find-my-dmv" className="rounded-md border px-5 py-3 text-sm font-semibold">Find your county office</a><a href="/vehicles/registration-fees-taxes" className="rounded-md border px-5 py-3 text-sm font-semibold">Estimate fees and taxes</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">The 30-day Texas deadline</h2><p className="mt-4 max-w-3xl leading-relaxed text-muted-foreground">New residents generally have 30 days after moving to Texas to register vehicles brought into the state. The process is completed through the county tax assessor-collector, not a DPS driver-license office.</p><div className="mt-8 rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">Important distinction</h3><p className="mt-3 text-muted-foreground">Registering the vehicle, transferring or retaining the title, paying motor vehicle tax, and obtaining plates are county tax-office functions. Getting a Texas driver license is a separate DPS transaction.</p></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Step-by-step registration process</h2><div className="mt-8 space-y-5">{steps.map(([title, body], index) => <article key={title} className="rounded-xl border bg-card p-6"><div className="flex gap-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary font-bold text-primary-foreground">{index + 1}</div><div><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{body}</p></div></div></article>)}</div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Documents to bring</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><div className="rounded-xl border bg-card p-6"><h3 className="font-bold">Core documents</h3><ul className="mt-4 list-disc space-y-2 pl-5 text-muted-foreground"><li>Out-of-state title or current registration receipt</li><li>Completed Form 130-U</li><li>Current driver license or government-issued photo ID</li><li>Proof of current vehicle insurance</li><li>Inspection report when required</li></ul></div><div className="rounded-xl border bg-card p-6"><h3 className="font-bold">May also be required</h3><ul className="mt-4 list-disc space-y-2 pl-5 text-muted-foreground"><li>Lienholder or lease documentation</li><li>Original lien release</li><li>Vehicle Identification Certificate or supporting ownership records</li><li>Payment for title, registration, county, processing, tax, plate, inspection, and EV charges</li></ul></div></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Inspection and emissions rules</h2><p className="mt-4 max-w-3xl text-muted-foreground">Since January 1, 2025, most non-commercial vehicles are no longer subject to a comprehensive annual safety inspection. Commercial vehicles still require a safety inspection. Non-commercial vehicles registered in designated emissions counties must pass emissions testing before registration.</p><div className="mt-7 rounded-xl border bg-card p-6"><h3 className="font-bold">Current emissions counties</h3><p className="mt-3 leading-relaxed text-muted-foreground">{emissionsCounties.join(", ")}. Bexar County is scheduled to begin emissions testing on November 1, 2026.</p><a href="/vehicles/inspections-emissions" className="mt-5 inline-block font-semibold text-primary">Read the complete inspection and emissions guide →</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Taxes and fees for new residents</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">$90 new-resident tax</h3><p className="mt-3 text-muted-foreground">A qualifying vehicle brought into Texas by a new resident is generally subject to a $90 new-resident tax when it was previously registered in that resident's name in another state or foreign country.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">When 6.25% use tax may apply</h3><p className="mt-3 text-muted-foreground">Use tax may apply when the vehicle was not previously registered in the new resident's name, when residency rules are not met, or when an existing Texas resident brings in an out-of-state purchase.</p></article></div><p className="mt-6 text-muted-foreground">Registration, title, county, processing, inspection-replacement, specialty-plate, and electric-vehicle fees may be charged in addition to tax.</p></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Connect this task to your Texas move</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Moving to Texas Resource Center", "https://texasdefined.com/moving-to-texas"],["Interactive Moving Checklist", "https://texasdefined.com/moving-to-texas"],["Texas Moving Cost Calculator", "/texas-moving-cost-calculator"],["Texas Driver License Guide", "/dmv/driver-license"],["Texas Vehicle Registration Guide", "/vehicles/registration"],["Registration Fees and Taxes", "/vehicles/registration-fees-taxes"]].map(([title, href]) => <a key={`${title}-${href}`} href={href} className="rounded-xl border bg-card p-5 font-semibold transition hover:-translate-y-0.5 hover:shadow-md">{title}<span className="mt-3 block text-sm text-primary">Open guide →</span></a>)}</div></div></section>

      <section className="mx-auto max-w-4xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-4xl px-4 py-10 text-sm text-muted-foreground">Deadlines, tax treatment, fees, inspection rules, forms, acceptable ownership evidence, and county procedures can change. Confirm your transaction with the county tax assessor-collector, TxDMV, and the Texas Comptroller before visiting an office.</div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/new-residents")({
  head: () => {
    const seo = buildSeo({ title: "Vehicle Registration for New Texas Residents", description: "How new Texas residents register an out-of-state vehicle, including the 30-day deadline, insurance, inspections, Form 130-U, the $90 tax, fees, and county office steps.", path: "/vehicles/new-residents", type: "article", keywords: "Texas vehicle registration new resident, register out of state vehicle Texas, moving to Texas car registration, Texas new resident vehicle tax" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Vehicle Registration for New Texas Residents", url: `${SITE_URL}/vehicles/new-residents`, isPartOf: { "@type": "WebSite", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Vehicle Registration for New Residents", item: `${SITE_URL}/vehicles/new-residents` }] }) },
    ] };
  },
  component: VehicleNewResidentsPage,
});