import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "How much is a Texas disabled parking placard?", answer: "A permanent blue placard has no fee. A temporary red placard costs $5. Confirm accepted payment methods with your county tax office." },
  { question: "How long is a Texas disabled parking placard valid?", answer: "A temporary red placard expires in six months or less. A permanent blue placard is renewable every four years." },
  { question: "Can a disabled veteran plate without the ISA use an accessible parking space?", answer: "No. Texas requires either a disabled parking placard or a license plate displaying the International Symbol of Access to use a designated accessible parking space." },
  { question: "Can someone else use my placard?", answer: "Only when the person with the disability is in the vehicle, either driving or being transported. Misuse can lead to fines and community service." },
  { question: "Where do I apply?", answer: "Apply in person or by mail through the county tax assessor-collector office in your county of residence using the required TxDMV form and medical certification." },
];

function DisabledParkingPage() {
  return (
    <main>
      <HubBreadcrumbs current="Texas Disabled Parking Placards and License Plates" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas accessible parking</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Disabled Parking Placards and License Plates</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Learn who qualifies for a Texas disabled parking placard or license plate, which forms to use, how medical certification works, what the placards cost, and when a Disabled Veteran plate does or does not include accessible-parking privileges.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/find-my-dmv" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Find your county tax office</a><a href="/vehicles/plates" className="rounded-md border px-5 py-3 text-sm font-semibold">Texas license plates guide</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Placard and plate options</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">Temporary red placard</h3><p className="mt-3 text-muted-foreground">For a qualifying temporary disability. It expires in six months or less and generally costs $5.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">Permanent blue placard</h3><p className="mt-3 text-muted-foreground">For a qualifying permanent disability. There is no fee, and it is renewable every four years.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">ISA license plate</h3><p className="mt-3 text-muted-foreground">A license plate displaying the International Symbol of Access is available for a qualifying permanent disability.</p></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Who qualifies?</h2><p className="mt-4 max-w-3xl text-muted-foreground">Eligibility is based on the Texas legal definition of disability. Qualifying conditions include severe visual impairment or mobility limitations that substantially impair a person's ability to move around. Mobility limitations may result from paralysis, lung disease, cardiac deficiency, wheelchair use, arthritis, a foot disorder, or another condition requiring a brace, cane, crutch, or similar assistive device.</p><p className="mt-4 max-w-3xl text-muted-foreground">A licensed physician or other authorized health care provider must complete the disability certification or provide an acceptable original prescription.</p></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">How to apply</h2><ol className="mt-7 space-y-4 text-muted-foreground"><li><strong className="text-foreground">1. Complete Form VTR-214.</strong> Use the Application for Persons with Disabilities Parking Placard and/or License Plate.</li><li><strong className="text-foreground">2. Obtain medical certification.</strong> Have the authorized provider complete the disability statement or supply the required original prescription.</li><li><strong className="text-foreground">3. Include identification.</strong> Provide a copy of the applicant's current driver license or government-issued photo ID.</li><li><strong className="text-foreground">4. Submit through the county.</strong> Apply in person or by mail at the county tax assessor-collector office in the applicant's county of residence.</li><li><strong className="text-foreground">5. Pay any applicable fee.</strong> Permanent placards are free; temporary placards are generally $5.</li></ol></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Renewal and replacement</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">Permanent placard renewal</h3><p className="mt-3 text-muted-foreground">Complete a new Form VTR-214. The health care provider generally does not need to recertify the disability when the renewal is supported by the original application or the expiring placard, subject to county requirements.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">Temporary placard expiration</h3><p className="mt-3 text-muted-foreground">A temporary placard is not simply extended. Apply for a new placard with new medical certification if the temporary disability continues beyond the original expiration date.</p></article></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Disabled Veteran plates and accessible parking</h2><p className="mt-4 max-w-3xl text-muted-foreground">Disabled Veteran plates use Form VTR-615 and have separate military-service eligibility rules. A DV plate without the International Symbol of Access does not authorize parking in an accessible space. A veteran who needs accessible-parking privileges must qualify for a placard or an ISA-bearing plate under the disability standard.</p><p className="mt-4 max-w-3xl text-muted-foreground">Government-meter exemptions and other parking benefits can vary by plate type and local ordinance. Private garages, airports, campuses, and federal facilities may follow different rules.</p></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Using the placard legally</h2><ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground"><li>The person with the disability must be driving or riding in the vehicle.</li><li>Display the placard as required when parked, but remove it from the mirror before driving if it obstructs visibility.</li><li>A valid placard or ISA plate may be used in designated accessible spaces.</li><li>Meter exemptions apply to state and local government meters, but local time limits may still apply.</li><li>Misuse can result in fines of up to $1,250 and up to 50 hours of community service.</li></ul></div></section>

      <section className="mx-auto max-w-4xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-4xl px-4 py-10 text-sm text-muted-foreground">Eligibility, forms, medical-certification rules, fees, and local parking privileges can change. Confirm current requirements with TxDMV and your county tax assessor-collector.</div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/disabled-parking")({
  head: () => {
    const seo = buildSeo({ title: "Texas Disabled Parking Placards and License Plates", description: "Texas disabled parking placard and license plate eligibility, Form VTR-214, fees, renewals, ISA requirements, and Disabled Veteran plate rules.", path: "/vehicles/disabled-parking", type: "article", keywords: "Texas disabled parking placard, Texas handicap placard, Form VTR-214, disabled license plate Texas, Disabled Veteran plate ISA" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Disabled Parking Placards and License Plates", url: `${SITE_URL}/vehicles/disabled-parking`, isPartOf: { "@type": "WebSite", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Disabled Parking Placards and Plates", item: `${SITE_URL}/vehicles/disabled-parking` }] }) },
    ] };
  },
  component: DisabledParkingPage,
});