import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "What forms are used in a Texas private vehicle sale?", answer: "The core documents are the properly assigned original title and Form 130-U. A lien release, power of attorney, gift affidavit, estate document, or other supporting record may also be required." },
  { question: "Who pays the tax in a private sale?", answer: "The buyer pays Texas motor-vehicle sales tax when applying for title. The rate is generally 6.25%, subject to standard presumptive value and other rules." },
  { question: "Does a bill of sale replace the title?", answer: "No. A bill of sale is useful evidence, but it does not replace the properly assigned title and required title application." },
  { question: "What if the seller has no title?", answer: "Do not complete the purchase based only on a promise. The seller should first obtain a certified copy or resolve the ownership problem. Some buyers may qualify for a bonded-title process, but approval is not guaranteed." },
];

function PrivatePartySalesPage() { return <main>
  <HubBreadcrumbs current="Texas Private Party Vehicle Sales" />
  <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Buyer and seller transaction guide</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Private Party Vehicle Sales</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">A step-by-step process for safe payment, title assignment, Form 130-U, taxes, plates, insurance, transit permits, and seller protection.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/vehicles/buying-a-car" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Buyer guide</a><a href="/vehicles/selling-a-car" className="rounded-md border px-5 py-3 text-sm font-semibold">Seller guide</a></div></div></section>
  <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
    <section><h2 className="text-3xl font-bold">Best practice: meet at the county tax office</h2><p className="mt-4">When possible, buyer and seller should complete the transaction at the county tax assessor-collector. Staff can identify obvious title problems before funds and possession are fully exchanged, and the seller can confirm that the buyer filed the title application.</p></section>
    <section><h2 className="text-3xl font-bold">Private-sale sequence</h2><ol className="mt-5 list-decimal space-y-3 pl-6"><li>Verify identities, VIN, title ownership, brands, and liens.</li><li>Complete an independent inspection and history check.</li><li>Agree in writing on price, payment, included property, and delivery.</li><li>Verify payment before transferring possession.</li><li>Complete the original title and Form 130-U without blanks or alterations.</li><li>Exchange lien releases and supporting documents.</li><li>Record the exact date and time possession changes.</li><li>Buyer applies for title within 30 days.</li><li>Seller files the Vehicle Transfer Notification within 30 days.</li></ol></section>
    <section><h2 className="text-3xl font-bold">Taxes and standard presumptive value</h2><p className="mt-4">The buyer generally pays 6.25% motor-vehicle sales tax. For many private-party used-vehicle transactions, the taxable amount is the greater of the reported purchase price or 80% of standard presumptive value. Qualifying gifts, dealer transactions, appraisals, and other exceptions follow different rules.</p></section>
    <section><h2 className="text-3xl font-bold">Plates and five-day transit permit</h2><p className="mt-4">The seller may remove the plates. A qualifying buyer can obtain one Vehicle Transit Permit valid for five calendar days to move the vehicle under the permit rules. A transit permit does not provide insurance or extend the title-transfer deadline.</p></section>
    <section><h2 className="text-3xl font-bold">Fraud and safety precautions</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Buyer</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-muted-foreground"><li>Never accept an open title.</li><li>Match seller ID to the title.</li><li>Check VIN and lien status.</li><li>Do not report a false price.</li></ul></div><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Seller</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-muted-foreground"><li>Verify cleared funds.</li><li>Keep copies and buyer details.</li><li>Remove toll tags and personal data.</li><li>File the transfer notification.</li></ul></div></div></section>
    <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
  </article>
</main>; }

export const Route = createFileRoute("/vehicles/private-party-sales")({ head: () => { const seo = buildSeo({ title: "Texas Private Party Vehicle Sales: Buyer and Seller Guide", description: "Texas private car sale guide covering title assignment, Form 130-U, taxes, VIN checks, payment, plates, permits and transfer notifications.", path: "/vehicles/private-party-sales", type: "article", keywords: "Texas private party car sale, private vehicle sale Texas, Form 130-U, Texas car bill of sale" }); return { meta: seo.meta, links: seo.links, scripts: [{ type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Texas Private Party Vehicle Sales", url:`${SITE_URL}/vehicles/private-party-sales` }) }, { type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item)=>({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) }] }; }, component: PrivatePartySalesPage });