import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const categories = [
  ["Farm trucks and truck tractors", "Use Form VTR-52-A. Eligibility depends on agricultural use, ownership, vehicle type, and registered weight. Farm registration does not authorize unrestricted commercial hauling."],
  ["Farm trailers and semitrailers", "A qualifying farm trailer may receive a Farm Trailer plate for a $5 fee. Trailers at 4,000 pounds gross weight or less may be exempt from both title and registration; title rules change above 4,000 and 34,000 pounds."],
  ["Antique vehicles", "Use Form VTR-54 for a qualifying vehicle at least 25 years old. Antique registration is intended for exhibitions, club activities, parades, maintenance, and limited pleasure use rather than routine transportation."],
  ["Classic vehicles", "Use Form VTR-850 for a qualifying vehicle at least 25 years old. Classic plates generally preserve normal vehicle use and annual registration obligations rather than imposing antique-use limits."],
  ["Custom vehicles and street rods", "Use Form VTR-852 and the required ASE safety inspection documentation. These categories depend on the vehicle's age, construction, design, and equipment."],
  ["Specialty and personalized plates", "Many organizational, occupational, military, charitable, collegiate, and personalized designs use Form VTR-999 or another plate-specific form. Fees and renewal rules vary by plate."],
] as const;

const faq = [
  { question: "How old must a vehicle be for Texas antique or classic plates?", answer: "The vehicle must generally be at least 25 years old. Antique and classic registration are not interchangeable: antique use is restricted, while classic registration generally allows ordinary operation subject to regular registration requirements." },
  { question: "Can an antique-plated vehicle be used as a daily driver?", answer: "No. Texas antique registration is for limited uses such as exhibitions, club activities, parades, maintenance, and occasional pleasure driving. A vehicle used for routine transportation should generally use regular or classic registration." },
  { question: "Does every farm trailer need a Texas title?", answer: "No. A qualifying farm trailer at 34,000 pounds gross weight or less may be titled at the owner's option unless it was previously titled. A farm trailer over 34,000 pounds must be titled and does not qualify for Farm Trailer plates." },
  { question: "Is registration required for a farm trailer weighing 4,000 pounds or less?", answer: "Registration may be optional when the trailer qualifies as a farm trailer and is primarily used as a farm vehicle. Owners may still obtain a Farm Trailer plate." },
  { question: "Where do I apply for farm, antique, classic, or specialty plates?", answer: "Most applications are submitted to the county tax assessor-collector. Some specialty and personalized plates may also be ordered through the state's specialty-plate vendor." },
];

function FarmAntiqueSpecialtyPage() {
  return (
    <main>
      <HubBreadcrumbs current="Farm, Antique, Classic & Specialty Vehicle Registration" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas special registration classes</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Farm, Antique, Classic & Specialty Vehicle Registration</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Choose the correct Texas registration class, plate application, use restrictions, title treatment, and county filing process for farm vehicles, farm trailers, antique and classic vehicles, street rods, custom vehicles, and specialty plates.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/find-my-dmv" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Find your county tax office</a><a href="/vehicles/plates" className="rounded-md border px-5 py-3 text-sm font-semibold">Texas license plate guide</a><a href="/vehicles/registration" className="rounded-md border px-5 py-3 text-sm font-semibold">Registration guide</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Which Texas registration category fits?</h2><p className="mt-4 max-w-3xl text-muted-foreground">The plate is not merely decorative. Each registration class has its own eligibility, permitted uses, fees, inspection treatment, weight limits, and paperwork.</p><div className="mt-8 grid gap-5 md:grid-cols-2">{categories.map(([title, description]) => <article key={title} className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 leading-relaxed text-muted-foreground">{description}</p></article>)}</div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Farm trailer title and registration thresholds</h2><div className="mt-8 overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-4 py-3">Gross weight</th><th className="px-4 py-3">General treatment for a qualifying farm trailer</th></tr></thead><tbody className="divide-y"><tr><td className="px-4 py-3 font-semibold">4,000 lbs. or less</td><td className="px-4 py-3">May be exempt from title and registration when primarily used as a farm vehicle; optional title and Farm Trailer plate are available.</td></tr><tr><td className="px-4 py-3 font-semibold">Over 4,000 through 34,000 lbs.</td><td className="px-4 py-3">Title is generally optional unless previously titled; qualifies for Farm Trailer plates.</td></tr><tr><td className="px-4 py-3 font-semibold">Over 34,000 lbs.</td><td className="px-4 py-3">Must be titled and registered with regular Trailer plates; does not qualify for Farm Trailer plates.</td></tr></tbody></table></div><p className="mt-5 text-sm text-muted-foreground">A qualifying farm trailer must be used for authorized agricultural purposes such as transporting agricultural products, livestock, farm supplies, or participating in equine activities or livestock shows. County offices may request ownership evidence, weight documentation, photographs, or additional forms.</p></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Antique versus classic registration</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">Antique plates</h3><p className="mt-3 text-muted-foreground">Antique registration uses Form VTR-54 and carries significant operating restrictions. It works best for a collector vehicle that is not used for regular transportation. Confirm the current multi-year registration period, fee, insurance, inspection, and plate-display requirements with the county office.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-bold">Classic plates</h3><p className="mt-3 text-muted-foreground">Classic registration uses Form VTR-850. The vehicle must generally be at least 25 years old, but ordinary use is permitted. Regular registration fees, annual renewal rules, insurance, and any applicable emissions requirements generally remain in effect.</p></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Forms commonly used</h2><ul className="mt-6 list-disc space-y-3 pl-6 text-muted-foreground"><li><strong>VTR-52-A:</strong> Application for Farm License Plate.</li><li><strong>VTR-54:</strong> Application for Antique License Plate.</li><li><strong>VTR-850:</strong> Application for Classic License Plates.</li><li><strong>VTR-852:</strong> ASE Safety Inspection and Application for Custom Vehicle or Street Rod License Plates.</li><li><strong>VTR-999:</strong> General Application for Specialty License Plates when a plate-specific form is not required.</li><li><strong>Form 130-U:</strong> Application for Texas Title and/or Registration when a title or ownership transaction is part of the filing.</li></ul></div></section>

      <section className="mx-auto max-w-4xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-4xl px-4 py-10 text-sm text-muted-foreground">Special registration rules and forms can change. Before filing, confirm eligibility, permitted use, vehicle age, gross weight, inspection status, fees, title requirements, and supporting documents with TxDMV and the county tax assessor-collector.</div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/farm-antique-specialty")({
  head: () => {
    const seo = buildSeo({ title: "Texas Farm, Antique, Classic & Specialty Vehicle Registration", description: "Texas farm truck and trailer registration, antique and classic vehicle plates, specialty plates, forms, restrictions, title thresholds, and county filing steps.", path: "/vehicles/farm-antique-specialty", type: "article", keywords: "Texas farm vehicle registration, Texas farm trailer plate, Texas antique plates, Texas classic plates, Texas specialty license plates" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Farm, Antique, Classic & Specialty Vehicle Registration", url: `${SITE_URL}/vehicles/farm-antique-specialty`, isPartOf: { "@type": "WebSite", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Farm, Antique, Classic & Specialty Registration", item: `${SITE_URL}/vehicles/farm-antique-specialty` }] }) },
    ] };
  },
  component: FarmAntiqueSpecialtyPage,
});