import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "How long do I have to title a vehicle after buying it in Texas?", answer: "A buyer generally must apply for title within 30 calendar days after the sale to avoid delinquent-transfer penalties." },
  { question: "Should I buy a vehicle without the original title?", answer: "No. TxDMV warns buyers not to leave a private sale without the properly assigned original title. Missing or defective ownership documents can require a bonded-title or court process." },
  { question: "How is sales tax calculated on a private-party purchase?", answer: "Texas generally charges 6.25% motor-vehicle sales tax. For many private-party used vehicles, tax is based on the greater of the purchase price or 80% of standard presumptive value unless an exception applies." },
  { question: "Can I drive the car if the seller keeps the plates?", answer: "A qualifying buyer may obtain one five-day Vehicle Transit Permit for the sale, but insurance and all permit conditions still apply." },
];

function BuyingCarPage() { return <main>
  <HubBreadcrumbs current="Buying a Car in Texas" />
  <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas buyer checklist</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Buying a Car in Texas</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">Verify the seller, VIN, title, liens, condition, taxes, insurance, inspection status, and transfer paperwork before money changes hands.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Official TxDMV guide</a><a href="/vehicles/private-party-sales" className="rounded-md border px-5 py-3 text-sm font-semibold">Private-sale checklist</a></div></div></section>
  <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
    <section><h2 className="text-3xl font-bold">Before paying</h2><ol className="mt-5 list-decimal space-y-3 pl-6"><li>Match the VIN on the dashboard, door label, and title.</li><li>Confirm the seller is the titled owner or has valid authority.</li><li>Review the title for liens, brands, alterations, and missing signatures.</li><li>Run a TxDMV-approved NMVTIS title-history check.</li><li>Arrange an independent mechanical inspection.</li><li>Verify insurance cost and lender requirements.</li><li>Calculate taxes, title, registration, and local fees.</li></ol></section>
    <section><h2 className="text-3xl font-bold">Documents to receive</h2><ul className="mt-5 list-disc space-y-3 pl-6"><li>Properly assigned original title with sale date and odometer disclosure when required.</li><li>Signed Form 130-U with the sales price.</li><li>Original lien release when a lien has been paid but remains recorded.</li><li>Bill of sale and payment receipt.</li><li>Any supporting power-of-attorney, estate, gift, or court documents.</li><li>Latest Vehicle Inspection Report when applicable and available.</li></ul></section>
    <section><h2 className="text-3xl font-bold">Dealer versus individual seller</h2><p className="mt-4">A licensed dealer normally files the title application for you and should provide a receipt showing the vehicle was titled in your name. In a private sale, the buyer is responsible for filing. TxDMV recommends that buyer and seller visit the county tax office together when possible.</p></section>
    <section><h2 className="text-3xl font-bold">Title and register within 30 days</h2><p className="mt-4">Take the assigned title, Form 130-U, proof of insurance, identification, inspection evidence when required, lien documents, and payment to the county tax assessor-collector. Delays can create penalties and leave the vehicle recorded in the seller's name.</p></section>
    <section className="rounded-xl border bg-muted/20 p-6"><h2 className="text-2xl font-bold">Walk away when</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>The seller will not show ID or is not the titled owner.</li><li>The VIN is altered or does not match.</li><li>The title is missing, open, erased, or reassigned through skipped owners.</li><li>A lien has no acceptable release.</li><li>The seller pressures you to report a false price.</li><li>The deal depends on promises to provide the title later.</li></ul></section>
    <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
  </article>
</main>; }

export const Route = createFileRoute("/vehicles/buying-a-car")({ head: () => { const seo = buildSeo({ title: "Buying a Car in Texas: Title, Tax and Inspection Checklist", description: "Texas car-buying checklist for title verification, VIN checks, liens, Form 130-U, sales tax, insurance, inspections and the 30-day deadline.", path: "/vehicles/buying-a-car", type: "article", keywords: "buying a car in Texas, Texas used car checklist, Texas vehicle title check, Form 130-U" }); return { meta: seo.meta, links: seo.links, scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Buying a Car in Texas", url:`${SITE_URL}/vehicles/buying-a-car` }) }, { type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item)=>({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) }] }; }, component: BuyingCarPage });