import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const steps = [
  ["1. Check the title before paying", "Match the VIN on the vehicle to the title, review the owner and lien information, and consider an NMVTIS title-history report before completing a private sale."],
  ["2. Complete the title assignment", "The seller should properly sign the negotiable title and enter the sale date and odometer reading when required. Do not accept an open title or leave required fields blank."],
  ["3. Complete Form 130-U", "The buyer and seller should complete and sign the Application for Texas Title and/or Registration, including the actual sales price and vehicle information."],
  ["4. Gather supporting documents", "Bring the signed title, Form 130-U, proof of liability insurance for registration, identification, lien-release documents when applicable, and any inspection or emissions record requested by the county."],
  ["5. Apply at the county tax office", "The buyer generally applies through the county tax assessor-collector within 30 calendar days of the sale and pays title, registration, local, and motor-vehicle tax amounts."],
] as const;

const faq = [
  { question: "How long does a Texas buyer have to transfer a vehicle title?", answer: "TxDMV says the vehicle must be titled in the buyer's name within 30 days of the sale. Waiting longer can trigger delinquent-transfer penalties." },
  { question: "What form is used for a Texas vehicle title transfer?", answer: "Most transfers use a properly assigned negotiable title and Application for Texas Title and/or Registration, Form 130-U. Special transfers may require additional affidavits or court documents." },
  { question: "How is Texas tax calculated on a private-party vehicle sale?", answer: "Texas motor-vehicle sales tax is generally 6.25% of the taxable value. For many private-party used-vehicle purchases, taxable value may be based on the greater of the sales price or 80% of the standard presumptive value unless an eligible certified appraisal or exception applies." },
  { question: "Should the seller file a Vehicle Transfer Notification?", answer: "Yes. TxDMV recommends filing the notification within 30 days. It updates the state motor-vehicle record to show the vehicle as sold and helps protect the seller from later toll and parking liabilities." },
  { question: "Can a gifted vehicle be transferred without sales tax?", answer: "Certain qualifying gifts use Form 14-317 and are subject to a $10 gift tax rather than ordinary sales tax. Both parties must satisfy the relationship and documentation rules." },
  { question: "What happens to the license plates after a private sale?", answer: "Texas sellers may remove and keep, transfer, or properly dispose of their plates. When plates are removed, the buyer may need a five-day Vehicle Transit Permit to move the vehicle legally." },
];

function TitleTransferPage() {
  return (
    <main>
      <HubBreadcrumbs current="Texas Vehicle Title Transfer" />
      <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas vehicle ownership</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Vehicle Title Transfer Guide</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Transfer a Texas vehicle title after a private sale, gift, inheritance, divorce, or other ownership change. Learn the 30-day deadline, required documents, taxes, seller protections, and county-office process.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle" target="_blank" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Open official TxDMV instructions</a><a href="/find-my-dmv" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Find a county tax office</a><a href="/vehicles/registration" className="rounded-md border px-5 py-3 text-sm font-semibold hover:bg-muted">Registration guide</a></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><div className="rounded-xl border border-amber-300 bg-amber-50 p-6 text-amber-950"><h2 className="text-xl font-bold">Complete the transfer within 30 days</h2><p className="mt-2 leading-relaxed">Texas buyers generally must apply for title within 30 calendar days after the sale. The safest private-sale process is for the buyer and seller to visit the county tax office together so the application is actually filed.</p></div><div className="mt-12"><h2 className="text-3xl font-bold">Private-sale title transfer checklist</h2><div className="mt-7 space-y-4">{steps.map(([title, text]) => <article key={title} className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></article>)}</div></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">What the buyer should bring</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{["Properly assigned original title","Completed and signed Form 130-U","Proof of liability insurance for registration","Government-issued identification","Lien release when the title shows a paid lien","Inspection or emissions documentation when requested","Payment for title, registration, county, local, and tax amounts","Additional affidavit or court documents for gifts, inheritance, or divorce"].map((item) => <div key={item} className="rounded-xl border bg-card p-5 font-medium">{item}</div>)}</div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Texas sales tax and standard presumptive value</h2><p className="mt-4 max-w-4xl leading-relaxed text-muted-foreground">The Texas motor-vehicle sales-tax rate is generally 6.25%. In many private-party used-vehicle transactions, the county calculates tax using the greater of the stated sales price or 80% of the vehicle's standard presumptive value. A qualifying certified appraisal or statutory exception can change that calculation.</p><div className="mt-7 grid gap-5 md:grid-cols-3"><article className="rounded-xl border bg-card p-6"><h3 className="font-semibold">Private sale</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">The buyer generally pays tax to the county tax assessor-collector when applying for title.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="font-semibold">Qualifying gift</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Eligible gifts generally use Form 14-317 and carry a $10 gift tax.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="font-semibold">Even exchange</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">A qualifying even exchange may be subject to a $5 tax instead of ordinary sales tax.</p></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Seller protection after the sale</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">File a Vehicle Transfer Notification</h3><p className="mt-3 leading-relaxed text-muted-foreground">File it within 30 days so TxDMV can mark the motor-vehicle record as sold. This helps protect the seller from parking-ticket and toll responsibility tied to the buyer's later use.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Keep transaction records</h3><p className="mt-3 leading-relaxed text-muted-foreground">Keep the buyer's name and address, sale date, sales price, VIN, copies of signed documents, and proof that the transfer notification was submitted.</p></article></div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Special ownership transfers</h2><div className="mt-7 space-y-5"><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Gifted vehicle</h3><p className="mt-2 leading-relaxed text-muted-foreground">A qualifying gift generally requires the title, Form 130-U, and Affidavit of Motor Vehicle Gift Transfer, Form 14-317. Both donor and recipient sign the required documents and submit them through the county tax office.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Inheritance or death of an owner</h3><p className="mt-2 leading-relaxed text-muted-foreground">The county may require probate documents, an heirship affidavit such as Form VTR-262, a death certificate, or other estate documents depending on how ownership passes.</p></article><article className="rounded-xl border bg-card p-6"><h3 className="text-xl font-semibold">Divorce</h3><p className="mt-2 leading-relaxed text-muted-foreground">A certified divorce decree awarding the vehicle may support the transfer. If the decree does not award it, the former spouse may need to properly assign the title.</p></article></div></section>

      <section className="border-y bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-14"><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></div></section>

      <section className="mx-auto max-w-5xl px-4 py-12"><h2 className="text-2xl font-bold">Related Texas vehicle resources</h2><div className="mt-5 flex flex-wrap gap-3"><a href="/vehicles/registration" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Vehicle registration</a><a href="/vehicles/renewal" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Registration renewal</a><a href="/find-my-dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">Office finder and fee estimator</a><a href="/dmv" className="rounded-md border px-4 py-2 font-semibold hover:bg-muted">DMV and DPS hub</a></div></section>
      <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground"><p>County procedures and required documents can vary by transaction. Confirm current forms, taxes, fees, title status, inspection requirements, and acceptable evidence with TxDMV, the Texas Comptroller, and your county tax assessor-collector before completing the transfer.</p></div></section>
    </main>
  );
}

export const Route = createFileRoute("/vehicles/title-transfer")({
  head: () => {
    const seo = buildSeo({ title: "Texas Vehicle Title Transfer: Forms, Tax, Fees & 30-Day Rule", description: "Transfer a Texas vehicle title after a private sale, gift, inheritance, or divorce. Learn Form 130-U, tax rules, seller protection, documents, and deadlines.", path: "/vehicles/title-transfer", type: "article", keywords: "Texas vehicle title transfer, Texas car title transfer, Form 130-U, Texas private car sale, Texas vehicle gift transfer, standard presumptive value" });
    return { meta: seo.meta, links: seo.links, scripts: [
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Vehicle Title Transfer Guide", description: "Texas vehicle title transfer steps, documents, taxes, deadlines, and special-transfer guidance.", mainEntityOfPage: `${SITE_URL}/vehicles/title-transfer`, publisher: { "@type": "Organization", name: "Keep TX Red", url: `${SITE_URL}/` } }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) },
      { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` }, { "@type": "ListItem", position: 2, name: "Texas DMV & Driver Services", item: `${SITE_URL}/dmv` }, { "@type": "ListItem", position: 3, name: "Texas Vehicle Title Transfer", item: `${SITE_URL}/vehicles/title-transfer` }] }) },
    ] };
  },
  component: TitleTransferPage,
});