import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "Should I go to the tax office with the buyer?", answer: "TxDMV recommends accompanying the buyer when possible so you can confirm the title application is filed." },
  { question: "What is a Vehicle Transfer Notification?", answer: "It tells TxDMV that the vehicle was sold. Filing within 30 days helps protect the seller from qualifying parking-ticket and toll liability after the sale." },
  { question: "Can I keep my Texas license plates?", answer: "Yes. A seller may remove and retain eligible plates for later transfer, transfer them to another qualifying vehicle, or deface and dispose of them." },
  { question: "When should I cancel insurance?", answer: "Do not cancel coverage until payment, possession, keys, title documents, and responsibility have actually transferred. Coordinate the exact timing with your insurer." },
];

function SellingCarPage() { return <main>
  <HubBreadcrumbs current="Selling a Car in Texas" />
  <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas seller protection guide</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Selling a Car in Texas</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">Transfer the title correctly, document payment and possession, manage plates and insurance, and file the Vehicle Transfer Notification promptly.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Official TxDMV guide</a><a href="/vehicles/private-party-sales" className="rounded-md border px-5 py-3 text-sm font-semibold">Private-sale checklist</a></div></div></section>
  <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
    <section><h2 className="text-3xl font-bold">Before listing the vehicle</h2><ul className="mt-5 list-disc space-y-3 pl-6"><li>Locate the original title and confirm the owner names.</li><li>Resolve recorded liens and obtain an original release when needed.</li><li>Gather maintenance records and disclose known material problems honestly.</li><li>Decide which payment methods you will accept and how funds will be verified.</li><li>Remove personal data from infotainment, toll, garage, and connected-car systems.</li></ul></section>
    <section><h2 className="text-3xl font-bold">At the sale</h2><ol className="mt-5 list-decimal space-y-3 pl-6"><li>Verify the buyer's identity and record contact information.</li><li>Confirm cleared payment before releasing the title and vehicle.</li><li>Complete the title assignment with the sale date and odometer reading when required.</li><li>Sign Form 130-U and clearly report the actual sales price.</li><li>Give the buyer required lien and supporting documents.</li><li>Create a signed bill of sale and keep copies of everything.</li></ol></section>
    <section><h2 className="text-3xl font-bold">Protect yourself after the sale</h2><p className="mt-4">File the TxDMV Vehicle Transfer Notification within 30 days. The notification does not transfer ownership, but it updates the record to show the vehicle was sold and can protect you from certain later parking and toll claims. Keep the confirmation with your sale records.</p></section>
    <section><h2 className="text-3xl font-bold">Plates, sticker, toll tags, and insurance</h2><p className="mt-4">Texas sellers may remove their plates. Retain eligible plates for a future transfer or deface them before disposal. Remove toll tags and delete the vehicle from toll accounts. Coordinate insurance cancellation only after the transaction is complete and the buyer has taken possession.</p></section>
    <section className="rounded-xl border bg-muted/20 p-6"><h2 className="text-2xl font-bold">Records to keep</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>Buyer name, address, phone, and identification details.</li><li>VIN, plate number, mileage, price, sale date, and exact transfer time.</li><li>Signed title, Form 130-U, bill of sale, and lien release copies.</li><li>Proof and method of payment.</li><li>Vehicle Transfer Notification confirmation.</li><li>Messages and written disclosures about condition.</li></ul></section>
    <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
  </article>
</main>; }

export const Route = createFileRoute("/vehicles/selling-a-car")({ head: () => { const seo = buildSeo({ title: "Selling a Car in Texas: Title and Seller Checklist", description: "Texas car-selling guide for title assignment, Form 130-U, payment, plates, insurance, records and the Vehicle Transfer Notification.", path: "/vehicles/selling-a-car", type: "article", keywords: "selling a car in Texas, Texas Vehicle Transfer Notification, Texas car seller checklist, Form 130-U" }); return { meta: seo.meta, links: seo.links, scripts: [{ type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Selling a Car in Texas", url:`${SITE_URL}/vehicles/selling-a-car` }) }, { type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item)=>({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) }] }; }, component: SellingCarPage });