import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "What is apportioned registration?", answer: "Apportioned registration under the International Registration Plan lets qualifying interstate carriers register through one base jurisdiction and pay fees according to travel in participating jurisdictions." },
  { question: "How do new Texas IRP accounts apply?", answer: "TxDMV requires new motor carrier accounts to be created online through TxFLEET." },
  { question: "Does a Texas-only fleet need IRP?", answer: "Usually not. Texas-only operations may instead qualify for ordinary commercial registration or the Multi-Year Intrastate Fleet Registration Program." },
  { question: "When is proof of Heavy Vehicle Use Tax required?", answer: "Federal proof of HVUT payment is generally required when registering vehicles with a gross weight of 55,000 pounds or more." },
];

function Page() {
  return <main>
    <HubBreadcrumbs current="Fleet, Commercial & Apportioned Registration" />
    <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas motor carriers</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Fleet, Commercial & Apportioned Registration</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Compare Texas-only fleet registration, apportioned registration under IRP, token trailers, motor-carrier credentials, taxes, inspections, and recordkeeping.</p></div></section>
    <section className="mx-auto max-w-5xl px-4 py-14 space-y-12">
      <section><h2 className="text-3xl font-bold">Choose the right registration program</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-card p-5"><h3 className="font-semibold">Interstate operations</h3><p className="mt-2 text-sm text-muted-foreground">IRP apportioned registration may apply when qualifying commercial vehicles travel in more than one member jurisdiction.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-semibold">Texas-only fleets</h3><p className="mt-2 text-sm text-muted-foreground">The Multi-Year Intrastate Fleet Registration Program is available for eligible fleets with at least 12 Texas-only units and offers one- to eight-year registration.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-semibold">Trailers</h3><p className="mt-2 text-sm text-muted-foreground">Qualifying semi-trailers over 6,000 pounds may use the Token Trailer program for multi-year registration.</p></div></div></section>
      <section><h2 className="text-3xl font-bold">How Texas IRP registration works</h2><ol className="mt-5 list-decimal space-y-3 pl-6 text-muted-foreground"><li>Create a motor carrier account in TxFLEET.</li><li>Submit fleet, vehicle, ownership, base-jurisdiction, distance, insurance, and operating information.</li><li>Pay apportioned fees calculated from each jurisdiction's percentage of fleet travel.</li><li>Maintain detailed distance source documents and summaries for renewal and audit.</li><li>Keep UCR, federal and state motor-carrier authority, inspections, taxes, and permits current when applicable.</li></ol></section>
      <section><h2 className="text-3xl font-bold">Important compliance items</h2><div className="mt-6 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-4 py-3">Requirement</th><th className="px-4 py-3">What to know</th></tr></thead><tbody className="divide-y"><tr><td className="px-4 py-3 font-semibold">HVUT</td><td className="px-4 py-3">IRS Form 2290 proof is generally required for vehicles at 55,000 pounds gross weight or more.</td></tr><tr><td className="px-4 py-3 font-semibold">Inspections</td><td className="px-4 py-3">Commercial vehicles continue to require a passing commercial safety inspection.</td></tr><tr><td className="px-4 py-3 font-semibold">UCR</td><td className="px-4 py-3">Interstate or international carriers may need current Unified Carrier Registration.</td></tr><tr><td className="px-4 py-3 font-semibold">Distance records</td><td className="px-4 py-3">IRP fleets must preserve records supporting mileage reported by jurisdiction and may be selected for audit.</td></tr><tr><td className="px-4 py-3 font-semibold">Intrastate authority</td><td className="px-4 py-3">Texas intrastate motor carriers may need a TxDMV number in addition to vehicle registration.</td></tr></tbody></table></div></section>
      <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
    </section>
    <section className="border-t bg-muted/20"><div className="mx-auto max-w-5xl px-4 py-10 text-sm text-muted-foreground">Commercial registration depends on vehicle weight, configuration, operating territory, ownership, use, and carrier authority. Confirm eligibility and filing requirements with TxDMV Commercial Fleet Services.</div></section>
  </main>;
}

export const Route = createFileRoute("/vehicles/commercial-fleet-irp")({
  head: () => { const seo = buildSeo({ title: "Texas Commercial Fleet & IRP Registration Guide", description: "Texas guide to apportioned IRP registration, TxFLEET, intrastate fleets, token trailers, HVUT, UCR, inspections, and motor-carrier records.", path: "/vehicles/commercial-fleet-irp", type: "article", keywords: "Texas IRP, apportioned registration Texas, TxFLEET, Texas commercial fleet registration, token trailer" }); return { meta: seo.meta, links: seo.links, scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Texas Fleet, Commercial & Apportioned Registration", url: `${SITE_URL}/vehicles/commercial-fleet-irp` }) }, { type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }) }] }; },
  component: Page,
});