import { createFileRoute } from "@tanstack/react-router";
import { HubBreadcrumbs } from "@/components/hub-breadcrumbs";
import { buildSeo, SITE_URL } from "@/lib/seo";

const faq = [
  { question: "What are the minimum Texas auto liability limits?", answer: "Texas minimum liability coverage is commonly described as 30/60/25: up to $30,000 for injury to one person, $60,000 total injury liability per accident, and $25,000 for property damage." },
  { question: "Does minimum liability insurance cover my own car?", answer: "No. Liability coverage pays for covered injuries and property damage you cause to others. Collision and comprehensive coverage protect your own vehicle, subject to policy terms and deductibles." },
  { question: "Do lenders require more than liability coverage?", answer: "Usually. A lender or lessor generally requires collision and comprehensive coverage while it has a financial interest in the vehicle." },
  { question: "How do I prove insurance in Texas?", answer: "Drivers may use an insurer-issued proof-of-insurance card or an accepted electronic version. Insurance status may also be checked through the TexasSure verification system." },
];

function AutoInsuranceRequirementsPage() { return <main>
  <HubBreadcrumbs current="Texas Auto Insurance Requirements" />
  <section className="border-b bg-muted/30"><div className="mx-auto max-w-5xl px-4 py-16 sm:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Texas liability coverage rules</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Texas Auto Insurance Requirements</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">Understand minimum 30/60/25 liability coverage, proof-of-insurance rules, lender requirements, optional protections, and the consequences of driving uninsured.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.tdi.texas.gov/consumer/auto-insurance.html" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Official Texas insurance guide</a><a href="/vehicles/financial-responsibility" className="rounded-md border px-5 py-3 text-sm font-semibold">Financial responsibility</a></div></div></section>
  <article className="mx-auto max-w-4xl space-y-10 px-4 py-14 leading-relaxed">
    <section><h2 className="text-3xl font-bold">Texas minimum liability coverage</h2><p className="mt-4">Most Texas drivers satisfy the financial-responsibility law by carrying liability insurance. The minimum limits are generally $30,000 for bodily injury to one person, $60,000 total bodily injury per accident, and $25,000 for property damage. These limits are minimums, not a prediction of what a serious crash will cost.</p></section>
    <section><h2 className="text-3xl font-bold">What liability insurance pays</h2><p className="mt-4">Liability coverage pays covered claims made by other people when you are legally responsible for a crash. Bodily-injury liability can pay medical costs, lost income, and related damages. Property-damage liability can pay to repair or replace another vehicle or damaged property.</p></section>
    <section><h2 className="text-3xl font-bold">Coverage that protects you</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Collision</h3><p className="mt-2 text-muted-foreground">Pays for covered collision damage to your vehicle, minus the deductible.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Comprehensive</h3><p className="mt-2 text-muted-foreground">Covers qualifying non-collision losses such as theft, hail, fire, flood, or falling objects.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Uninsured/underinsured motorist</h3><p className="mt-2 text-muted-foreground">Can protect you when an at-fault driver has no insurance or insufficient limits.</p></div><div className="rounded-xl border bg-card p-5"><h3 className="font-bold">Personal injury protection</h3><p className="mt-2 text-muted-foreground">Can pay qualifying medical expenses, lost income, and related costs regardless of fault.</p></div></div></section>
    <section><h2 className="text-3xl font-bold">Proof of insurance</h2><p className="mt-4">Keep current proof in the vehicle or available electronically. You may need it after a crash, during a traffic stop, when registering a vehicle, or when completing an emissions or commercial inspection. Make sure the VIN, insured names, dates, and vehicle information are accurate.</p></section>
    <section><h2 className="text-3xl font-bold">Lender and lease requirements</h2><p className="mt-4">A lender or leasing company normally requires physical-damage coverage and may set deductible limits. If required coverage lapses, the creditor may purchase expensive force-placed coverage that protects its interest but provides limited protection to you.</p></section>
    <section className="rounded-xl border bg-muted/20 p-6"><h2 className="text-2xl font-bold">Coverage review checklist</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>Choose liability limits based on assets and risk, not only the legal minimum.</li><li>Confirm every household driver and vehicle is handled correctly.</li><li>Review deductibles and emergency savings.</li><li>Ask about uninsured motorist and PIP selections or rejections.</li><li>Check rideshare, delivery, business, trailer, and rental-car use.</li><li>Update the insurer after moving, refinancing, or changing vehicles.</li></ul></section>
    <section><h2 className="text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map((item) => <details key={item.question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-semibold">{item.question}</summary><p className="mt-3 text-muted-foreground">{item.answer}</p></details>)}</div></section>
    <p className="border-t pt-8 text-sm text-muted-foreground">Insurance policy language, prices, underwriting, discounts, and legal requirements can change. Confirm coverage with a licensed insurer or agent and current Texas Department of Insurance guidance.</p>
  </article>
</main>; }

export const Route = createFileRoute("/vehicles/auto-insurance-requirements")({ head: () => { const seo = buildSeo({ title: "Texas Auto Insurance Requirements: Minimum 30/60/25 Coverage", description: "Texas auto insurance guide covering minimum liability limits, proof of insurance, lender requirements, optional coverage and uninsured-driving consequences.", path: "/vehicles/auto-insurance-requirements", type: "article", keywords: "Texas auto insurance requirements, Texas minimum liability insurance, 30 60 25 Texas, proof of insurance Texas" }); return { meta:seo.meta, links:seo.links, scripts:[{ type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:"Texas Auto Insurance Requirements", url:`${SITE_URL}/vehicles/auto-insurance-requirements` }) }, { type:"application/ld+json", children:JSON.stringify({ "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map((item)=>({ "@type":"Question", name:item.question, acceptedAnswer:{ "@type":"Answer", text:item.answer } })) }) }] }; }, component: AutoInsuranceRequirementsPage });