import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";

const CATEGORIES = [["", "Unassigned"], ["shirts", "T-Shirts"], ["hoodies", "Sweatshirts"], ["hats", "Hats"], ["drinkware", "Drinkware"], ["stickers", "Stickers"], ["tote-bags", "Tote Bags"], ["accessories", "Accessories"]] as const;
const COLLECTIONS = [["patriotic", "Patriotic"], ["texas", "Texas"], ["floral", "Floral"], ["conservative", "Conservative"], ["texas-pride", "Texas Pride"], ["outdoors", "Outdoors"], ["home", "Home"], ["gifts", "Gifts"], ["texas-wildlife", "Texas Wildlife"], ["gulf-coast", "Gulf Coast"], ["bbq", "BBQ"], ["holiday", "Holiday Collection"]] as const;

type StoreKey = "keeptxred" | "texasdefined";
type ViewKey = "all" | "keeptxred" | "texasdefined" | "both" | "hidden";
type ProductRow = {
  id: string; printify_product_id: string | null; title: string; description: string | null; price: number; currency: string; image_url: string; synced_at: string;
  publish_keeptxred: boolean; publish_texasdefined: boolean;
  keeptxred_title: string | null; texasdefined_title: string | null;
  keeptxred_description: string | null; texasdefined_description: string | null;
  keeptxred_image_url: string | null; texasdefined_image_url: string | null;
  keeptxred_category: string | null; texasdefined_category: string | null;
  keeptxred_collections: string[] | null; texasdefined_collections: string[] | null;
  keeptxred_featured: boolean; texasdefined_featured: boolean;
  keeptxred_display_order: number; texasdefined_display_order: number;
  is_new: boolean; is_on_sale: boolean;
};

type StoreChanges = { enabled?: boolean; title?: string | null; description?: string | null; image?: string | null; category?: string | null; collections?: string[]; featured?: boolean; order?: number };

export const Route = createFileRoute("/admin/shop-products")({ head: () => ({ meta: [{ title: "Store Catalog — Admin" }, { name: "robots", content: "noindex, follow" }] }), component: ShopProductsAdmin });

function ShopProductsAdmin() {
  const [passcode, setPasscode] = useState(""); const [authenticated, setAuthenticated] = useState(false); const [products, setProducts] = useState<ProductRow[]>([]); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [view, setView] = useState<ViewKey>("all");

  useEffect(() => { const saved = sessionStorage.getItem("ktr-admin-passcode") ?? ""; const unlocked = sessionStorage.getItem("ktr-admin-ok") === "1"; const fallback = (import.meta.env.VITE_ADMIN_PASSCODE as string) || "keeptxred"; const token = saved || (unlocked ? fallback : ""); if (token) { setPasscode(token); setAuthenticated(true); void loadProducts(token); } else setLoading(false); }, []);

  async function loadProducts(token = passcode) { if (!token) { setAuthenticated(false); setLoading(false); return; } setAuthenticated(true); setLoading(true); setError(""); try { const response = await fetch("/api/admin/shop-products", { headers: { "x-admin-passcode": token } }); const payload = await response.json() as { ok?: boolean; products?: ProductRow[]; error?: string }; if (!response.ok || !payload.ok) throw new Error(payload.error || "Unable to load products"); sessionStorage.setItem("ktr-admin-passcode", token); sessionStorage.setItem("ktr-admin-ok", "1"); setProducts(payload.products ?? []); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load products"); } finally { setLoading(false); } }

  async function saveUpdates(updates: Array<Partial<ProductRow> & { id: string }>, key: string) { setSaving(key); setError(""); try { const response = await fetch("/api/admin/shop-products", { method: "PATCH", headers: { "content-type": "application/json", "x-admin-passcode": passcode }, body: JSON.stringify({ updates }) }); const payload = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !payload.ok) throw new Error(payload.error || "Unable to save products"); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save products"); } finally { setSaving(null); } }

  function patchLocal(id: string, changes: Partial<ProductRow>) { setProducts((current) => current.map((product) => product.id === id ? { ...product, ...changes } : product)); }
  function storeFields(product: ProductRow, store: StoreKey) { return store === "keeptxred" ? { enabled: product.publish_keeptxred, title: product.keeptxred_title ?? "", description: product.keeptxred_description ?? "", image: product.keeptxred_image_url ?? "", category: product.keeptxred_category, collections: product.keeptxred_collections ?? [], featured: product.keeptxred_featured, order: product.keeptxred_display_order } : { enabled: product.publish_texasdefined, title: product.texasdefined_title ?? "", description: product.texasdefined_description ?? "", image: product.texasdefined_image_url ?? "", category: product.texasdefined_category, collections: product.texasdefined_collections ?? [], featured: product.texasdefined_featured, order: product.texasdefined_display_order }; }
  function patchStore(product: ProductRow, store: StoreKey, changes: StoreChanges) { patchLocal(product.id, store === "keeptxred" ? { ...(changes.enabled !== undefined ? { publish_keeptxred: changes.enabled } : {}), ...(changes.title !== undefined ? { keeptxred_title: changes.title } : {}), ...(changes.description !== undefined ? { keeptxred_description: changes.description } : {}), ...(changes.image !== undefined ? { keeptxred_image_url: changes.image } : {}), ...(changes.category !== undefined ? { keeptxred_category: changes.category } : {}), ...(changes.collections !== undefined ? { keeptxred_collections: changes.collections } : {}), ...(changes.featured !== undefined ? { keeptxred_featured: changes.featured } : {}), ...(changes.order !== undefined ? { keeptxred_display_order: changes.order } : {}) } : { ...(changes.enabled !== undefined ? { publish_texasdefined: changes.enabled } : {}), ...(changes.title !== undefined ? { texasdefined_title: changes.title } : {}), ...(changes.description !== undefined ? { texasdefined_description: changes.description } : {}), ...(changes.image !== undefined ? { texasdefined_image_url: changes.image } : {}), ...(changes.category !== undefined ? { texasdefined_category: changes.category } : {}), ...(changes.collections !== undefined ? { texasdefined_collections: changes.collections } : {}), ...(changes.featured !== undefined ? { texasdefined_featured: changes.featured } : {}), ...(changes.order !== undefined ? { texasdefined_display_order: changes.order } : {}) }); }

  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return products.filter((product) => { const titles = [product.title, product.keeptxred_title, product.texasdefined_title].filter(Boolean).join(" ").toLowerCase(); const matchesQuery = !needle || titles.includes(needle) || product.id.toLowerCase().includes(needle) || product.printify_product_id?.toLowerCase().includes(needle); const matchesView = view === "all" || (view === "keeptxred" && product.publish_keeptxred && !product.publish_texasdefined) || (view === "texasdefined" && product.publish_texasdefined && !product.publish_keeptxred) || (view === "both" && product.publish_keeptxred && product.publish_texasdefined) || (view === "hidden" && !product.publish_keeptxred && !product.publish_texasdefined); return matchesQuery && matchesView; }); }, [products, query, view]);
  async function bulkAssign(target: "keeptxred" | "texasdefined" | "both" | "hidden") { const ids = selected.length ? selected : filtered.map((product) => product.id); const updates = ids.map((id) => ({ id, publish_keeptxred: target === "keeptxred" || target === "both", publish_texasdefined: target === "texasdefined" || target === "both" })); setProducts((current) => current.map((product) => ids.includes(product.id) ? { ...product, ...updates.find((item) => item.id === product.id) } : product)); await saveUpdates(updates, "bulk"); setSelected([]); }

  if (!authenticated && !loading) return <main className="mx-auto max-w-md px-6 py-20"><Link to="/admin" className="text-sm font-semibold text-primary hover:underline">← Admin dashboard</Link><h1 className="mt-6 text-3xl font-bold">Store Catalog</h1><p className="mt-2 text-sm text-muted-foreground">Enter the regular admin passcode.</p><form className="mt-6 space-y-3" onSubmit={(event) => { event.preventDefault(); void loadProducts(); }}><input type="password" value={passcode} onChange={(event) => setPasscode(event.target.value)} placeholder="Admin passcode" className="h-11 w-full rounded-md border border-border px-3"/><button type="submit" className="h-11 w-full rounded-md bg-primary font-semibold text-primary-foreground">Open store catalog</button></form>{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}</main>;

  return <main className="min-h-screen bg-muted/20"><header className="border-b bg-background"><div className="mx-auto max-w-7xl px-4 py-6"><Link to="/admin" className="text-sm font-semibold text-primary hover:underline">← Admin dashboard</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Store Catalog</h1><p className="mt-1 text-sm text-muted-foreground">Assign products and customize the title, description, image, category, collections, and placement for each storefront.</p></div><button onClick={() => void loadProducts()} className="rounded-md border border-border bg-background px-4 py-2 text-sm font-semibold">Refresh</button></div></div></header><section className="mx-auto max-w-7xl px-4 py-6">
    <div className="grid gap-3 lg:grid-cols-[1fr_auto]"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search shared or storefront title, product ID, or Printify ID" className="h-11 rounded-md border border-border bg-background px-3"/><div className="flex gap-2 overflow-x-auto">{(["all", "keeptxred", "texasdefined", "both", "hidden"] as ViewKey[]).map((option) => <button key={option} onClick={() => setView(option)} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-semibold ${view === option ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background"}`}>{option === "keeptxred" ? "KeepTXRed" : option === "texasdefined" ? "TexasDefined" : option[0].toUpperCase() + option.slice(1)}</button>)}</div></div>
    <div className="mt-4 flex flex-wrap items-center gap-2 rounded-lg border bg-background p-3"><span className="mr-2 text-sm font-semibold">{selected.length ? `${selected.length} selected` : `Bulk action applies to ${filtered.length} visible`}</span>{(["keeptxred", "texasdefined", "both", "hidden"] as const).map((target) => <button key={target} disabled={saving === "bulk" || filtered.length === 0} onClick={() => void bulkAssign(target)} className="rounded-md border px-3 py-1.5 text-sm font-semibold disabled:opacity-50">{target === "keeptxred" ? "Set KeepTXRed" : target === "texasdefined" ? "Set TexasDefined" : target === "both" ? "Set Both" : "Hide"}</button>)}</div>
    {error ? <div className="mt-4 border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><p className="font-semibold">The catalog could not load or save.</p><p className="mt-1">{error}</p></div> : null}<p className="mt-4 text-sm font-semibold">{loading ? "Loading products…" : `${filtered.length} products`}</p>
    <div className="mt-4 grid gap-4">{filtered.map((product) => <article key={product.id} className="rounded-xl border border-border bg-background p-4"><div className="grid gap-4 lg:grid-cols-[28px_96px_minmax(0,1fr)]"><input type="checkbox" checked={selected.includes(product.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, product.id] : current.filter((id) => id !== product.id))} aria-label={`Select ${product.title}`}/><img src={product.image_url} alt="" className="h-24 w-24 rounded-lg bg-muted object-cover"/><div><h2 className="font-semibold">{product.title}</h2><p className="mt-1 text-sm text-muted-foreground">{new Intl.NumberFormat("en-US", { style: "currency", currency: product.currency || "USD" }).format(product.price)} · Printify {product.printify_product_id || "not linked"}</p><p className="mt-2 line-clamp-2 text-xs text-muted-foreground">Shared Printify content remains the fallback when a storefront override is blank.</p></div></div>
      <div className="mt-5 grid gap-4 xl:grid-cols-2">{(["keeptxred", "texasdefined"] as StoreKey[]).map((store) => { const fields = storeFields(product, store); return <fieldset key={store} className="rounded-lg border p-4"><legend className="px-2 text-sm font-bold">{store === "keeptxred" ? "KeepTXRed.com" : "TexasDefined.com"}</legend><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center justify-between gap-3 text-sm font-semibold sm:col-span-2"><span>Show for sale</span><input type="checkbox" checked={fields.enabled} onChange={(event) => patchStore(product, store, { enabled: event.target.checked })}/></label>
        <label className="text-sm font-semibold sm:col-span-2">Storefront title<input maxLength={180} value={fields.title} onChange={(event) => patchStore(product, store, { title: event.target.value })} placeholder={product.title} className="mt-1 h-10 w-full rounded-md border bg-background px-2 font-normal"/></label>
        <label className="text-sm font-semibold sm:col-span-2">Storefront description<textarea maxLength={5000} value={fields.description} onChange={(event) => patchStore(product, store, { description: event.target.value })} placeholder={product.description || "Shared Printify description"} rows={4} className="mt-1 w-full rounded-md border bg-background p-2 font-normal"/></label>
        <label className="text-sm font-semibold sm:col-span-2">Primary image URL<input type="url" value={fields.image} onChange={(event) => patchStore(product, store, { image: event.target.value })} placeholder={product.image_url} className="mt-1 h-10 w-full rounded-md border bg-background px-2 font-normal"/></label>
        <label className="text-sm font-semibold">Category<select value={fields.category ?? ""} onChange={(event) => patchStore(product, store, { category: event.target.value || null })} className="mt-1 h-10 w-full rounded-md border bg-background px-2 font-normal">{CATEGORIES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold">Display order<input type="number" min={0} max={9999} value={fields.order} onChange={(event) => patchStore(product, store, { order: Number(event.target.value) || 0 })} className="mt-1 h-10 w-full rounded-md border bg-background px-2 font-normal"/></label><label className="flex items-center justify-between gap-3 text-sm"><span>Featured</span><input type="checkbox" checked={fields.featured} onChange={(event) => patchStore(product, store, { featured: event.target.checked })}/></label><div className="sm:col-span-2"><p className="text-sm font-semibold">Collections</p><div className="mt-2 flex flex-wrap gap-3">{COLLECTIONS.map(([value, label]) => <label key={value} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={fields.collections.includes(value)} onChange={(event) => patchStore(product, store, { collections: event.target.checked ? [...fields.collections, value] : fields.collections.filter((item) => item !== value) })}/>{label}</label>)}</div></div></div></fieldset>; })}</div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><div className="flex gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={product.is_new} onChange={(event) => patchLocal(product.id, { is_new: event.target.checked })}/>New arrival</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={product.is_on_sale} onChange={(event) => patchLocal(product.id, { is_on_sale: event.target.checked })}/>On sale</label></div><button onClick={() => void saveUpdates([{ ...product }], product.id)} disabled={saving === product.id} className="rounded-md bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60">{saving === product.id ? "Saving…" : "Save product"}</button></div></article>)}</div>
  </section></main>;
}
