import type { TexasCostOfLivingResult } from "@/types/cost/TexasCostOfLiving";
export const formatCostCurrency=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
export const explainMonthlyExpenses=(r:TexasCostOfLivingResult)=>`Your estimated monthly cost of living is ${formatCostCurrency(r.summary.totalMonthlyCost)} including housing, utilities, transportation, and lifestyle expenses.`;
export const explainHousingCost=(r:TexasCostOfLivingResult)=>{const p=Math.round(r.analysis.housingRatio*100);return p<=28?`Housing represents ${p}% of income, which is generally affordable.`:p<=36?`Housing represents ${p}% of income, which should be monitored.`:`Housing represents ${p}% of income, which may create financial pressure.`};
export const explainSavingsRate=(r:TexasCostOfLivingResult)=>`Your estimated savings rate is ${Math.round(r.analysis.savingsRate*100)}%.`;
export const explainAffordabilityScore=(r:TexasCostOfLivingResult)=>r.analysis.affordabilityScore>=80?"This budget appears highly sustainable.":r.analysis.affordabilityScore>=60?"This budget appears workable.":"This budget may require adjustments.";
export const generateRelocationSummary=(r:TexasCostOfLivingResult)=>`For ${r.input.city}, estimated monthly expenses are ${formatCostCurrency(r.summary.totalMonthlyCost)} with an affordability score of ${r.analysis.affordabilityScore}/100.`;
export function explainLargestExpense(r:TexasCostOfLivingResult){const items=[['housing',r.summary.housing],['utilities',r.summary.utilities],['transportation',r.summary.transportation],['lifestyle',r.summary.lifestyle]] as const;const largest=[...items].sort((a,b)=>b[1]-a[1])[0];return `Your largest expense category is ${largest[0]} at approximately ${formatCostCurrency(largest[1])} per month.`}
export const generateCostOfLivingSEODescription=(location="Texas")=>`Use this ${location} cost of living calculator to estimate housing, utilities, transportation, lifestyle expenses, and income needed for your household.`;
