import { calculateMonthlyPayment } from "@/lib/calculators/calculatorHelpers";
import type { PhaseCalculatorDefinition, PhaseCalculatorResult } from "@/types/calculators/phaseCalculator";

const money = (label: string, value: number, highlight = false): PhaseCalculatorResult => ({ label, value: Math.max(0, value), type: "currency", highlight });
const percent = (label: string, value: number): PhaseCalculatorResult => ({ label, value, type: "percent" });
const f = (key: string, label: string, defaultValue: number, prefix?: string, suffix?: string) => ({ key, label, defaultValue, prefix, suffix });
const faq = (title: string) => [
  { question: `Is the ${title} an official quote?`, answer: "No. It is an educational estimate based on the values you enter and common Texas assumptions. Confirm costs with the appropriate lender, taxing authority, insurer, employer, or service provider." },
  { question: "Does this calculator store my information?", answer: "No. The calculation runs in your browser and does not require an account." },
];

const mortgageResults = (i: Record<string, number>) => {
  const loan = Math.max(0, i.homePrice - i.downPayment);
  const pi = calculateMonthlyPayment(loan, i.interestRate, i.loanTerm);
  const tax = i.homePrice * i.propertyTaxRate / 100 / 12;
  const insurance = i.annualInsurance / 12;
  const pmi = i.homePrice > 0 && i.downPayment / i.homePrice < .2 ? loan * i.pmiRate / 100 / 12 : 0;
  const total = pi + tax + insurance + pmi + (i.hoa || 0);
  return [money("Total monthly payment", total, true), money("Principal and interest", pi), money("Property tax", tax), money("Home insurance", insurance), money("PMI", pmi), money("Loan amount", loan)];
};

const definitions: PhaseCalculatorDefinition[] = [
  { key:"mortgage", title:"Texas Mortgage Calculator", description:"Estimate principal, interest, Texas property taxes, insurance, PMI, and HOA costs.", slug:"/tools/texas-mortgage-calculator", category:"Housing", fields:[f("homePrice","Home price",400000,"$"),f("downPayment","Down payment",80000,"$"),f("interestRate","Interest rate",6.5,undefined,"%"),f("loanTerm","Loan term",30,undefined,"years"),f("propertyTaxRate","Property tax rate",1.8,undefined,"%"),f("annualInsurance","Annual insurance",2800,"$"),f("pmiRate","Annual PMI rate",0.6,undefined,"%"),f("hoa","Monthly HOA",0,"$")], calculate:mortgageResults, faq:faq("Texas Mortgage Calculator") },
  { key:"propertyTax", title:"Texas Property Tax Calculator", description:"Estimate annual and monthly Texas property taxes after a homestead exemption.", slug:"/tools/texas-property-tax-calculator", category:"Taxes", fields:[f("appraisedValue","Appraised value",400000,"$"),f("homesteadExemption","Homestead exemption",100000,"$"),f("taxRate","Combined tax rate",2.1,undefined,"%")], calculate:i=>{const taxable=Math.max(0,i.appraisedValue-i.homesteadExemption);const annual=taxable*i.taxRate/100;return[money("Estimated annual tax",annual,true),money("Estimated monthly tax",annual/12),money("Taxable value",taxable),money("Estimated exemption savings",i.homesteadExemption*i.taxRate/100)];}, faq:faq("Texas Property Tax Calculator") },
  { key:"homeInsurance", title:"Texas Home Insurance Calculator", description:"Estimate an annual Texas homeowners insurance premium from home value, location risk, deductible, and coverage choices.", slug:"/tools/texas-home-insurance-calculator", category:"Insurance", fields:[f("homeValue","Home value",400000,"$"),f("baseRate","Base annual rate",0.9,undefined,"%"),f("riskFactor","Location risk factor",1),f("deductibleCredit","Deductible discount",10,undefined,"%")], calculate:i=>{const annual=i.homeValue*i.baseRate/100*i.riskFactor*(1-i.deductibleCredit/100);return[money("Estimated annual premium",annual,true),money("Estimated monthly premium",annual/12),money("Coverage basis",i.homeValue),percent("Applied deductible discount",i.deductibleCredit)];}, faq:faq("Texas Home Insurance Calculator") },
  { key:"homeAffordability", title:"Texas Home Affordability Calculator", description:"Estimate an affordable Texas home price using income, debts, down payment, interest rate, and housing costs.", slug:"/tools/texas-home-affordability-calculator", category:"Housing", fields:[f("annualIncome","Annual household income",120000,"$"),f("monthlyDebt","Monthly debt payments",750,"$"),f("downPayment","Available down payment",60000,"$"),f("interestRate","Interest rate",6.5,undefined,"%"),f("loanTerm","Loan term",30,undefined,"years"),f("dtiLimit","Target total DTI",36,undefined,"%")], calculate:i=>{const budget=Math.max(0,i.annualIncome/12*i.dtiLimit/100-i.monthlyDebt);const taxInsurance=budget*.27;const pi=budget-taxInsurance;const r=i.interestRate/100/12,n=i.loanTerm*12;const loan=r===0?pi*n:pi*(Math.pow(1+r,n)-1)/(r*Math.pow(1+r,n));return[money("Estimated affordable home price",loan+i.downPayment,true),money("Estimated loan amount",loan),money("Monthly housing budget",budget),percent("Target debt-to-income ratio",i.dtiLimit)];}, faq:faq("Texas Home Affordability Calculator") },
  { key:"closingCost", title:"Texas Closing Cost Calculator", description:"Estimate buyer closing costs and cash needed to close on a Texas home.", slug:"/tools/texas-closing-cost-calculator", category:"Housing", fields:[f("homePrice","Purchase price",400000,"$"),f("downPayment","Down payment",80000,"$"),f("lenderFees","Lender fees",3500,"$"),f("titleRate","Title and settlement rate",0.8,undefined,"%"),f("prepaids","Prepaids and escrow",6000,"$")], calculate:i=>{const title=i.homePrice*i.titleRate/100;const costs=title+i.lenderFees+i.prepaids;return[money("Estimated cash to close",i.downPayment+costs,true),money("Estimated closing costs",costs),money("Down payment",i.downPayment),money("Title and settlement",title),money("Lender fees",i.lenderFees),money("Prepaids and escrow",i.prepaids)];}, faq:faq("Texas Closing Cost Calculator") },
  { key:"utilityCost", title:"Texas Utility Cost Calculator", description:"Estimate monthly electricity, water, gas, internet, and trash costs for a Texas household.", slug:"/tools/texas-utility-cost-calculator", category:"Utilities", fields:[f("homeSizeSqFt","Home size",2500,undefined,"sq ft"),f("occupants","Occupants",3),f("electricityRate","Electricity rate",0.16,"$","/kWh"),f("climateFactor","Climate factor",1),f("waterUsageFactor","Water usage factor",1),f("gasUsageFactor","Gas usage factor",1),f("internetCost","Internet",70,"$"),f("trashCost","Trash",25,"$")], calculate:i=>{const electricity=(500+i.homeSizeSqFt*.35+i.occupants*80)*i.electricityRate*i.climateFactor;const water=(35+i.occupants*18)*i.waterUsageFactor;const gas=(25+i.homeSizeSqFt*.012)*i.gasUsageFactor;const total=electricity+water+gas+i.internetCost+i.trashCost;return[money("Estimated monthly utilities",total,true),money("Electricity",electricity),money("Water",water),money("Natural gas",gas),money("Internet",i.internetCost),money("Trash",i.trashCost),money("Estimated annual utilities",total*12)];}, faq:faq("Texas Utility Cost Calculator") },
  { key:"costOfLiving", title:"Texas Cost of Living Calculator", description:"Compare a household budget with a selected Texas cost index.", slug:"/tools/texas-cost-of-living-calculator", category:"Relocation", fields:[f("currentMonthlyCost","Current monthly spending",6000,"$"),f("currentIndex","Current location index",110),f("texasIndex","Texas location index",95)], calculate:i=>{const adjusted=i.currentMonthlyCost*i.texasIndex/i.currentIndex;return[money("Comparable Texas monthly cost",adjusted,true),money("Comparable Texas annual cost",adjusted*12),money("Estimated monthly difference",Math.abs(i.currentMonthlyCost-adjusted)),percent("Estimated cost difference",(i.texasIndex/i.currentIndex-1)*100)];}, faq:faq("Texas Cost of Living Calculator") },
  { key:"salaryComparison", title:"Texas Salary Comparison Calculator", description:"Estimate the salary needed to maintain purchasing power when moving to Texas.", slug:"/tools/texas-salary-comparison-calculator", category:"Financial", fields:[f("currentSalary","Current salary",100000,"$"),f("currentIndex","Current cost index",115),f("texasIndex","Texas cost index",95),f("currentStateTaxRate","Current state income tax",5,undefined,"%")], calculate:i=>{const equivalent=i.currentSalary*i.texasIndex/i.currentIndex;const stateTaxSavings=i.currentSalary*i.currentStateTaxRate/100;return[money("Cost-adjusted Texas salary",equivalent,true),money("Estimated state income-tax savings",stateTaxSavings),money("Estimated purchasing-power difference",Math.abs(i.currentSalary-equivalent)+stateTaxSavings)];}, faq:faq("Texas Salary Comparison Calculator") },
  { key:"movingCost", title:"Texas Moving Cost Calculator", description:"Estimate transportation, labor, travel, packing, and setup costs for a move to Texas.", slug:"/tools/texas-moving-cost-calculator", category:"Relocation", fields:[f("distance","Moving distance",800,undefined,"miles"),f("homeSize","Home size",2000,undefined,"sq ft"),f("ratePerMile","Transport rate",2.5,"$","/mile"),f("laborRate","Labor per square foot",1.1,"$"),f("travel","Household travel",900,"$"),f("setup","Deposits and setup",1200,"$")], calculate:i=>{const transport=i.distance*i.ratePerMile;const labor=i.homeSize*i.laborRate;const total=transport+labor+i.travel+i.setup;return[money("Estimated moving cost",total,true),money("Transportation",transport),money("Loading and labor",labor),money("Household travel",i.travel),money("Texas setup costs",i.setup)];}, faq:faq("Texas Moving Cost Calculator") },
  { key:"propertyTaxImpact", title:"Texas Property Tax Impact Calculator", description:"See how appraisal and tax-rate changes could affect a Texas property-tax bill.", slug:"/tools/texas-property-tax-impact-calculator", category:"Taxes", fields:[f("currentValue","Current taxable value",350000,"$"),f("newValue","New taxable value",385000,"$"),f("currentRate","Current tax rate",2.1,undefined,"%"),f("newRate","New tax rate",2.05,undefined,"%")], calculate:i=>{const current=i.currentValue*i.currentRate/100;const next=i.newValue*i.newRate/100;return[money("Estimated new annual tax",next,true),money("Current annual tax",current),money("Annual change",Math.abs(next-current)),money("Monthly change",Math.abs(next-current)/12),percent("Percent change",current?((next-current)/current)*100:0)];}, faq:faq("Texas Property Tax Impact Calculator") },
  { key:"texasMortgagePayment", title:"Texas Mortgage Payment Impact Calculator", description:"Measure how price, down payment, and interest-rate changes affect a Texas mortgage payment.", slug:"/tools/texas-mortgage-payment-impact-calculator", category:"Housing", fields:[f("homePrice","Home price",400000,"$"),f("downPayment","Down payment",80000,"$"),f("interestRate","Interest rate",6.5,undefined,"%"),f("comparisonRate","Comparison rate",5.75,undefined,"%"),f("loanTerm","Loan term",30,undefined,"years")], calculate:i=>{const loan=i.homePrice-i.downPayment;const current=calculateMonthlyPayment(loan,i.interestRate,i.loanTerm);const comparison=calculateMonthlyPayment(loan,i.comparisonRate,i.loanTerm);return[money("Payment at current rate",current,true),money("Payment at comparison rate",comparison),money("Monthly difference",Math.abs(current-comparison)),money("Loan-term difference",Math.abs(current-comparison)*i.loanTerm*12)];}, faq:faq("Texas Mortgage Payment Impact Calculator") },
  { key:"texasRentVsBuy", title:"Texas Rent vs. Buy Calculator", description:"Compare the estimated long-term costs of renting and buying in Texas.", slug:"/tools/texas-rent-vs-buy-calculator", category:"Housing", fields:[f("monthlyRent","Monthly rent",2200,"$"),f("homePrice","Home price",400000,"$"),f("downPayment","Down payment",80000,"$"),f("interestRate","Interest rate",6.5,undefined,"%"),f("years","Comparison period",7,undefined,"years"),f("appreciationRate","Annual appreciation",3,undefined,"%")], calculate:i=>{const loan=i.homePrice-i.downPayment;const mortgage=calculateMonthlyPayment(loan,i.interestRate,30);const rentTotal=i.monthlyRent*12*i.years;const buyPayments=mortgage*12*i.years+i.downPayment;const appreciation=i.homePrice*(Math.pow(1+i.appreciationRate/100,i.years)-1);const netBuy=Math.max(0,buyPayments-appreciation);return[money("Estimated rent cost",rentTotal),money("Estimated net buy cost",netBuy,true),money("Estimated appreciation",appreciation),money("Estimated difference",Math.abs(rentTotal-netBuy))];}, faq:faq("Texas Rent vs. Buy Calculator") },
  { key:"texasDownPaymentAssistance", title:"Texas Down Payment Assistance Calculator", description:"Estimate a potential assistance amount and remaining cash requirement for a Texas home purchase.", slug:"/tools/texas-down-payment-assistance-calculator", category:"Housing", fields:[f("homePrice","Home price",300000,"$"),f("requiredDownPercent","Required down payment",3.5,undefined,"%"),f("assistancePercent","Potential assistance",4,undefined,"%"),f("availableCash","Available cash",10000,"$")], calculate:i=>{const required=i.homePrice*i.requiredDownPercent/100;const assistance=i.homePrice*i.assistancePercent/100;const remaining=Math.max(0,required-assistance-i.availableCash);return[money("Potential assistance",assistance,true),money("Required down payment",required),money("Available cash",i.availableCash),money("Remaining down-payment need",remaining)];}, faq:faq("Texas Down Payment Assistance Calculator") },
  { key:"texasClosingCost", title:"Texas Closing Cost Calculator", description:"Estimate Texas buyer and seller closing costs using transaction-specific percentages.", slug:"/tools/texas-closing-cost-estimator", category:"Housing", fields:[f("salePrice","Sale price",400000,"$"),f("buyerRate","Buyer closing-cost rate",2.5,undefined,"%"),f("sellerRate","Seller closing-cost rate",7,undefined,"%"),f("buyerCredits","Seller credits to buyer",0,"$")], calculate:i=>{const buyer=Math.max(0,i.salePrice*i.buyerRate/100-i.buyerCredits);const seller=i.salePrice*i.sellerRate/100+i.buyerCredits;return[money("Estimated buyer closing costs",buyer,true),money("Estimated seller closing costs",seller),money("Combined transaction costs",buyer+seller),money("Seller credits",i.buyerCredits)];}, faq:faq("Texas Closing Cost Calculator") },
  { key:"texasPropertyTaxCounty", title:"Texas Property Tax Estimator by County", description:"Estimate county-level Texas property taxes with a local combined tax rate and exemption.", slug:"/tools/texas-property-tax-by-county", category:"Taxes", fields:[f("appraisedValue","Appraised value",400000,"$"),f("exemption","Applicable exemption",100000,"$"),f("countyRate","County-area combined rate",2.15,undefined,"%")], calculate:i=>{const taxable=Math.max(0,i.appraisedValue-i.exemption);const annual=taxable*i.countyRate/100;return[money("Estimated annual property tax",annual,true),money("Estimated monthly escrow",annual/12),money("Taxable value",taxable),money("Estimated exemption benefit",i.exemption*i.countyRate/100),percent("Combined local rate",i.countyRate)];}, faq:faq("Texas Property Tax Estimator by County") },
];

export const phaseCalculatorDefinitions = Object.fromEntries(definitions.map(definition => [definition.key, definition])) as Record<string, PhaseCalculatorDefinition>;
export function getPhaseCalculatorDefinition(key: string): PhaseCalculatorDefinition {
  const definition = phaseCalculatorDefinitions[key];
  if (!definition) throw new Error(`Unknown calculator: ${key}`);
  return definition;
}
