import type { ElectionPoll, ValidPollEntryDraft } from "@/types/elections";
import { electionIds, electionSlugs } from "@/types/elections";

export interface PollFileWorkflowOutput {
  record: ElectionPoll;
  json: string;
  filename: string;
}

/**
 * Converts a validated admin draft into the canonical ElectionPoll contract.
 * The generated record remains in review until an editor verifies it through
 * the pull-request workflow.
 */
export function createPollFileWorkflowOutput(
  draft: ValidPollEntryDraft,
  now: Date = new Date(),
): PollFileWorkflowOutput {
  const timestamp = now.toISOString();
  const pollId = electionIds.poll(`poll-${draft.slug}`);
  const slug = electionSlugs.poll(draft.slug);
  const responses = draft.responses.map((response, index) => ({
    id: `${draft.slug}-response-${index + 1}`,
    label: response.label,
    candidateId: response.candidateId ? electionIds.candidate(response.candidateId) : null,
    party: null,
    percentage: response.percentage,
    respondentCount: null,
    marginFromLeader: null,
    isLeader: false,
    isUndecided: /undecided|unsure|not sure/i.test(response.label),
    isOther: /other|someone else|another candidate/i.test(response.label),
  }));
  const leader = responses
    .filter((response) => response.percentage != null)
    .sort((left, right) => (right.percentage ?? 0) - (left.percentage ?? 0))[0];
  const normalizedResponses = responses.map((response) => ({
    ...response,
    isLeader: Boolean(leader && response.id === leader.id),
    marginFromLeader:
      leader?.percentage == null || response.percentage == null
        ? null
        : Math.round((response.percentage - leader.percentage) * 10) / 10,
  }));

  const record: ElectionPoll = {
    id: pollId,
    slug,
    electionCycleId: electionIds.cycle(draft.electionCycleId),
    raceId: draft.raceId ? electionIds.race(draft.raceId) : null,
    jurisdictionId: null,
    title: draft.title,
    status: "published",
    pollster: {
      name: draft.pollsterName,
      slug: slugify(draft.pollsterName),
      websiteUrl: null,
      grade: "unrated",
      transparencyScore: null,
      methodologyUrl: draft.methodologyUrl,
    },
    sponsors: [],
    fieldStartDate: draft.fieldStartDate,
    fieldEndDate: draft.fieldEndDate,
    releaseDate: draft.releaseDate,
    revisedAt: null,
    methodology: {
      population: draft.population,
      sampleSize: draft.sampleSize,
      marginOfError: draft.marginOfError,
      confidenceLevel: null,
      mode: draft.mode,
      languages: [],
      weightingDescription: null,
      samplingDescription: null,
      likelyVoterModelDescription: null,
      questionOrderRandomized: null,
      includesCellPhones: null,
      responseRate: null,
      methodologyUrl: draft.methodologyUrl,
    },
    questions: [
      {
        id: `${draft.slug}-primary-question`,
        type: "head_to_head",
        prompt: draft.questionPrompt,
        order: 1,
        sampleSize: draft.sampleSize,
        population: draft.population,
        responses: normalizedResponses,
        notes: null,
      },
    ],
    primaryQuestionId: `${draft.slug}-primary-question`,
    toplineUrl: draft.sourceUrl,
    questionnaireUrl: null,
    crosstabsUrl: null,
    archiveUrl: null,
    internalPoll: draft.internalPoll,
    partisanPoll: draft.partisanPoll,
    trackingPoll: false,
    supersededByPollId: null,
    notes: "Generated by the Election Central file-based poll workflow; verify in pull-request review.",
    createdAt: timestamp,
    updatedAt: timestamp,
    verificationStatus: "pending_review",
    verifiedAt: null,
    verifiedBy: null,
    verificationNotes: "Requires editorial verification before merge.",
    publicationStatus: "in_review",
    publishedAt: null,
    unpublishedAt: null,
    scheduledFor: null,
    publishedBy: null,
    dataAsOf: timestamp,
    lastCheckedAt: timestamp,
    staleAfter: addDays(now, 14).toISOString(),
    expiresAt: addDays(now, 45).toISOString(),
    freshnessStatus: "fresh",
    source: {
      sourceId: null,
      sourceName: draft.sourceName,
      sourceType: "pollster",
      sourceUrl: draft.sourceUrl,
      sourceRecordId: null,
      retrievedAt: timestamp,
      attributionText: null,
    },
  };

  return {
    record,
    json: `${JSON.stringify(record, null, 2)}\n`,
    filename: `${draft.slug}.poll.json`,
  };
}

function slugify(value: string) {
  const slug = value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return slug || null;
}

function addDays(date: Date, days: number) {
  return new Date(date.getTime() + days * 86_400_000);
}
