import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const FEEDS=["upcomingmeetingshouse","upcomingmeetingssenate","todaysfiledhouse","todaysfiledsenate","todaysbillspassed","upcomingcalendarshouse","upcomingcalendarssenate","todaysbilltext","todaysfiscalnotes","todaysbillanalyses"].map((type)=>`https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=${type}`);
const HEADERS={"User-Agent":"Mozilla/5.0 (compatible; KeepTXRedBot/1.7; +https://keeptxred.com)",Accept:"application/rss+xml,application/xml,text/xml,text/html,*/*"};
const BILL_RE=/\b(HB|SB|HJR|SJR|HCR|SCR|HR|SR)\s*(?:NO\.?\s*)?(\d{1,5})\b/gi;
type BillRef={legislature:number;sessionCode:string;billType:string;billNumber:number};

const clean=(value:string)=>value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/gi,"$1").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const pick=(block:string,tag:string)=>clean(block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,`i`))?.[1]||"");
const span=(html:string,id:string)=>clean(html.match(new RegExp(`<span[^>]+id=["']${id}["'][^>]*>([\\s\\S]*?)<\\/span>`,`i`))?.[1]||"");
const slug=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const iso=(value:string)=>{const m=value.match(/\b(\d{1,2})\/(\d{1,2})\/(\d{2,4})\b/);if(!m)return null;const y=m[3].length===2?`20${m[3]}`:m[3];return `${y}-${m[1].padStart(2,"0")}-${m[2].padStart(2,"0")}`;};
const absolute=(value:string)=>{try{return new URL(value,"https://capitol.texas.gov/").toString();}catch{return null;}};
const sessionFrom=(value:string)=>{try{value=decodeURIComponent(value);}catch{}const m=value.match(/\/tlodocs\/(\d{2})(R|\d+)\//i)||value.match(/[?&]LegSess=(\d{2})(R|\d+)\b/i);return m?{legislature:+m[1],sessionCode:m[2].toUpperCase()}:null;};
function refs(text:string,session:any):BillRef[]{if(!session)return[];const out=new Map<string,BillRef>();for(const m of text.matchAll(BILL_RE)){const ref={...session,billType:m[1].toLowerCase(),billNumber:+m[2]};out.set(`${ref.legislature}:${ref.sessionCode}:${ref.billType}:${ref.billNumber}`,ref);}return [...out.values()];}
async function get(url:string,timeout=18000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{headers:HEADERS,redirect:"follow",signal:controller.signal});return{ok:response.ok,status:response.status,text:response.ok?await response.text():""};}finally{clearTimeout(timer);}}
function actions(html:string){const out:any[]=[];for(const row of html.match(/<tr\b[\s\S]*?<\/tr>/gi)||[]){const cell=(label:string)=>clean(row.match(new RegExp(`<td[^>]+data-label=["']${label}["'][^>]*>([\\s\\S]*?)<\\/td>`,`i`))?.[1]||"");const text=cell("Action Description"),date=iso(cell("Action Date"));if(!text||!date)continue;const rawChamber=cell("Action Chamber").toUpperCase(),chamber=rawChamber==="H"?"house":rawChamber==="S"?"senate":rawChamber==="E"?"executive":null;const href=row.match(/<td[^>]+data-label=["']Action Description["'][^>]*>[\s\S]*?<a[^>]+href=["']([^"']+)["']/i)?.[1]||"";out.push({text,date,chamber,source:href?absolute(href):null});}return out;}
function status(actionsList:any[]){const text=actionsList.map((action)=>action.text.toLowerCase());if(text.some((x)=>x.includes("vetoed")))return["vetoed","Vetoed",false];if(text.some((x)=>x.includes("effective on")||x.includes("effective immediately")))return["effective","Effective",true];if(text.some((x)=>x.includes("signed by the governor")))return["signed","Signed",true];if(text.some((x)=>x.includes("sent to the governor")))return["sent-to-governor","Sent to governor",false];if(text.some((x)=>/^passed\b/.test(x)||x.includes("passage")))return["passed","Passed",false];if(text.some((x)=>x.includes("referred to")))return["referred-to-committee","In committee",false];return["filed","Filed",false];}

Deno.serve(async(request)=>{
  if(request.method!=="POST")return Response.json({error:"POST required"},{status:405});
  const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return Response.json({error:"config missing"},{status:500});
  const db=createClient(url,key,{auth:{persistSession:false}}),found=new Map<string,BillRef>(),stats:any={feeds:0,items:0,linked:0,refs:0,already_present:0,created:0,actions:0,sponsors:0,errors:[]};
  try{
    for(const feed of FEEDS){const response=await get(feed,25000);if(!response.ok){stats.errors.push(`${feed} HTTP ${response.status}`);continue;}stats.feeds++;const items=response.text.match(/<item\b[\s\S]*?<\/item>/gi)||[];stats.items+=items.length;for(const raw of items.slice(0,100)){const link=pick(raw,"link"),session=sessionFrom(`${link}\n${raw}`);let context=raw,foundRefs=refs(context,session);if(/upcomingmeetings|upcomingcalendars/i.test(feed)&&link&&/capitol\.texas\.gov/i.test(link)){const page=await get(link,15000);if(page.ok){stats.linked++;context+=page.text;foundRefs=refs(context,session||sessionFrom(link)||sessionFrom(page.text));}}for(const ref of foundRefs)found.set(`${ref.legislature}:${ref.sessionCode}:${ref.billType}:${ref.billNumber}`,ref);}}
    stats.refs=found.size;
    for(const ref of found.values()){
      const{data:existing}=await db.from("bills").select("id").eq("legislature_number",ref.legislature).eq("session_code",ref.sessionCode).eq("bill_type",ref.billType).eq("bill_number",ref.billNumber).maybeSingle();if(existing?.id){stats.already_present++;continue;}
      const token=`${ref.billType.toUpperCase()}${ref.billNumber}`,identifier=`${ref.billType.toUpperCase()} ${ref.billNumber}`,history=`https://capitol.texas.gov/BillLookup/History.aspx?LegSess=${ref.legislature}${ref.sessionCode}&Bill=${token}`,page=await get(history,25000);if(!page.ok){stats.errors.push(`${identifier} history HTTP ${page.status}`);continue;}
      const caption=span(page.text,"lblCaptionText");if(!caption){stats.errors.push(`${identifier} missing caption`);continue;}
      const historyActions=actions(page.text),state=status(historyActions),chronological=[...historyActions].reverse(),introduced=chronological.find((action)=>/filed/i.test(action.text))?.date||chronological[0]?.date||null,latest=historyActions[0]?.date||introduced;
      const{data:sessionRow}=await db.from("legislative_sessions").select("id").eq("legislature_number",ref.legislature).eq("session_code",ref.sessionCode).maybeSingle();const effective=historyActions.find((action)=>/effective/i.test(action.text)),effectiveDate=effective?(iso(effective.text)||effective.date):null;
      const{data:bill,error:billError}=await db.from("bills").insert({legislative_session_id:sessionRow?.id||null,legislature_number:ref.legislature,session_code:ref.sessionCode,bill_type:ref.billType,bill_number:ref.billNumber,chamber:ref.billType.startsWith("h")?"house":ref.billType.startsWith("s")?"senate":"joint",caption,current_status_code:state[0],current_status_label:state[1],current_status_description:historyActions[0]?.text||state[1],introduced_date:introduced,last_action_date:latest,effective_date:effectiveDate,became_law:state[2],is_active:true,source_url:history,bill_text_url:`https://capitol.texas.gov/BillLookup/Text.aspx?LegSess=${ref.legislature}${ref.sessionCode}&Bill=${token}`,last_synced_at:new Date().toISOString()}).select("id").single();if(billError)throw billError;stats.created++;
      for(let index=0;index<historyActions.length;index++){const action=historyActions[index],{error}=await db.from("bill_actions").insert({bill_id:bill.id,action_date:action.date,action_sequence:900000-index,chamber:action.chamber,action_code:"tlo-history",action_text:action.text,source_url:action.source||history});if(error)throw error;stats.actions++;}
      const groups:[[string,string,string],[string,string,string],[string,string,string],[string,string,string]]=[["lblAuthor","author",ref.billType.startsWith("h")?"house":"senate"],["lblCoauthor","coauthor",ref.billType.startsWith("h")?"house":"senate"],["lblSponsor","sponsor",ref.billType.startsWith("h")?"senate":"house"],["lblCosponsor","cosponsor",ref.billType.startsWith("h")?"senate":"house"]];let sequence=0;
      for(const group of groups){for(const name of span(page.text,group[0]).split("|").map((value)=>value.trim()).filter(Boolean)){const{error}=await db.from("bill_sponsors").insert({bill_id:bill.id,external_legislator_id:`tlo:${group[1]}:${slug(name)}`,sponsor_name:name,sponsor_slug:slug(name),sponsor_role:group[1],chamber:group[2],sequence:sequence++});if(error)throw error;stats.sponsors++;}}
    }
    return Response.json({ok:true,stats});
  }catch(error){let message="";try{message=error instanceof Error?error.message:JSON.stringify(error);}catch{message=String(error);}return Response.json({ok:false,error:message,stats},{status:500});}
});
