import { createFileRoute } from "@tanstack/react-router";
import { dedupeArticleBody } from "@/lib/article-dedupe";
import { detectDiscoverCategory } from "@/lib/seo-headline";
import { scoreDiscoverMatch, type HeadlineVariants } from "@/lib/ctr-score";
import { getArticleImage } from "@/lib/fallback-images";
import { enrichArticleRow } from "@/lib/content-quality";
import { generateFeaturedImageForSlugDirect } from "@/lib/featured-image.functions";
import { isDuplicateTitle, dedupeByTitle } from "@/lib/title-similarity";
import { articleMainWordCount } from "@/lib/article-length";
import { scoreFeedItem, TEXAS_RELEVANCE_MIN } from "@/lib/viral-score";
import { neutralizeFirstPersonTitle } from "@/lib/neutralize-headline";
import { runEditorialRewrite } from "@/lib/editorial-pipeline";
import { resolveFeedPublishSource } from "@/lib/feed-publish-source";

// Reuses the existing Texas relevance scorer (title + description + source
// entity signals) so a source labelled "USGS Earthquakes — Texas" cannot push
// non-Texas events (Peru, California, etc.) into Texas-facing surfaces.
// Items that score below the shared TEXAS_RELEVANCE_MIN floor are dropped
// before they reach texas_news_feed and before native articles are minted,
// which is what gates visibility on /happening-now and category feeds.
function isTexasRelevantItem(it: Item): boolean {
  const r = scoreFeedItem({
    title: it.title ?? "",
    source: it.source ?? "",
    pub_date: it.pub_date,
    description: it.description ?? "",
  });
  return r.texasRelevanceScore >= TEXAS_RELEVANCE_MIN;
}

// Tiered minimum word counts for ingested RSS rewrites. Short official press
// releases (governor, SoS, Texas Register) rarely justify 2,000 words, so we
// gate them at a lower "breaking news" floor. Analysis-friendly lifestyle /
// business feeds get a middle tier. Evergreen articles are generated by a
// separate pipeline and still enforce the 5,000-word rule there.
const MIN_WORDS_BREAKING = 800;
const MIN_WORDS_ANALYSIS = 1200;
// Used inside the AI prompt/expansion payload as the baseline the model
// should aim for. Individual items are gated by their tiered target below.
const NON_EVERGREEN_MIN_MAIN_WORDS = MIN_WORDS_BREAKING;

function minWordsForItem(it: Item, rw: Rewrite | null): number {
  const cat = (rw?.category ?? it.category ?? categoryFor(it.source)).toLowerCase();
  if (cat === "non-political" || cat === "business" || cat === "education" || cat === "sports") {
    return MIN_WORDS_ANALYSIS;
  }
  return MIN_WORDS_BREAKING;
}

// Image-bucket taxonomy. Kept in sync with CATEGORY_IMAGE_POOLS in
// src/lib/fallback-images.ts. AI batch classifier tags each new article with
// one of these so the render layer can pick a matching free stock photo.
// Hard-coded official Texas RSS feeds. Preserved as a fallback (and always
// merged with enabled content_sources rows) so ingestion keeps working even
// if the Source Library is empty or the DB read fails.
const HARDCODED_SOURCES: { name: string; url: string; category?: string }[] = [
  { name: "Office of the Governor", url: "https://gov.texas.gov/news/rss" },
  { name: "Texas Secretary of State", url: "https://www.sos.state.tx.us/rss/press.xml" },
  { name: "Texas Register", url: "https://www.sos.state.tx.us/texreg/texreg.xml" },
  // Non-Political feed group: human-interest, culture, parks, lifestyle, viral.
  {
    name: "Texas Parks & Wildlife",
    url: "https://tpwd.texas.gov/newsmedia/releases/rss/",
    category: "Non-Political",
  },
  { name: "Texas Monthly", url: "https://www.texasmonthly.com/feed/", category: "Non-Political" },
  { name: "Texas Standard", url: "https://www.texasstandard.org/feed/", category: "Non-Political" },
  // National outlets frequently publish Texas political stories that local-only
  // feeds never carry. Google News supplies a stable RSS discovery layer while
  // the Texas relevance gate below still rejects unrelated national coverage.
  {
    name: "Fox News — Texas (Google News)",
    url: "https://news.google.com/rss/search?q=site%3Afoxnews.com+Texas+when%3A7d&hl=en-US&gl=US&ceid=US%3Aen",
    category: "Politics",
  },
  {
    name: "Breitbart — Texas (Google News)",
    url: "https://news.google.com/rss/search?q=site%3Abreitbart.com+Texas+when%3A7d&hl=en-US&gl=US&ceid=US%3Aen",
    category: "Politics",
  },
];

type IngestSource = { name: string; url: string; category?: string };

// One-time editorial recovery items are merged into each storage-only ingest
// and deduped by canonical link. This guarantees a specifically requested
// missed story reaches Content Opportunities even when database migrations
// are not applied automatically by the hosting deployment.
const EDITORIAL_BACKFILLS: Item[] = [
  {
    title:
      "Joe Rogan warns liberals against trying to turn Texas blue, says it would wreck the state's delicate balance",
    link:
      "https://www.foxnews.com/media/joe-rogan-warns-liberals-against-trying-turn-texas-blue-says-would-wreck-states-delicate-balance",
    pub_date: "2026-07-28T00:00:00.000Z",
    source: "Fox News",
    category: "Politics",
    description:
      "Podcaster Joe Rogan discussed the political character of Austin and Texas during a conversation with wildlife television personality Forrest Galante. Rogan described Austin as a progressive city surrounded by strongly Republican parts of Texas and argued that the contrast creates a balance that benefits the city and the state. He said Austin progressives tend to be more reasonable than liberals he encountered in New York or Los Angeles and pushed back on stereotypes that portray Texas as culturally uniform or unsophisticated. Rogan, who moved from Los Angeles to Austin during the COVID-19 era and records his podcast in the area, warned activists who want to make Texas uniformly Democratic that doing so could undermine what makes the state attractive, including for newcomers. The discussion also touched on the phrase Keep Austin weird and surrounded, Austin's long history of Democratic municipal leadership, and the city's position as a liberal enclave inside a Republican-led state. Rogan's comments are relevant to the continuing debate over demographic change, migration, political identity, and Democratic efforts to become more competitive in statewide Texas elections.",
  },
  {
    title:
      "Report: James Talarico filmed driving rental truck in 'Real Texan' campaign ad",
    link:
      "https://www.breitbart.com/politics/2026/07/29/report-james-talarico-drives-enterprise-rental-truck-real-texan-campaign-ad/",
    pub_date: "2026-07-29T00:00:00.000Z",
    source: "Breitbart",
    category: "Politics",
    description:
      "A July 29 Breitbart report concerns Texas Democratic politician James Talarico and a campaign advertisement presenting him driving a pickup truck. The report says the vehicle shown in the advertisement was an Enterprise rental rather than Talarico's own truck. The story focuses on political image-making, the authenticity of campaign advertising, and how candidates present their Texas identity to voters. Talarico is the Democratic nominee in the 2026 Texas United States Senate race, according to the official election records used by KeepTXRed's Election Central. His active statewide campaign makes the presentation and production choices in campaign advertising relevant to voters evaluating the candidates. The reported rental does not itself establish a violation of election law, but it creates a factual question about how the advertisement was staged and whether viewers understood the truck to be personally associated with the candidate. Because the advertisement targets Texas voters during an active statewide election, the report belongs in the Politics content-review queue. Editors can use the source report, official candidate records, and any campaign response when deciding whether to publish a full KeepTXRed article.",
  },
];

// Merge hard-coded official sources with any enabled content_sources rows that
// declare an rss_url. Dedupe by feed URL (case-insensitive). The Source Library
// is additive — it never removes an official feed.
async function loadSources(supabaseAdmin: {
  from: (t: string) => {
    select: (c: string) => {
      eq: (
        col: string,
        val: unknown,
      ) => {
        not: (
          col: string,
          op: string,
          val: unknown,
        ) => Promise<{ data: unknown; error: { message: string } | null }>;
      };
    };
  };
}): Promise<{ sources: IngestSource[]; enabledDbCount: number }> {
  const list: IngestSource[] = [...HARDCODED_SOURCES];
  const seen = new Set(list.map((s) => s.url.toLowerCase()));
  let enabledDbCount = 0;
  try {
    const { data, error } = await supabaseAdmin
      .from("content_sources")
      .select("source_name, rss_url, category, enabled")
      .eq("enabled", true)
      .not("rss_url", "is", null);
    if (error) {
      console.warn("[ingest-feeds] content_sources load failed:", error.message);
    } else if (Array.isArray(data)) {
      const rows = data as {
        source_name: string;
        rss_url: string | null;
        category: string | null;
      }[];
      enabledDbCount = rows.length;
      for (const r of rows) {
        const url = (r.rss_url ?? "").trim();
        if (!url) continue;
        const key = url.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        list.push({ name: r.source_name, url, category: r.category ?? undefined });
      }
    }
  } catch (e) {
    console.warn("[ingest-feeds] content_sources load threw:", e);
  }
  return { sources: list, enabledDbCount };
}

function decode(s: string) {
  return s
    .replace(/<!\[CDATA\[(.*?)\]\]>/gs, "$1")
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/&nbsp;/g, " ")
    .replace(/&(?:lsquo|rsquo);/g, "'")
    .replace(/&(?:ldquo|rdquo);/g, '"')
    .replace(/&(?:ndash|mdash);/g, "—")
    .replace(/&hellip;/g, "…")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/<[^>]+>/g, "")
    .trim();
}

function pick(block: string, tag: string): string {
  const m = block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, "i"));
  return m ? decode(m[1]) : "";
}

type Item = {
  title: string;
  link: string;
  pub_date: string;
  source: string;
  description: string;
  category?: string;
};

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
}

// Block daily puzzle / crossword / word-game filler that some lifestyle
// feeds (Texas Monthly, etc.) publish every day. Matches variants like
// "The Daily Crossword", "Daily Puzzle for ...", "Word Game", "Sudoku".
export function isPuzzleTitle(title: string): boolean {
  const t = title.toLowerCase();
  return (
    /\bcrossword\b/.test(t) ||
    /\bsudoku\b/.test(t) ||
    /\bword\s*(game|search|jumble|wrangler)\b/.test(t) ||
    /\b(daily|weekly)\s+puzzle\b/.test(t) ||
    /\bpuzzle\s+(for|of\s+the\s+day)\b/.test(t) ||
    /\bmini\s+puzzle\b/.test(t) ||
    // recurring daily-column filler (mirrors src/lib/low-value-titles.ts)
    /\bword\s+wrangler\b/.test(t) ||
    /\bhoroscope(s)?\b/.test(t) ||
    /\bquiz\s+of\s+the\s+(day|week)\b/.test(t) ||
    /\bcartoon\s+of\s+the\s+day\b/.test(t) ||
    /\bnewsletter\b/.test(t)
  );
}

function hashStr(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h).toString(36).slice(0, 6);
}

type ImageBucket =
  "food" | "sports" | "politics" | "business" | "weather" | "technology" | "default";

function deterministicImageBucket(title: string, dek: string): ImageBucket {
  const text = `${title} ${dek}`.toLowerCase();
  if (/\b(food|restaurant|recipe|barbecue|bbq)\b/.test(text)) return "food";
  if (/\b(sport|football|baseball|basketball|soccer|team|game)\b/.test(text)) return "sports";
  if (/\b(election|governor|legislature|senate|house|campaign|politic)\b/.test(text))
    return "politics";
  if (/\b(business|company|economy|jobs|market|tax)\b/.test(text)) return "business";
  if (/\b(weather|storm|hurricane|tornado|flood|heat)\b/.test(text)) return "weather";
  if (/\b(technology|tech|software|ai|energy|ercot|grid)\b/.test(text)) return "technology";
  return "default";
}

async function classifyImageBuckets(
  rows: { slug: string; title: string; dek: string }[],
  _lovableApiKey: string,
): Promise<Record<string, ImageBucket>> {
  return Object.fromEntries(
    rows.map((row) => [row.slug, deterministicImageBucket(row.title, row.dek)]),
  );
}

async function rewriteHeadlinesBatch(
  rows: { slug: string; title: string }[],
  _lovableApiKey: string,
): Promise<Record<string, string>> {
  return Object.fromEntries(rows.map((row) => [row.slug, neutralizeFirstPersonTitle(row.title)]));
}

async function generateHeadlineVariantsBatch(
  rows: { slug: string; title: string }[],
  _lovableApiKey: string,
): Promise<Record<string, HeadlineVariants>> {
  return Object.fromEntries(rows.map((row) => [row.slug, { a: row.title, b: row.title }]));
}

async function contentFingerprint(it: Item): Promise<string> {
  const normalized = [
    it.link.trim().toLowerCase(),
    it.title.trim().replace(/\s+/g, " ").toLowerCase(),
    it.pub_date.slice(0, 10),
    it.description.trim().replace(/\s+/g, " "),
  ].join("\n");
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(normalized));
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

const ALLOWED_CATEGORIES = [
  "Politics",
  "Elections",
  "Laws",
  "Legislature",
  "Business",
  "Sports",
  "Education",
  "Non-Political",
] as const;

function categoryFor(source: string): string {
  const s = source.toLowerCase();
  if (s.includes("governor")) return "Politics";
  if (s.includes("secretary")) return "Elections";
  if (s.includes("register")) return "Laws";
  if (s.includes("parks") || s.includes("monthly") || s.includes("standard"))
    return "Non-Political";
  return "Legislature";
}

type Rewrite = {
  title: string;
  dek: string;
  keywords: string[];
  summary: string;
  relevance: string;
  analysis?: string;
  sections?: { heading: string; paragraphs: string[] }[];
  keyTakeaways: string[];
  faq?: { q: string; a: string }[];
  category?: string;
};

type GeneratedArticleBody = {
  intro: string[];
  sections: { heading?: string; paragraphs?: string[]; bullets?: string[] }[];
  faq?: { q?: string; a?: string }[];
  keyTakeaways?: string[];
};

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

// Small concurrency limiter used by the batch rewrite path. Cloudflare Workers
// have a fixed wall-clock budget per request; firing `Promise.all` over
// hundreds of 15–90s AI fetches was killing the whole invocation, which
// showed up in logs as every rewrite ending in `no_response` (the fetch was
// aborted before it ever reached the AI gateway). Capping concurrency lets
// each rewrite complete and lets us log per-item outcomes.
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let cursor = 0;
  const workers = Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, async () => {
    while (true) {
      const i = cursor++;
      if (i >= items.length) return;
      out[i] = await fn(items[i], i);
    }
  });
  await Promise.all(workers);
  return out;
}

function articleBodyText(body: GeneratedArticleBody): string {
  const parts: string[] = [];
  (body.intro ?? []).forEach((p) => parts.push(p));
  (body.sections ?? []).forEach((s) => {
    if (s.heading) parts.push(s.heading);
    (s.paragraphs ?? []).forEach((p) => parts.push(p));
    (s.bullets ?? []).forEach((p) => parts.push(p));
  });
  (body.faq ?? []).forEach((f) => {
    if (f.q) parts.push(f.q);
    if (f.a) parts.push(f.a);
  });
  (body.keyTakeaways ?? []).forEach((p) => parts.push(p));
  return parts.join(" ");
}

const REWRITE_SYSTEM = `You are the Keep TX Red editorial engine. Rewrite a Texas news item from an official source into a fully ORIGINAL article for keeptxred.com.

HARD RULES:
- Extract only facts (who/what/when/where/why). Never copy sentences or phrasing from the source. No direct quote longer than 10 words.
- Neutral, factual tone in Summary, Relevance, and Key Takeaways. Analysis is clearly labeled opinion and is optional.
- Mobile-friendly paragraphs (2–4 sentences each).
- Meta description (dek) MUST be <= 155 characters.
- Title must be SEO-optimized, original, and not resemble the source headline.
- 5–10 lowercase keywords, Texas-specific where possible.
- MINIMUM LENGTH: every non-evergreen article MUST be at least ${NON_EVERGREEN_MIN_MAIN_WORDS} words of original MAIN STORY PROSE across summary + analysis + sections only. Do NOT count Texas relevance, source attribution, FAQ, key takeaways, title, dek, or source lists toward this minimum. There is no upper word limit. Do not summarize briefly; expand with source-grounded context, background, stakeholders, local impact, timeline, what changes next, and reader context until the main story prose meets the minimum.
- TEXAS RELEVANCE IS REQUIRED — the "relevance" field must always name Texas or a specific Texas city/region and explain the local stake, even if the source is national.
- Add a short original CONTEXT paragraph (history, prior action, comparable state precedent) inside the "summary" or as the first sentences of "relevance".
- Include 5–8 additional article sections in "sections". Each section must have a clear heading and 2–4 substantial paragraphs. Do not use filler, generic slogans, or repeated paragraphs.
- FAQ answers should be substantial enough to help readers, not one-line answers.
- Output VALID JSON only matching the schema below.

CATEGORY: Choose the best fit from: Politics, Elections, Laws, Legislature, Business, Sports, Education, Non-Political. Use "Non-Political" for human-interest, animals, viral, culture, festivals, weather, travel, lifestyle, entertainment, science, and parks/wildlife stories. Do NOT use Education as a fallback — only true school/academic policy.

SCHEMA:
{"title":"...","dek":"<=155 chars","keywords":["..."],"summary":"substantial opening section","relevance":"substantial Texas relevance section","analysis":"optional labeled editorial interpretation, or omit","sections":[{"heading":"...","paragraphs":["..."]}],"keyTakeaways":["3-5 short bullets"],"faq":[{"q":"...","a":"..."}],"category":"one of the allowed values"}`;

function isRedditLink(link: string): boolean {
  try {
    const u = new URL(link);
    return /(^|\.)reddit\.com$/i.test(u.hostname);
  } catch {
    return false;
  }
}

async function fetchRedditSelftext(link: string): Promise<string | null> {
  try {
    const u = new URL(link);
    const jsonUrl = `https://www.reddit.com${u.pathname.replace(/\/?$/, "")}.json`;
    const r = await fetch(jsonUrl, {
      headers: { "User-Agent": "KeepTXRed/1.0 (+https://keeptxred.com)" },
      signal: AbortSignal.timeout(8000),
    });
    if (!r.ok) return null;
    const data = (await r.json()) as Array<{
      data?: { children?: Array<{ data?: { selftext?: string } }> };
    }>;
    const selftext = data?.[0]?.data?.children?.[0]?.data?.selftext ?? "";
    const cleaned = selftext.replace(/\s+/g, " ").trim();
    return cleaned.length > 0 ? cleaned : null;
  } catch {
    return null;
  }
}

type RedditPostData = {
  selftext: string | null;
  externalUrl: string | null;
};

// One request covers both self-posts and link-posts: Red…5745 tokens truncated… AI calls).
    for (const row of articleRows) {
      const anyRow = row as Record<string, unknown>;
      const variants =
        variantMap[row.slug] ??
        ({
          a: (anyRow.seo_headline as string | null) ?? row.title,
          b: row.title,
        } as HeadlineVariants);
      anyRow.headline_variants = variants;

      const resolvedImageUrl = getArticleImage({
        slug: row.slug,
        image_url: (anyRow.image_url as string | null | undefined) ?? null,
        image_category: (anyRow.image_category as string | null) ?? null,
        category: row.category,
        title: variants.a,
        dek: row.dek,
        keywords: row.keywords ?? null,
      });
      anyRow.ctr_score = scoreDiscoverMatch({
        slug: row.slug,
        title: row.title,
        dek: row.dek,
        seo_headline: (anyRow.seo_headline as string | null) ?? null,
        discover_category: (anyRow.discover_category as string | null) ?? null,
        image_category: (anyRow.image_category as string | null) ?? null,
        image_url: (anyRow.image_url as string | null | undefined) ?? null,
        category: row.category,
        keywords: row.keywords ?? null,
        seo_keywords: (anyRow.seo_keywords as string[] | null) ?? null,
        resolvedImageUrl,
      });
    }

    articleRows.forEach((r) => enrichArticleRow(r));

    // Deduplicate: (1) collapse near-duplicate titles within this batch,
    // (2) drop anything whose title matches an article published in the
    // last 7 days. Same story, different wording must never appear twice.
    const withinBatch = dedupeByTitle(articleRows as Array<{ title: string; slug: string }>);
    stageCounts.dedupedInBatch = articleRows.length - withinBatch.length;
    const sinceIso = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
    const { data: recent } = await supabaseAdmin
      .from("daily_articles")
      .select("title")
      .gte("published_at", sinceIso);
    const recentTitles = (recent ?? []).map((r: { title: string }) => r.title);
    const dedupedSlugs = new Set(
      withinBatch
        .filter((r) => !recentTitles.some((t) => isDuplicateTitle(t, r.title)))
        .map((r) => r.slug),
    );
    stageCounts.dedupedVsRecent = withinBatch.length - dedupedSlugs.size;
    const uniqueArticleRows = articleRows.filter((r) => dedupedSlugs.has(r.slug));
    if (uniqueArticleRows.length === 0) {
      console.log("[ingest-feeds] all articles deduped", stageCounts);
      return new Response(
        JSON.stringify({
          ok: true,
          inserted,
          nativeMinted: 0,
          skipped: fresh.length,
          dedupedAll: true,
          stageCounts,
        }),
        { headers: { "Content-Type": "application/json" } },
      );
    }

    const { error: artErr, count: artCount } = await supabaseAdmin
      .from("daily_articles")
      .upsert(uniqueArticleRows, { onConflict: "slug", ignoreDuplicates: true, count: "exact" });
    if (artErr) {
      console.error("[ingest-feeds] daily_articles upsert failed", {
        message: artErr?.message,
        count: uniqueArticleRows.length,
      });
    }
    if (!artErr) {
      nativeMinted = artCount ?? uniqueArticleRows.length;
      stageCounts.articlesUpserted = nativeMinted;
      await Promise.allSettled(
        uniqueArticleRows.map((row: { slug: string }) =>
          generateFeaturedImageForSlugDirect(row.slug, true),
        ),
      );
      // Write the internal slug back onto the feed row so cards can link to it.
      const linkResults = await Promise.all(
        uniqueArticleRows.map((row: { slug: string }) => {
          const src = articleSourceBySlug.get(row.slug);
          if (!src) return Promise.resolve({ ok: false });
          return supabaseAdmin
            .from("texas_news_feed")
            .update({ internal_slug: row.slug })
            .eq("link", src.link)
            .then((r) => ({ ok: !r.error, error: r.error?.message }));
        }),
      );
      stageCounts.internalSlugsLinked = linkResults.filter(
        (r) => (r as { ok?: boolean }).ok,
      ).length;
      const linkErrors = linkResults.filter(
        (r) => (r as { ok?: boolean }).ok === false && (r as { error?: string }).error,
      );
      if (linkErrors.length > 0) {
        console.error("[ingest-feeds] internal_slug writeback errors", {
          count: linkErrors.length,
          sample: linkErrors.slice(0, 3),
        });
      }
    }
    console.log("[ingest-feeds] batch complete", stageCounts);
  }

  // Backfill internal_slug for any older feed rows that don't have one yet.
  const { data: orphans } = await supabaseAdmin
    .from("texas_news_feed")
    .select("id,title,link,source,description,pub_date")
    .is("internal_slug", null)
    .limit(25);
  if (orphans?.length) {
    const lovableApiKey = process.env.LOVABLE_API_KEY;
    const items: Item[] = orphans!.map((row) => ({
      title: row.title,
      link: row.link,
      source: row.source,
      pub_date: row.pub_date,
      description: row.description ?? "",
    }));
    const rewrites: (Rewrite | null)[] = lovableApiKey
      ? await mapWithConcurrency(items, 4, (it) => rewriteItemWithRetry(it, lovableApiKey!))
      : items.map(() => null);
    console.log("[ingest-feeds] orphan backfill", {
      candidates: items.length,
      rewriteSucceeded: rewrites.filter(Boolean).length,
      rewriteFailed: rewrites.filter((r) => !r).length,
    });
    // Only mint articles for orphans whose rewrite succeeded.
    const paired = items
      .map((it, i) => ({ it, rw: rewrites[i] }))
      .filter((p): p is { it: Item; rw: Rewrite } => p.rw !== null);
    const backPaired = paired
      .map(({ it, rw }) => ({ it, rw, row: buildArticleRow(it, rw) }))
      .filter(({ it, rw, row }) => {
        const target = minWordsForItem(it, rw);
        const words = articleMainWordCount(row.body_json);
        if (words < target) {
          console.warn("[ingest-feeds] backfill dropped article below tiered floor", {
            slug: row.slug,
            source: it.source,
            words,
            target,
          });
          return false;
        }
        return true;
      });
    const backRows = backPaired.map(({ row }) => row);
    backRows.forEach((r) => enrichArticleRow(r));
    if (backRows.length > 0) {
      await supabaseAdmin
        .from("daily_articles")
        .upsert(backRows, { onConflict: "slug", ignoreDuplicates: true });
      await Promise.allSettled(
        backRows.map((row: { slug: string }) => generateFeaturedImageForSlugDirect(row.slug, true)),
      );
      await Promise.all(
        backPaired.map(({ it, row }) =>
          supabaseAdmin
            .from("texas_news_feed")
            .update({ internal_slug: row.slug })
            .eq("link", it.link),
        ),
      );
    }
  }

  // Canonical-URL dedupe: for any daily_articles rows sharing the same
  // source_url, keep the most-recently-updated slug and drop the rest.
  let dedupedCanonical = 0;
  let dedupeSkippedReason: string | null = null;
  try {
    // Total daily_articles row count — used both to skip cleanup on empty-run
    // scenarios and to enforce a % safety cap on how much a single ingest may
    // delete. A prior version of this block wiped the whole table when the
    // rewrite batch produced no rows AND canonical dedupe ran unchecked.
    const { count: totalArticles } = await supabaseAdmin
      .from("daily_articles")
      .select("id", { count: "exact", head: true });
    const totalCount = totalArticles ?? 0;

    // Safety rule 3: if the table already has articles but THIS ingest run
    // produced zero successful rewrites (native mint + backfill both silent),
    // do not run destructive cleanup — an empty rewrite batch is not evidence
    // that historical rows are duplicates.
    if (totalCount > 0 && nativeMinted === 0) {
      dedupeSkippedReason = "no successful rewrites in this run";
    } else {
      const { data: dupes } = await supabaseAdmin
        .from("daily_articles")
        .select("id, slug, source_url, published_at")
        .not("source_url", "is", null)
        .order("published_at", { ascending: false, nullsFirst: false })
        .limit(1000);
      if (dupes?.length) {
        // Group by canonical source_url; keep the newest (list is already
        // sorted desc by published_at), mark strictly older siblings for
        // deletion. Rows without a source_url were excluded above.
        const seen = new Set<string>();
        const toDelete: string[] = [];
        for (const row of dupes! as { id: string; slug: string; source_url: string | null }[]) {
          const key = row.source_url;
          if (!key) continue;
          if (seen.has(key!)) toDelete.push(row.id);
          else seen.add(key!);
        }
        if (toDelete.length > 0) {
          // Never delete a published URL during ingestion. Older rows may
          // already be indexed or linked externally; deleting them creates
          // avoidable 404s. Source-level dedupe should happen before a new slug
          // is published, or via an explicit persisted redirect.
          dedupeSkippedReason = `preserved ${toDelete.length} published duplicate-source URL(s)`;
          console.warn("[ingest-feeds] canonical dedupe preserved published URLs", {
            candidates: toDelete.length,
            total: totalCount,
          });
        }
      }
    }
  } catch (e) {
    console.error("canonical dedupe failed", e);
  }

  return new Response(
    JSON.stringify({
      ok: true,
      fetched: all.length,
      candidates: fresh.length,
      inserted,
      nativeMinted,
      dedupedCanonical,
      dedupeSkippedReason,
      stageCounts,
      diag,
    }),
    { headers: { "Content-Type": "application/json" } },
  );
}

/**
 * Single-item publish path used by the Admin "Publish to Keep Texas Red"
 * button. Reuses the same rewrite → build → enrich → image pipeline as the
 * batch ingestion so category, article type, SEO and image logic remain the
 * single source of truth. Safe to call multiple times: if the feed row is
 * already linked to a daily_articles slug, returns that slug unchanged.
 */
export async function publishSingleFeedItem(
  feedItemId: number,
): Promise<{ ok: boolean; slug?: string; error?: string; alreadyPublished?: boolean }> {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { data: row, error: rowErr } = await supabaseAdmin
    .from("texas_news_feed")
    .select("id,title,link,source,description,pub_date,internal_slug,extracted_body,preflight_json")
    .eq("id", feedItemId)
    .maybeSingle();
  if (rowErr || !row) {
    return { ok: false, error: rowErr?.message ?? "Feed item not found" };
  }
  if (row.internal_slug) {
    return { ok: true, slug: row.internal_slug, alreadyPublished: true };
  }
  if (isPuzzleTitle(row.title)) {
    return { ok: false, error: "Puzzle / filler titles are blocked from publish." };
  }
  const lovableApiKey = process.env.LOVABLE_API_KEY;
  if (!lovableApiKey) return { ok: false, error: "Missing LOVABLE_API_KEY" };

  const item: Item = {
    title: row.title,
    link: row.link,
    source: row.source,
    pub_date: row.pub_date,
    description: row.description ?? "",
  };

  // ------------------------------------------------------------------
  // FULL SOURCE EXTRACTION FIRST — the preflight must see the real body,
  // not the ~40-word RSS summary. Reuse a previously stored extracted body
  // when we already paid to fetch it. Otherwise run extraction exactly once,
  // cache it, and hand it to the preflight assessor.
  // ------------------------------------------------------------------
  const cachedBody =
    typeof (row as { extracted_body?: string | null }).extracted_body === "string"
      ? ((row as { extracted_body?: string | null }).extracted_body ?? "").trim()
      : "";
  let extractedBody: string = cachedBody;
  let extractionFailureStage: "extraction" | "preflight" | "none" = "none";
  let resolvedSourceWordCount: number | null = null;

  if (isRedditLink(item.link)) {
    // Reddit RSS descriptions rarely contain the post body — pull selftext from
    // the public JSON endpoint so the AI rewrite has real source material.
    // Refuse to publish headline-only Reddit posts rather than fabricating facts.
    let selftext: string | null = null;
    let externalUrl: string | null = null;
    let linkedText: string | null = null;

    if (!cachedBody) {
      const redditData = await fetchRedditPostData(item.link);
      selftext = redditData.selftext;
      externalUrl = redditData.externalUrl;
      if (externalUrl) linkedText = await fetchLinkedArticleText(externalUrl);
    }

    const resolvedSource = resolveFeedPublishSource({
      cachedExtraction: cachedBody,
      storedDescription: item.description,
      redditSelftext: selftext,
      linkedArticleText: linkedText,
      linkedArticleUrl: externalUrl,
    });
    extractedBody = resolvedSource.text;
    resolvedSourceWordCount = resolvedSource.wordCount;

    if (!resolvedSource.meetsAbsoluteMinimum) {
      extractionFailureStage = "extraction";
      const { assessRewritePreflight: preflightAssess, toPersistedSnapshot } =
        await import("@/lib/rewrite-preflight");
      const blocked = preflightAssess({
        title: item.title,
        description: resolvedSource.text,
        link: item.link,
      });
      await supabaseAdmin
        .from("texas_news_feed")
        .update({ preflight_json: toPersistedSnapshot(blocked, extractionFailureStage) } as never)
        .eq("id", feedItemId);
      return {
        ok: false,
        error:
          "This Reddit post does not contain enough text to generate a factual KeepTXRed article.",
      };
    }
  } else if (!extractedBody) {
    // Non-Reddit path: if the stored RSS description is short, run the same
    // linked-article extraction we already use for Reddit link posts so a
    // 40-word RSS summary is never treated as the full source.
    const rssBody = item.description?.trim() ?? "";
    const rssWords = wordCount(rssBody);
    if (rssWords < 400 && item.link && /^https?:\/\//i.test(item.link)) {
      const fetched = await fetchLinkedArticleText(item.link);
      if (fetched && wordCount(fetched) > rssWords) {
        extractedBody = rssBody ? `${rssBody}\n\n${fetched}` : fetched;
      } else {
        extractedBody = rssBody;
      }
    } else {
      extractedBody = rssBody;
    }
  }

  // The AI rewrite prompt now sees the full extracted body, not the RSS blurb.
  if (extractedBody) item.description = extractedBody;

  // Deterministic preflight — refuse to spend AI rewrite credits when the
  // extracted source clearly cannot produce a factual article.
  const {
    assessRewritePreflight,
    assertRewriteableOrThrow,
    toPersistedSnapshot,
    PreflightBlockedError,
  } = await import("@/lib/rewrite-preflight");
  const preflight = assessRewritePreflight({
    title: item.title,
    description: extractedBody, // ALWAYS the full extracted body, never the RSS blurb alone
    link: item.link,
  });
  console.log("[publishSingleFeedItem] preflight", {
    feed_item_id: feedItemId,
    rewriteable: preflight.rewriteable,
    reason: preflight.reason,
    source_word_count: preflight.sourceWordCount,
    used_cached_extraction: cachedBody.length > 0,
    extracted_body_words: resolvedSourceWordCount ?? wordCount(extractedBody),
  });

  // Persist the extraction + preflight snapshot so page loads and admin
  // dashboards can render the reason without recomputing.
  await supabaseAdmin
    .from("texas_news_feed")
    .update({
      extracted_body: extractedBody || null,
      preflight_json: toPersistedSnapshot(preflight, preflight.rewriteable ? "none" : "preflight"),
    } as never)
    .eq("id", feedItemId);

  if (!preflight.rewriteable) {
    return {
      ok: false,
      error: `Rewrite skipped before AI generation: ${preflight.message}`,
    };
  }

  // Hard guard — no matter how we got here, refuse to call the paid rewrite
  // function when preflight is not ok. Throws PreflightBlockedError so tests
  // can prove the rewrite mock is never reached.
  assertRewriteableOrThrow(preflight);

  const fingerprint = await contentFingerprint(item);
  // Generated database types are refreshed after the migration is applied.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const cacheClient = supabaseAdmin as any;
  const { data: cachedRow } = await cacheClient
    .from("ai_rewrite_cache")
    .select("result_json,status")
    .eq("content_fingerprint", fingerprint)
    .maybeSingle();
  const cached = cachedRow as unknown as { result_json?: Rewrite | null; status?: string } | null;
  let rw = cached?.status === "completed" && cached.result_json ? cached.result_json : null;

  if (!rw) {
    const configuredLimit = Number.parseInt(process.env.DAILY_AI_REWRITE_LIMIT ?? "8", 10);
    const dailyLimit = Number.isFinite(configuredLimit)
      ? Math.min(50, Math.max(1, configuredLimit))
      : 8;
    const { data: claimData, error: claimError } = await supabaseAdmin.rpc(
      "claim_ai_rewrite_slot" as never,
      {
        p_content_fingerprint: fingerprint,
        p_feed_item_id: feedItemId,
        p_daily_limit: dailyLimit,
      } as never,
    );
    if (claimError) {
      return { ok: false, error: `Could not reserve AI rewrite budget: ${claimError.message}` };
    }
    const claim = claimData as unknown as string;
    if (claim === "budget_exhausted") {
      return {
        ok: false,
        error: `Daily AI rewrite budget reached (${dailyLimit}). Try again after midnight UTC.`,
      };
    }
    if (claim === "in_progress") {
      return {
        ok: false,
        error: "This source is already being rewritten. Try again in a few minutes.",
      };
    }
    if (claim === "cached") {
      const { data: refreshedRow } = await cacheClient
        .from("ai_rewrite_cache")
        .select("result_json")
        .eq("content_fingerprint", fingerprint)
        .maybeSingle();
      rw =
        (refreshedRow as unknown as { result_json?: Rewrite | null } | null)?.result_json ?? null;
    } else {
      rw = await rewriteItemWithRetry(item, lovableApiKey);
      const cacheUpdate = rw
        ? {
            status: "completed",
            result_json: rw,
            failure_reason: null,
            completed_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          }
        : {
            status: "failed",
            result_json: null,
            failure_reason: "AI rewrite failed",
            completed_at: null,
            updated_at: new Date().toISOString(),
          };
      await cacheClient
        .from("ai_rewrite_cache")
        .update(cacheUpdate as never)
        .eq("content_fingerprint", fingerprint);
    }
  }

  if (!rw) return { ok: false, error: "AI rewrite failed" };
  void PreflightBlockedError; // keep type import referenced for downstream callers

  const articleRow = buildArticleRow(item, rw);
  const target = minWordsForItem(item, rw);
  const words = articleMainWordCount(articleRow.body_json);
  if (words < target) {
    return {
      ok: false,
      error: `Rewrite below tiered minimum (${words}/${target} words). Try again.`,
    };
  }
  enrichArticleRow(articleRow);

  const { error: upsertErr } = await supabaseAdmin
    .from("daily_articles")
    .upsert([articleRow], { onConflict: "slug", ignoreDuplicates: true });
  if (upsertErr) return { ok: false, error: upsertErr.message };

  await supabaseAdmin
    .from("texas_news_feed")
    .update({ internal_slug: articleRow.slug })
    .eq("id", feedItemId);

  // Fire-and-forget image generation; UI already renders without it.
  void generateFeaturedImageForSlugDirect(articleRow.slug, true).catch(() => undefined);

  return { ok: true, slug: articleRow.slug };
}
