import { createFileRoute } from "@tanstack/react-router";
import { dedupeArticleBody } from "@/lib/article-dedupe";
import { detectDiscoverCategory } from "@/lib/seo-headline";
import { scoreDiscoverMatch, type HeadlineVariants } from "@/lib/ctr-score";
import { getArticleImage } from "@/lib/fallback-images";
import { enrichArticleRow } from "@/lib/content-quality";
import { generateFeaturedImageForSlugDirect } from "@/lib/featured-image.functions";
import { isDuplicateTitle, dedupeByTitle } from "@/lib/title-similarity";
import { articleMainWordCount } from "@/lib/article-length";
import { scoreFeedItem, TEXAS_RELEVANCE_MIN } from "@/lib/viral-score";

// Reuses the existing Texas relevance scorer (title + description + source
// entity signals) so a source labelled "USGS Earthquakes — Texas" cannot push
// non-Texas events (Peru, California, etc.) into Texas-facing surfaces.
// Items that score below the shared TEXAS_RELEVANCE_MIN floor are dropped
// before they reach texas_news_feed and before native articles are minted,
// which is what gates visibility on /happening-now and category feeds.
function isTexasRelevantItem(it: Item): boolean {
  const r = scoreFeedItem({
    title: it.title ?? "",
    source: it.source ?? "",
    pub_date: it.pub_date,
    description: it.description ?? "",
  });
  return r.texasRelevanceScore >= TEXAS_RELEVANCE_MIN;
}

// Tiered minimum word counts for ingested RSS rewrites. Short official press
// releases (governor, SoS, Texas Register) rarely justify 2,000 words, so we
// gate them at a lower "breaking news" floor. Analysis-friendly lifestyle /
// business feeds get a middle tier. Evergreen articles are generated by a
// separate pipeline and still enforce the 5,000-word rule there.
const MIN_WORDS_BREAKING = 800;
const MIN_WORDS_ANALYSIS = 1200;
// Used inside the AI prompt/expansion payload as the baseline the model
// should aim for. Individual items are gated by their tiered target below.
const NON_EVERGREEN_MIN_MAIN_WORDS = MIN_WORDS_BREAKING;

function minWordsForItem(it: Item, rw: Rewrite | null): number {
  const cat = (rw?.category ?? it.category ?? categoryFor(it.source)).toLowerCase();
  if (cat === "non-political" || cat === "business" || cat === "education" || cat === "sports") {
    return MIN_WORDS_ANALYSIS;
  }
  return MIN_WORDS_BREAKING;
}

// Image-bucket taxonomy. Kept in sync with CATEGORY_IMAGE_POOLS in
// src/lib/fallback-images.ts. AI batch classifier tags each new article with
// one of these so the render layer can pick a matching free stock photo.
const IMAGE_BUCKETS = ["food", "sports", "politics", "business", "weather", "technology", "default"] as const;
type ImageBucket = (typeof IMAGE_BUCKETS)[number];

/**
 * ONE Gemini call per ingestion batch. Sends only {id, title, dek} — never the
 * full body — and asks for a JSON map of id -> image bucket. Cached in
 * daily_articles.image_category so we never re-classify the same article.
 */
async function classifyImageBuckets(
  rows: { slug: string; title: string; dek: string }[],
  lovableApiKey: string,
): Promise<Record<string, ImageBucket>> {
  if (rows.length === 0) return {};
  const payload = rows.map((r) => ({ id: r.slug, title: r.title.slice(0, 180), summary: (r.dek || "").slice(0, 200) }));
  try {
    const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": lovableApiKey },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content:
              "Classify each article into ONE image category: food, sports, politics, business, weather, technology, default. Use 'default' when nothing fits. Return JSON object mapping id -> category. No prose.",
          },
          { role: "user", content: JSON.stringify(payload) },
        ],
        response_format: { type: "json_object" },
      }),
      signal: AbortSignal.timeout(20000),
    });
    if (!r.ok) return {};
    const data = (await r.json()) as { choices?: { message?: { content?: string } }[] };
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}") as Record<string, string>;
    const out: Record<string, ImageBucket> = {};
    for (const [id, cat] of Object.entries(parsed)) {
      const c = String(cat).toLowerCase().trim() as ImageBucket;
      if ((IMAGE_BUCKETS as readonly string[]).includes(c)) out[id] = c;
    }
    return out;
  } catch {
    return {};
  }
}

/**
 * ONE Gemini call per ingestion batch. Sends ONLY {id, title} — never the
 * body — and asks for SEO-optimized Google Discover headlines. Cached in
 * daily_articles.seo_headline so the frontend never reprocesses.
 */
async function rewriteHeadlinesBatch(
  rows: { slug: string; title: string }[],
  lovableApiKey: string,
): Promise<Record<string, string>> {
  if (rows.length === 0) return {};
  const payload = rows.map((r) => ({ id: r.slug, title: r.title.slice(0, 200) }));
  try {
    const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": lovableApiKey },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content:
              "Rewrite each headline to be SEO-friendly and optimized for Google Discover. Rules: no clickbait, keep factual accuracy, improve clarity and search relevance, front-load the key topic (Texas, Houston, BBQ, Election, etc.), active voice, 50-90 characters preferred. Return JSON object mapping id -> rewritten_headline. No prose.",
          },
          { role: "user", content: JSON.stringify(payload) },
        ],
        response_format: { type: "json_object" },
      }),
      signal: AbortSignal.timeout(20000),
    });
    if (!r.ok) return {};
    const data = (await r.json()) as { choices?: { message?: { content?: string } }[] };
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}") as Record<string, unknown>;
    const out: Record<string, string> = {};
    for (const [id, headline] of Object.entries(parsed)) {
      const h = String(headline ?? "").trim();
      if (h.length >= 15 && h.length <= 140) out[id] = h;
    }
    return out;
  } catch {
    return {};
  }
}

/**
 * ONE Gemini call per ingestion batch. Generates 2 factual headline variants
 * (A = SEO-focused, B = direct) for cheap A/B testing at render time. Never
 * called per-request; result cached in daily_articles.headline_variants.
 */
async function generateHeadlineVariantsBatch(
  rows: { slug: string; title: string }[],
  lovableApiKey: string,
): Promise<Record<string, HeadlineVariants>> {
  if (rows.length === 0) return {};
  const payload = rows.map((r) => ({ id: r.slug, title: r.title.slice(0, 200) }));
  try {
    const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": lovableApiKey },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content:
              "Create 2 headline versions for each article optimized for Google Discover CTR. Rules: both must be factual (no clickbait exaggeration); variant 'a' is slightly more SEO-focused (front-loads key entity/topic, 50-90 chars); variant 'b' is more direct and conversational (shorter, punchier). Return JSON object: { id: { a: '...', b: '...' } }. No prose.",
          },
          { role: "user", content: JSON.stringify(payload) },
        ],
        response_format: { type: "json_object" },
      }),
      signal: AbortSignal.timeout(20000),
    });
    if (!r.ok) return {};
    const data = (await r.json()) as { choices?: { message?: { content?: string } }[] };
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}") as Record<string, unknown>;
    const out: Record<string, HeadlineVariants> = {};
    for (const [id, v] of Object.entries(parsed)) {
      const obj = v as { a?: unknown; b?: unknown };
      const a = String(obj?.a ?? "").trim();
      const b = String(obj?.b ?? "").trim();
      if (a.length >= 15 && a.length <= 140 && b.length >= 15 && b.length <= 140) {
        out[id] = { a, b };
      }
    }
    return out;
  } catch {
    return {};
  }
}

// Hard-coded official Texas RSS feeds. Preserved as a fallback (and always
// merged with enabled content_sources rows) so ingestion keeps working even
// if the Source Library is empty or the DB read fails.
const HARDCODED_SOURCES: { name: string; url: string; category?: string }[] = [
  { name: "Office of the Governor", url: "https://gov.texas.gov/news/rss" },
  { name: "Texas Secretary of State", url: "https://www.sos.state.tx.us/rss/press.xml" },
  { name: "Texas Register", url: "https://www.sos.state.tx.us/texreg/texreg.xml" },
  // Non-Political feed group: human-interest, culture, parks, lifestyle, viral.
  { name: "Texas Parks & Wildlife", url: "https://tpwd.texas.gov/newsmedia/releases/rss/", category: "Non-Political" },
  { name: "Texas Monthly", url: "https://www.texasmonthly.com/feed/", category: "Non-Political" },
  { name: "Texas Standard", url: "https://www.texasstandard.org/feed/", category: "Non-Political" },
];

type IngestSource = { name: string; url: string; category?: string };

// Merge hard-coded official sources with any enabled content_sources rows that
// declare an rss_url. Dedupe by feed URL (case-insensitive). The Source Library
// is additive — it never removes an official feed.
async function loadSources(
  supabaseAdmin: { from: (t: string) => { select: (c: string) => { eq: (col: string, val: unknown) => { not: (col: string, op: string, val: unknown) => Promise<{ data: unknown; error: { message: string } | null }> } } } },
): Promise<{ sources: IngestSource[]; enabledDbCount: number }> {
  const list: IngestSource[] = [...HARDCODED_SOURCES];
  const seen = new Set(list.map((s) => s.url.toLowerCase()));
  let enabledDbCount = 0;
  try {
    const { data, error } = await supabaseAdmin
      .from("content_sources")
      .select("source_name, rss_url, category, enabled")
      .eq("enabled", true)
      .not("rss_url", "is", null);
    if (error) {
      console.warn("[ingest-feeds] content_sources load failed:", error.message);
    } else if (Array.isArray(data)) {
      const rows = data as { source_name: string; rss_url: string | null; category: string | null }[];
      enabledDbCount = rows.length;
      for (const r of rows) {
        const url = (r.rss_url ?? "").trim();
        if (!url) continue;
        const key = url.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        list.push({ name: r.source_name, url, category: r.category ?? undefined });
      }
    }
  } catch (e) {
    console.warn("[ingest-feeds] content_sources load threw:", e);
  }
  return { sources: list, enabledDbCount };
}

function decode(s: string) {
  return s
    .replace(/<!\[CDATA\[(.*?)\]\]>/gs, "$1")
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/&nbsp;/g, " ")
    .replace(/&(?:lsquo|rsquo);/g, "'")
    .replace(/&(?:ldquo|rdquo);/g, '"')
    .replace(/&(?:ndash|mdash);/g, "—")
    .replace(/&hellip;/g, "…")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/<[^>]+>/g, "")
    .trim();
}

function pick(block: string, tag: string): string {
  const m = block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, "i"));
  return m ? decode(m[1]) : "";
}

type Item = { title: string; link: string; pub_date: string; source: string; description: string; category?: string };

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
}

// Block daily puzzle / crossword / word-game filler that some lifestyle
// feeds (Texas Monthly, etc.) publish every day. Matches variants like
// "The Daily Crossword", "Daily Puzzle for ...", "Word Game", "Sudoku".
export function isPuzzleTitle(title: string): boolean {
  const t = title.toLowerCase();
  return (
    /\bcrossword\b/.test(t) ||
    /\bsudoku\b/.test(t) ||
    /\bword\s*(game|search|jumble)\b/.test(t) ||
    /\b(daily|weekly)\s+puzzle\b/.test(t) ||
    /\bpuzzle\s+(for|of\s+the\s+day)\b/.test(t) ||
    /\bmini\s+puzzle\b/.test(t)
  );
}

function hashStr(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h).toString(36).slice(0, 6);
}

const ALLOWED_CATEGORIES = [
  "Politics",
  "Elections",
  "Laws",
  "Legislature",
  "Business",
  "Sports",
  "Education",
  "Non-Political",
] as const;

function categoryFor(source: string): string {
  const s = source.toLowerCase();
  if (s.includes("governor")) return "Politics";
  if (s.includes("secretary")) return "Elections";
  if (s.includes("register")) return "Laws";
  if (s.includes("parks") || s.includes("monthly") || s.includes("standard")) return "Non-Political";
  return "Legislature";
}

type Rewrite = {
  title: string;
  dek: string;
  keywords: string[];
  summary: string;
  relevance: string;
  analysis?: string;
  sections?: { heading: string; paragraphs: string[] }[];
  keyTakeaways: string[];
  faq?: { q: string; a: string }[];
  category?: string;
};

type GeneratedArticleBody = {
  intro: string[];
  sections: { heading?: string; paragraphs?: string[]; bullets?: string[] }[];
  faq?: { q?: string; a?: string }[];
  keyTakeaways?: string[];
};

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function articleBodyText(body: GeneratedArticleBody): string {
  const parts: string[] = [];
  (body.intro ?? []).forEach((p) => parts.push(p));
  (body.sections ?? []).forEach((s) => {
    if (s.heading) parts.push(s.heading);
    (s.paragraphs ?? []).forEach((p) => parts.push(p));
    (s.bullets ?? []).forEach((p) => parts.push(p));
  });
  (body.faq ?? []).forEach((f) => {
    if (f.q) parts.push(f.q);
    if (f.a) parts.push(f.a);
  });
  (body.keyTakeaways ?? []).forEach((p) => parts.push(p));
  return parts.join(" ");
}

const REWRITE_SYSTEM = `You are the Keep TX Red editorial engine. Rewrite a Texas news item from an official source into a fully ORIGINAL article for keeptxred.com.

HARD RULES:
- Extract only facts (who/what/when/where/why). Never copy sentences or phrasing from the source. No direct quote longer than 10 words.
- Neutral, factual tone in Summary, Relevance, and Key Takeaways. Analysis is clearly labeled opinion and is optional.
- Mobile-friendly paragraphs (2–4 sentences each).
- Meta description (dek) MUST be <= 155 characters.
- Title must be SEO-optimized, original, and not resemble the source headline.
- 5–10 lowercase keywords, Texas-specific where possible.
- MINIMUM LENGTH: every non-evergreen article MUST be at least ${NON_EVERGREEN_MIN_MAIN_WORDS} words of original MAIN STORY PROSE across summary + analysis + sections only. Do NOT count Texas relevance, source attribution, FAQ, key takeaways, title, dek, or source lists toward this minimum. There is no upper word limit. Do not summarize briefly; expand with source-grounded context, background, stakeholders, local impact, timeline, what changes next, and reader context until the main story prose meets the minimum.
- TEXAS RELEVANCE IS REQUIRED — the "relevance" field must always name Texas or a specific Texas city/region and explain the local stake, even if the source is national.
- Add a short original CONTEXT paragraph (history, prior action, comparable state precedent) inside the "summary" or as the first sentences of "relevance".
- Include 5–8 additional article sections in "sections". Each section must have a clear heading and 2–4 substantial paragraphs. Do not use filler, generic slogans, or repeated paragraphs.
- FAQ answers should be substantial enough to help readers, not one-line answers.
- Output VALID JSON only matching the schema below.

CATEGORY: Choose the best fit from: Politics, Elections, Laws, Legislature, Business, Sports, Education, Non-Political. Use "Non-Political" for human-interest, animals, viral, culture, festivals, weather, travel, lifestyle, entertainment, science, and parks/wildlife stories. Do NOT use Education as a fallback — only true school/academic policy.

SCHEMA:
{"title":"...","dek":"<=155 chars","keywords":["..."],"summary":"substantial opening section","relevance":"substantial Texas relevance section","analysis":"optional labeled editorial interpretation, or omit","sections":[{"heading":"...","paragraphs":["..."]}],"keyTakeaways":["3-5 short bullets"],"faq":[{"q":"...","a":"..."}],"category":"one of the allowed values"}`;

async function rewriteItem(it: Item, lovableApiKey: string): Promise<Rewrite | null> {
  try {
    const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": lovableApiKey },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: REWRITE_SYSTEM },
          {
            role: "user",
            content: `SOURCE: ${it.source}\nORIGINAL HEADLINE: ${it.title}\nORIGINAL SUMMARY: ${it.description}\nLINK: ${it.link}\nDATE: ${it.pub_date}\n\nRewrite per the rules. Return JSON only.`,
          },
        ],
        response_format: { type: "json_object" },
        max_tokens: 9000,
      }),
        signal: AbortSignal.timeout(90000),
    });
    if (!r.ok) return null;
    const data = (await r.json()) as { choices?: { message?: { content?: string } }[] };
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}") as Rewrite;
    if (!parsed?.title || !parsed?.summary || !parsed?.dek) return null;
    if (!parsed?.relevance || parsed.relevance.trim().length < 40) return null;
    parsed.dek = parsed.dek.slice(0, 155);
    parsed.keywords = (parsed.keywords ?? []).slice(0, 10).map((k) => String(k).toLowerCase());
    parsed.keyTakeaways = (parsed.keyTakeaways ?? []).slice(0, 5);
    parsed.sections = (parsed.sections ?? [])
      .filter((s) => s?.heading && Array.isArray(s.paragraphs) && s.paragraphs.length > 0)
      .slice(0, 10);
    return parsed;
  } catch {
    return null;
  }
}

function rewriteMainProseWordCount(rw: Rewrite): number {
  const prose = [
    rw.summary,
    rw.analysis ?? "",
    ...(rw.sections ?? []).flatMap((s) => s.paragraphs ?? []),
  ].join(" ");
  return wordCount(prose);
}

// Ask the model to expand an existing draft up to the required length. Feeds
// like TPWD press releases are 100–200 words, so a single-shot rewrite rarely
// clears the 2,000-word non-evergreen floor. This pass grows the draft
// section-by-section using the same source facts.
async function expandRewrite(it: Item, prior: Rewrite, lovableApiKey: string): Promise<Rewrite | null> {
  const currentWords = rewriteMainProseWordCount(prior);
  const need = NON_EVERGREEN_MIN_MAIN_WORDS - currentWords;
  if (need <= 0) return prior;
  try {
    const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": lovableApiKey },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: REWRITE_SYSTEM },
          {
            role: "user",
            content: `SOURCE: ${it.source}\nORIGINAL HEADLINE: ${it.title}\nORIGINAL SUMMARY: ${it.description}\nLINK: ${it.link}\nDATE: ${it.pub_date}\n\nDRAFT (JSON) — expand this into a longer, source-grounded article. Keep every existing fact, do not fabricate quotes or figures, and add ${need + 400}+ words of additional MAIN STORY PROSE (summary + analysis + sections). Add 3–6 new sections covering Texas background, prior actions, stakeholders, timeline, what changes next, and reader impact. Preserve the schema.\n\n${JSON.stringify(prior)}`,
          },
        ],
        response_format: { type: "json_object" },
        max_tokens: 12000,
      }),
      signal: AbortSignal.timeout(120000),
    });
    if (!r.ok) return null;
    const data = (await r.json()) as { choices?: { message?: { content?: string } }[] };
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}") as Rewrite;
    if (!parsed?.title || !parsed?.summary || !parsed?.dek || !parsed?.relevance) return null;
    parsed.dek = parsed.dek.slice(0, 155);
    parsed.keywords = (parsed.keywords ?? prior.keywords ?? []).slice(0, 10).map((k) => String(k).toLowerCase());
    parsed.keyTakeaways = (parsed.keyTakeaways ?? prior.keyTakeaways ?? []).slice(0, 5);
    parsed.sections = (parsed.sections ?? [])
      .filter((s) => s?.heading && Array.isArray(s.paragraphs) && s.paragraphs.length > 0)
      .slice(0, 12);
    return parsed;
  } catch {
    return null;
  }
}

// Rewrite pipeline: first pass drafts, then up to two expansion passes grow
// the article until it clears the non-evergreen minimum word count.
// Transient AI-gateway failures also get one retry on the initial draft.
async function rewriteItemWithRetry(it: Item, lovableApiKey: string): Promise<Rewrite | null> {
  let draft = await rewriteItem(it, lovableApiKey);
  if (!draft) {
    await new Promise((res) => setTimeout(res, 600));
    draft = await rewriteItem(it, lovableApiKey);
  }
  if (!draft) {
    console.warn("[ingest-feeds] rewrite failed after retry", { source: it.source, link: it.link });
    return null;
  }
  const target = minWordsForItem(it, draft);
  // Only expand when the first pass is short AND we can add real Texas
  // value. Expansion is skipped once the draft clears the tiered minimum,
  // avoiding filler paragraphs written solely to hit a word count.
  for (let pass = 0; pass < 2; pass++) {
    if (rewriteMainProseWordCount(draft) >= target) return draft;
    const expanded = await expandRewrite(it, draft, lovableApiKey);
    if (!expanded) break;
    draft = expanded;
  }
  const finalWords = rewriteMainProseWordCount(draft);
  if (finalWords < target) {
    console.warn("[ingest-feeds] rewrite below tiered minimum, keeping best draft", {
      source: it.source,
      link: it.link,
      words: finalWords,
      target,
    });
  }
  // Return the best draft we produced rather than dropping the item; a
  // downstream row-level check enforces a hard floor so we never publish a
  // near-empty article, but we no longer silently discard usable coverage.
  return draft;
}

function buildArticleRow(it: Item, rw: Rewrite | null) {
  const datePrefix = it.pub_date.slice(0, 10);
  const baseTitle = rw?.title ?? it.title;
  const slug = `live-${datePrefix}-${slugify(baseTitle)}-${hashStr(it.link)}`;
  const aiCat =
    rw?.category && (ALLOWED_CATEGORIES as readonly string[]).includes(rw.category) ? rw.category : null;
  const cat = aiCat ?? it.category ?? categoryFor(it.source);
  const sections: { heading: string; paragraphs: string[] }[] = [
    {
      heading: "Texas relevance",
      paragraphs: [rw?.relevance ?? `This update from the ${it.source} affects Texans and is being tracked by the Keep TX Red newsroom.`],
    },
  ];
  for (const section of rw?.sections ?? []) {
    if (section.heading && Array.isArray(section.paragraphs) && section.paragraphs.length > 0) {
      sections.push({ heading: section.heading, paragraphs: section.paragraphs });
    }
  }
  if (rw?.analysis) {
    sections.push({ heading: "Analysis", paragraphs: [rw.analysis] });
  }
  sections.push({
    heading: "Source attribution",
    paragraphs: [
      `This story was reported using a public release from the ${it.source}. Keep TX Red rewrote the coverage independently and links to the official statement for verification.`,
    ],
  });

  const bodyJson = dedupeArticleBody({
    updated: it.pub_date.slice(0, 10),
    intro: [rw?.summary ?? it.description ?? `${it.source} released a new update for Texans.`],
    sections,
    faq: rw?.faq ?? [],
    sources: [{ label: `${it.source} — official release`, url: it.link }],
    keyTakeaways:
      rw?.keyTakeaways && rw.keyTakeaways.length > 0
        ? rw.keyTakeaways
        : [
            `Source: ${it.source}.`,
            "Keep TX Red rewrites every ingested story into original editorial coverage.",
          ],
  });

  return {
    slug,
    internal_url: `/news/${slug}`,
    is_ingested: true,
    category: cat,
    title: baseTitle.slice(0, 200),
    dek: (rw?.dek ?? (it.description || it.title)).slice(0, 155),
    body: articleBodyText(bodyJson),
    author: "Keep TX Red Newsroom",
    source_name: it.source,
    source_url: it.link,
    published_at: it.pub_date,
    kind: "ingested",
    is_breaking: false,
    score: 0,
    keywords: rw?.keywords ?? [],
    body_json: bodyJson,
  };
}

function parseFeed(xml: string, source: string): Item[] {
  const items: Item[] = [];
  const blocks = xml.match(/<(item|entry)[\s\S]*?<\/(item|entry)>/gi) || [];
  for (const b of blocks) {
    const title = pick(b, "title");
    let link = pick(b, "link");
    if (!link) {
      const m = b.match(/<link[^>]*href=["']([^"']+)["']/i);
      if (m) link = m[1];
    }
    const rawDate = pick(b, "pubDate") || pick(b, "updated") || pick(b, "published") || "";
    const description = pick(b, "description") || pick(b, "summary") || pick(b, "content");
    const ts = Date.parse(rawDate);
    if (title && link) {
      // Skip junk titles like "PDF format" / "HTML format" that some feeds
      // (e.g. Texas Register) emit as separate items pointing to the same
      // issue in a different file format. They aren't headlines.
      const t = title.trim().toLowerCase();
      if (/^(pdf|html|rss|xml|word|doc|docx|txt|text|epub)\s*(format|version)?$/.test(t)) {
        continue;
      }
      // Skip daily puzzle / crossword / word-game filler that some lifestyle
      // feeds (Texas Monthly, etc.) publish every day. They aren't news.
      if (isPuzzleTitle(title)) continue;
      items.push({
        title: title.slice(0, 500),
        link,
        pub_date: new Date(isNaN(ts) ? Date.now() : ts).toISOString(),
        source,
        description: description.slice(0, 1000),
      });
    }
  }
  return items;
}

export const Route = createFileRoute("/api/public/hooks/ingest-feeds")({
  server: {
    handlers: {
      POST: handler,
      GET: handler,
    },
  },
});

async function handler() {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

  const { sources: SOURCES, enabledDbCount } = await loadSources(
    supabaseAdmin as unknown as Parameters<typeof loadSources>[0],
  );
  console.log(
    `[ingest-feeds] sources: ${SOURCES.length} total (hardcoded=${HARDCODED_SOURCES.length}, db_enabled_with_rss=${enabledDbCount})`,
  );

  const results = await Promise.all(
    SOURCES.map(async (s) => {
      try {
        const res = await fetch(s.url, {
          headers: {
            "User-Agent": "KeepTXRedBot/1.0 (+https://www.keeptxred.com)",
            Accept: "application/rss+xml, application/atom+xml, application/xml, text/xml, */*",
          },
          signal: AbortSignal.timeout(15000),
        });
        if (!res.ok) return { source: s.name, url: s.url, status: res.status, items: [] as Item[] };
        const items = parseFeed(await res.text(), s.name)
          .slice(0, 25)
          .map((it) => ({ ...it, category: s.category }));
        return { source: s.name, url: s.url, status: res.status, items };
      } catch (e) {
        return { source: s.name, url: s.url, status: 0, error: String(e), items: [] as Item[] };
      }
    }),
  );

  const all = results.flatMap((r) => r.items);
  const diag = results.map(({ items, ...rest }) => ({ ...rest, count: items.length }));
  const okSources = results.filter((r) => (r as { status?: number }).status && (r as { status: number }).status >= 200 && (r as { status: number }).status < 300).length;
  console.log(`[ingest-feeds] fetched ${all.length} items from ${okSources}/${SOURCES.length} sources`);
  if (all.length === 0) {
    return new Response(JSON.stringify({ ok: true, inserted: 0, fetched: 0, diag }), {
      headers: { "Content-Type": "application/json" },
    });
  }

  // Dedupe by link against existing rows
  const links = Array.from(new Set(all.map((i) => i.link)));
  const { data: existing } = await supabaseAdmin
    .from("texas_news_feed")
    .select("link")
    .in("link", links);
  const have = new Set((existing ?? []).map((r: { link: string }) => r.link));
  const fresh = all.filter((i) => !have.has(i.link));

  let inserted = 0;
  if (fresh.length > 0) {
    // texas_news_feed has no `category` column — strip it before insert.
    const feedRows = fresh.map(({ category: _c, ...rest }) => rest);
    const { error, count } = await supabaseAdmin
      .from("texas_news_feed")
      .upsert(feedRows, { onConflict: "link", ignoreDuplicates: true, count: "exact" });
    if (error) {
      return new Response(JSON.stringify({ ok: false, error: error.message }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
    inserted = count ?? fresh.length;
  }
  console.log(`[ingest-feeds] imported ${inserted} new items into texas_news_feed (fresh=${fresh.length})`);

  // Mint a native Keep TX Red article for every freshly ingested feed item so
  // Happening Now only ever links to internal /news/{slug} URLs.
  let nativeMinted = 0;
  if (fresh.length > 0) {
    const lovableApiKey = process.env.LOVABLE_API_KEY;
    const rewrites: (Rewrite | null)[] = lovableApiKey
      ? await Promise.all(fresh.map((it) => rewriteItemWithRetry(it, lovableApiKey)))
      : fresh.map(() => null);
    // Skip items whose AI rewrite failed — never publish empty stub articles.
    const paired = fresh
      .map((it, i) => ({ it, rw: rewrites[i] }))
      .filter((p): p is { it: Item; rw: Rewrite } => p.rw !== null);
    const pairedRows = paired
      .map(({ it, rw }) => ({ it, rw, row: buildArticleRow(it, rw) }))
      .filter(({ it, rw, row }) => {
        const target = minWordsForItem(it, rw);
        const words = articleMainWordCount(row.body_json);
        if (words < target) {
          console.warn("[ingest-feeds] dropping article below tiered floor", {
            slug: row.slug,
            source: it.source,
            words,
            target,
          });
          return false;
        }
        return true;
      });
    const articleRows = pairedRows.map(({ row }) => row);
    const articleSourceBySlug = new Map(pairedRows.map(({ it, row }) => [row.slug, it]));
    if (articleRows.length === 0) {
      return new Response(
        JSON.stringify({ ok: true, inserted, nativeMinted: 0, skipped: fresh.length }),
        { headers: { "Content-Type": "application/json" } },
      );
    }

    // ONE AI call classifies the whole batch into image buckets (cached in DB).
    const imageMap = lovableApiKey
      ? await classifyImageBuckets(
          articleRows.map((r) => ({ slug: r.slug, title: r.title, dek: r.dek })),
          lovableApiKey,
        )
      : {};
    // ONE AI call rewrites the batch's headlines for SEO/Discover (cached in DB).
    const seoMap = lovableApiKey
      ? await rewriteHeadlinesBatch(
          articleRows.map((r) => ({ slug: r.slug, title: r.title })),
          lovableApiKey,
        )
      : {};
    for (const row of articleRows) {
      const seo = seoMap[row.slug] ?? null;
      const headline = seo ?? row.title;
      const discover = detectDiscoverCategory(`${headline} ${row.dek}`);
      (row as { image_category?: string | null }).image_category = imageMap[row.slug] ?? null;
      (row as { seo_headline?: string | null }).seo_headline = seo;
      (row as { discover_category?: string | null }).discover_category =
        discover === "other" ? null : discover;
      (row as { seo_keywords?: string[] | null }).seo_keywords = row.keywords ?? null;
    }

    // ONE AI call generates A/B headline variants for the whole batch.
    const variantMap = lovableApiKey
      ? await generateHeadlineVariantsBatch(
          articleRows.map((r) => ({
            slug: r.slug,
            title: (r as { seo_headline?: string | null }).seo_headline ?? r.title,
          })),
          lovableApiKey,
        )
      : {};

    // Compute CTR score deterministically for every row (0 AI calls).
    for (const row of articleRows) {
      const anyRow = row as Record<string, unknown>;
      const variants =
        variantMap[row.slug] ??
        ({
          a: (anyRow.seo_headline as string | null) ?? row.title,
          b: row.title,
        } as HeadlineVariants);
      anyRow.headline_variants = variants;

      const resolvedImageUrl = getArticleImage({
        slug: row.slug,
        image_url: (anyRow.image_url as string | null | undefined) ?? null,
        image_category: (anyRow.image_category as string | null) ?? null,
        category: row.category,
        title: variants.a,
        dek: row.dek,
        keywords: row.keywords ?? null,
      });
      anyRow.ctr_score = scoreDiscoverMatch({
        slug: row.slug,
        title: row.title,
        dek: row.dek,
        seo_headline: (anyRow.seo_headline as string | null) ?? null,
        discover_category: (anyRow.discover_category as string | null) ?? null,
        image_category: (anyRow.image_category as string | null) ?? null,
        image_url: (anyRow.image_url as string | null | undefined) ?? null,
        category: row.category,
        keywords: row.keywords ?? null,
        seo_keywords: (anyRow.seo_keywords as string[] | null) ?? null,
        resolvedImageUrl,
      });
    }

    articleRows.forEach((r) => enrichArticleRow(r));

    // Deduplicate: (1) collapse near-duplicate titles within this batch,
    // (2) drop anything whose title matches an article published in the
    // last 7 days. Same story, different wording must never appear twice.
    const withinBatch = dedupeByTitle(articleRows as Array<{ title: string; slug: string }>);
    const sinceIso = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
    const { data: recent } = await supabaseAdmin
      .from("daily_articles")
      .select("title")
      .gte("published_at", sinceIso);
    const recentTitles = (recent ?? []).map((r: { title: string }) => r.title);
    const dedupedSlugs = new Set(
      withinBatch
        .filter((r) => !recentTitles.some((t) => isDuplicateTitle(t, r.title)))
        .map((r) => r.slug),
    );
    const uniqueArticleRows = articleRows.filter((r) => dedupedSlugs.has(r.slug));
    if (uniqueArticleRows.length === 0) {
      return new Response(
        JSON.stringify({ ok: true, inserted, nativeMinted: 0, skipped: fresh.length, dedupedAll: true }),
        { headers: { "Content-Type": "application/json" } },
      );
    }

    const { error: artErr, count: artCount } = await supabaseAdmin
      .from("daily_articles")
      .upsert(uniqueArticleRows, { onConflict: "slug", ignoreDuplicates: true, count: "exact" });
    if (!artErr) {
      nativeMinted = artCount ?? uniqueArticleRows.length;
      await Promise.allSettled(
        uniqueArticleRows.map((row: { slug: string }) => generateFeaturedImageForSlugDirect(row.slug, true)),
      );
      // Write the internal slug back onto the feed row so cards can link to it.
      await Promise.all(
        uniqueArticleRows.map((row: { slug: string }) => {
          const src = articleSourceBySlug.get(row.slug);
          if (!src) return Promise.resolve();
          return supabaseAdmin
            .from("texas_news_feed")
            .update({ internal_slug: row.slug })
            .eq("link", src.link);
        }),
      );
    }
  }

  // Backfill internal_slug for any older feed rows that don't have one yet.
  const { data: orphans } = await supabaseAdmin
    .from("texas_news_feed")
    .select("id,title,link,source,description,pub_date")
    .is("internal_slug", null)
    .limit(25);
  if (orphans && orphans.length > 0) {
    const lovableApiKey = process.env.LOVABLE_API_KEY;
    const items: Item[] = orphans.map((row) => ({
      title: row.title,
      link: row.link,
      source: row.source,
      pub_date: row.pub_date,
      description: row.description ?? "",
    }));
    const rewrites: (Rewrite | null)[] = lovableApiKey
      ? await Promise.all(items.map((it) => rewriteItemWithRetry(it, lovableApiKey)))
      : items.map(() => null);
    // Only mint articles for orphans whose rewrite succeeded.
    const paired = items
      .map((it, i) => ({ it, rw: rewrites[i] }))
      .filter((p): p is { it: Item; rw: Rewrite } => p.rw !== null);
    const backPaired = paired
      .map(({ it, rw }) => ({ it, rw, row: buildArticleRow(it, rw) }))
      .filter(({ it, rw, row }) => {
        const target = minWordsForItem(it, rw);
        const words = articleMainWordCount(row.body_json);
        if (words < target) {
          console.warn("[ingest-feeds] backfill dropped article below tiered floor", {
            slug: row.slug,
            source: it.source,
            words,
            target,
          });
          return false;
        }
        return true;
      });
    const backRows = backPaired.map(({ row }) => row);
    backRows.forEach((r) => enrichArticleRow(r));
    if (backRows.length > 0) {
      await supabaseAdmin
        .from("daily_articles")
        .upsert(backRows, { onConflict: "slug", ignoreDuplicates: true });
      await Promise.allSettled(
        backRows.map((row: { slug: string }) => generateFeaturedImageForSlugDirect(row.slug, true)),
      );
      await Promise.all(
        backPaired.map(({ it, row }) =>
          supabaseAdmin.from("texas_news_feed").update({ internal_slug: row.slug }).eq("link", it.link),
        ),
      );
    }
  }

  // Canonical-URL dedupe: for any daily_articles rows sharing the same
  // source_url, keep the most-recently-updated slug and drop the rest.
  let dedupedCanonical = 0;
  let dedupeSkippedReason: string | null = null;
  try {
    // Total daily_articles row count — used both to skip cleanup on empty-run
    // scenarios and to enforce a % safety cap on how much a single ingest may
    // delete. A prior version of this block wiped the whole table when the
    // rewrite batch produced no rows AND canonical dedupe ran unchecked.
    const { count: totalArticles } = await supabaseAdmin
      .from("daily_articles")
      .select("id", { count: "exact", head: true });
    const totalCount = totalArticles ?? 0;

    // Safety rule 3: if the table already has articles but THIS ingest run
    // produced zero successful rewrites (native mint + backfill both silent),
    // do not run destructive cleanup — an empty rewrite batch is not evidence
    // that historical rows are duplicates.
    if (totalCount > 0 && nativeMinted === 0) {
      dedupeSkippedReason = "no successful rewrites in this run";
    } else {
      const { data: dupes } = await supabaseAdmin
        .from("daily_articles")
        .select("id, slug, source_url, published_at")
        .not("source_url", "is", null)
        .order("published_at", { ascending: false, nullsFirst: false })
        .limit(1000);
      if (dupes && dupes.length > 0) {
        // Group by canonical source_url; keep the newest (list is already
        // sorted desc by published_at), mark strictly older siblings for
        // deletion. Rows without a source_url were excluded above.
        const seen = new Set<string>();
        const toDelete: string[] = [];
        for (const row of dupes as { id: string; slug: string; source_url: string | null }[]) {
          const key = row.source_url;
          if (!key) continue;
          if (seen.has(key)) toDelete.push(row.id);
          else seen.add(key);
        }
        if (toDelete.length > 0) {
          // Safety rule 2: never delete more than 10% of daily_articles in a
          // single cleanup pass. If the candidate set exceeds that cap, abort
          // so a bad dedupe signature can't wipe the archive.
          const cap = Math.max(1, Math.floor(totalCount * 0.1));
          if (toDelete.length > cap) {
            dedupeSkippedReason = `refused to delete ${toDelete.length} rows (>10% of ${totalCount})`;
            console.warn("[ingest-feeds] canonical dedupe aborted", {
              candidates: toDelete.length,
              total: totalCount,
              cap,
            });
          } else {
            await supabaseAdmin.from("daily_articles").delete().in("id", toDelete);
            dedupedCanonical = toDelete.length;
          }
        }
      }
    }
  } catch (e) {
    console.error("canonical dedupe failed", e);
  }

  return new Response(
    JSON.stringify({ ok: true, fetched: all.length, candidates: fresh.length, inserted, nativeMinted, dedupedCanonical, dedupeSkippedReason, diag }),
    { headers: { "Content-Type": "application/json" } },
  );
}

/**
 * Single-item publish path used by the Admin "Publish to Keep Texas Red"
 * button. Reuses the same rewrite → build → enrich → image pipeline as the
 * batch ingestion so category, article type, SEO and image logic remain the
 * single source of truth. Safe to call multiple times: if the feed row is
 * already linked to a daily_articles slug, returns that slug unchanged.
 */
export async function publishSingleFeedItem(
  feedItemId: number,
): Promise<{ ok: boolean; slug?: string; error?: string; alreadyPublished?: boolean }> {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { data: row, error: rowErr } = await supabaseAdmin
    .from("texas_news_feed")
    .select("id,title,link,source,description,pub_date,internal_slug")
    .eq("id", feedItemId)
    .maybeSingle();
  if (rowErr || !row) {
    return { ok: false, error: rowErr?.message ?? "Feed item not found" };
  }
  if (row.internal_slug) {
    return { ok: true, slug: row.internal_slug, alreadyPublished: true };
  }
  if (isPuzzleTitle(row.title)) {
    return { ok: false, error: "Puzzle / filler titles are blocked from publish." };
  }
  const lovableApiKey = process.env.LOVABLE_API_KEY;
  if (!lovableApiKey) return { ok: false, error: "Missing LOVABLE_API_KEY" };

  const item: Item = {
    title: row.title,
    link: row.link,
    source: row.source,
    pub_date: row.pub_date,
    description: row.description ?? "",
  };
  const rw = await rewriteItemWithRetry(item, lovableApiKey);
  if (!rw) return { ok: false, error: "AI rewrite failed" };

  const articleRow = buildArticleRow(item, rw);
  const target = minWordsForItem(item, rw);
  const words = articleMainWordCount(articleRow.body_json);
  if (words < target) {
    return { ok: false, error: `Rewrite below tiered minimum (${words}/${target} words). Try again.` };
  }
  enrichArticleRow(articleRow);

  const { error: upsertErr } = await supabaseAdmin
    .from("daily_articles")
    .upsert([articleRow], { onConflict: "slug", ignoreDuplicates: true });
  if (upsertErr) return { ok: false, error: upsertErr.message };

  await supabaseAdmin
    .from("texas_news_feed")
    .update({ internal_slug: articleRow.slug })
    .eq("id", feedItemId);

  // Fire-and-forget image generation; UI already renders without it.
  void generateFeaturedImageForSlugDirect(articleRow.slug, true).catch(() => undefined);

  return { ok: true, slug: articleRow.slug };
}