from pathlib import Path

path = Path('src/routes/api/public/hooks/generate-news.ts')
text = path.read_text()

old = '''function normalizeOverlongSummary(summary?: string): string | undefined {\n  if (typeof summary !== "string") return summary;\n  const trimmed = summary.trim();\n  const words = trimmed.split(/\\s+/).filter(Boolean);\n  if (words.length <= 90) return trimmed;\n\n  const sentences = trimmed.match(/[^.!?]+(?:[.!?]+|$)/g) ?? [];\n  const kept: string[] = [];\n  let keptWords = 0;\n  for (const sentence of sentences) {\n    const sentenceText = sentence.trim();\n    if (!sentenceText) continue;\n    const sentenceWords = sentenceText.split(/\\s+/).filter(Boolean).length;\n    if (keptWords + sentenceWords > 90) break;\n    kept.push(sentenceText);\n    keptWords += sentenceWords;\n  }\n\n  if (keptWords >= 45) return kept.join(" ");\n  return words.slice(0, 90).join(" ");\n}\n'''
new = '''function normalizeSummaryLength(summary?: string, sections?: NewsSection[]): string | undefined {\n  if (typeof summary !== "string") return summary;\n  const trimmed = summary.trim();\n  const words = trimmed.split(/\\s+/).filter(Boolean);\n\n  if (words.length > 90) {\n    const sentences = trimmed.match(/[^.!?]+(?:[.!?]+|$)/g) ?? [];\n    const kept: string[] = [];\n    let keptWords = 0;\n    for (const sentence of sentences) {\n      const sentenceText = sentence.trim();\n      if (!sentenceText) continue;\n      const sentenceWords = sentenceText.split(/\\s+/).filter(Boolean).length;\n      if (keptWords + sentenceWords > 90) break;\n      kept.push(sentenceText);\n      keptWords += sentenceWords;\n    }\n    if (keptWords >= 45) return kept.join(" ");\n    return words.slice(0, 90).join(" ");\n  }\n\n  if (words.length >= 45) return trimmed;\n\n  const firstBodyParagraph = (sections ?? [])\n    .flatMap((section) => section?.paragraphs ?? [])\n    .map((paragraph) => paragraph?.trim() ?? "")\n    .find(Boolean);\n\n  if (!firstBodyParagraph) return trimmed;\n\n  const supplementSentences = firstBodyParagraph.match(/[^.!?]+(?:[.!?]+|$)/g) ?? [firstBodyParagraph];\n  const combined: string[] = [trimmed];\n  let combinedWords = words.length;\n  for (const sentence of supplementSentences) {\n    const sentenceText = sentence.trim();\n    if (!sentenceText || trimmed.includes(sentenceText)) continue;\n    const sentenceWords = sentenceText.split(/\\s+/).filter(Boolean).length;\n    if (combinedWords + sentenceWords > 90) {\n      const remaining = Math.max(0, 90 - combinedWords);\n      if (remaining > 0) combined.push(sentenceText.split(/\\s+/).slice(0, remaining).join(" "));\n      break;\n    }\n    combined.push(sentenceText);\n    combinedWords += sentenceWords;\n    if (combinedWords >= 45) break;\n  }\n\n  return combined.join(" ").trim();\n}\n'''
if old not in text:
    raise SystemExit('normalizer block not found')
text = text.replace(old, new, 1)
text = text.replace('a.summary = normalizeOverlongSummary(a.summary);', 'a.summary = normalizeSummaryLength(a.summary, a.sections);', 1)
path.write_text(text)
