from pathlib import Path

path = Path('src/routes/api/public/hooks/generate-news.ts')
text = path.read_text()

anchor1 = 'type ScoredItem = RssItem & { score: number; isBreaking: boolean };\n'
insert1 = '''type ScoredItem = RssItem & { score: number; isBreaking: boolean };\n\nconst MIN_VERIFIED_SOURCE_WORDS = 600;\n\ntype SourcePreflightDiagnostic = {\n  title: string;\n  source: string;\n  sourceWords: number;\n};\n\ntype SourcePreflightSummary = {\n  threshold: number;\n  selected_count: number;\n  skipped_count: number;\n  stories: SourcePreflightDiagnostic[];\n};\n\nclass InsufficientVerifiedSourceError extends Error {\n  diagnostics: SourcePreflightSummary;\n\n  constructor(diagnostics: SourcePreflightSummary) {\n    super('All selected stories failed verified-source sufficiency preflight');\n    this.name = 'InsufficientVerifiedSourceError';\n    this.diagnostics = diagnostics;\n  }\n}\n\nfunction sourceWordCount(value: string | undefined): number {\n  return (value ?? '').trim().split(/\\s+/).filter(Boolean).length;\n}\n'''
if 'const MIN_VERIFIED_SOURCE_WORDS = 600;' not in text:
    if anchor1 not in text:
        raise SystemExit('anchor1 not found')
    text = text.replace(anchor1, insert1, 1)

old_rewrite = '''async function rewriteWithAi(items: ScoredItem[], lovableApiKey: string) {\n  const selected = await Promise.all(items.slice(0, 10).map(hydrateSourceContext));\n  const combined: RewrittenArticle[] = [];\n  const failures: string[] = [];\n\n  // Long-form stories get their own structured-output request and full output-token budget.\n  for (let index = 0; index < selected.length; index += 1) {\n    const story = selected[index];\n    try {\n      const rewritten = await rewriteBatchWithAi([story], lovableApiKey);\n      const article = rewritten.find((candidate) => candidate.source_index === 1);\n      if (article) {\n        combined.push({ ...article, source_index: index + 1 });\n      } else {\n        const message = `story ${index + 1} produced no editorially valid article`;\n        failures.push(message);\n        console.warn("[generate-news] individual story produced no editorially valid article", {\n          sourceIndex: index + 1,\n          title: story.title,\n        });\n      }\n    } catch (storyError) {\n      if (isQuotaOrRateLimitError(storyError)) throw storyError;\n      failures.push(String(storyError));\n      console.warn("[generate-news] individual story rewrite skipped after one attempt", {\n        sourceIndex: index + 1,\n        title: story.title,\n        error: String(storyError),\n      });\n    }\n\n    if (index < selected.length - 1) {\n      await new Promise((resolve) => setTimeout(resolve, 1000));\n    }\n  }\n\n  if (combined.length === 0 && failures.length > 0) {\n    throw new Error(`All selected rewrites failed: ${failures.slice(0, 3).join(" | ")}`);\n  }\n\n  return combined.slice(0, 10);\n}\n'''
new_rewrite = '''async function rewriteWithAi(items: ScoredItem[], lovableApiKey: string) {\n  const selected = await Promise.all(\n    items.slice(0, 10).map(async (item, originalIndex) => ({\n      story: await hydrateSourceContext(item),\n      originalIndex,\n    })),\n  );\n\n  const diagnostics: SourcePreflightSummary = {\n    threshold: MIN_VERIFIED_SOURCE_WORDS,\n    selected_count: selected.length,\n    skipped_count: 0,\n    stories: selected.map(({ story }) => ({\n      title: story.title,\n      source: story.source,\n      sourceWords: sourceWordCount(story.sourceText || story.description),\n    })),\n  };\n\n  const eligible = selected.filter(({ story }, index) => {\n    const sourceWords = diagnostics.stories[index].sourceWords;\n    const passes = sourceWords >= MIN_VERIFIED_SOURCE_WORDS;\n    if (!passes) {\n      diagnostics.skipped_count += 1;\n      console.warn("[generate-news] skipped thin verified source before AI rewrite", {\n        title: story.title,\n        source: story.source,\n        sourceWords,\n        threshold: MIN_VERIFIED_SOURCE_WORDS,\n      });\n    }\n    return passes;\n  });\n\n  if (eligible.length === 0) {\n    throw new InsufficientVerifiedSourceError(diagnostics);\n  }\n\n  const combined: RewrittenArticle[] = [];\n  const failures: string[] = [];\n\n  // Long-form stories get their own structured-output request and full output-token budget.\n  // Thin verified sources have already been removed, so no AI quota is spent on them.\n  for (let index = 0; index < eligible.length; index += 1) {\n    const { story, originalIndex } = eligible[index];\n    try {\n      const rewritten = await rewriteBatchWithAi([story], lovableApiKey);\n      const article = rewritten.find((candidate) => candidate.source_index === 1);\n      if (article) {\n        combined.push({ ...article, source_index: originalIndex + 1 });\n      } else {\n        const message = `story ${originalIndex + 1} produced no editorially valid article`;\n        failures.push(message);\n        console.warn("[generate-news] individual story produced no editorially valid article", {\n          sourceIndex: originalIndex + 1,\n          title: story.title,\n        });\n      }\n    } catch (storyError) {\n      if (isQuotaOrRateLimitError(storyError)) throw storyError;\n      failures.push(String(storyError));\n      console.warn("[generate-news] individual story rewrite skipped after one attempt", {\n        sourceIndex: originalIndex + 1,\n        title: story.title,\n        error: String(storyError),\n      });\n    }\n\n    if (index < eligible.length - 1) {\n      await new Promise((resolve) => setTimeout(resolve, 1000));\n    }\n  }\n\n  if (combined.length === 0 && failures.length > 0) {\n    throw new Error(`All selected rewrites failed: ${failures.slice(0, 3).join(" | ")}`);\n  }\n\n  return combined.slice(0, 10);\n}\n'''
if 'skipped thin verified source before AI rewrite' not in text:
    if old_rewrite not in text:
        raise SystemExit('rewriteWithAi anchor not found')
    text = text.replace(old_rewrite, new_rewrite, 1)

old_catch = '''        let rewritten: RewrittenArticle[];\n        try {\n          rewritten = await rewriteWithAi(items, lovableApiKey);\n        } catch (err) {\n          console.error("AI rewrite failed", err);\n          return Response.json({ error: "AI rewrite failed", details: String(err) }, { status: 500 });\n        }\n'''
new_catch = '''        let rewritten: RewrittenArticle[];\n        try {\n          rewritten = await rewriteWithAi(items, lovableApiKey);\n        } catch (err) {\n          if (err instanceof InsufficientVerifiedSourceError) {\n            return Response.json(\n              {\n                ok: true,\n                no_items: true,\n                reason: "insufficient_verified_source",\n                inserted: 0,\n                diagnostics: err.diagnostics,\n              },\n              { status: 200 },\n            );\n          }\n          console.error("AI rewrite failed", err);\n          return Response.json({ error: "AI rewrite failed", details: String(err) }, { status: 500 });\n        }\n'''
if 'reason: "insufficient_verified_source"' not in text:
    if old_catch not in text:
        raise SystemExit('route catch anchor not found')
    text = text.replace(old_catch, new_catch, 1)

path.write_text(text)
