import type {LoanProgram,TexasDownPaymentResult} from "@/types/downPayment/TexasDownPayment";
export const formatDownPaymentCurrency=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
export function explainLoanProgram(program:LoanProgram){return program==="conventional"?"Conventional loans generally require between 3% and 20% down, with PMI often required below 20%.":program==="fha"?"FHA loans may allow 3.5% down but include mortgage insurance.":program==="va"?"Eligible VA borrowers may qualify for zero-down financing with no monthly PMI.":"Eligible USDA loans may offer zero-down financing in qualifying areas."}
export const explainPMI=(r:TexasDownPaymentResult)=>r.program.requiresPMI?"Private mortgage insurance may be required based on your selected down payment.":"PMI is generally not expected for this scenario.";
export const explainCashNeeded=(r:TexasDownPaymentResult)=>`Estimated cash needed at closing is ${formatDownPaymentCurrency(r.cash.totalCashNeeded)}.`;
export const explainSavingsTimeline=(r:TexasDownPaymentResult)=>r.timeline.monthsNeeded===0?"Your current savings appear sufficient.":`At your current savings rate, it may take approximately ${r.timeline.monthsNeeded} months to reach your goal.`;
export function calculateDownPaymentReadinessScore(r:TexasDownPaymentResult){let score=50;if(r.cash.cashShortfall===0)score+=35;if(!r.program.requiresPMI)score+=10;if(r.input.downPaymentPercent>=.2)score+=5;return Math.min(100,score)}
export const generateDownPaymentRecommendation=(r:TexasDownPaymentResult)=>calculateDownPaymentReadinessScore(r)>=90?"You appear financially prepared for a home purchase.":calculateDownPaymentReadinessScore(r)>=75?"Your savings are in a solid position.":calculateDownPaymentReadinessScore(r)>=60?"Continue building your down payment and emergency reserves.":"Focus on increasing savings before purchasing.";
export const generateDownPaymentSEODescription=(location="Texas")=>`Use this ${location} down payment calculator to estimate your down payment, closing costs, PMI impact, cash needed, and savings timeline.`;
