import type {TexasRentVsBuyResult} from "@/types/home/TexasRentVsBuy";
export const formatHousingCurrency=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
export const explainRentScenario=(r:TexasRentVsBuyResult)=>`Over the analysis period, renting costs approximately ${formatHousingCurrency(r.rentAnalysis.totalRentPaid)}.`;
export const explainBuyScenario=(r:TexasRentVsBuyResult)=>`Buying creates an estimated future home value of ${formatHousingCurrency(r.buyAnalysis.homeValueFuture)} and builds approximately ${formatHousingCurrency(r.buyAnalysis.equityBuilt)} in ownership value.`;
export const explainWealthDifference=(r:TexasRentVsBuyResult)=>r.comparison.wealthDifference>0?`Buying produces approximately ${formatHousingCurrency(r.comparison.wealthDifference)} more projected wealth.`:r.comparison.wealthDifference<0?`Renting produces approximately ${formatHousingCurrency(Math.abs(r.comparison.wealthDifference))} more projected value.`:"The projected financial difference is minimal.";
export const explainBreakEven=(r:TexasRentVsBuyResult)=>r.comparison.breakEvenYear?`The estimated ownership advantage begins around year ${r.comparison.breakEvenYear}.`:"The current assumptions do not show a clear ownership break-even point.";
export const generateHousingRecommendation=(r:TexasRentVsBuyResult)=>r.comparison.winner==="buy"?"Buying appears to create stronger long-term financial value.":r.comparison.winner==="rent"?"Renting appears financially competitive and may provide greater flexibility.":"Personal goals and lifestyle should influence the decision.";
export const explainHousingScore=(r:TexasRentVsBuyResult)=>r.decisionScore>=80?"Buying has a strong projected financial advantage.":r.decisionScore>=60?"Buying has a moderate projected advantage.":r.decisionScore<=40?"Renting may provide a stronger outcome.":"The two options are financially similar.";
export const generateRentVsBuySEODescription=(location="Texas")=>`Use this ${location} rent vs buy calculator to compare mortgage costs, rental expenses, home equity growth, and long-term financial outcomes.`;
