/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotingLocationsRouteImport } from './routes/voting-locations'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TexasUtilityCostCalculatorRouteImport } from './routes/texas-utility-cost-calculator'
import { Route as TexasSportsRouteImport } from './routes/texas-sports'
import { Route as TexasSalaryComparisonByCityRouteImport } from './routes/texas-salary-comparison-by-city'
import { Route as TexasSalaryCalculatorRouteImport } from './routes/texas-salary-calculator'
import { Route as TexasRentVsBuyCalculatorRouteImport } from './routes/texas-rent-vs-buy-calculator'
import { Route as TexasRefinanceSavingsCalculatorRouteImport } from './routes/texas-refinance-savings-calculator'
import { Route as TexasPropertyTaxIncreaseCalculatorRouteImport } from './routes/texas-property-tax-increase-calculator'
import { Route as TexasPoliticsRouteImport } from './routes/texas-politics'
import { Route as TexasNewsRouteImport } from './routes/texas-news'
import { Route as TexasMovingCostCalculatorRouteImport } from './routes/texas-moving-cost-calculator'
import { Route as TexasMortgagePayoffCalculatorRouteImport } from './routes/texas-mortgage-payoff-calculator'
import { Route as TexasMortgageCalculatorRouteImport } from './routes/texas-mortgage-calculator'
import { Route as TexasLawsRouteImport } from './routes/texas-laws'
import { Route as TexasLawPolicyRouteImport } from './routes/texas-law-policy'
import { Route as TexasHomeownershipCostCalculatorRouteImport } from './routes/texas-homeownership-cost-calculator'
import { Route as TexasHomeInsuranceCalculatorRouteImport } from './routes/texas-home-insurance-calculator'
import { Route as TexasHomeEquityGrowthCalculatorRouteImport } from './routes/texas-home-equity-growth-calculator'
import { Route as TexasHomeEquityCalculatorRouteImport } from './routes/texas-home-equity-calculator'
import { Route as TexasHomeAffordabilityCalculatorRouteImport } from './routes/texas-home-affordability-calculator'
import { Route as TexasFinancialToolsRouteImport } from './routes/texas-financial-tools'
import { Route as TexasEconomyRouteImport } from './routes/texas-economy'
import { Route as TexasDownPaymentCalculatorRouteImport } from './routes/texas-down-payment-calculator'
import { Route as TexasDownPaymentAssistanceCalculatorRouteImport } from './routes/texas-down-payment-assistance-calculator'
import { Route as TexasCostOfLivingCalculatorRouteImport } from './routes/texas-cost-of-living-calculator'
import { Route as TexasClosingCostCalculatorRouteImport } from './routes/texas-closing-cost-calculator'
import { Route as TexasBusinessRouteImport } from './routes/texas-business'
import { Route as TexasBudgetPlannerRouteImport } from './routes/texas-budget-planner'
import { Route as TexasRouteImport } from './routes/texas'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TaxCalculatorRouteImport } from './routes/tax-calculator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapProductsDotxmlRouteImport } from './routes/sitemap-products[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapNewsDotxmlRouteImport } from './routes/sitemap-news[.]xml'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as SitemapEvergreenDotxmlRouteImport } from './routes/sitemap-evergreen[.]xml'
import { Route as SitemapAuthorsDotxmlRouteImport } from './routes/sitemap-authors[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RepresentativesRouteImport } from './routes/representatives'
import { Route as RegisterToVoteRouteImport } from './routes/register-to-vote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MovingToTexasRouteImport } from './routes/moving-to-texas'
import { Route as LivingInTexasRouteImport } from './routes/living-in-texas'
import { Route as LegislativeUpdatesRouteImport } from './routes/legislative-updates'
import { Route as LawsToKnowRouteImport } from './routes/laws-to-know'
import { Route as LawsRouteImport } from './routes/laws'
import { Route as KeepTexasRedRouteImport } from './routes/keep-texas-red'
import { Route as HoustonRouteImport } from './routes/houston'
import { Route as HappeningNowRouteImport } from './routes/happening-now'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as FindRepresentativeRouteImport } from './routes/find-representative'
import { Route as FindMySchoolDistrictRouteImport } from './routes/find-my-school-district'
import { Route as FindMyDmvRouteImport } from './routes/find-my-dmv'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as EditorialStandardsRouteImport } from './routes/editorial-standards'
import { Route as CountyElectionsRouteImport } from './routes/county-elections'
import { Route as ContactLegislatorsRouteImport } from './routes/contact-legislators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidateGuidesRouteImport } from './routes/candidate-guides'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutKeepTexasRedRouteImport } from './routes/about-keep-texas-red'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TexasIndexRouteImport } from './routes/texas.index'
import { Route as TexasSportsIndexRouteImport } from './routes/texas-sports.index'
import { Route as TexasNewsIndexRouteImport } from './routes/texas-news.index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as TexasSlugRouteImport } from './routes/texas.$slug'
import { Route as TexasSportsLeagueRouteImport } from './routes/texas-sports.$league'
import { Route as TexasNewsTopicRouteImport } from './routes/texas-news.$topic'
import { Route as TexasBusinessTopicRouteImport } from './routes/texas-business.$topic'
import { Route as ShopCheckoutReturnRouteImport } from './routes/shop.checkout-return'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as NewsNonPoliticalRouteImport } from './routes/news.non-political'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as TexasSportsTeamTeamRouteImport } from './routes/texas-sports.team.$team'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicPropertyAddressLookupRouteImport } from './routes/api/public/property-address-lookup'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTrackVariantRouteImport } from './routes/api/public/hooks/track-variant'
import { Route as ApiPublicHooksSyncPrintifyRouteImport } from './routes/api/public/hooks/sync-printify'
import { Route as ApiPublicHooksScoreViralBackfillRouteImport } from './routes/api/public/hooks/score-viral-backfill'
import { Route as ApiPublicHooksScoreViralRouteImport } from './routes/api/public/hooks/score-viral'
import { Route as ApiPublicHooksListShopsRouteImport } from './routes/api/public/hooks/list-shops'
import { Route as ApiPublicHooksIngestFeedsRouteImport } from './routes/api/public/hooks/ingest-feeds'
import { Route as ApiPublicHooksHealthRouteImport } from './routes/api/public/hooks/health'
import { Route as ApiPublicHooksGenerateSportsRouteImport } from './routes/api/public/hooks/generate-sports'
import { Route as ApiPublicHooksGenerateNewsRouteImport } from './routes/api/public/hooks/generate-news'
import { Route as ApiPublicHooksGenerateEvergreenRouteImport } from './routes/api/public/hooks/generate-evergreen'
import { Route as ApiPublicHooksBackfillFeaturedImagesRouteImport } from './routes/api/public/hooks/backfill-featured-images'
import { Route as ApiPublicArticleImageFilenameRouteImport } from './routes/api/public/article-image.$filename'
import { Route as ApiPublicOauthFacebookStartRouteImport } from './routes/api/public/oauth/facebook/start'
import { Route as ApiPublicOauthFacebookCallbackRouteImport } from './routes/api/public/oauth/facebook/callback'

const VotingLocationsRoute = VotingLocationsRouteImport.update({
  id: '/voting-locations',
  path: '/voting-locations',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasUtilityCostCalculatorRoute =
  TexasUtilityCostCalculatorRouteImport.update({
    id: '/texas-utility-cost-calculator',
    path: '/texas-utility-cost-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasSportsRoute = TexasSportsRouteImport.update({
  id: '/texas-sports',
  path: '/texas-sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasSalaryComparisonByCityRoute =
  TexasSalaryComparisonByCityRouteImport.update({
    id: '/texas-salary-comparison-by-city',
    path: '/texas-salary-comparison-by-city',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasSalaryCalculatorRoute = TexasSalaryCalculatorRouteImport.update({
  id: '/texas-salary-calculator',
  path: '/texas-salary-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasRentVsBuyCalculatorRoute =
  TexasRentVsBuyCalculatorRouteImport.update({
    id: '/texas-rent-vs-buy-calculator',
    path: '/texas-rent-vs-buy-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasRefinanceSavingsCalculatorRoute =
  TexasRefinanceSavingsCalculatorRouteImport.update({
    id: '/texas-refinance-savings-calculator',
    path: '/texas-refinance-savings-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasPropertyTaxIncreaseCalculatorRoute =
  TexasPropertyTaxIncreaseCalculatorRouteImport.update({
    id: '/texas-property-tax-increase-calculator',
    path: '/texas-property-tax-increase-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasPoliticsRoute = TexasPoliticsRouteImport.update({
  id: '/texas-politics',
  path: '/texas-politics',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasNewsRoute = TexasNewsRouteImport.update({
  id: '/texas-news',
  path: '/texas-news',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasMovingCostCalculatorRoute =
  TexasMovingCostCalculatorRouteImport.update({
    id: '/texas-moving-cost-calculator',
    path: '/texas-moving-cost-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasMortgagePayoffCalculatorRoute =
  TexasMortgagePayoffCalculatorRouteImport.update({
    id: '/texas-mortgage-payoff-calculator',
    path: '/texas-mortgage-payoff-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasMortgageCalculatorRoute = TexasMortgageCalculatorRouteImport.update({
  id: '/texas-mortgage-calculator',
  path: '/texas-mortgage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasLawsRoute = TexasLawsRouteImport.update({
  id: '/texas-laws',
  path: '/texas-laws',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasLawPolicyRoute = TexasLawPolicyRouteImport.update({
  id: '/texas-law-policy',
  path: '/texas-law-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasHomeownershipCostCalculatorRoute =
  TexasHomeownershipCostCalculatorRouteImport.update({
    id: '/texas-homeownership-cost-calculator',
    path: '/texas-homeownership-cost-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasHomeInsuranceCalculatorRoute =
  TexasHomeInsuranceCalculatorRouteImport.update({
    id: '/texas-home-insurance-calculator',
    path: '/texas-home-insurance-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasHomeEquityGrowthCalculatorRoute =
  TexasHomeEquityGrowthCalculatorRouteImport.update({
    id: '/texas-home-equity-growth-calculator',
    path: '/texas-home-equity-growth-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasHomeEquityCalculatorRoute =
  TexasHomeEquityCalculatorRouteImport.update({
    id: '/texas-home-equity-calculator',
    path: '/texas-home-equity-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasHomeAffordabilityCalculatorRoute =
  TexasHomeAffordabilityCalculatorRouteImport.update({
    id: '/texas-home-affordability-calculator',
    path: '/texas-home-affordability-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasFinancialToolsRoute = TexasFinancialToolsRouteImport.update({
  id: '/texas-financial-tools',
  path: '/texas-financial-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasEconomyRoute = TexasEconomyRouteImport.update({
  id: '/texas-economy',
  path: '/texas-economy',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasDownPaymentCalculatorRoute =
  TexasDownPaymentCalculatorRouteImport.update({
    id: '/texas-down-payment-calculator',
    path: '/texas-down-payment-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasDownPaymentAssistanceCalculatorRoute =
  TexasDownPaymentAssistanceCalculatorRouteImport.update({
    id: '/texas-down-payment-assistance-calculator',
    path: '/texas-down-payment-assistance-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasCostOfLivingCalculatorRoute =
  TexasCostOfLivingCalculatorRouteImport.update({
    id: '/texas-cost-of-living-calculator',
    path: '/texas-cost-of-living-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasClosingCostCalculatorRoute =
  TexasClosingCostCalculatorRouteImport.update({
    id: '/texas-closing-cost-calculator',
    path: '/texas-closing-cost-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TexasBusinessRoute = TexasBusinessRouteImport.update({
  id: '/texas-business',
  path: '/texas-business',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasBudgetPlannerRoute = TexasBudgetPlannerRouteImport.update({
  id: '/texas-budget-planner',
  path: '/texas-budget-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TexasRoute = TexasRouteImport.update({
  id: '/texas',
  path: '/texas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxCalculatorRoute = TaxCalculatorRouteImport.update({
  id: '/tax-calculator',
  path: '/tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsDotxmlRoute = SitemapProductsDotxmlRouteImport.update({
  id: '/sitemap-products.xml',
  path: '/sitemap-products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapNewsDotxmlRoute = SitemapNewsDotxmlRouteImport.update({
  id: '/sitemap-news.xml',
  path: '/sitemap-news.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEvergreenDotxmlRoute = SitemapEvergreenDotxmlRouteImport.update({
  id: '/sitemap-evergreen.xml',
  path: '/sitemap-evergreen.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapAuthorsDotxmlRoute = SitemapAuthorsDotxmlRouteImport.update({
  id: '/sitemap-authors.xml',
  path: '/sitemap-authors.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativesRoute = RepresentativesRouteImport.update({
  id: '/representatives',
  path: '/representatives',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterToVoteRoute = RegisterToVoteRouteImport.update({
  id: '/register-to-vote',
  path: '/register-to-vote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingToTexasRoute = MovingToTexasRouteImport.update({
  id: '/moving-to-texas',
  path: '/moving-to-texas',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingInTexasRoute = LivingInTexasRouteImport.update({
  id: '/living-in-texas',
  path: '/living-in-texas',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislativeUpdatesRoute = LegislativeUpdatesRouteImport.update({
  id: '/legislative-updates',
  path: '/legislative-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsToKnowRoute = LawsToKnowRouteImport.update({
  id: '/laws-to-know',
  path: '/laws-to-know',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsRoute = LawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepTexasRedRoute = KeepTexasRedRouteImport.update({
  id: '/keep-texas-red',
  path: '/keep-texas-red',
  getParentRoute: () => rootRouteImport,
} as any)
const HoustonRoute = HoustonRouteImport.update({
  id: '/houston',
  path: '/houston',
  getParentRoute: () => rootRouteImport,
} as any)
const HappeningNowRoute = HappeningNowRouteImport.update({
  id: '/happening-now',
  path: '/happening-now',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRepresentativeRoute = FindRepresentativeRouteImport.update({
  id: '/find-representative',
  path: '/find-representative',
  getParentRout…14105 tokens truncated…outeImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-school-district': {
      id: '/find-my-school-district'
      path: '/find-my-school-district'
      fullPath: '/find-my-school-district'
      preLoaderRoute: typeof FindMySchoolDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-dmv': {
      id: '/find-my-dmv'
      path: '/find-my-dmv'
      fullPath: '/find-my-dmv'
      preLoaderRoute: typeof FindMyDmvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-standards': {
      id: '/editorial-standards'
      path: '/editorial-standards'
      fullPath: '/editorial-standards'
      preLoaderRoute: typeof EditorialStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/county-elections': {
      id: '/county-elections'
      path: '/county-elections'
      fullPath: '/county-elections'
      preLoaderRoute: typeof CountyElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-legislators': {
      id: '/contact-legislators'
      path: '/contact-legislators'
      fullPath: '/contact-legislators'
      preLoaderRoute: typeof ContactLegislatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-guides': {
      id: '/candidate-guides'
      path: '/candidate-guides'
      fullPath: '/candidate-guides'
      preLoaderRoute: typeof CandidateGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-keep-texas-red': {
      id: '/about-keep-texas-red'
      path: '/about-keep-texas-red'
      fullPath: '/about-keep-texas-red'
      preLoaderRoute: typeof AboutKeepTexasRedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texas/': {
      id: '/texas/'
      path: '/'
      fullPath: '/texas/'
      preLoaderRoute: typeof TexasIndexRouteImport
      parentRoute: typeof TexasRoute
    }
    '/texas-sports/': {
      id: '/texas-sports/'
      path: '/'
      fullPath: '/texas-sports/'
      preLoaderRoute: typeof TexasSportsIndexRouteImport
      parentRoute: typeof TexasSportsRoute
    }
    '/texas-news/': {
      id: '/texas-news/'
      path: '/'
      fullPath: '/texas-news/'
      preLoaderRoute: typeof TexasNewsIndexRouteImport
      parentRoute: typeof TexasNewsRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texas/$slug': {
      id: '/texas/$slug'
      path: '/$slug'
      fullPath: '/texas/$slug'
      preLoaderRoute: typeof TexasSlugRouteImport
      parentRoute: typeof TexasRoute
    }
    '/texas-sports/$league': {
      id: '/texas-sports/$league'
      path: '/$league'
      fullPath: '/texas-sports/$league'
      preLoaderRoute: typeof TexasSportsLeagueRouteImport
      parentRoute: typeof TexasSportsRoute
    }
    '/texas-news/$topic': {
      id: '/texas-news/$topic'
      path: '/$topic'
      fullPath: '/texas-news/$topic'
      preLoaderRoute: typeof TexasNewsTopicRouteImport
      parentRoute: typeof TexasNewsRoute
    }
    '/texas-business/$topic': {
      id: '/texas-business/$topic'
      path: '/$topic'
      fullPath: '/texas-business/$topic'
      preLoaderRoute: typeof TexasBusinessTopicRouteImport
      parentRoute: typeof TexasBusinessRoute
    }
    '/shop/checkout-return': {
      id: '/shop/checkout-return'
      path: '/checkout-return'
      fullPath: '/shop/checkout-return'
      preLoaderRoute: typeof ShopCheckoutReturnRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/news/non-political': {
      id: '/news/non-political'
      path: '/non-political'
      fullPath: '/news/non-political'
      preLoaderRoute: typeof NewsNonPoliticalRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texas-sports/team/$team': {
      id: '/texas-sports/team/$team'
      path: '/team/$team'
      fullPath: '/texas-sports/team/$team'
      preLoaderRoute: typeof TexasSportsTeamTeamRouteImport
      parentRoute: typeof TexasSportsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/property-address-lookup': {
      id: '/api/public/property-address-lookup'
      path: '/api/public/property-address-lookup'
      fullPath: '/api/public/property-address-lookup'
      preLoaderRoute: typeof ApiPublicPropertyAddressLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/track-variant': {
      id: '/api/public/hooks/track-variant'
      path: '/api/public/hooks/track-variant'
      fullPath: '/api/public/hooks/track-variant'
      preLoaderRoute: typeof ApiPublicHooksTrackVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-printify': {
      id: '/api/public/hooks/sync-printify'
      path: '/api/public/hooks/sync-printify'
      fullPath: '/api/public/hooks/sync-printify'
      preLoaderRoute: typeof ApiPublicHooksSyncPrintifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/score-viral-backfill': {
      id: '/api/public/hooks/score-viral-backfill'
      path: '/api/public/hooks/score-viral-backfill'
      fullPath: '/api/public/hooks/score-viral-backfill'
      preLoaderRoute: typeof ApiPublicHooksScoreViralBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/score-viral': {
      id: '/api/public/hooks/score-viral'
      path: '/api/public/hooks/score-viral'
      fullPath: '/api/public/hooks/score-viral'
      preLoaderRoute: typeof ApiPublicHooksScoreViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/list-shops': {
      id: '/api/public/hooks/list-shops'
      path: '/api/public/hooks/list-shops'
      fullPath: '/api/public/hooks/list-shops'
      preLoaderRoute: typeof ApiPublicHooksListShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-feeds': {
      id: '/api/public/hooks/ingest-feeds'
      path: '/api/public/hooks/ingest-feeds'
      fullPath: '/api/public/hooks/ingest-feeds'
      preLoaderRoute: typeof ApiPublicHooksIngestFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health': {
      id: '/api/public/hooks/health'
      path: '/api/public/hooks/health'
      fullPath: '/api/public/hooks/health'
      preLoaderRoute: typeof ApiPublicHooksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-sports': {
      id: '/api/public/hooks/generate-sports'
      path: '/api/public/hooks/generate-sports'
      fullPath: '/api/public/hooks/generate-sports'
      preLoaderRoute: typeof ApiPublicHooksGenerateSportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-news': {
      id: '/api/public/hooks/generate-news'
      path: '/api/public/hooks/generate-news'
      fullPath: '/api/public/hooks/generate-news'
      preLoaderRoute: typeof ApiPublicHooksGenerateNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-evergreen': {
      id: '/api/public/hooks/generate-evergreen'
      path: '/api/public/hooks/generate-evergreen'
      fullPath: '/api/public/hooks/generate-evergreen'
      preLoaderRoute: typeof ApiPublicHooksGenerateEvergreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-featured-images': {
      id: '/api/public/hooks/backfill-featured-images'
      path: '/api/public/hooks/backfill-featured-images'
      fullPath: '/api/public/hooks/backfill-featured-images'
      preLoaderRoute: typeof ApiPublicHooksBackfillFeaturedImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article-image/$filename': {
      id: '/api/public/article-image/$filename'
      path: '/api/public/article-image/$filename'
      fullPath: '/api/public/article-image/$filename'
      preLoaderRoute: typeof ApiPublicArticleImageFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/facebook/start': {
      id: '/api/public/oauth/facebook/start'
      path: '/api/public/oauth/facebook/start'
      fullPath: '/api/public/oauth/facebook/start'
      preLoaderRoute: typeof ApiPublicOauthFacebookStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/facebook/callback': {
      id: '/api/public/oauth/facebook/callback'
      path: '/api/public/oauth/facebook/callback'
      fullPath: '/api/public/oauth/facebook/callback'
      preLoaderRoute: typeof ApiPublicOauthFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsNonPoliticalRoute: typeof NewsNonPoliticalRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsNonPoliticalRoute: NewsNonPoliticalRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopCheckoutReturnRoute: typeof ShopCheckoutReturnRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopCheckoutReturnRoute: ShopCheckoutReturnRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface TexasRouteChildren {
  TexasSlugRoute: typeof TexasSlugRoute
  TexasIndexRoute: typeof TexasIndexRoute
}

const TexasRouteChildren: TexasRouteChildren = {
  TexasSlugRoute: TexasSlugRoute,
  TexasIndexRoute: TexasIndexRoute,
}

const TexasRouteWithChildren = TexasRoute._addFileChildren(TexasRouteChildren)

interface TexasBusinessRouteChildren {
  TexasBusinessTopicRoute: typeof TexasBusinessTopicRoute
}

const TexasBusinessRouteChildren: TexasBusinessRouteChildren = {
  TexasBusinessTopicRoute: TexasBusinessTopicRoute,
}

const TexasBusinessRouteWithChildren = TexasBusinessRoute._addFileChildren(
  TexasBusinessRouteChildren,
)

interface TexasNewsRouteChildren {
  TexasNewsTopicRoute: typeof TexasNewsTopicRoute
  TexasNewsIndexRoute: typeof TexasNewsIndexRoute
}

const TexasNewsRouteChildren: TexasNewsRouteChildren = {
  TexasNewsTopicRoute: TexasNewsTopicRoute,
  TexasNewsIndexRoute: TexasNewsIndexRoute,
}

const TexasNewsRouteWithChildren = TexasNewsRoute._addFileChildren(
  TexasNewsRouteChildren,
)

interface TexasSportsRouteChildren {
  TexasSportsLeagueRoute: typeof TexasSportsLeagueRoute
  TexasSportsIndexRoute: typeof TexasSportsIndexRoute
  TexasSportsTeamTeamRoute: typeof TexasSportsTeamTeamRoute
}

const TexasSportsRouteChildren: TexasSportsRouteChildren = {
  TexasSportsLeagueRoute: TexasSportsLeagueRoute,
  TexasSportsIndexRoute: TexasSportsIndexRoute,
  TexasSportsTeamTeamRoute: TexasSportsTeamTeamRoute,
}

const TexasSportsRouteWithChildren = TexasSportsRoute._addFileChildren(
  TexasSportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutKeepTexasRedRoute: AboutKeepTexasRedRoute,
  AdminRoute: AdminRoute,
  CandidateGuidesRoute: CandidateGuidesRoute,
  ContactRoute: ContactRoute,
  ContactLegislatorsRoute: ContactLegislatorsRoute,
  CountyElectionsRoute: CountyElectionsRoute,
  EditorialStandardsRoute: EditorialStandardsRoute,
  ElectionsRoute: ElectionsRoute,
  FindMyDmvRoute: FindMyDmvRoute,
  FindMySchoolDistrictRoute: FindMySchoolDistrictRoute,
  FindRepresentativeRoute: FindRepresentativeRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  GlossaryRoute: GlossaryRoute,
  HappeningNowRoute: HappeningNowRoute,
  HoustonRoute: HoustonRoute,
  KeepTexasRedRoute: KeepTexasRedRoute,
  LawsRoute: LawsRoute,
  LawsToKnowRoute: LawsToKnowRoute,
  LegislativeUpdatesRoute: LegislativeUpdatesRoute,
  LivingInTexasRoute: LivingInTexasRoute,
  MovingToTexasRoute: MovingToTexasRoute,
  NewsRoute: NewsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterToVoteRoute: RegisterToVoteRoute,
  RepresentativesRoute: RepresentativesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapAuthorsDotxmlRoute: SitemapAuthorsDotxmlRoute,
  SitemapEvergreenDotxmlRoute: SitemapEvergreenDotxmlRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapNewsDotxmlRoute: SitemapNewsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapProductsDotxmlRoute: SitemapProductsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxCalculatorRoute: TaxCalculatorRoute,
  TermsRoute: TermsRoute,
  TexasRoute: TexasRouteWithChildren,
  TexasBudgetPlannerRoute: TexasBudgetPlannerRoute,
  TexasBusinessRoute: TexasBusinessRouteWithChildren,
  TexasClosingCostCalculatorRoute: TexasClosingCostCalculatorRoute,
  TexasCostOfLivingCalculatorRoute: TexasCostOfLivingCalculatorRoute,
  TexasDownPaymentAssistanceCalculatorRoute:
    TexasDownPaymentAssistanceCalculatorRoute,
  TexasDownPaymentCalculatorRoute: TexasDownPaymentCalculatorRoute,
  TexasEconomyRoute: TexasEconomyRoute,
  TexasFinancialToolsRoute: TexasFinancialToolsRoute,
  TexasHomeAffordabilityCalculatorRoute: TexasHomeAffordabilityCalculatorRoute,
  TexasHomeEquityCalculatorRoute: TexasHomeEquityCalculatorRoute,
  TexasHomeEquityGrowthCalculatorRoute: TexasHomeEquityGrowthCalculatorRoute,
  TexasHomeInsuranceCalculatorRoute: TexasHomeInsuranceCalculatorRoute,
  TexasHomeownershipCostCalculatorRoute: TexasHomeownershipCostCalculatorRoute,
  TexasLawPolicyRoute: TexasLawPolicyRoute,
  TexasLawsRoute: TexasLawsRoute,
  TexasMortgageCalculatorRoute: TexasMortgageCalculatorRoute,
  TexasMortgagePayoffCalculatorRoute: TexasMortgagePayoffCalculatorRoute,
  TexasMovingCostCalculatorRoute: TexasMovingCostCalculatorRoute,
  TexasNewsRoute: TexasNewsRouteWithChildren,
  TexasPoliticsRoute: TexasPoliticsRoute,
  TexasPropertyTaxIncreaseCalculatorRoute:
    TexasPropertyTaxIncreaseCalculatorRoute,
  TexasRefinanceSavingsCalculatorRoute: TexasRefinanceSavingsCalculatorRoute,
  TexasRentVsBuyCalculatorRoute: TexasRentVsBuyCalculatorRoute,
  TexasSalaryCalculatorRoute: TexasSalaryCalculatorRoute,
  TexasSalaryComparisonByCityRoute: TexasSalaryComparisonByCityRoute,
  TexasSportsRoute: TexasSportsRouteWithChildren,
  TexasUtilityCostCalculatorRoute: TexasUtilityCostCalculatorRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VotingLocationsRoute: VotingLocationsRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  ApiPublicPropertyAddressLookupRoute: ApiPublicPropertyAddressLookupRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicArticleImageFilenameRoute: ApiPublicArticleImageFilenameRoute,
  ApiPublicHooksBackfillFeaturedImagesRoute:
    ApiPublicHooksBackfillFeaturedImagesRoute,
  ApiPublicHooksGenerateEvergreenRoute: ApiPublicHooksGenerateEvergreenRoute,
  ApiPublicHooksGenerateNewsRoute: ApiPublicHooksGenerateNewsRoute,
  ApiPublicHooksGenerateSportsRoute: ApiPublicHooksGenerateSportsRoute,
  ApiPublicHooksHealthRoute: ApiPublicHooksHealthRoute,
  ApiPublicHooksIngestFeedsRoute: ApiPublicHooksIngestFeedsRoute,
  ApiPublicHooksListShopsRoute: ApiPublicHooksListShopsRoute,
  ApiPublicHooksScoreViralRoute: ApiPublicHooksScoreViralRoute,
  ApiPublicHooksScoreViralBackfillRoute: ApiPublicHooksScoreViralBackfillRoute,
  ApiPublicHooksSyncPrintifyRoute: ApiPublicHooksSyncPrintifyRoute,
  ApiPublicHooksTrackVariantRoute: ApiPublicHooksTrackVariantRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicOauthFacebookCallbackRoute: ApiPublicOauthFacebookCallbackRoute,
  ApiPublicOauthFacebookStartRoute: ApiPublicOauthFacebookStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

