/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TaxCalculatorRouteImport } from './routes/tax-calculator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RepresentativesRouteImport } from './routes/representatives'
import { Route as RegisterToVoteRouteImport } from './routes/register-to-vote'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FindRepresentativeRouteImport } from './routes/find-representative'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as CountyElectionsRouteImport } from './routes/county-elections'
import { Route as ContactLegislatorsRouteImport } from './routes/contact-legislators'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxCalculatorRoute = TaxCalculatorRouteImport.update({
  id: '/tax-calculator',
  path: '/tax-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativesRoute = RepresentativesRouteImport.update({
  id: '/representatives',
  path: '/representatives',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterToVoteRoute = RegisterToVoteRouteImport.update({
  id: '/register-to-vote',
  path: '/register-to-vote',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRepresentativeRoute = FindRepresentativeRouteImport.update({
  id: '/find-representative',
  path: '/find-representative',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const CountyElectionsRoute = CountyElectionsRouteImport.update({
  id: '/county-elections',
  path: '/county-elections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactLegislatorsRoute = ContactLegislatorsRouteImport.update({
  id: '/contact-legislators',
  path: '/contact-legislators',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-legislators': typeof ContactLegislatorsRoute
  '/county-elections': typeof CountyElectionsRoute
  '/elections': typeof ElectionsRoute
  '/find-representative': typeof FindRepresentativeRoute
  '/news': typeof NewsRoute
  '/register-to-vote': typeof RegisterToVoteRoute
  '/representatives': typeof RepresentativesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-calculator': typeof TaxCalculatorRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-legislators': typeof ContactLegislatorsRoute
  '/county-elections': typeof CountyElectionsRoute
  '/elections': typeof ElectionsRoute
  '/find-representative': typeof FindRepresentativeRoute
  '/news': typeof NewsRoute
  '/register-to-vote': typeof RegisterToVoteRoute
  '/representatives': typeof RepresentativesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-calculator': typeof TaxCalculatorRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-legislators': typeof ContactLegislatorsRoute
  '/county-elections': typeof CountyElectionsRoute
  '/elections': typeof ElectionsRoute
  '/find-representative': typeof FindRepresentativeRoute
  '/news': typeof NewsRoute
  '/register-to-vote': typeof RegisterToVoteRoute
  '/representatives': typeof RepresentativesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-calculator': typeof TaxCalculatorRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-legislators'
    | '/county-elections'
    | '/elections'
    | '/find-representative'
    | '/news'
    | '/register-to-vote'
    | '/representatives'
    | '/sitemap.xml'
    | '/tax-calculator'
    | '/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-legislators'
    | '/county-elections'
    | '/elections'
    | '/find-representative'
    | '/news'
    | '/register-to-vote'
    | '/representatives'
    | '/sitemap.xml'
    | '/tax-calculator'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact-legislators'
    | '/county-elections'
    | '/elections'
    | '/find-representative'
    | '/news'
    | '/register-to-vote'
    | '/representatives'
    | '/sitemap.xml'
    | '/tax-calculator'
    | '/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactLegislatorsRoute: typeof ContactLegislatorsRoute
  CountyElectionsRoute: typeof CountyElectionsRoute
  ElectionsRoute: typeof ElectionsRoute
  FindRepresentativeRoute: typeof FindRepresentativeRoute
  NewsRoute: typeof NewsRoute
  RegisterToVoteRoute: typeof RegisterToVoteRoute
  RepresentativesRoute: typeof RepresentativesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaxCalculatorRoute: typeof TaxCalculatorRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-calculator': {
      id: '/tax-calculator'
      path: '/tax-calculator'
      fullPath: '/tax-calculator'
      preLoaderRoute: typeof TaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representatives': {
      id: '/representatives'
      path: '/representatives'
      fullPath: '/representatives'
      preLoaderRoute: typeof RepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-to-vote': {
      id: '/register-to-vote'
      path: '/register-to-vote'
      fullPath: '/register-to-vote'
      preLoaderRoute: typeof RegisterToVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-representative': {
      id: '/find-representative'
      path: '/find-representative'
      fullPath: '/find-representative'
      preLoaderRoute: typeof FindRepresentativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/county-elections': {
      id: '/county-elections'
      path: '/county-elections'
      fullPath: '/county-elections'
      preLoaderRoute: typeof CountyElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-legislators': {
      id: '/contact-legislators'
      path: '/contact-legislators'
      fullPath: '/contact-legislators'
      preLoaderRoute: typeof ContactLegislatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactLegislatorsRoute: ContactLegislatorsRoute,
  CountyElectionsRoute: CountyElectionsRoute,
  ElectionsRoute: ElectionsRoute,
  FindRepresentativeRoute: FindRepresentativeRoute,
  NewsRoute: NewsRoute,
  RegisterToVoteRoute: RegisterToVoteRoute,
  RepresentativesRoute: RepresentativesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxCalculatorRoute: TaxCalculatorRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
