-- Daily Texas News automation: 2026-08-09-san-antonio-ai-fake-legal-citations
WITH item AS (
SELECT $slug$2026-08-09-san-antonio-ai-fake-legal-citations$slug$::text slug,
       $cat$Texas News$cat$::text category,
       $title$San Antonio Appeals Court Finds Fake AI Citations in School Case, Sharpening Warning for Texas Lawyers$title$::text title,
       $dek$Four citations in an appellate brief were fabricated or misrepresented, underscoring the professional risk of using generative AI without checking the underlying law.$dek$::text dek,
       $source$San Antonio Express-News$source$::text source_name,
       $url$https://www.expressnews.com/news/article/judges-couldn-t-find-cases-found-instead-ai-22377207.php$url$::text source_url,
       '2026-08-09T17:28:00Z'::timestamptz published_at,
       40::int score,
       FALSE::boolean is_breaking,
       $img$/images/news/generated/2026-08-09/ai-legal-citations.svg$img$::text image_url,
       $alt$Editorial illustration of a Texas courthouse brief beside an AI screen showing broken citation links.$alt$::text image_alt_text,
       $body$A San Antonio appeals court has delivered a blunt warning about generative AI in the legal profession after judges found citations in a school-discipline brief that were fabricated or materially inaccurate. The Fourth Court of Appeals identified four problem citations while reviewing a case involving a mother who challenged disciplinary action against her fifth-grade son. The court still decided the underlying dispute, but it made clear that lawyers cannot outsource professional responsibility to a chatbot. The episode belongs in [Texas News](/texas-news) because it turns a familiar technology warning—AI can hallucinate—into a concrete question of court integrity, client representation and professional discipline.

The problem with fabricated citations is not merely embarrassing. Legal arguments depend on authority: statutes, rules and prior decisions that can be checked by the opposing side and the judge. A nonexistent case can waste court time, distort an argument and undermine confidence in everything else a lawyer has filed. Generative systems are particularly risky because they can produce text that looks exactly like a conventional case citation, complete with plausible party names, reporters and dates. The formatting creates confidence without proof. Readers who follow [Latest News](/news) have seen AI errors in many industries, but a courtroom attaches unusually high consequences to invented facts.

The responsibility remains with the lawyer because the lawyer signs or submits the document. That principle predates AI. Attorneys have always been expected to verify research performed by junior lawyers, staff members or outside services. A language model is simply another research aid, not a licensed advocate. If software suggests a case, the next step is to retrieve the actual opinion and confirm that it exists, says what the draft claims, remains good law and applies to the relevant jurisdiction. Skipping those steps is not a technological problem; it is a breakdown in legal workflow.

Courts across the country have encountered similar filings as AI tools have become more common. The recurring pattern is instructive: the system often does not respond “I don’t know.” Instead it completes the pattern the user seems to want. In legal research, that can mean inventing an authority that would make the argument stronger. Newer products can reduce the risk by grounding answers in verified databases, but even specialized tools can summarize a case incorrectly. Lawyers therefore need a verification step that is independent of the generative system that produced the answer.

Texas courts and bar regulators now have to decide how much formal rulemaking is needed. The Texas Supreme Court has considered requirements that emphasize verification and allow sanctions for fabricated legal references. Some judges favor certifications about AI use; others argue existing ethics rules already cover competence, candor and supervision. There is a danger in writing rules so narrowly around today’s technology that they become obsolete when tools change. A durable standard would focus on the output: lawyers are responsible for factual and legal accuracy regardless of whether a mistake came from AI, a search engine, a database or a human assistant.

Law firms also have a management problem. Banning AI completely may push use underground, especially when clients expect faster and cheaper work. Allowing unrestricted use can create confidentiality and accuracy risks. A better policy distinguishes tasks. Generative tools may be useful for brainstorming, organizing facts, drafting non-substantive language or creating checklists. They are much riskier when asked to supply authorities, quote cases, calculate deadlines or make assertions that no one independently verifies. Firms should train lawyers to recognize those boundaries and document how final work was checked.

Clients have a stake too. AI can reduce the time required for routine drafting, but a client should not pay for speed that creates a new risk of sanctions or a damaged case. Courts can impose costs, strike filings or refer lawyers for discipline when invented authorities appear. Even when the legal issue itself survives, credibility with the judge can be difficult to rebuild. That is why the San Antonio case matters beyond one school dispute. It demonstrates that careless AI use can become part of the record and follow an attorney long after the software session is forgotten.

There is also an educational lesson. Law schools increasingly teach students to use AI tools while emphasizing source verification. That is likely more realistic than pretending the technology will disappear. Future lawyers need to understand both how to prompt systems effectively and when not to trust an answer. Traditional legal research skills—reading cases, tracing citations, checking subsequent history and distinguishing holding from dicta—become more valuable, not less, when a machine can generate polished text instantly. The faster the first draft becomes, the more important the validation discipline becomes.

The Express-News report on the Fourth Court of Appeals episode is a useful marker for Texas. Generative AI has moved from novelty to ordinary workplace tool, and courts are now building the boundaries through real cases. The lesson is simple enough to survive the next generation of software: a lawyer can use technology to assist the work, but cannot delegate the duty of truthfulness. Every citation that reaches a Texas judge still needs to lead to a real source that says what the lawyer claims it says.$body$::text body,
       $links$[{"href": "/texas-news", "kind": "hub", "label": "Texas News"}, {"href": "/news", "kind": "hub", "label": "Latest News"}]$links$::jsonb internal_links
), prepared AS (
SELECT *,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — source report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)) body_json FROM item
)
INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,internal_links,featured_image_url,image_url,image_alt_text)
SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,internal_links,image_url,image_url,image_alt_text FROM prepared
ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,internal_links=EXCLUDED.internal_links,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;
