-- New-infrastructure test article: 2026-08-09-san-antonio-puffy-taco-race
WITH item AS (
SELECT '2026-08-09-san-antonio-puffy-taco-race'::text slug,'Viral'::text category,'San Antonio’s Puffy Taco Race Is Still Going Strong After More Than Three Decades of Deliberate Defeat'::text title,'A child chasing and tackling a giant taco at Missions games remains one of Texas baseball’s strangest and most beloved traditions.'::text dek,'San Antonio Express-News'::text source_name,'https://www.expressnews.com/news/article/san-antonio-explained-puffy-taco-races-baseball-22362579.php'::text source_url,'2026-08-09T16:33:00Z'::timestamptz published_at,31::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/puffy-taco-race.svg'::text image_url,'Editorial illustration of a giant puffy taco mascot racing a child around a baseball diamond under San Antonio stadium lights.'::text image_alt_text,$body$San Antonio has a baseball tradition that makes almost no sense until you see it once. After the sixth inning at many San Antonio Missions games, a child takes the field and chases a giant puffy taco around the bases. The objective is not a clean footrace. The child is expected to catch Henry the Puffy Taco and tackle him before the mascot reaches home plate. The taco, by design, usually loses. That ritual has survived for more than three decades and has become one of the city’s most recognizable pieces of minor-league baseball culture.

The promotion began in 1989 as an advertisement for Henry’s Puffy Tacos, the San Antonio restaurant associated with the mascot. Minor-league teams have always relied on between-inning entertainment, but the best promotions stop feeling like advertisements and become local folklore. The Puffy Taco Race reached that point years ago. Fans who may not remember the score can remember the moment a child flattened a taco near home plate.

Part of the appeal is the certainty of the outcome. Sports are interesting because nobody knows who will win. The Puffy Taco Race is funny because almost everybody does know. The child is the hero, the taco is the willing victim and the crowd participates in a tiny piece of theater. That formula works because the mascot commits to the bit. Henry runs hard enough to make the chase believable and then, at the right moment, becomes catchable.

The one famous exception proves the rule. In 1992, Henry the Puffy Taco unexpectedly won. The child racing that night, Randy Neuenfeldt, became part of San Antonio sports lore because losing to the mascot was not supposed to happen. Years later, the Missions staged a rematch and gave him a chance at redemption as an adult. The original upset still gets remembered because it violated an unwritten civic contract: the kid is supposed to beat the taco.

That history helps explain why the race survives in an era when stadium promotions can be designed around social-media clips and corporate sponsorship packages. The Puffy Taco did not need to be invented for the internet. It was already visually absurd, easy to understand and unmistakably local. A giant regional food being chased by a child is the kind of scene that translates perfectly to a phone screen without losing its original charm.

The tradition also reflects how minor-league baseball fits into Texas sports culture. Fans attend for the game, but families also expect entertainment that is less formal than a major-league experience. Mascots, contests and local food are part of the product. Keep TX Red’s Texas Sports coverage follows the teams and athletes, while the broader Texas News hub captures the local traditions that make those games feel different from one city to the next.

San Antonio’s puffy taco is particularly well suited to that role because the food itself is tied to the city. A puffy taco shell is fried until it expands into a light, crisp shape, then filled with the familiar ingredients of a taco. Turning that food into a mascot is both ridiculous and logical. It is difficult to imagine the same promotion working quite the same way in a city without the culinary connection.

The race is also surprisingly participatory. Children can sign up for a chance to compete, which means the tradition is continually renewed by new families. A parent who remembers watching the race as a child can bring a son or daughter who now wants to be the person chasing Henry. That generational cycle is how a promotion becomes an institution.

There is a business lesson hidden inside the silliness. Local sponsorship works best when the sponsor contributes something people would miss if it disappeared. The Puffy Taco Race does that. The restaurant name remains attached to the mascot, but fans do not experience the event as a commercial interruption. They experience it as part of the ballpark.

The Missions have changed affiliations, players come and go, stadium plans evolve and San Antonio itself keeps growing. Henry the Puffy Taco keeps getting tackled. That continuity gives the race an outsized emotional value. In a city where development can make familiar places feel temporary, a ridiculous mascot losing on purpose becomes a small form of stability.

Texas has plenty of serious sports traditions, from Friday night football to college rivalries. The Puffy Taco Race belongs to the other category: traditions that survive because they are funny, specific and impossible to export. San Antonio did not need a national mascot concept. It already had a taco willing to lose for the children.

The race also gives the Missions a piece of identity that can survive changes in professional baseball. Minor-league affiliations can shift, league structures can be reorganized and players may spend only a few months in town before promotion or release. A local ritual creates continuity independent of the roster. Fans know that even if they cannot name every prospect, the taco will still appear and a child will still be waiting to chase it.

That continuity has marketing value for San Antonio itself. Visitors searching for something distinctively local often want experiences that cannot be reproduced in another city. The Alamo and River Walk are obvious examples; a puffy taco getting tackled at a baseball game is smaller, but it carries the same sense of place. It is a reminder that civic identity is often built from odd little traditions people decide are worth keeping.$body$::text body), prepared AS (SELECT *, replace(replace(body,'Texas sports culture','[Texas sports culture](/sports)'),'Texas News hub','[Texas News](/texas-news) hub') linked_body FROM item)
INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text,internal_links)
SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(linked_body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',to_jsonb(string_to_array(linked_body,E'\n\n')))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — source report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)),image_url,image_url,image_alt_text,'[{"href":"/sports","kind":"hub","label":"Texas Sports"},{"href":"/texas-news","kind":"hub","label":"Texas News"}]'::jsonb FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text,internal_links=EXCLUDED.internal_links;

-- New-infrastructure test article: 2026-08-09-screaming-goat-san-antonio
WITH item AS (SELECT '2026-08-09-screaming-goat-san-antonio'::text slug,'Viral'::text category,'Beer, Brunch and Actual Goats: Hill Country Taproom Is Bringing Its Barnyard Formula to San Antonio'::text title,'Screaming Goat Yard & Tap plans a new location near UTSA, complete with live entertainment, a larger kitchen and several of the goats that made the original venue famous.'::text dek,'MySA'::text source_name,'https://www.mysanantonio.com/food/article/screaming-goat-san-antonio-22377648.php'::text source_url,'2026-08-09T16:34:00Z'::timestamptz published_at,29::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/screaming-goat-san-antonio.svg'::text image_url,'Editorial illustration of a San Antonio taproom patio with brunch plates, beer taps and playful goats near outdoor string lights.'::text image_alt_text,$body$A Hill Country business built around a combination that sounds like a social-media joke is expanding into San Antonio: beer, brunch and live goats. Screaming Goat Yard & Tap, which started in Spring Branch, is preparing a second location near the University of Texas at San Antonio on Loop 1604. The new site is expected to keep the original venue’s casual outdoor atmosphere, broad drink selection and Southern-leaning menu while adding a larger kitchen and, most importantly for its identity, several goats.

The animals are not a decorative afterthought. They are part of the brand. Customers at the original location can see the goats, take photos and participate in events such as goat yoga. The combination makes the venue instantly understandable online. A picture of friends holding drinks on a patio is common. A picture of the same scene with a goat leaning into the frame is much more likely to be shared.

That viral quality has helped Screaming Goat stand out in a crowded Texas hospitality market. Bars and restaurants are constantly competing for attention, especially in fast-growing areas where new concepts open every month. A memorable experience gives customers a reason to talk about a place after the meal is over. The challenge is making sure the novelty does not overshadow the food and service required to turn a first visit into a repeat customer.

The San Antonio location gives the business access to a very different customer base from Spring Branch. The UTSA area is surrounded by students, apartments, office development, retail and growing neighborhoods. Loop 1604 also carries enormous traffic from the northwest side. A family-friendly outdoor taproom can attract students, young professionals, parents and weekend groups at different times of day.

The larger kitchen may allow the San Antonio site to expand its menu, including dishes that were difficult to execute in the original space. Management has discussed the possibility of adding items such as oysters. That matters because a concept built on goats can get people through the door once, but a broader menu gives them reasons to come back when the novelty is no longer new.

The company says six or seven goats are expected to make the move initially. That creates operational responsibilities beyond what most restaurants face. Animal care, guest interaction, sanitation and safe separation between food-service areas and livestock all have to work together. The animals must be treated as living creatures rather than props, and the venue has to manage enthusiastic customers who may not understand how to interact with them.

Texas businesses have a long history of turning regional eccentricity into an advantage. Roadside attractions, giant mascots, dance halls and unusual restaurants thrive because visitors want an experience they cannot get from a generic national chain. Screaming Goat fits that tradition in a modern form. The goats are both an attraction and a marketing engine.

Keep TX Red’s Texas News hub regularly tracks the fast-changing business and culture landscape around the state, while the Latest News page surfaces the newest openings and community stories. The Screaming Goat expansion is a smaller story than a major corporate relocation, but it captures the same underlying pattern: San Antonio’s northwest side continues to attract concepts that believe population growth can support another location.

There is also a tourism angle. Visitors to San Antonio already build itineraries around food, breweries and Hill Country day trips. A goat-filled taproom near the edge of the city can position itself as a bridge between the urban market and the Hill Country identity that inspired the original location. That is a stronger story than simply opening another bar near a highway.

The opening timeline remains flexible while the company hires and finishes preparations. Restaurant openings often move because of inspections, staffing, equipment deliveries and construction details, so customers should treat any target date as approximate until the business announces service has begun.

If the concept works, the goats will be the reason many people hear about the new location, but they will not be the only reason it survives. Hospitality businesses depend on consistency, food quality, service and repeat traffic. The barnyard hook creates attention. The harder task is converting that attention into a neighborhood business.

For San Antonio, the arrival of Screaming Goat is another reminder that Texas dining culture increasingly blends food with entertainment. People are not just buying brunch or a beer. They are buying a place to gather, take a picture, bring friends and tell a story later. In this case, the story happens to include a goat.

The expansion will also test whether the concept can scale without becoming too polished. Part of the charm of the original venue is that it feels casual and slightly unpredictable. A second location near a major university will face heavier traffic and more standardized expectations. Management will have to preserve the personality while building systems strong enough to handle larger crowds, event nights and the very people who discovered the place online.

Neighbors will be watching practical details as well. Outdoor venues generate questions about parking, noise, late-night activity and traffic, especially around Loop 1604. A successful opening will depend not just on attracting customers but on fitting into a rapidly developing part of the city. The goats may dominate the photos, yet permitting, staffing and neighborhood operations will determine whether the business becomes a durable addition.$body$::text body), prepared AS (SELECT *,replace(replace(body,'Texas News hub','[Texas News](/texas-news) hub'),'Latest News page','[Latest News](/news) page') linked_body FROM item)
INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text,internal_links) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(linked_body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',to_jsonb(string_to_array(linked_body,E'\n\n')))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — source report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)),image_url,image_url,image_alt_text,'[{"href":"/texas-news","kind":"hub","label":"Texas News"},{"href":"/news","kind":"hub","label":"Latest News"}]'::jsonb FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text,internal_links=EXCLUDED.internal_links;

-- New-infrastructure test article: 2026-08-09-kingston-flemings-youth-camp
WITH item AS (SELECT '2026-08-09-kingston-flemings-youth-camp'::text slug,'Viral'::text category,'NBA Rookie Kingston Flemings Comes Home to San Antonio and Puts 200 Kids Through His Own Basketball Camp'::text title,'The Brennan High School star returned after becoming a first-round NBA pick, using his second annual camp to keep a direct connection with the community that raised him.'::text dek,'San Antonio Express-News'::text source_name,'https://www.expressnews.com/sports/high-school/article/atlanta-hawks-guard-kingston-flemings-hosts-camp-22380242.php'::text source_url,'2026-08-09T16:35:00Z'::timestamptz published_at,30::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/kingston-flemings-camp.svg'::text image_url,'Editorial illustration of a young NBA player leading children through basketball drills in a San Antonio high school gym.'::text image_alt_text,$body$Kingston Flemings did not wait long after reaching the NBA to bring some of that momentum back to San Antonio. The former Brennan High School star returned home to host his second annual “4 The City” youth basketball camp, giving roughly 200 elementary and middle-school boys a day of drills, competition, photos and direct interaction with a player whose path from a local gym to the first round of the NBA draft is still fresh enough for the campers to remember.

That timing is what makes the camp resonate. Flemings is not a distant retired star whose career belongs to another generation. He was recently playing in the same high-school environment as many of the kids attending. He then starred at the University of Houston before entering the NBA. For a young San Antonio player, the sequence feels visible and immediate: Brennan, college basketball, the draft and then back home to the same community.

Flemings’ basketball résumé gives the event credibility. He became one of the most decorated boys basketball players produced by San Antonio in years, earning statewide recognition before continuing his rise at Houston. His success made him a first-round pick, turning a local prospect into a professional athlete with national expectations. Camps built around that kind of trajectory can make elite basketball feel less abstract to children who are still learning basic footwork and shooting form.

The event was also intentionally local. Flemings worked with people he trusts, including former teammates, coaches and family members. His younger sister Bella, a Duke player, is part of the same basketball family and is expected to host a girls’ camp. That creates a broader community connection than a one-day celebrity appearance. The people teaching the drills understand the schools, gyms and neighborhoods the campers come from.

For the children, the value is not that a few hours of instruction will transform anyone into an NBA player. Skill development is cumulative. What a camp can do is give young athletes specific habits to take home: balance, repetition, defensive effort, ball control, communication and the willingness to work through mistakes. A camper may remember one correction from Flemings longer than a dozen routine practices.

The social side matters too. Youth sports can be expensive, and access to high-level coaching is uneven. Community camps provide a concentrated experience that can motivate families to keep children involved. They also allow kids to meet others who share the same interest, turning basketball into a network rather than an individual pursuit.

Keep TX Red’s Texas Sports coverage follows athletes as they move from high school to college and the professional level, while Texas News captures the community stories around those careers. Flemings’ return sits squarely between the two. It is sports news because of who he has become, but it is a San Antonio community story because of where he chose to spend the day.

There is a reputational benefit for Flemings as well, though that does not make the gesture less meaningful. Professional athletes are increasingly expected to build personal brands from the beginning of their careers. Community work is one way to do that. The strongest version is when the branding aligns with a real connection. Flemings can credibly talk about giving back to San Antonio because the gyms and coaches are part of his own story.

The camp also gives Brennan High School a visible example of what its program can produce. Younger athletes training in the same building can see a direct line between school basketball and the professional game. Coaches cannot promise that outcome to anyone, but they can point to the habits and support system that helped one former player reach it.

San Antonio has always embraced athletes who maintain a relationship with the city after moving to larger stages. Spurs players often become permanent parts of local culture, but the same dynamic can begin before a player ever wears a Spurs uniform. Flemings now plays elsewhere, yet his hometown connection remains strong enough that an NBA road game in San Antonio will carry extra meaning.

The most lasting part of the event may be the simplest. Two hundred children got to spend a day in a gym with someone who recently sat where they sit. They saw that success did not erase his connection to home. For a young player, that can make ambition feel more concrete. For Flemings, returning to Brennan is a way to make sure the next chapter of his career does not close the door on the first one.

There is also a mentoring effect that goes beyond basketball technique. Young athletes often hear abstract advice about grades, discipline, sleep, nutrition and handling attention. Hearing those messages from a player only a few years older can make them land differently. Flemings can speak from recent experience about recruiting, college expectations and the transition from being the best player in a local gym to competing against elite talent every day.

For parents, camps like this also provide a realistic setting to talk about expectations. Professional sports are an extraordinary outcome, not a normal career path. The healthier lesson is that serious training can build confidence, teamwork and habits that matter even if a child never plays beyond high school. A hometown NBA player can inspire ambition while coaches and families keep the larger perspective grounded.$body$::text body), prepared AS (SELECT *,replace(replace(body,'Texas Sports coverage','[Texas Sports](/sports) coverage'),'Texas News','[Texas News](/texas-news)') linked_body FROM item)
INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text,internal_links) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(linked_body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',to_jsonb(string_to_array(linked_body,E'\n\n')))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — source report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)),image_url,image_url,image_alt_text,'[{"href":"/sports","kind":"hub","label":"Texas Sports"},{"href":"/texas-news","kind":"hub","label":"Texas News"}]'::jsonb FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text,internal_links=EXCLUDED.internal_links;

-- New-infrastructure test article: 2026-08-09-alebrije-bakery-return
WITH item AS (SELECT '2026-08-09-alebrije-bakery-return'::text slug,'Viral'::text category,'Beloved San Antonio Panadería Alebrije Pops Back Up After a Year Away'::text title,'Alebrije Bakery’s return at a Southtown coffee shop gives fans their first real taste of a comeback after the acclaimed bakery shut its doors in 2025.'::text dek,'San Antonio Express-News'::text source_name,'https://www.expressnews.com/news/article/alebrije-bakery-pop-coffee-shop-next-weekend-22370789.php'::text source_url,'2026-08-09T16:36:00Z'::timestamptz published_at,28::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/alebrije-bakery-return.svg'::text image_url,'Editorial illustration of colorful Mexican pastries displayed at a San Antonio coffee shop pop-up with papel picado overhead.'::text image_alt_text,$body$San Antonio food fans are getting a small but meaningful comeback from Alebrije Bakery, the acclaimed panadería that closed its Government Hill storefront in 2025. The bakery is returning through a pop-up at Poetic Republic Coffee in Southtown, bringing back the pastries and visual style that made it a favorite before financial and personal pressures forced the owners to step away. The event is not a full reopening, but after more than a year of uncertainty it is the clearest sign yet that Alebrije may have a future in a new form.

Alebrije built a following by combining Mexican baking traditions with a bright, modern presentation. Its cakes, guava-filled pastries, marranitos and other pan dulce were recognizable on a display case and on social media. That visual identity mattered, but regular customers also connected with the people behind the counter. When the bakery closed, the reaction was not simply disappointment over losing a place to buy sweets. It felt like the disappearance of a neighborhood institution that had become part of San Antonio’s evolving food scene.

Owner Cris Méndez has spoken publicly about the difficulty of keeping the business alive, including the emotional strain of using personal money to support operations and worrying about employees. That part of the story is familiar to independent restaurant owners across Texas. A popular business can still struggle with rent, labor, ingredients, debt and the unpredictable rhythm of customer traffic. Social-media attention is helpful, but it does not automatically produce a stable margin.

The pop-up model offers a different way to return. Instead of immediately taking on the full cost of a permanent storefront, Alebrije can bake for limited events, measure demand and rebuild its audience gradually. The host coffee shop provides a venue and existing customer traffic. For the bakery, that reduces risk. For Poetic Republic, it creates an event that can draw people who may become coffee-shop customers as well.

Pop-ups have become an important part of the Texas food economy because they allow chefs and bakers to test concepts without signing a long lease. Some remain temporary by design. Others become the bridge to a permanent location. In Alebrije’s case, the format can also help the team determine what kind of comeback is sustainable after the challenges of the previous shop.

The timing is especially meaningful because San Antonio’s bakery scene has become more competitive and more visible. Traditional panaderías remain essential, while younger bakers are experimenting with regional flavors, laminated pastries, specialty cakes and hybrid concepts. Alebrije was part of that new wave before its closure. A successful return would put a familiar name back into a landscape that continued changing while it was gone.

Keep TX Red’s Texas News hub follows the businesses and cultural institutions that shape local communities, while the Latest News page captures openings, returns and events as they happen. A bakery pop-up may look small beside major economic news, but independent food businesses are often where residents experience change most directly. When one disappears or returns, people notice.

The event also demonstrates the power of goodwill. A business that closes badly can lose its audience. Alebrije instead appears to have retained a core group of customers who wanted the team to come back when it was ready. That patience gives the bakery something valuable: a second launch with built-in awareness. The challenge is turning that goodwill into a model that does not recreate the financial pressure that caused the closure.

Fans should not assume the pop-up guarantees a permanent reopening. Méndez has described a gradual approach, and that is probably the healthiest interpretation. A limited event can be successful on its own even if the next step is another pop-up rather than a storefront. The point is that the ovens are working again and the team is serving customers.

There is also something characteristically San Antonio about the setting. A beloved Mexican-inspired bakery returning inside an independent Southtown coffee shop is the kind of collaboration that reflects the city’s neighborhood food culture. It is less polished than a corporate relaunch and more personal because customers know the story behind the pastries.

For Alebrije, this weekend is a test without having to feel like an all-or-nothing test. The bakery can sell what it does best, reconnect with people and learn what demand looks like after a year away. For customers, the assignment is easier: show up, buy the pastry they missed and enjoy the fact that one of San Antonio’s most colorful bakeries is back in public, even if only one weekend at a time.

The return may also be useful to other small food businesses watching from the sidelines. Closing does not always have to mean failure or finality. Sometimes the cost structure of a storefront is the problem rather than the product itself. A pop-up can preserve a brand, keep a team connected and allow an owner to rebuild without immediately taking on the same fixed expenses. That is a practical form of resilience in an industry where margins are famously thin.

Customers play a role in whether that model works. Showing up for a pop-up is different from liking a comeback post online. Limited events give supporters a direct way to convert goodwill into revenue, and they provide the bakery with real information about demand. If the lines are strong and the economics work, Alebrije can plan its next step with evidence instead of nostalgia alone.$body$::text body), prepared AS (SELECT *,replace(replace(body,'Texas News hub','[Texas News](/texas-news) hub'),'Latest News page','[Latest News](/news) page') linked_body FROM item)
INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text,internal_links) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(linked_body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',to_jsonb(string_to_array(linked_body,E'\n\n')))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — source report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)),image_url,image_url,image_alt_text,'[{"href":"/texas-news","kind":"hub","label":"Texas News"},{"href":"/news","kind":"hub","label":"Latest News"}]'::jsonb FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text,internal_links=EXCLUDED.internal_links;

-- New-infrastructure test article: 2026-08-09-daniella-guzman-kprc-return
WITH item AS (SELECT '2026-08-09-daniella-guzman-kprc-return'::text slug,'Viral'::text category,'Houston Anchor Daniella Guzman Returns to KPRC After Ticket Probe and Charity Repayment'::text title,'KPRC says its review found no evidence complimentary concert and World Cup tickets influenced Guzman’s journalism, though the station acknowledged the appearance of a conflict.'::text dek,'Houston Chronicle'::text source_name,'https://www.houstonchronicle.com/news/houston-texas/trending/article/daniella-guzman-kprc-tickets-22374351.php'::text source_url,'2026-08-09T16:37:00Z'::timestamptz published_at,32::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/daniella-guzman-kprc-return.svg'::text image_url,'Editorial illustration of a Houston television news desk with stadium tickets, a microphone and an ethics checklist.'::text image_alt_text,$body$Houston television anchor Daniella Guzman is back on the KPRC morning desk after an internal review of complimentary tickets she received for a concert and a FIFA World Cup match. The station says it found no evidence that the gifts influenced her reporting, but the episode still became a high-profile lesson in how quickly questions about journalistic ethics can become a public story of their own. Guzman acknowledged the appearance of a conflict and made a charitable donation equal to the value of the tickets.

The controversy began when reports surfaced that Guzman had received hospitality connected to the Harris County Sports & Convention Corporation, which manages NRG Stadium. The tickets included access to a Bruno Mars concert and a World Cup match during a period when Houston was receiving enormous attention as a host city. For a journalist, accepting something of substantial value from an organization that can appear in news coverage creates an obvious ethical question even if no favorable story is ever produced.

KPRC placed Guzman on leave while it reviewed the situation. That decision turned a newsroom policy matter into a broader Houston conversation because Guzman is a recognizable morning anchor with deep ties to the city. The station’s eventual conclusion was narrower than the public debate: investigators said they found no evidence her journalism had been compromised. The problem was the perception created by accepting the tickets.

That distinction is central to media ethics. A conflict of interest can exist even when nobody changes a story, kills a story or gives someone favorable coverage. News organizations often impose strict gift rules because audiences cannot see every editorial decision that happens inside a newsroom. Avoiding gifts is therefore a way to preserve trust before anyone has to investigate whether influence occurred.

Guzman’s decision to donate the value of the tickets to charity functions as a corrective rather than proof that the original acceptance was harmless. It removes the financial benefit and acknowledges that the situation should have been handled differently. KPRC’s willingness to put a prominent anchor on leave also signals that the station considered the issue serious enough to investigate publicly.

The story became especially viral because it combined celebrity, the World Cup, a major concert and local government-linked hospitality. Each element is attention-grabbing on its own. Together they produced a controversy that traveled well beyond the normal audience for newsroom policy. Keep TX Red’s Houston coverage follows stories with direct local impact, while the Texas News hub tracks media and public-trust issues across the state.

There is a wider question for Houston institutions that distribute premium tickets. Stadium authorities, sports bodies and other public or quasi-public organizations often have suites, sponsor allocations and hospitality budgets. Who receives those benefits can become controversial when recipients include elected officials, journalists, contractors or others whose work intersects with the organization. Transparency about distribution rules can reduce suspicion before it becomes a scandal.

For journalists, the lesson is old but durable: access has value. A seat in a premium suite is not the same as a press credential required to cover an event. Newsrooms generally distinguish between professional access and personal entertainment because the latter can create obligations, or at least the appearance of them. In an era of declining trust in media, appearances matter more than ever.

Guzman’s return suggests KPRC believes the incident does not warrant ending her role. Viewers will make their own judgments, and some may see the response as sufficient while others believe the station should have acted more harshly. The important point is that the process produced a public explanation. Silence would have invited more speculation.

The episode also illustrates how local anchors occupy a hybrid space between journalists and public personalities. Morning television encourages familiarity, social-media engagement and community visibility. That makes anchors valuable to stations but also increases scrutiny of their personal conduct. A private decision to accept tickets can quickly become a public ethics story because the person involved is part of the station’s brand.

Houston hosted the World Cup as a civic showcase, and the tournament generated enormous demand for tickets and VIP access. The Guzman controversy is a reminder that scarce access can carry political and ethical weight long after the match is over. For KPRC, the investigation is finished. For Texas newsrooms, the conversation about gifts, hospitality and public trust is likely to last much longer.

The case may push other Texas newsrooms to revisit their own policies. Written rules are most useful when employees know how they apply to modern forms of hospitality, including influencer-style invitations, luxury suites and promotional events. A policy drafted around accepting a free dinner can become ambiguous when a sports authority offers access worth hundreds or thousands of dollars. Clearer rules protect both journalists and their employers from having to make decisions after a controversy erupts.

Public agencies can improve the situation from the other side by publishing hospitality records proactively. If premium tickets are distributed through a consistent, documented process, residents can see who benefited and why. That kind of transparency does not eliminate ethical questions for recipients, but it reduces the chance that valuable public assets are handed out through relationships nobody can scrutinize.$body$::text body), prepared AS (SELECT *,replace(replace(body,'Houston coverage','[Houston](/houston) coverage'),'Texas News hub','[Texas News](/texas-news) hub') linked_body FROM item)
INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text,internal_links) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(linked_body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',to_jsonb(string_to_array(linked_body,E'\n\n')))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — source report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)),image_url,image_url,image_alt_text,'[{"href":"/houston","kind":"hub","label":"Houston"},{"href":"/texas-news","kind":"hub","label":"Texas News"}]'::jsonb FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text,internal_links=EXCLUDED.internal_links;