CREATE TABLE IF NOT EXISTS public.ai_rewrite_cache (
  content_fingerprint text PRIMARY KEY,
  feed_item_id bigint REFERENCES public.texas_news_feed(id) ON DELETE SET NULL,
  status text NOT NULL CHECK (status IN ('pending', 'completed', 'failed')),
  result_json jsonb,
  failure_reason text,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ai_rewrite_cache_claimed_at_idx
  ON public.ai_rewrite_cache (claimed_at DESC);

ALTER TABLE public.ai_rewrite_cache ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.ai_rewrite_cache TO service_role;

CREATE TABLE IF NOT EXISTS public.ai_rewrite_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_fingerprint text NOT NULL,
  feed_item_id bigint REFERENCES public.texas_news_feed(id) ON DELETE SET NULL,
  claimed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ai_rewrite_usage_claimed_at_idx
  ON public.ai_rewrite_usage (claimed_at DESC);

ALTER TABLE public.ai_rewrite_usage ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.ai_rewrite_usage TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ai_rewrite_usage_id_seq TO service_role;

-- Atomically reserves one paid rewrite for the current UTC day. Completed
-- fingerprints are cache hits and do not consume another slot. Failed or stale
-- attempts can be retried manually, but each new claim counts against the cap.
CREATE OR REPLACE FUNCTION public.claim_ai_rewrite_slot(
  p_content_fingerprint text,
  p_feed_item_id bigint,
  p_daily_limit integer DEFAULT 8
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing public.ai_rewrite_cache%ROWTYPE;
  v_used integer;
BEGIN
  IF p_daily_limit < 1 THEN
    RETURN 'budget_exhausted';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('ai_rewrite_daily_budget'));

  SELECT * INTO v_existing
  FROM public.ai_rewrite_cache
  WHERE content_fingerprint = p_content_fingerprint
  FOR UPDATE;

  IF FOUND AND v_existing.status = 'completed' AND v_existing.result_json IS NOT NULL THEN
    RETURN 'cached';
  END IF;

  IF FOUND
     AND v_existing.status = 'pending'
     AND v_existing.updated_at > now() - interval '15 minutes' THEN
    RETURN 'in_progress';
  END IF;

  SELECT count(*) INTO v_used
  FROM public.ai_rewrite_usage
  WHERE claimed_at >= date_trunc('day', now())
    AND claimed_at < date_trunc('day', now()) + interval '1 day';

  IF v_used >= p_daily_limit THEN
    RETURN 'budget_exhausted';
  END IF;

  INSERT INTO public.ai_rewrite_cache (
    content_fingerprint,
    feed_item_id,
    status,
    result_json,
    failure_reason,
    claimed_at,
    completed_at,
    updated_at
  )
  VALUES (
    p_content_fingerprint,
    p_feed_item_id,
    'pending',
    NULL,
    NULL,
    now(),
    NULL,
    now()
  )
  ON CONFLICT (content_fingerprint) DO UPDATE SET
    feed_item_id = EXCLUDED.feed_item_id,
    status = 'pending',
    result_json = NULL,
    failure_reason = NULL,
    claimed_at = now(),
    completed_at = NULL,
    updated_at = now();

  INSERT INTO public.ai_rewrite_usage (content_fingerprint, feed_item_id)
  VALUES (p_content_fingerprint, p_feed_item_id);

  RETURN 'claimed';
END;
$$;

REVOKE ALL ON FUNCTION public.claim_ai_rewrite_slot(text, bigint, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_ai_rewrite_slot(text, bigint, integer) TO service_role;
