-- ChatGPT auto article: Venezuelan crude surge to Texas
WITH item AS (SELECT '2026-08-09-texas-venezuelan-oil-import-surge'::text slug,'Business'::text category,'Texas Refineries Turn More to Venezuelan Crude as Middle East Supply Risks Rise'::text title,'Gulf Coast imports of Venezuelan heavy crude have surged, giving Texas refineries another supply source while Strait of Hormuz disruptions squeeze Middle Eastern flows.'::text dek,'The Texas Tribune'::text source_name,'https://www.texastribune.org/2026/07/28/texas-venezuelan-oil-imports-refineries-strait-hormuz/'::text source_url,'2026-08-09T15:32:00Z'::timestamptz published_at,34::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/texas-venezuelan-oil.svg'::text image_url,'Editorial illustration of a Gulf Coast refinery, tanker ship and crude oil route toward Texas.'::text image_alt_text,$body$Texas refineries are relying much more heavily on Venezuelan crude as instability around the Strait of Hormuz disrupts traditional Middle Eastern supply routes. Federal data cited by The Texas Tribune show average Venezuelan imports to the Gulf Coast rising from roughly 110,000 barrels per day in January to about 575,000 barrels per day in June. Texas is receiving the largest share. The shift matters because many Gulf Coast refineries were built to process heavy crude grades, and Venezuelan barrels can replace some of the supply that has become harder to obtain from countries such as Saudi Arabia and Iraq.

The Texas coast is uniquely positioned for the change. More than 10 Texas refineries are equipped to handle Venezuela’s heavier crude, and S&P Global Energy data cited in the report show Texas receiving about 43% of Venezuelan oil entering the United States this year. Louisiana has received another large share. That concentration reflects decades of investment in complex Gulf Coast refineries that can convert dense, high-sulfur crude into gasoline, diesel, jet fuel and other products. When a major source of heavy crude is interrupted, those plants cannot always replace it efficiently with the lighter oil produced in many U.S. shale fields.

The timing is tied to a broader global shock. The on-again, off-again closure of the Strait of Hormuz during the Iran conflict has sharply limited shipments that normally move from the Persian Gulf toward the United States and other markets. Texas refiners that depend on a mix of crude grades have therefore been looking for alternatives. Venezuelan production, after years of sanctions and decline, has re-entered the Gulf Coast supply picture at a moment when those barrels have unusually high strategic value.

For Texas consumers, the relationship between crude supply and pump prices is not immediate or one-to-one. Gasoline and diesel prices depend on global oil prices, refinery outages, seasonal demand, inventories, taxes and distribution costs. Still, a refinery with dependable access to the grade of crude it was designed to process can run more efficiently than one forced to scramble for substitutes. That makes diversified supply valuable even if no single tanker shipment creates a visible change at a neighborhood gas station.

The numbers also illustrate how quickly energy trade can change when geopolitics changes. The United States effectively banned Venezuelan oil imports for years under sanctions. Now Gulf Coast imports have climbed to their highest average daily volume since 2018. The policy environment around Venezuela remains unusual, and the long-term direction is not guaranteed. Analysts cited by the Tribune expect production growth to level off unless the country attracts substantial capital investment to repair and expand an oil industry that once produced far more than it does today.

That creates both an opportunity and a vulnerability for Texas. More Venezuelan crude gives refiners flexibility during a Middle East disruption, but replacing one concentrated foreign source with another does not eliminate geopolitical risk. The best protection for a refining hub is optionality: pipelines, ports, storage, contracts and refinery configurations that allow operators to switch among suppliers when markets change. The Gulf Coast’s scale is an advantage because it already has much of that infrastructure, but the current episode shows why maintaining it matters.

The surge also complicates the usual political language around American energy independence. Texas produces enormous volumes of crude oil, yet domestic shale production tends to be lighter than the heavy barrels some coastal refineries were engineered to run. The United States can therefore be a major oil producer and still import crude because the qualities of the oil matter. At the same time, the country exports other grades and refined products. That two-way trade is not necessarily a contradiction; it is a feature of a refinery system built over many decades around different feedstocks and global markets.

Port communities along the Texas coast will feel the change through tanker traffic, terminal activity and refinery operations. More imported crude can support throughput and jobs, but it also means more exposure to global shipping conditions and foreign policy decisions. The economic significance extends beyond Houston or Corpus Christi because refined fuels and petrochemical feedstocks move from the coast into supply chains across the state and nation.

The most important near-term signals are whether the Strait of Hormuz remains constrained, whether Venezuelan production continues to rise and whether Texas refiners can secure enough heavy crude without paying a large premium. If Middle Eastern flows normalize, refiners may rebalance their sourcing. If disruptions continue, Venezuelan barrels could remain an important buffer. Either way, Texas is once again demonstrating that its energy economy is global even when the wells, refineries and jobs are located inside the state.

This article is an independent Keep TX Red rewrite based on reporting published by The Texas Tribune on July 28, 2026. The report cited federal and industry data showing Gulf Coast Venezuelan crude imports rising to roughly 575,000 barrels per day in June, with Texas receiving the largest state share.$body$::text body), prepared AS (SELECT *,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — original report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)) body_json FROM item) INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;