-- Current Texas viral: DeSoto football handshake
WITH item AS (SELECT '2026-09-04-desoto-handshake-viral-backlash'::text slug,'Sports'::text category,'DeSoto Football Apologizes After Viral Handshake Snub Draws National Backlash'::text title,'DeSoto High School’s football program apologized after captains declined pregame handshakes with St. Thomas Aquinas, while the opposing coach urged the public to show the Texas teenagers grace.'::text dek,'CBS Texas / CBS Miami'::text source_name,'https://www.cbsnews.com/texas/news/desoto-football-st-thomas-aquinas-game-handshake-incident-9-1-2026/'::text source_url,'2026-09-04T23:59:00Z'::timestamptz published_at,33::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-09-04/desoto-handshake-viral.jpg'::text image_url,'high school football captains at midfield during a tense pregame handshake.'::text image_alt_text,$body$DeSoto High School's football program has apologized after video of its captains declining to shake hands with players from St. Thomas Aquinas before a nationally televised season opener spread across social media, turning a few seconds at midfield into a national argument about sportsmanship, discipline and how adults respond when teenagers make a public mistake.

The incident occurred Aug. 29 in Fort Lauderdale, Florida. Players from St. Thomas Aquinas approached the coin toss with hands extended, while DeSoto's representatives did not return the handshakes and walked away. Clips quickly circulated online, drawing criticism from football fans, parents and commentators far beyond either school community.

DeSoto football issued an apology Aug. 31, acknowledging that the moment did not reflect the program's standards. The response was appropriate. Pregame sportsmanship rituals exist for a reason: competitors can play with intensity while still recognizing the humanity of the people across from them. Refusing a basic handshake on a national broadcast invited an interpretation that the Texas team was showing disrespect.

But the story did not end with the apology. St. Thomas Aquinas coach Roger Harriott urged people to show grace to the DeSoto players rather than turning the incident into permanent condemnation. His response is worth emphasizing because the athletes at the center of the backlash are high-school students, not professional entertainers or elected officials.

Accountability and grace are not opposites. Coaches can tell players that their conduct was wrong, require them to apologize and reinforce expectations without encouraging thousands of strangers to attack teenagers online. In fact, that is one of the central purposes of school athletics: young people make mistakes in a structured environment where adults can teach them how to respond.

DeSoto is one of Texas' highest-profile football programs. That success brings extra scrutiny. Players represent their school and community when they travel, especially in nationally televised matchups. A behavior that might have been noticed by a few hundred people decades ago can now be clipped, posted and viewed millions of times before a team reaches the locker room.

Social media also strips moments of context. Viewers see a short video and fill in motives that may or may not be accurate. Perhaps the players intended disrespect; perhaps they were caught up in competitive emotion or following an ill-considered team posture. The visual itself is enough to judge the behavior, but it is not enough to know everything about the students involved.

That distinction should guide adult reaction. It is fair to say the handshake refusal was poor sportsmanship. It is not fair to use one clip to declare that the players are bad people, that their families failed or that an entire Texas community lacks character. The point of an apology is to acknowledge a wrong and create a path forward.

High school football in Texas carries cultural weight that can be hard for outsiders to understand. Programs build community identity, generate enormous local interest and create college opportunities for athletes. Coaches therefore teach much more than schemes and conditioning. They are expected to set standards for attendance, academics, discipline, public behavior and how players handle winning and losing.

Pregame rituals are a small but visible part of that education. Shaking hands does not make rivals less competitive. It establishes that the contest has boundaries. Players can hit hard within the rules and then help an opponent up. They can celebrate a victory without humiliating the other side. Those habits transfer beyond sports because most adult competition also depends on rules and mutual respect.

There is a lesson for broadcasters and online commentators too. Viral sports moments are valuable content, and outrage drives engagement. But media coverage should remember the age of the participants. Naming a school and reporting an official team response is different from encouraging targeted harassment of individual minors.

The opposing coach modeled that restraint. Harriott had every reason to defend his players, who were visibly left hanging at midfield. Instead of escalating the feud, he publicly encouraged grace. That response reinforces his own program's values more effectively than an extended exchange of insults would have.

DeSoto's apology now needs to be matched by behavior, not endless public punishment. If the captains meet future opponents respectfully and the program reinforces its expectations, the incident can become a brief lesson rather than a defining label. If similar behavior repeats, critics would have stronger grounds to argue there is a deeper culture problem.

School administrators may also consider how teams prepare for high-profile travel games. A five-minute reminder before leaving the locker room about coin-toss protocol, postgame conduct and social-media visibility can prevent avoidable controversies. Teenagers are still learning to manage adrenaline and public attention; clear expectations help.

The viral backlash reflects a broader frustration with declining civility in public life. Adults see politicians, celebrities and anonymous users insulting one another constantly, then expect teenagers to display perfect sportsmanship under pressure. Schools should hold students to high standards, but adults should be willing to model those standards when responding.

Texas football is at its best when fierce competition and respect coexist. The handshake at midfield is symbolic, but symbols matter precisely because they communicate values in a few seconds. DeSoto's captains made the wrong choice in that moment. Their program acknowledged it. The opposing coach asked the public not to turn a teachable mistake into a mob.

That should be enough to move the story toward its proper conclusion. The next measure of DeSoto's character will not be the viral clip; it will be how the team behaves after learning from it.$body$::text body), prepared AS (SELECT *,jsonb_build_object('updated','2026-09-04','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',to_jsonb(regexp_split_to_array(body,E'\n\n')))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label','CBS Texas — DeSoto football apology','url','https://www.cbsnews.com/texas/news/desoto-football-st-thomas-aquinas-game-handshake-incident-9-1-2026/'),jsonb_build_object('label','CBS Miami — St. Thomas Aquinas coach urges grace','url','https://www.cbsnews.com/miami/news/desoto-football-st-thomas-aquinas-game-handshake-incident-coach-speaks/')),'keyTakeaways',jsonb_build_array(dek)) body_json FROM item) INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;