-- ChatGPT auto article: Texas community college funding gap
WITH item AS (
SELECT '2026-08-09-texas-community-college-funding-gap'::text slug,'Education'::text category,'Texas Community Colleges Brace for Cuts as Performance Funding Outruns the State Budget'::text title,'Colleges earned more outcome-based funding than lawmakers budgeted, forcing proration and putting hiring, advising and other local spending under pressure.'::text dek,'The Texas Tribune'::text source_name,'https://www.texastribune.org/2026/07/28/texas-community-college-funding-shortfalls/'::text source_url,'2026-08-09T15:30:00Z'::timestamptz published_at,31::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/community-college-funding.svg'::text image_url,'Editorial illustration of a Texas community college campus beside a shrinking budget chart.'::text image_alt_text,$body$Texas community colleges are confronting an awkward consequence of the state’s new performance-based funding system: schools produced more of the student outcomes Texas said it wanted, but the state did not appropriate enough money to pay the full amount those results generated. College leaders told a Texas Senate committee that the shortfall is already being translated into local budget decisions, including pressure on hiring, faculty support and advising. The issue is not that colleges missed their targets. It is that the formula produced a larger statewide obligation than lawmakers had funded, forcing the Texas Higher Education Coordinating Board to reduce, or prorate, what individual colleges receive.

That distinction matters because Texas intentionally redesigned community-college finance around outcomes rather than simply enrollment. The model rewards schools when students complete credentials, transfer successfully or reach other milestones that lawmakers believe should lead to better jobs and stronger regional economies. In theory, the incentive is straightforward: colleges that help more students finish valuable programs should receive more state support. The early years of the system are now exposing the budget risk built into that promise. If student success rises faster than the appropriation behind the formula, the same schools that improve performance can still find themselves planning cuts.

San Jacinto College President Brenda Hellyer described the practical effect during the legislative hearing, saying a funding gap quickly becomes a question of salaries and services such as advising. That is especially significant for community colleges because their students often rely on hands-on support to navigate work schedules, family responsibilities, financial aid and the transition into technical programs or universities. Advising is not an abstract administrative expense for those students. It can determine whether a student selects the right courses, remains eligible for aid, completes a credential on time or leaves school after accumulating credits that do not lead anywhere.

The funding pressure also reaches beyond individual campuses. Texas has leaned heavily on community colleges to supply nurses, technicians, welders, cybersecurity workers, advanced-manufacturing employees and other occupations that employers say are difficult to fill. Many of those programs are expensive to operate because they require specialized instructors, laboratories, equipment and relatively small class sizes. A budget model that becomes unpredictable from year to year makes it harder for colleges to add capacity precisely where local employers are asking for more trained workers. That can turn a state finance problem into a workforce-development problem.

There is a reasonable argument on the other side of the ledger. State budgets are finite, and an outcomes formula cannot function as an unlimited promise without some mechanism to keep spending within the amount lawmakers approved. Proration is one way to preserve budget discipline when actual results exceed forecasts. The problem is one of expectations. If colleges are told to make investments in order to improve completions and then learn afterward that the dollars attached to those completions will be reduced, administrators have less confidence that they can make the same investments again the next year.

For taxpayers, the most important question is whether the formula is calibrated well enough to reward performance without creating recurring surprise deficits. Lawmakers could respond by increasing appropriations, changing the dollar value attached to outcomes, building a reserve into the system, or using more conservative forecasts when they write the budget. Each option has tradeoffs. More money requires finding room elsewhere in the state budget. Lower reward values weaken the incentive. A reserve could help smooth good years and bad years but would need clear rules so schools know what to expect.

The dispute is also a reminder that performance funding changes behavior only when institutions believe the rules will remain dependable. A college planning a new nursing cohort or industrial technology program may need to hire faculty and buy equipment before the first student ever earns a credential. Those commitments are difficult to reverse quickly. If state payments can swing because aggregate statewide performance was stronger than expected, individual colleges may become more cautious about expansion even when their regions need it. That would work against the original goal of tying public dollars more closely to student and workforce outcomes.

Texas lawmakers now have actual operating data they did not have when the redesigned system was created. That is useful. Early shortfalls do not automatically mean the model is broken, but they do show where forecasts and appropriations failed to match reality. The next budget debate should therefore focus not only on how much money colleges receive, but on whether the state can make the payment rules predictable enough for presidents and boards to plan multi-year programs. A performance system is strongest when a school can estimate what a successful student outcome will actually be worth.

For students, the immediate stakes are simpler: whether classes are available, instructors are hired, advisers have manageable caseloads and career programs can keep pace with employer demand. Community colleges serve a large share of Texans who need an affordable route into a credential or a four-year degree. When state finance becomes unstable, those students often feel the effect through reduced services long before the mechanics of the funding formula become widely understood. The legislative review gives Texas a chance to correct that mismatch before temporary belt-tightening becomes a structural feature of the system.

This article is an independent Keep TX Red rewrite based on reporting published by The Texas Tribune on July 28, 2026. The underlying report described testimony from community-college leaders and the state’s decision to prorate outcome-based payments after student performance exceeded the projections used to build the budget.$body$::text body
), prepared AS (SELECT *,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — original report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)) body_json FROM item)
INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text)
SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text FROM prepared
ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;