-- Daily Texas news batch for 2026-08-08. Original Keep TX Red rewrites with unique hero images.

WITH items(slug,category,title,dek,source_name,source_url,published_at,score,is_breaking,image_url,image_alt_text,body) AS (VALUES
('2026-08-08-san-antonio-arena-ballot-fight','Texas News','San Antonio Council Pushes Back on Mayor’s Bid to Revisit Spurs Arena Funding','Mayor Gina Ortiz Jones is pressing for new ballot questions tied to arena financing and Ready to Work funds, but several council members and civic groups argue voters have already spoken.','San Antonio Express-News','https://www.expressnews.com/news/article/san-antonio-mayor-spurs-ready-to-work-votes-22378954.php','2026-08-08T13:10:00Z'::timestamptz,27,TRUE,'/images/news/generated/2026-08-08/san-antonio-arena-ballot.svg','Illustrated arena and civic plaza representing San Antonio''s debate over Spurs arena financing.','San Antonio’s fight over the proposed downtown Spurs arena is entering another political phase as Mayor Gina Ortiz Jones urges the City Council to place new funding questions before voters. The dispute centers on whether the city should revisit commitments connected to the planned arena and whether remaining money from the voter-approved Ready to Work job-training program should be redirected. The mayor says the city’s projected budget gap requires another public decision. Critics say the proposal would reopen questions voters and elected officials have already settled.

The arena plan is part of a larger downtown development strategy built around a new home for the San Antonio Spurs. County voters previously approved $311 million toward the roughly $1.3 billion project, while the city has been considering additional financing tools. Jones has raised concerns about issuing hundreds of millions of dollars in city debt while San Antonio faces a projected $158 million budget deficit. Her proposal would ask voters whether to authorize up to $489 million in bonds tied to the arena and related work.

The political problem for the mayor is that several council members, business leaders and community organizations say another election would create uncertainty around a project that has already moved through multiple public votes and council actions. They argue that the arena package and Ready to Work program each received direct voter approval and that overturning or redirecting those commitments should not become a routine response to budget pressure. Supporters of the mayor’s approach counter that changing financial conditions justify giving taxpayers another say before long-term obligations are locked in.

Ready to Work has become a separate flashpoint. The sales-tax-funded workforce program was designed to help residents obtain training and credentials for higher-paying jobs. Jones has suggested asking voters to allow remaining funds to be used for other qualified projects, while opponents say the program is only now beginning to show stronger placement results and should be allowed to continue as approved. That disagreement has broadened the arena fight into a larger debate about whether San Antonio should protect dedicated voter-approved programs when city finances tighten.

The City Council is expected to consider the mayor’s ballot proposal before the August 17 deadline for November election items. At the moment, Jones appears to lack a clear council majority. That could change as public meetings and lobbying continue, but the next several days will determine whether San Antonio voters see another arena-related question this fall or whether the current financing path stays intact. For taxpayers, the practical issues are the size of the city’s debt exposure, the future of the workforce program and whether another election would clarify the debate or simply reopen it. This article is an independent Keep TX Red rewrite based on reporting from the San Antonio Express-News.'),
('2026-08-08-south-texas-career-training-grants','Education','Texas Awards $1.69 Million in Career-Training Grants to Seven South Texas Schools','Seven South Texas schools will receive Jobs and Education for Texans grants for equipment used in high-demand technical and career programs.','Office of the Texas Governor','https://gov.texas.gov/news/post/governor-abbott-announces-over-1.6-million-in-career-training-grants-for-south-texas-schools','2026-08-08T13:11:00Z'::timestamptz,24,FALSE,'/images/news/generated/2026-08-08/south-texas-career-grants.svg','Illustrated South Texas technical school building representing new career-training grants.','Seven South Texas schools are receiving a combined $1.69 million in Jobs and Education for Texans grants, giving local career and technical education programs new money for equipment used to train students for high-demand occupations. Gov. Greg Abbott announced the awards through the Texas Workforce Commission, describing the grants as part of the state’s effort to connect classrooms with employers that need skilled workers.

The JET program is designed to help public community colleges, technical institutes, school districts and charter schools buy equipment for career programs that lead students toward recognized credentials and jobs. Unlike broad operating grants, JET awards are typically tied to specific workforce programs and equipment needs. That can mean machinery, medical training equipment, welding systems, laboratory tools, information-technology hardware or other specialized assets that schools often struggle to purchase through normal budgets.

For South Texas, the grants matter because many communities are trying to expand career pathways without requiring every student to pursue a four-year degree. Employers in health care, advanced manufacturing, construction, energy, transportation and other technical fields routinely report demand for workers with certifications and practical training. A school that can put industry-standard equipment in front of students gives those students a better chance to leave with experience that translates directly to a job or apprenticeship.

The awards also fit a larger Texas strategy of using workforce programs to support regional economic development. When a company considers expanding in a smaller city, the availability of trained workers can be as important as taxes, land or infrastructure. Career programs give local leaders a way to show employers that the labor pipeline is being built alongside new business recruitment. For students, the benefit is more immediate: access to expensive equipment while still in school can shorten the path between graduation and a paycheck.

The governor’s office said the seven grants total $1,692,417. Schools receiving the funds will be responsible for putting the equipment into approved training programs and serving the student populations described in their applications. Texans should watch not only the amount of money distributed but also the number of students who complete credentials, enter related jobs and remain in the region after training. Those outcomes will determine whether the grants become a one-time equipment purchase or a durable workforce investment for South Texas. This article is an independent Keep TX Red rewrite based on the governor’s announcement.'),
('2026-08-08-south-texas-drought-heat','Weather','South Texas Drought Deepens as Laredo’s Dry Stretch Extends Into August','Laredo and several other South Texas cities are seeing persistent dry conditions, with triple-digit heat and little meaningful rain in the near-term forecast.','Laredo Morning Times','https://www.lmtonline.com/local/article/temperature-high-low-thunder-storm-weather-nws-22378872.php','2026-08-08T13:12:00Z'::timestamptz,26,TRUE,'/images/news/generated/2026-08-08/south-texas-drought.svg','Illustrated cracked South Texas landscape and shrinking water channel representing drought and extreme heat.','South Texas is moving deeper into August with another stretch of punishing heat and limited rainfall, extending drought concerns from Laredo toward Corpus Christi, San Antonio, Austin and Brownsville. Laredo has gone more than two weeks without measurable rain after a wetter start to the summer, and forecasters do not expect a meaningful break in the pattern in the immediate forecast.

The dry spell is notable because June delivered substantial rainfall to parts of the region. Laredo recorded more than five inches during the month, including a heavy mid-June event. Since then, the pattern has shifted sharply. Rain totals over roughly the past month and a half have been sparse, allowing soil moisture to drop and heat to build. The city’s last significant rainfall came in late July, and the current streak could approach three weeks if the forecast holds.

Temperatures are adding pressure. July averaged well above normal in Laredo, with average daytime highs above 100 degrees. Early August has remained even hotter, including unusually warm overnight lows. Those high minimum temperatures matter because they give homes, infrastructure, livestock and the human body less time to recover after daytime heat. Prolonged warm nights are one of the more dangerous features of extended summer heat events.

The drought picture is not limited to one city. South Texas communities are watching reservoir levels, municipal water demand, agricultural conditions and wildfire fuels. Corpus Christi has already spent years managing water-supply concerns, while ranchers and farmers across the region remain sensitive to changes in pasture conditions and soil moisture. Even isolated thunderstorms can provide temporary relief without meaningfully reversing a longer-term deficit.

Forecasters expect temperatures around 101 to 103 degrees in Laredo through the weekend and early next week, with breezy conditions at times. That combination can accelerate evaporation and dry vegetation. Residents should continue to follow local water restrictions and heat guidance, especially for outdoor work and recreation. A few scattered storms elsewhere in South Texas could develop, but the larger pattern still favors heat and limited widespread rainfall. The key question for the second half of August is whether the ridge of high pressure breaks often enough to allow Gulf moisture and storm systems to reach the region. This article is an independent Keep TX Red rewrite based on reporting from the Laredo Morning Times.'),
('2026-08-08-houston-school-return-storms-wbgt','Houston','Houston’s Back-to-School Weekend Brings Storm Chances and New Heat-Safety Rules','Afternoon thunderstorms may interrupt the final weekend before classes resume, while a new UIL heat metric will shape outdoor practices as students return.','Houston Chronicle','https://www.houstonchronicle.com/news/houston-weather/forecast/article/houston-afternoon-storms-before-school-year-starts-22378140.php','2026-08-08T13:13:00Z'::timestamptz,25,FALSE,'/images/news/generated/2026-08-08/houston-back-to-school-storms.svg','Illustrated school beneath storm clouds and lightning representing Houston''s back-to-school weather and heat-safety concerns.','Houston families heading into the final weekend before the school year begins are facing a familiar August combination: oppressive humidity, heat indices above 100 degrees and a chance of afternoon thunderstorms. The weather is not expected to become a washout, but storms could disrupt outdoor plans, youth sports, band practices and travel as students prepare to return to class.

Saturday is expected to begin warm and muggy with partial sunshine. As temperatures rise and the Gulf sea breeze pushes inland, scattered thunderstorms may develop during the afternoon, especially across southern parts of Southeast Texas. Any storm that forms could produce locally heavy rain, gusty winds and frequent lightning. Because summer thunderstorms are often highly localized, one neighborhood may stay dry while another sees a brief downpour.

The timing is especially relevant for school activities because the University Interscholastic League is using Wet Bulb Globe Temperature, or WBGT, as the required heat-safety measure for outdoor practices. WBGT accounts for more than the air temperature. It incorporates humidity, direct sunlight and wind to estimate the actual stress athletes and marching-band students experience. That can lead to activity restrictions even on days when the official temperature does not look extraordinary.

Houston-area schools and coaches will have to balance two different weather risks at once: heat before storms arrive and lightning or heavy rain once convection develops. Heat index values could climb beyond 100 degrees before afternoon storms offer any relief. When thunder is heard, outdoor activities generally need to move indoors regardless of how close a scheduled practice or event is to completion.

The unsettled pattern may continue into early next week as deeper Gulf moisture spreads into the region. For families, the practical advice is straightforward: build extra time into outdoor plans, keep water available, monitor radar and school communications, and do not assume a cloudy sky eliminates heat danger. The new WBGT rules will make heat decisions more standardized across Texas athletics, but they may also surprise parents accustomed to judging practice conditions by temperature alone. This weekend offers an early preview of how Houston schools will manage the combination of heat, humidity and fast-developing summer storms. This article is an independent Keep TX Red rewrite based on reporting from the Houston Chronicle.'),
('2026-08-08-tamu-fort-worth-campus-milestone','Business','Texas A&M Opens First Building at $1.5 Billion Fort Worth Campus','The new Law & Education Building is open, and construction is beginning on an 11-story research tower intended to anchor a major downtown innovation district.','Chron','https://www.chron.com/texas/article/texas-a-m-fort-worth-campus-22375370.php','2026-08-08T13:14:00Z'::timestamptz,29,FALSE,'/images/news/generated/2026-08-08/tamu-fort-worth-campus.svg','Illustrated modern university towers representing Texas A&M''s new Fort Worth campus.','Texas A&M has opened the first major building at its expanding Fort Worth campus, marking a visible milestone in a project expected to reshape part of southeast downtown. The eight-story Law & Education Building gives the university system a permanent academic anchor in the city while work begins on the next phase of a campus whose total investment is projected at roughly $1.5 billion.

The new 228,000-square-foot building will host programs from Texas A&M University and Tarleton State University as well as several Texas A&M System agencies. The mix includes law, engineering, health-related programs, business and other professional fields. The goal is to place students, researchers and public agencies near one another in a downtown setting that can also connect directly with private employers.

Officials also broke ground on an 11-story Research & Innovation Building. That facility is expected to focus on partnerships in aerospace, engineering, biotechnology, transportation and other research-intensive industries. The campus is being developed as part of the broader Switchyard Innovation District, a concept intended to combine education, applied research and entrepreneurship rather than operate as a traditional isolated university campus.

The economic-development pitch is significant for Fort Worth. North Texas continues to add residents and employers, but the region also competes nationally for research investment and highly skilled workers. A major university presence downtown can support legal education, engineering talent and technology commercialization while giving companies another reason to locate offices and laboratories nearby. Texas A&M has projected that the completed campus could eventually support more than 25,000 jobs and generate billions of dollars in annual economic activity.

The full buildout is expected to continue through 2029. The immediate test will be whether the new campus attracts the kind of industry partnerships and student demand envisioned by planners. If it does, Fort Worth could gain something more than additional university classrooms: a dense research and professional district tied to one of the largest public university systems in the country. For Texas taxpayers and local leaders, the coming years will show whether the scale of the investment produces the promised workforce, research and economic-development returns. This article is an independent Keep TX Red rewrite based on reporting from Chron.'),
('2026-08-08-mission-texas-bat-colony','Viral','A Huge Bat Colony in Mission Is Becoming One of South Texas’ Most Surprising Nighttime Attractions','Hundreds of residents are gathering to watch Mexican free-tailed bats pour from a Rio Grande Valley roost in synchronized waves.','MySA','https://www.mysanantonio.com/news/south-texas/article/mission-mexican-free-tailed-bats-22363363.php','2026-08-08T13:15:00Z'::timestamptz,23,FALSE,'/images/news/generated/2026-08-08/mission-bat-colony.svg','Illustrated moonlit sky filled with Mexican free-tailed bats over South Texas.','Mission, Texas, is developing an unlikely evening attraction: a massive colony of Mexican free-tailed bats that erupts from a local roost in waves as the sun goes down. The spectacle has become a community event in the Rio Grande Valley, drawing families, naturalists and curious residents who might otherwise travel hours to watch the better-known bat flights in Austin or San Antonio.

The colony has occupied the area for years, but local advocacy has helped turn it into a destination. Mission resident Mindy Schroeder Brown has spent more than a decade documenting and promoting the bats, building an online community and organizing educational gatherings. At a recent meetup, more than 200 people arrived to watch the emergence while volunteers and Texas Master Naturalists explained what the animals were doing.

One of the most surprising details is where the bats actually roost. Visitors may expect a huge cave or the underside of a bridge, but many of these bats squeeze into narrow crevices along concrete wing walls. The colony is largely made up of mothers and young bats during the migration season. As the evening air cools, they begin leaving in dense groups, creating swirling formations sometimes described by bat watchers as cauldrons.

Mexican free-tailed bats are familiar across Texas, but large urban or suburban colonies have a special ability to become local landmarks. Austin’s Congress Avenue Bridge is the best-known example, while Bracken Cave near San Antonio holds one of the world’s largest bat colonies. Mission’s emerging attraction gives the Rio Grande Valley its own version of that experience, with the added appeal of a community-driven gathering rather than a heavily commercialized event.

The viral appeal is easy to understand. The flight is dramatic, free to watch and different every night depending on weather and the behavior of the colony. It also gives residents a chance to learn why bats matter to Texas ecosystems, particularly as insect predators. Organizers are encouraging viewers to respect the roost and avoid disturbing the animals. If interest keeps growing, Mission could find itself with a new piece of South Texas identity: a sunset bat show that residents once drove north to see. This article is an independent Keep TX Red rewrite based on reporting from MySA.'),
('2026-08-08-tomball-isd-athletics-heat-upgrades','Viral','Tomball ISD Plans $91 Million in Athletic Upgrades as Extreme Heat Reshapes Texas Sports','New turf, lighting and indoor multiprogram facilities are intended to keep practices moving when heat and storms make outdoor fields unusable.','Chron','https://www.chron.com/sports/highschool/article/tomball-isd-athletic-upgrades-heat-22379005.php','2026-08-08T13:16:00Z'::timestamptz,24,FALSE,'/images/news/generated/2026-08-08/tomball-athletics-upgrades.svg','Illustrated Texas football field and stadium representing Tomball ISD''s major athletic-facility upgrades.','Tomball ISD is moving ahead with roughly $91 million in athletic-facility improvements, including new turf fields, lighting and large indoor practice centers. The scale of the investment has attracted attention well beyond the district because it shows how Texas school systems are adapting football and other outdoor activities to extreme heat and unpredictable weather.

About $14 million of the work will upgrade existing facilities at Tomball Memorial High School and four junior highs. Plans include synthetic turf football fields, energy-efficient LED lighting, improved tracks, storage, a new press box and changes to baseball, softball and gym facilities. Construction on those projects is expected to begin in early 2027 and take several months.

The larger investment is approximately $76.7 million for Multiprogram Activity Centers at the district’s three high schools. These indoor facilities are expected to include 80-yard turf fields and enough flexible space for football, band and other programs to practice when outdoor conditions are unsafe. Completion is planned for 2029.

Weather is a major reason the proposal resonates. Texas schools are operating under updated UIL heat-safety rules that rely on Wet Bulb Globe Temperature, a measure that incorporates humidity, sunlight and wind. Tomball officials have said weather disrupted a large share of district activities in 2024. Indoor space gives coaches and directors an alternative to canceling or repeatedly rescheduling when heat, lightning or heavy rain make outdoor practice risky.

The spending will still invite debate over priorities, especially in a fast-growing suburban district where classrooms, transportation and staffing compete for capital dollars. Supporters will point to the number of students who use athletic and multipurpose facilities, not just varsity football players. Critics may question whether the price tag is justified. Either way, Tomball’s plan illustrates a broader Texas trend: school construction is increasingly being designed around climate and heat-safety constraints that were once treated as occasional disruptions. In that sense, the project is as much about keeping school programs operational as it is about building better stadiums. This article is an independent Keep TX Red rewrite based on reporting from Chron.'),
('2026-08-08-tamu-texarkana-athletics-complex','Viral','Texas A&M-Texarkana’s $35 Million Sports Complex Will Add a 6,000-Seat Football Stadium','The growing Division II program is building new on-campus baseball, softball and football facilities ahead of its 2027 football debut.','Chron','https://www.chron.com/sports/college/article/tamu-texarkana-athletics-complex-22353880.php','2026-08-08T13:17:00Z'::timestamptz,22,FALSE,'/images/news/generated/2026-08-08/tamu-texarkana-athletics.svg','Illustrated college football stadium and athletic complex representing Texas A&M-Texarkana''s expansion.','Texas A&M University-Texarkana is making a $35 million bet on athletics as the school expands its Division II profile and prepares to launch football. The Red River Credit Union Athletic Complex will give the university permanent on-campus homes for several sports and add a 6,000-seat football stadium before the Eagles begin play in fall 2027.

The project is notable because baseball and softball will move onto campus rather than relying on off-site facilities. Plans include new fields with synthetic turf, locker rooms, press areas and support spaces. Tennis courts, a sports-performance center, food service and event space are also part of the broader complex.

Football is the biggest attention-grabber. The new program will become the university’s 22nd varsity sport, giving Texarkana another college football presence and creating a new recruiting and game-day identity for the campus. A 6,000-seat stadium is modest by major-college standards but significant for a developing Division II program. It gives the school room to build local attendance without starting with a facility that is too large to fill consistently.

The first phase is estimated at about $18 million, with the larger complex expected to be completed in stages. The project also includes an unusual public-safety component: a partnership with the Texas Division of Emergency Management for a tornado safe room. That feature reflects the campus’s location in a part of Texas where severe thunderstorms and tornadoes are a recurring risk.

For the university, the real return will be measured in enrollment, recruiting and community engagement. Athletic departments at smaller universities often serve as front doors for prospective students and alumni, especially when a new football program generates regional attention. The complex also creates spaces that can host events beyond varsity competition. If the investment works as planned, Texas A&M-Texarkana will enter 2027 with more than a new team. It will have a substantially different physical campus and a much larger athletic presence in northeast Texas. This article is an independent Keep TX Red rewrite based on reporting from Chron.'),
('2026-08-08-south-padre-horned-lizard','Viral','A Texas Horned Lizard Turned Up in the Gulf — and Even Experts Aren’t Sure Why','A South Padre Island resident thought she had found a toad in the surf before realizing it was one of Texas’ most recognizable threatened reptiles.','Chron','https://www.chron.com/wildlife/article/texas-horned-lizard-south-padre-island-22357969.php','2026-08-08T13:18:00Z'::timestamptz,25,FALSE,'/images/news/generated/2026-08-08/south-padre-horned-lizard.svg','Illustrated Texas horned lizard at the edge of the Gulf surf on South Padre Island.','A South Padre Island beach walk produced one of the stranger Texas wildlife encounters of the summer when a resident spotted what appeared to be a small toad struggling in the Gulf surf. The animal turned out to be a Texas horned lizard, the spiny reptile many Texans grew up calling a horny toad.

Jennifer Gomes found the animal waterlogged and sluggish near the shoreline. After moving it out of the surf, she posted a photograph online and learned that the creature was a Texas horned lizard. The species is listed as threatened in Texas and has disappeared from many places where it was once common, making any close encounter noteworthy.

The mystery is how the lizard ended up in the water. Experts say Texas horned lizards do occur on barrier islands, including South Padre, so the animal’s presence on the island itself was not impossible. What is unusual is finding one in active surf. Herpetologists suggested several possibilities: it may have been washed from a dune or embankment, carried by runoff, or simply wandered too close to the water and been caught by a wave.

After the lizard recovered, Gomes released it in brushy habitat farther inland. Wildlife experts generally advise moving a stressed horned lizard away from direct surf and into suitable nearby cover rather than transporting it long distances. The animals depend on specific habitat and food sources, including ants, and relocation far from where they were found can create additional problems.

The story spread because the Texas horned lizard has an outsized place in state culture. Its flattened body, crown of horns and unusual defenses make it instantly recognizable, and older Texans often remember seeing them in yards and vacant lots before populations declined. Habitat loss, pesticide use and changes in ant communities have all been associated with that decline. This South Padre encounter does not mean the species is suddenly rebounding statewide, but it is a reminder that pockets of suitable habitat remain — sometimes in places where beachgoers least expect to find one. This article is an independent Keep TX Red rewrite based on reporting from Chron.'),
('2026-08-08-fluffy-iglesias-san-antonio-netflix','Viral','Gabriel ‘Fluffy’ Iglesias Will Film His 10th Netflix Special in San Antonio','The comedian is returning to the Alamo City on August 20 for a milestone taping after a planned San Antonio recording was derailed five years ago.','MySA','https://www.mysanantonio.com/entertainment/article/gabriel-fluffy-iglesias-san-antonio-netflix-22365122.php','2026-08-08T13:19:00Z'::timestamptz,23,FALSE,'/images/news/generated/2026-08-08/fluffy-san-antonio-netflix.svg','Illustrated comedy stage and spotlight representing Gabriel Iglesias filming a Netflix special in San Antonio.','Gabriel Fluffy Iglesias is bringing a milestone comedy taping to San Antonio, where he plans to record his 10th Netflix special on August 20. The announcement immediately drew attention from local fans because the city was supposed to host one of his taped performances years ago before the plan was disrupted when Iglesias contracted COVID-19.

Iglesias announced the San Antonio date in a social-media video that also introduced fans to his new Chihuahua, Bronco. He told followers that returning to the Alamo City should not be a surprise given the abandoned 2021 plans. Tickets went on sale through his official site, setting up a one-night event that will eventually reach a much larger streaming audience.

The comedian has built a strong relationship with San Antonio despite being a California native. He has repeatedly performed in the city, visited local restaurants and interacted with fans in public. At past appearances he has spoken warmly about the region, and local audiences have treated him as a familiar visitor rather than a touring celebrity making a one-off stop.

The announcement also folded in another piece of San Antonio internet culture when Iglesias referenced a viral local song that has circulated on TikTok. That helped the video travel beyond his core comedy audience and gave the taping a distinctly local feel. Netflix specials often use city-specific crowd energy and references, so San Antonio fans will be watching to see how much of the final show reflects the location.

For the city, a major streaming comedy taping is a small but meaningful entertainment win. It puts a recognizable San Antonio audience and venue in front of viewers around the world while adding to the city’s growing list of film, television and live-event productions. For Iglesias, the show closes a five-year loop. The Alamo City date that fell apart in 2021 is now becoming the setting for a career milestone, and that backstory is a large part of why the event has generated so much local excitement. This article is an independent Keep TX Red rewrite based on reporting from MySA.')
), prepared AS (
SELECT *, jsonb_build_object('updated','2026-08-08','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — original report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)) AS body_json FROM items
)
INSERT INTO public.daily_articles (slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text)
SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text FROM prepared
ON CONFLICT (slug) DO UPDATE SET internal_url=EXCLUDED.internal_url,is_ingested=EXCLUDED.is_ingested,category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,kind=EXCLUDED.kind,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;
