-- Separate automated rewrite budgeting from explicit admin publishing.
-- Automated rewrites are capped at 25 successful rewrites per UTC day.
-- Manual admin requests receive a short-lived, one-time bypass marker.
-- Failed AI rewrites are recorded separately and removed from budget usage.

CREATE TABLE IF NOT EXISTS public.ai_rewrite_manual_bypass (
  feed_item_id bigint PRIMARY KEY REFERENCES public.texas_news_feed(id) ON DELETE CASCADE,
  granted_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '10 minutes')
);

ALTER TABLE public.ai_rewrite_manual_bypass ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.ai_rewrite_manual_bypass TO service_role;

CREATE TABLE IF NOT EXISTS public.ai_rewrite_failures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_fingerprint text NOT NULL,
  feed_item_id bigint REFERENCES public.texas_news_feed(id) ON DELETE SET NULL,
  failure_reason text,
  failed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ai_rewrite_failures_failed_at_idx
  ON public.ai_rewrite_failures (failed_at DESC);

ALTER TABLE public.ai_rewrite_failures ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.ai_rewrite_failures TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ai_rewrite_failures_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.grant_manual_ai_rewrite_bypass(
  p_feed_item_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_feed_item_id IS NULL OR p_feed_item_id < 1 THEN
    RAISE EXCEPTION 'p_feed_item_id must be positive'
      USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.ai_rewrite_manual_bypass (feed_item_id, granted_at, expires_at)
  VALUES (p_feed_item_id, now(), now() + interval '10 minutes')
  ON CONFLICT (feed_item_id) DO UPDATE SET
    granted_at = now(),
    expires_at = now() + interval '10 minutes';
END;
$$;

REVOKE ALL ON FUNCTION public.grant_manual_ai_rewrite_bypass(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.grant_manual_ai_rewrite_bypass(bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.claim_ai_rewrite_slot(
  p_content_fingerprint text,
  p_feed_item_id bigint,
  p_daily_limit integer DEFAULT 25
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing public.ai_rewrite_cache%ROWTYPE;
  v_used integer;
  v_manual boolean := false;
  v_effective_limit integer;
BEGIN
  IF p_content_fingerprint IS NULL OR btrim(p_content_fingerprint) = '' THEN
    RAISE EXCEPTION 'p_content_fingerprint must not be empty'
      USING ERRCODE = '22023';
  END IF;

  -- The production automated allowance is 25. Preserve the ability to raise
  -- it through configuration, but never allow stale callers still passing 8
  -- to reduce the intended limit.
  v_effective_limit := LEAST(50, GREATEST(25, COALESCE(p_daily_limit, 25)));

  PERFORM pg_advisory_xact_lock(hashtext('ai_rewrite_daily_budget'));

  DELETE FROM public.ai_rewrite_manual_bypass
  WHERE expires_at <= now();

  SELECT * INTO v_existing
  FROM public.ai_rewrite_cache
  WHERE content_fingerprint = p_content_fingerprint
  FOR UPDATE;

  IF FOUND
     AND v_existing.status = 'completed'
     AND v_existing.result_json IS NOT NULL THEN
    DELETE FROM public.ai_rewrite_manual_bypass
    WHERE feed_item_id = p_feed_item_id;
    RETURN 'cached';
  END IF;

  IF FOUND
     AND v_existing.status = 'pending'
     AND v_existing.updated_at > now() - interval '15 minutes' THEN
    RETURN 'in_progress';
  END IF;

  DELETE FROM public.ai_rewrite_manual_bypass
  WHERE feed_item_id = p_feed_item_id
    AND expires_at > now()
  RETURNING true INTO v_manual;

  IF NOT COALESCE(v_manual, false) THEN
    SELECT count(*) INTO v_used
    FROM public.ai_rewrite_usage
    WHERE claimed_at >= date_trunc('day', now())
      AND claimed_at < date_trunc('day', now()) + interval '1 day';

    IF v_used >= v_effective_limit THEN
      RETURN 'budget_exhausted';
    END IF;
  END IF;

  INSERT INTO public.ai_rewrite_cache (
    content_fingerprint,
    feed_item_id,
    status,
    result_json,
    failure_reason,
    claimed_at,
    completed_at,
    updated_at
  )
  VALUES (
    p_content_fingerprint,
    p_feed_item_id,
    'pending',
    NULL,
    NULL,
    now(),
    NULL,
    now()
  )
  ON CONFLICT (content_fingerprint) DO UPDATE SET
    feed_item_id = EXCLUDED.feed_item_id,
    status = 'pending',
    result_json = NULL,
    failure_reason = NULL,
    claimed_at = now(),
    completed_at = NULL,
    updated_at = now();

  IF NOT COALESCE(v_manual, false) THEN
    INSERT INTO public.ai_rewrite_usage (content_fingerprint, feed_item_id)
    VALUES (p_content_fingerprint, p_feed_item_id);
  END IF;

  RETURN CASE WHEN COALESCE(v_manual, false) THEN 'claimed_manual' ELSE 'claimed' END;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_ai_rewrite_slot(text, bigint, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_ai_rewrite_slot(text, bigint, integer) TO service_role;

COMMENT ON FUNCTION public.claim_ai_rewrite_slot(text, bigint, integer) IS
  'Atomically claims an AI rewrite. Automated successful rewrites are limited to 25 per UTC day; explicit admin requests bypass the automated allowance.';

CREATE OR REPLACE FUNCTION public.record_failed_ai_rewrite()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_usage_id bigint;
BEGIN
  IF NEW.status = 'failed' AND OLD.status IS DISTINCT FROM 'failed' THEN
    INSERT INTO public.ai_rewrite_failures (
      content_fingerprint,
      feed_item_id,
      failure_reason,
      failed_at
    )
    VALUES (
      NEW.content_fingerprint,
      NEW.feed_item_id,
      NEW.failure_reason,
      now()
    );

    SELECT id INTO v_usage_id
    FROM public.ai_rewrite_usage
    WHERE content_fingerprint = NEW.content_fingerprint
    ORDER BY claimed_at DESC, id DESC
    LIMIT 1;

    IF v_usage_id IS NOT NULL THEN
      DELETE FROM public.ai_rewrite_usage WHERE id = v_usage_id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ai_rewrite_cache_record_failure ON public.ai_rewrite_cache;
CREATE TRIGGER ai_rewrite_cache_record_failure
AFTER UPDATE OF status ON public.ai_rewrite_cache
FOR EACH ROW
EXECUTE FUNCTION public.record_failed_ai_rewrite();

COMMENT ON TABLE public.ai_rewrite_failures IS
  'Failed AI rewrite attempts. Failures are tracked independently and do not consume the automated daily success allowance.';
