-- Daily Texas news batch: five major stories and five viral stories.
-- Original Keep TX Red rewrites, deduplicated against the August 8 chat-created batches.

WITH items(slug,category,title,dek,source_name,source_url,published_at,score,is_breaking,image_url,image_alt_text,body) AS (VALUES
('2026-08-09-hisd-school-security-2026','Education','HISD Adds More Armed Officers and New Game-Day Rules as 160,000 Students Return','Houston ISD is expanding campus security, first-day patrols and athletic-event entry rules as more than 160,000 students begin the 2026-27 school year.','Houston Chronicle','https://www.houstonchronicle.com/news/houston-texas/education/hisd/article/hisd-security-2026-22374217.php','2026-08-09T05:35:00Z'::timestamptz,38,TRUE,'/images/news/generated/2026-08-09/hisd-school-security-2026.svg','Editorial illustration of a Houston school protected by a security shield and patrol lights.','Houston Independent School District is starting the 2026-27 school year with a larger security footprint around campuses and tighter rules at athletic events, a significant operational shift for a district serving more than 160,000 students.

The district says armed officers will be stationed at 112 campuses this year, up from roughly 100 last year. Every HISD middle and high school will have an armed officer assigned, while a 24-hour district patrol unit will monitor campuses that do not have an officer permanently on site. The approach reflects a continuing challenge across Texas: state law requires armed security at public schools, but districts have struggled with the cost and availability of qualified personnel.

HISD and the Houston Police Department are also relaunching Project Safe Start for the first day of classes. The long-running program puts additional officers and community volunteers along routes students use to reach school. Houston Ministers Against Crime will again place volunteers around campuses, and neighborhood volunteers near Marshall Middle School will continue a patrol effort that began after 11-year-old Josue Flores was killed while walking home from school in 2016.

Families attending school sports will notice another change. HISD is requiring approved clear bags at UIL athletic events, continuing bag inspections and security scanning, and requiring spectators under 18 to show student identification. Most minors will also need to be accompanied by an adult, although HISD high school students and student-athletes have limited exceptions if they present identification.

The district is keeping weapons-detection systems installed at high schools in 2025 and says its safety strategy also includes crisis-response teams, behavioral support, facility maintenance and community partnerships. That layered model is intended to reduce reliance on any single security measure.

The practical test will come once schools and stadiums are full. More officers and stricter entry procedures can improve deterrence and response, but they can also create bottlenecks if families are not prepared for new rules. HISD parents should check campus-specific instructions before Monday and allow extra time at major events while the district adjusts to the new procedures.'),
('2026-08-09-reeves-county-2gw-data-center-campus','Business','A 2-Gigawatt West Texas Data Center Campus Pushes the Permian Deeper Into the AI Economy','Liberty Energy and PowerBridge are building a powered data-center platform in West Texas, beginning with a planned 2-gigawatt campus and more than 300 megawatts of initial generation.','Liberty Energy','https://investors.libertyfrac.com/news-and-events/press-releases/2026/07-22-2026-230509078','2026-08-09T05:36:00Z'::timestamptz,37,FALSE,'/images/news/generated/2026-08-09/reeves-county-2gw-data-center-campus.svg','Editorial illustration of a West Texas data center campus connected to natural-gas power infrastructure.','West Texas is becoming more than an oil-and-gas production region. A new partnership between Liberty Energy and PowerBridge is positioning the Permian Basin as a major location for the next wave of artificial-intelligence infrastructure.

The companies have formed a joint venture centered on PowerBridge’s Alpha Digital Campus, a planned 2-gigawatt powered data-center development in West Texas. Liberty Power Innovations is expected to design, build and operate modular generation and energy-management systems, while PowerBridge will provide the digital-campus sites, fiber infrastructure and other development work needed for large computing customers.

The first phase is expected to include more than 300 megawatts of generation capacity, with initial power delivery targeted for the fourth quarter of 2027 and additional deployment continuing into the first half of 2028. The companies describe the model as a way to shorten development timelines for hyperscale and AI customers that increasingly want certainty about power before committing billions of dollars to computing equipment.

For Texas, the project lands in the middle of a much larger argument about who should pay for the power demands of data centers. ERCOT has received an extraordinary volume of large-load requests, most of them tied to data centers, forcing regulators to redesign the process for connecting giant new users to the grid. Projects that bring dedicated generation can reduce some transmission pressure, but they still raise questions about fuel supply, emissions, water, roads and local tax incentives.

The Permian has one obvious advantage: abundant natural gas and an energy workforce already comfortable building industrial-scale infrastructure. That gives West Texas a plausible path to turn oil-field expertise into a broader power-and-computing economy. It could also create new competition for workers, land and pipeline capacity.

The Alpha project is not guaranteed to reach its full 2-gigawatt scale. Large data-center developments are often announced in phases and can change with customer demand, financing and permitting. Still, the joint venture is another sign that Texas energy companies increasingly see AI infrastructure as a core business opportunity rather than a side market. The next two years will show whether West Texas can convert that opportunity into durable local investment without shifting hidden infrastructure costs onto residents.'),
('2026-08-09-texas-july-mass-layoffs','Business','Nearly 1,200 Texas Layoffs Put New Pressure on a Job Market With Rising Unemployment','WARN notices and company announcements show a broad July layoff wave, with Dallas-Fort Worth taking the largest share as Texas unemployment remains above the national rate.','MySA','https://www.mysanantonio.com/business/article/mass-layoffs-texas-22375609.php','2026-08-09T05:37:00Z'::timestamptz,36,FALSE,'/images/news/generated/2026-08-09/texas-july-mass-layoffs.svg','Editorial illustration of Texas employment notices, office buildings and a falling jobs chart.','Texas continues to add jobs overall, but a new round of mass-layoff notices is a reminder that the state’s labor market is becoming more uneven.

Nearly 1,200 workers were affected by major layoff announcements tied to July, with roughly two-thirds of the losses concentrated in Dallas-Fort Worth. One of the largest notices came from SP+ Corporation’s Metropolis operation, which said 307 workers could lose their positions when a contract at Dallas-Fort Worth International Airport ends. Fifth Third Bank also filed a notice affecting 115 workers in Frisco following its merger with Comerica.

Other cuts span industries and regions. Layoffs have touched energy services, logistics, manufacturing, health-related businesses and technology. Microsoft-linked gaming operations in Texas have also been part of recent reductions. The mix matters because it suggests the weakness is not confined to a single struggling industry.

The broader labor data remains complicated. Texas added nearly 178,000 jobs over the year through June, but the state unemployment rate reached 4.9 percent, compared with 4.1 percent nationally. A growing labor force can push unemployment higher even while employers are adding positions, because more people are actively looking for work. Still, a widening gap with the national rate deserves attention.

WARN notices provide only a partial picture. Federal law generally requires advance notice for certain large layoffs and plant closings, but many smaller reductions do not qualify. Some announced layoffs also do not end in permanent unemployment if workers are hired by a successor contractor or quickly move to another company.

For Texas policymakers, the key question is whether July represents normal churn in a huge economy or the beginning of a broader slowdown. The state still benefits from population growth, energy investment, manufacturing projects and corporate relocations. At the same time, high borrowing costs, automation, mergers and contract changes are reshaping payrolls. Texans looking for work may increasingly find that the state can be adding jobs in aggregate while particular metro areas and industries are moving in the opposite direction.'),
('2026-08-09-texas-am-professors-classroom-lawsuit','Education','Texas A&M Professors Challenge Classroom Restrictions in Federal Court','Faculty members are asking a federal judge to block Texas A&M System rules governing instruction on race, gender ideology, sexual orientation and course material outside approved syllabi.','Houston Chronicle','https://www.houstonchronicle.com/news/houston-texas/education/article/texas-am-aclu-race-gender-lawsuit-22373331.php','2026-08-09T05:38:00Z'::timestamptz,36,FALSE,'/images/news/generated/2026-08-09/texas-am-professors-classroom-lawsuit.svg','Editorial illustration of a university lecture hall, law books and a federal courthouse.','A federal lawsuit filed by Texas A&M System professors is putting one of the state’s most consequential higher-education policy fights before a judge.

The plaintiffs, represented by the ACLU of Texas and supported by the American Association of University Professors, are challenging system rules that restrict classroom advocacy or instruction involving race ideology, gender ideology, sexual orientation and gender identity without prior approval. A separate policy also limits faculty from introducing material administrators consider inconsistent with an approved syllabus.

Texas A&M officials say the policies are designed to ensure academic responsibility, consistency and accountability to students and taxpayers. The system has said the lawsuit lacks merit and that it intends to defend the rules. Faculty groups argue the restrictions instead amount to viewpoint discrimination and are so vague that professors cannot know what classroom discussion could trigger discipline.

The dispute is no longer theoretical. Systemwide reviews have led to six course cancellations, modifications to hundreds of courses and the end of the flagship campus women’s and gender studies program. The lawsuit also points to course materials that were removed or revised, including readings from Plato and the film “Moonlight.” At least several fall 2026 courses were canceled or altered during the review process.

The professors are asking the court to declare the policies unconstitutional under the First and Fourteenth Amendments, temporarily stop enforcement while the case proceeds, restore canceled classes and ultimately revoke the restrictions. Texas A&M counters that governing boards have a legitimate role in determining how taxpayer-supported universities use required courses and public resources.

The result could extend far beyond College Station. Texas lawmakers and university regents have been increasing oversight of curriculum, governance and diversity-related programs across public higher education. Similar legal challenges are already underway elsewhere in the state. A ruling that clearly defines how far a public university may go in controlling course content would give both faculty and governing boards a new legal boundary. Until then, professors, students and administrators will continue operating in an environment where academic policy and constitutional law are colliding in real time.'),
('2026-08-09-presidio-border-wall-levee-ruling','Border','Federal Judge Allows Presidio Border Wall Work to Move Forward Through Levee System','The West Texas border town failed to win an emergency halt to federal wall construction, leaving local flooding and levee concerns unresolved as the case continues.','Associated Press','https://apnews.com/article/a1534ab0dd9d0c1215d574dcd2098250','2026-08-09T05:39:00Z'::timestamptz,35,FALSE,'/images/news/generated/2026-08-09/presidio-border-wall-levee-ruling.svg','Editorial illustration of a border wall crossing a West Texas levee beside the Rio Grande.','A federal judge has allowed the Department of Homeland Security to continue border-wall construction through Presidio’s levee system, rejecting the West Texas city’s request for an emergency order that would have stopped the work.

Presidio, a community of roughly 3,200 residents along the Rio Grande, argued that the project could interfere with flood protection and that federal agencies had not completed steps the city believes are necessary before construction crosses the levee. City officials have raised concerns that changes to the system could increase flood risk or leave local taxpayers responsible for future problems.

The federal government has defended the project as part of its broader border-security authority. Judge Reggie B. Walton concluded that Presidio had not shown it was likely to succeed on the merits strongly enough to justify blocking construction at this stage. The ruling does not resolve every underlying claim, but it means work can continue while the litigation proceeds.

The case highlights a recurring tension along the Texas border. Federal wall projects are designed around immigration enforcement and national-security priorities, while the land they cross is also part of local drainage systems, ranches, wildlife corridors, roads and private property. In Presidio, the levee is not an abstract piece of infrastructure; it is part of the city’s protection from the Rio Grande.

The Trump administration is pursuing a much larger border-wall program across the Southwest and has relied on statutory authority that allows the government to waive certain environmental and procedural requirements. Supporters argue that broad waiver authority is necessary to prevent local disputes from delaying border security. Opponents say the same authority can leave communities with limited recourse when projects affect water, land or public safety.

For Presidio residents, the immediate issue is construction oversight. The city will be watching how contractors alter or cross the levee, what engineering safeguards are used and whether federal agencies accept responsibility for future maintenance or damage. The legal fight may continue, but the physical work is no longer waiting for the court case to finish.'),
('2026-08-09-luke-kornet-roadside-help','Viral','Spurs Center Luke Kornet Goes Viral for Stopping to Help a Stranded San Antonio Driver','A roadside act of kindness by the Spurs big man was captured on TikTok and quickly spread among San Antonio basketball fans.','Pounding The Rock','https://www.poundingtherock.com/spurs-discussion-threads/106820/open-thread-luke-kornet-stops-to-help-a-local-motorist','2026-08-09T05:40:00Z'::timestamptz,27,FALSE,'/images/news/generated/2026-08-09/luke-kornet-roadside-help.svg','Editorial illustration of a tall basketball player helping beside a stalled car in San Antonio.','San Antonio Spurs center Luke Kornet is getting attention for something that had nothing to do with a box score.

A TikTok user posted video of Kornet stopping to help a motorist dealing with car trouble in San Antonio. The clip spread quickly through Spurs fan circles, where viewers recognized the 7-foot-1 center and praised him for pulling over instead of simply driving past.

There is not much spectacle to the moment, which is probably why it resonated. Kornet was not at a team event, there was no promotional setup, and the interaction appeared to be an ordinary roadside problem that happened to involve a very recognizable NBA player. In an offseason filled with trade rumors, arena debates and social-media workout clips, a few minutes of practical help created its own story.

Kornet joined a Spurs organization whose public identity has long leaned heavily on community involvement. Players regularly appear at youth events, school programs and charitable activities, but spontaneous encounters often feel different to fans because they are not part of a scheduled appearance. The viral reaction suggests San Antonio still pays close attention to how players behave away from the arena.

The story also arrived during a busy stretch for the team’s broader community presence. Spurs players have been traveling, training and participating in summer activities, while the organization continues preparing for the coming season and its long-term arena plans. Kornet’s roadside stop offered a much smaller reminder of the relationship between the franchise and the city.

Viral clips can exaggerate or strip away context, so this one should be kept in proportion. It was a driver having trouble and another person stopping to help. But sometimes that simplicity is exactly what people want to share. In a city where Spurs players are treated as neighbors as much as celebrities, Kornet earned a burst of goodwill by acting like one.'),
('2026-08-09-san-antonio-frida-fest-record','Viral','San Antonio’s Frida Fest Wants a World Record Sea of Flower Crowns and Unibrows','The 10th annual festival is inviting Texans to dress as Frida Kahlo for a Guinness World Record attempt at Wonderland of the Americas.','San Antonio Express-News','https://www.expressnews.com/lifestyle/article/frida-fest-2026-22375315.php','2026-08-09T05:41:00Z'::timestamptz,26,FALSE,'/images/news/generated/2026-08-09/san-antonio-frida-fest-record.svg','Editorial illustration of colorful flower crowns and artist palettes for San Antonio Frida Fest.','San Antonio’s annual celebration of Frida Kahlo is adding an unusually ambitious goal this year: putting enough people in full Frida-inspired dress to claim a Guinness World Record.

Frida Fest will mark its 10th anniversary Aug. 15 and 16 at Wonderland of the Americas. Organizers are planning a record attempt for the largest gathering of people dressed as the Mexican painter, with the main count scheduled for 3 p.m. Saturday. The festival itself runs from noon to 5 p.m. both days and is free to attend.

The record attempt will require more than simply wearing a floral headband. Organizers say participants should arrive in recognizable Kahlo-inspired clothing from flower crown to colorful footwear. All ages and genders are invited to take part, which fits the festival’s long-running emphasis on community art rather than strict impersonation.

Beyond the record attempt, the event includes more than 60 vendors and galleries, live performances, a curated art exhibition and a community fashion show. A Frida look-alike contest will run both days. The combination has helped the event grow from a local arts gathering into a San Antonio summer tradition with a strong social-media life.

Kahlo remains a particularly powerful cultural figure in South Texas, where her Mexican identity, self-portraiture, fashion and personal history are immediately recognizable across generations. That makes the world-record concept more than a costume stunt. It is also a visual expression of the region’s cross-border cultural identity.

Whether Guinness ultimately certifies a record will depend on documentation and participation, not just enthusiasm. But even a failed attempt would produce the kind of scene built for photos: hundreds of flower crowns, bold colors and carefully drawn brows gathered under one roof. For organizers, that may be the real win — turning a decade-old local festival into a citywide invitation to make art together.'),
('2026-08-09-san-antonio-zoo-dinos-after-dark-changes','Viral','San Antonio Zoo Expands “Dinos After Dark” After Viral Crowd Backlash','Long parking waits and social-media complaints pushed the zoo to add dates, longer hours, more exits and new traffic controls for its popular nighttime dinosaur event.','MySA','https://www.mysanantonio.com/lifestyle/article/dinos-after-dark-san-antonio-zoo-22371600.php','2026-08-09T05:42:00Z'::timestamptz,27,FALSE,'/images/news/generated/2026-08-09/san-antonio-zoo-dinos-after-dark-changes.svg','Editorial illustration of glowing dinosaurs, traffic cones and a nighttime San Antonio Zoo entrance.','San Antonio Zoo is changing one of its summer attractions after a packed nighttime event triggered long traffic delays and a wave of complaints online.

“Dinos After Dark,” built around the zoo’s Zoorassic Park animatronic dinosaur exhibit, drew a large crowd when it opened more broadly to the public. Guests posted videos and complaints describing long waits to park, enter and leave, with some saying the traffic experience overwhelmed what was supposed to be a family-friendly night out.

The zoo says about 13,000 people visited across the full day, including both normal operating hours and the special nighttime event. Officials said the problem was less the total daily attendance than the fact that so many guests arrived and departed during the same narrow window. That created the kind of surge normally associated with a concert or major sporting event.

In response, the zoo is spreading attendance across more time and more nights. The attraction will now run Fridays and Saturdays through Labor Day weekend, adding 11 dates. Hours are expanding from the original 7-to-10 p.m. window to 6-to-11 p.m. The zoo also says it will open more parking, add another exit, adjust pedestrian routes, open more of the property to distribute crowds and work with park police on traffic flow.

The underlying attraction remains the same: illuminated animatronic dinosaurs, fog, performers, themed food and interactive displays. Admission is free for active members and $9.99 for other guests. The viral backlash did not kill the event; it effectively forced the zoo to redesign the logistics around its popularity.

That is a useful distinction. Social media can amplify complaints, but in this case the complaints pointed to a concrete operational problem that the zoo could address. Families considering a future date should still expect a busy event, but the wider schedule and longer hours should reduce the single-wave crush that caused the first round of frustration.'),
('2026-08-09-houston-facebook-marketplace-food','Viral','Houston’s Latest Viral Food Court Is Facebook Marketplace','Home cooks and small food businesses are turning Marketplace listings into social-media hits, creating a new path to customers — and new questions about Texas cottage-food rules.','Houston Chronicle','https://www.houstonchronicle.com/food-restaurants/article/facebook-marketplace-food-houston-22357822.php','2026-08-09T05:43:00Z'::timestamptz,28,FALSE,'/images/news/generated/2026-08-09/houston-facebook-marketplace-food.svg','Editorial illustration of a smartphone marketplace filled with Houston food boxes and takeout dishes.','Facebook Marketplace is becoming an unlikely restaurant-discovery tool in Houston, where home cooks and tiny food businesses are using the same platform known for used furniture and cars to sell dinner.

The trend has taken off as customers post food-haul videos on TikTok and Instagram. Listings range from birria pizza and oxtail bowls to garlic-Parmesan crab, candied grapes and elaborate desserts. One viral video can send a wave of direct messages to a cook who previously relied almost entirely on friends and neighborhood word of mouth.

For aspiring food entrepreneurs, the appeal is obvious. Marketplace offers a huge local audience without the rent, commissions and startup costs associated with a storefront or delivery app. Some sellers use it as a first step toward a licensed commercial kitchen. Houston chef Jaquese Jones, for example, moved her fried-chicken and biscuit operation into a commercial kitchen after building demand through social media and Marketplace.

The legal side is more complicated. Texas has expanded its cottage-food law, but home kitchens still cannot simply sell every type of prepared meal. Meat and other potentially hazardous foods generally fall outside what may be made and sold from a home under cottage-food rules. Refrigerated foods that are allowed come with additional registration, labeling and handling requirements. Customers therefore cannot assume that every attractive Marketplace listing is operating under the same rules as a restaurant.

Food safety is part of the conversation as well. Houston has recently dealt with public-health concerns involving foodborne illness, and informal sales make it harder for customers to know where ingredients were prepared or what inspections apply. At the same time, many buyers say they value the ability to support local cooks directly and discover dishes that may not exist on conventional menus.

The trend is likely to keep growing because the economics are powerful on both sides: sellers get cheap customer acquisition and buyers get highly local, highly shareable food. The next phase will determine whether more of those businesses move into licensed kitchens or whether regulators take a closer look at sales that fall outside Texas cottage-food law.'),
('2026-08-09-sarah-acosta-ksat-farewell','Viral','Sarah Acosta’s Final KSAT Broadcast Turns Into a San Antonio Farewell','After eight years at KSAT and 17 years in journalism, the morning anchor signed off with an emotional thank-you that spread across San Antonio social media.','MySA','https://www.mysanantonio.com/entertainment/article/sarah-acosta-ksat-22371602.php','2026-08-09T05:44:00Z'::timestamptz,25,FALSE,'/images/news/generated/2026-08-09/sarah-acosta-ksat-farewell.svg','Editorial illustration of a San Antonio television anchor desk, microphone and farewell screen.','San Antonio television viewers said goodbye this weekend to a familiar morning-news face as Sarah Acosta delivered her final broadcast on KSAT 12.

Acosta is leaving the news industry after 17 years in journalism, including eight years at KSAT. During her final “Good Morning San Antonio” appearance on Saturday, she thanked viewers and colleagues and reflected on the stories and personal milestones that unfolded while she was on the station’s morning team.

Her departure drew strong reaction because local morning anchors occupy an unusual place in a city’s daily routine. They are present for severe-weather mornings, school closings, elections, major tragedies and the lighter stories people watch while getting ready for work. Over years, that repetition creates familiarity that is different from the relationship audiences have with national television personalities.

Acosta’s own career included assignments ranging from flying with the Blue Angels and covering packed school pep rallies to reporting on severe weather and local environmental issues. In messages posted before her final show, she said some of the work she valued most came during her last year, including stories about protecting San Antonio drinking water and addressing climate change.

Colleagues also used social media to share tributes and memories, helping turn the sign-off into a broader community farewell. Acosta has said she is leaving journalism but not necessarily leaving storytelling, and she has indicated that San Antonio remains home.

The television business is changing quickly, with stations across Texas cutting staff, reorganizing newscasts and experimenting with new technology. Acosta’s exit is not being presented as part of those layoffs, but the timing makes her farewell feel like another marker of how rapidly local media is evolving. For viewers who have started their mornings with her for years, the immediate change is simpler: Monday’s broadcast will sound and feel a little different.' )
),
prepared AS (
  SELECT *, jsonb_build_object(
    'updated', published_at::date::text,
    'intro', jsonb_build_array(dek),
    'sections', jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),
    'faq', jsonb_build_array(),
    'sources', jsonb_build_array(jsonb_build_object('label', source_name || ' — original report', 'url', source_url)),
    'keyTakeaways', jsonb_build_array(dek)
  ) AS body_json
  FROM items
)
INSERT INTO public.daily_articles
(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text)
SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text
FROM prepared
ON CONFLICT (slug) DO UPDATE SET
internal_url=EXCLUDED.internal_url,
is_ingested=EXCLUDED.is_ingested,
category=EXCLUDED.category,
title=EXCLUDED.title,
dek=EXCLUDED.dek,
source_name=EXCLUDED.source_name,
source_url=EXCLUDED.source_url,
published_at=EXCLUDED.published_at,
score=EXCLUDED.score,
is_breaking=EXCLUDED.is_breaking,
kind=EXCLUDED.kind,
body=EXCLUDED.body,
body_json=EXCLUDED.body_json,
featured_image_url=EXCLUDED.featured_image_url,
image_url=EXCLUDED.image_url,
image_alt_text=EXCLUDED.image_alt_text;