-- Current Texas news: Texas A&M core curriculum review
WITH item AS (SELECT '2026-09-04-texas-am-core-curriculum-sb37'::text slug,'Education'::text category,'Texas A&M Regents Cut More Than 200 Courses From Core Lists Under SB 37 Review'::text title,'The Texas A&M System approved revised core curricula after a course-by-course SB 37 review, removing more than 200 classes from core eligibility while leaving many available as electives.'::text dek,'The Texas Tribune / Texas A&M System'::text source_name,'https://www.texastribune.org/2026/09/03/texas-am-remove-core-courses-lgbtq-race-climate-change/'::text source_url,'2026-09-04T23:52:00Z'::timestamptz published_at,42::int score,TRUE::boolean is_breaking,'/images/news/generated/2026-09-04/tamu-core-curriculum-review.svg'::text image_url,'Editorial illustration of a Texas university campus, course catalog and review checklist.'::text image_alt_text,$body$The Texas A&M University System has removed more than 200 courses from the lists students may use to satisfy core curriculum requirements after a systemwide review required by Senate Bill 37, marking one of the clearest examples yet of how the 2025 higher-education law is reshaping public universities.

The Board of Regents approved revised core curricula for 11 system universities this week after administrators reviewed courses one by one. The affected classes are not automatically banned. Universities may continue offering many of them as electives or as requirements within a major. The practical change is that students will no longer be able to use the removed courses to satisfy statewide core categories such as communication, humanities, social sciences or other general-education requirements.

That distinction matters. A headline saying a course was "removed" can suggest that a university has prohibited the subject entirely. The Texas Tribune reported that courses touching LGBTQ literature, ethnic studies, climate change, gender and race were among those taken out of core lists. The A&M System's own announcement described the process as a comprehensive review intended to comply with SB 37 and ensure core offerings meet statutory and academic requirements. Students can still encounter many of those subjects outside the core.

SB 37 increased governing-board oversight of university curriculum and academic programs. Supporters said elected or appointed public officials needed more accountability over taxpayer-funded institutions, especially for courses that fulfill basic degree requirements for large numbers of students. Critics warned that regents could become political gatekeepers for academic content and pressure faculty to avoid controversial subjects.

The A&M vote brings that theoretical argument into a concrete setting. Core curriculum is uniquely important because nearly every undergraduate must complete it. A specialized elective in a major might enroll dozens of students; a core-approved course can attract students from across campus who are trying to satisfy a graduation requirement. Removing a course from the core can sharply reduce enrollment even if the catalog number survives.

System leaders have emphasized that the review focused on whether courses fit core objectives and state law, not on a blanket prohibition against particular viewpoints. That is an important claim and one that can be tested. The strongest evidence will be the before-and-after course lists, the written criteria reviewers used and whether similar standards were applied to courses across the ideological spectrum.

Faculty critics are likely to focus on academic freedom. Universities traditionally give faculty substantial authority over curriculum because subject-matter specialists are best positioned to judge disciplinary rigor. Public universities, however, are also state institutions governed by boards with legal responsibilities and public accountability. Texas is now pushing that balance toward regents and lawmakers. The question is not whether governing boards have authority; they plainly do. The question is how directly political officials should use that authority to shape what counts toward a student's general education.

Students also have a practical concern: degree planning. A course that counted toward the core when a student registered may not count the same way for a future student. Universities will need clear transition rules so that students are not unexpectedly delayed or forced to take additional credits because an approved list changed. Advising systems and degree audits will have to reflect the new classifications accurately.

There is also a transfer issue. Texas has worked for years to make core curriculum portable among public institutions. When a student completes an approved core component at one Texas public college or university, that credit often transfers in a predictable way. Changes in what institutions place inside their core can therefore affect community-college pathways and transfers as well as four-year students already on campus.

The political debate will likely intensify because the removed-course examples are easy to turn into national talking points. Conservatives can point to classes with titles involving identity or activism and argue that taxpayers should not be required to subsidize them as general education. Progressives can point to the same list and argue that officials are targeting scholarship about race, gender or climate because of its subject matter. Neither argument establishes how rigorous a particular course actually is.

A better accountability test is course-specific. What learning objectives did the class claim? Which state core objective was it supposed to satisfy? What assignments and readings were required? Did reviewers apply the same standard to traditional and newer fields? Were professors given an opportunity to revise a syllabus or appeal a decision? Those details will show whether SB 37 is functioning as quality control or as ideological filtering.

Texas A&M's size ensures the decision will be watched by every public university system in the state. Other governing boards face the same law and similar review obligations. If A&M's approach becomes a template, hundreds more course classifications could change statewide. If controversy produces litigation or legislative revisions, the implementation could shift again.

For now, students should not assume that an affected subject has vanished from campus. The immediate effect is narrower but still meaningful: more than 200 courses will no longer carry the same power inside the core curriculum. That change influences enrollment, faculty planning, transfer pathways and the definition of what Texas considers essential undergraduate learning.

The next useful step is transparency. The A&M System should maintain public lists of removed and retained courses, explain the standards used, and document any appeals or revisions. Supporters of SB 37 should welcome that scrutiny because clear criteria would demonstrate the law is being applied consistently. Critics should also focus on the evidence rather than treating every curricular change as censorship. With public universities, taxpayers, students and faculty all have a legitimate stake in seeing how the decisions were made.$body$::text body), prepared AS (SELECT *,jsonb_build_object('updated','2026-09-04','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label','The Texas Tribune — Texas A&M core course review','url','https://www.texastribune.org/2026/09/03/texas-am-remove-core-courses-lgbtq-race-climate-change/'),jsonb_build_object('label','Texas A&M System — Regents approve core curricula','url','https://news.tamus.edu/stories/texas-am-system-regents-approve-core-curricula-after-comprehensive-review/')),'keyTakeaways',jsonb_build_array(dek)) body_json FROM item) INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;