-- Current Texas news: Paxton financial disclosures
WITH item AS (SELECT '2026-09-04-paxton-financial-disclosures-ethics'::text slug,'Politics'::text category,'Paxton Financial Disclosures Raise New Federal Ethics Questions in Texas Senate Race'::text title,'A joint investigation found apparent omissions involving rental income, mortgages and property values in Ken Paxton’s federal Senate disclosures; his campaign disputes the significance of the findings.'::text dek,'The Texas Tribune / ProPublica'::text source_name,'https://www.texastribune.org/2026/09/04/texas-ken-paxton-personal-financial-disclosures-ethics-law-us-senate-race/'::text source_url,'2026-09-04T23:50:00Z'::timestamptz published_at,46::int score,TRUE::boolean is_breaking,'/images/news/generated/2026-09-04/paxton-financial-disclosures.jpg'::text image_url,'Texas financial disclosure papers, rental homes and a magnifying glass.'::text image_alt_text,$body$Texas Attorney General Ken Paxton is facing a new round of scrutiny over the personal financial disclosure he filed as the Republican nominee for the U.S. Senate, after a joint investigation by The Texas Tribune and ProPublica identified rental income, mortgages and property valuations that experts said appear inconsistent with federal disclosure rules.

The issue is not a finding of criminal guilt, and no federal ethics body has announced a sanction. It is, however, a significant transparency question in a statewide Senate race because federal candidates are required to disclose enough about their assets, liabilities and income for voters to evaluate potential conflicts of interest. The news organizations reported that Paxton listed seven homes but reported no income from them, even though all but one were advertised for rent during the relevant reporting periods. They also found three mortgages tied to condos at a Utah golf resort that were not listed as liabilities.

Three ethics specialists consulted by the news organizations said federal law requires rental income to be disclosed when it exceeds the reporting threshold. Federal rules also generally require candidates to report loans over $10,000 unless a loan is tied to a personal residence. The reporting found mortgage documents for three Utah condos totaling about $1.3 million. Those properties were not among the liabilities Paxton disclosed for the period examined by reporters.

Paxton's campaign rejected the suggestion that the filing reflected wrongdoing. A campaign spokesperson pointed to his private-sector career and characterized the reporting as a manufactured political controversy. Paxton declined the news organizations' requests for a detailed interview about the individual properties and entries. That response matters because the central dispute is not whether Paxton owns real estate; it is whether the federal form accurately captured income, debt and fair-market values in the way disclosure law requires.

One of the most striking examples involves a 42-acre tract south of Fort Worth. The joint investigation reported that Paxton valued his interest at no more than $50,000 on a prior filing, while a business partner said Paxton's share had been worth about $1 million for years. The 2026 filing then placed the property in a much higher value range. Federal disclosure instructions allow some use of tax assessments, but experts told the news organizations that a filer must adjust a valuation when an assessment is materially below fair market value.

The broader public-interest question is why these forms exist. Financial disclosures are not designed to prove that a candidate has done anything improper by becoming wealthy or owning investment property. They are intended to reveal enough about sources of income, debt and ownership for voters, journalists and ethics officials to identify relationships that might create conflicts. An incomplete filing can frustrate that purpose even when a missing item ultimately has an innocent explanation.

The issue has extra weight because Paxton is not simply a private citizen seeking office for the first time. He has served as Texas attorney general since 2015 and previously served in the Legislature. His finances were examined during the 2023 impeachment process, which ended with the Texas Senate acquitting him on all articles tried. The current questions are separate from that case, and the old allegations should not be treated as proof about the accuracy of a new federal form. But the history guarantees that any ambiguity in his finances will draw intense attention.

The timing also puts the story directly into the general-election campaign. Paxton is running against Democratic state Rep. James Talarico for the U.S. Senate. Financial transparency, trust in government and the personal wealth of officeholders are already campaign themes. Both campaigns have political incentives to frame the disclosure issue aggressively, which makes it especially important for voters to distinguish documented facts from campaign rhetoric.

What is documented at this point is narrower. Reporters reviewed public property records, rental listings and federal disclosure forms. They found properties apparently being rented despite reported income of none or less than the disclosure threshold, mortgages that were not listed, and property values that changed sharply between filings. Ethics experts said those facts raise apparent compliance problems. Paxton's campaign disputes the significance of the findings. No final enforcement determination has been announced.

Federal disclosure rules can carry civil or criminal consequences for knowing falsification, but that does not mean every omission results in a prosecution or even a penalty. Filers can amend reports, and enforcement depends on intent, materiality and the response of the relevant authorities. The Senate Ethics Committee is responsible for reviewing candidate disclosures, though its processes are often less visible than a criminal investigation.

For Texas voters, the most useful next step is to watch for an amended filing or a detailed property-by-property explanation. If the homes produced little or no reportable income, documentation could resolve part of the dispute. If the Utah condos qualify for an exemption, Paxton could explain why. If valuations were based on a permitted method, the campaign can make that case. Transparency is the practical remedy for ambiguity.

This is ultimately a story about disclosure, not a verdict. The allegations are serious because they concern a candidate's compliance with federal ethics law, but the strongest way to assess them is through the filings, land records, rental evidence and any response from federal ethics officials. Keep TX Red will update this report if Paxton files amendments, provides additional documentation or if the Senate Ethics Committee takes formal action.$body$::text body), prepared AS (SELECT *,jsonb_build_object('updated','2026-09-04','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',to_jsonb(regexp_split_to_array(body,E'\n\n')))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label','The Texas Tribune — Paxton financial disclosures','url','https://www.texastribune.org/2026/09/04/texas-ken-paxton-personal-financial-disclosures-ethics-law-us-senate-race/'),jsonb_build_object('label','ProPublica — Paxton financial disclosures','url','https://www.propublica.org/article/ken-paxton-senate-financial-disclosures-ethics-law')),'keyTakeaways',jsonb_build_array(dek)) body_json FROM item) INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;