-- ChatGPT auto article: Texas crime rate decline
WITH item AS (SELECT '2026-08-09-texas-crime-rate-decline'::text slug,'Public Safety'::text category,'Texas Crime Rate Keeps Falling, With McAllen Reporting Historic Lows'::text title,'State crime data show a multi-year decline, while McAllen and Brownsville each reported sharp 2025 drops and McAllen says crime is at its lowest level in four decades.'::text dek,'The Texas Tribune'::text source_name,'https://www.texastribune.org/2026/07/23/texas-crime-rates-drop/'::text source_url,'2026-08-09T15:33:00Z'::timestamptz published_at,35::int score,FALSE::boolean is_breaking,'/images/news/generated/2026-08-09/texas-crime-rate-drop.svg'::text image_url,'Editorial illustration of a Texas city skyline, public-safety shield and descending crime-rate chart.'::text image_alt_text,$body$Texas crime rates continued to move downward in the latest statewide data, extending a decline that began after a recent peak in 2022. Uniform Crime Reporting data from the Texas Department of Public Safety, as summarized by The Texas Tribune, show the statewide crime rate falling 3.3% from 2022 to 2023, another 8.2% from 2023 to 2024, and 13% from 2024 to 2025. McAllen is drawing particular attention because city leaders say its crime level is now the lowest in roughly 40 years. Brownsville also reported a large decline in 2025.

Those numbers are important because public perceptions of crime often move more slowly than the data. Texans can simultaneously experience a highly publicized violent incident, see constant crime footage online and live in a state where the overall rate is declining. Both realities can be true. Statewide statistics aggregate millions of people and many categories of offenses; they do not erase the harm experienced by individual victims or guarantee that every neighborhood is improving at the same rate. But they are essential for evaluating broad claims about whether public safety is getting better or worse.

McAllen reported a 21% drop in crime in 2025, according to the Tribune, and Brownsville reported a decline of the same size. McAllen Police Chief Victor Rodriguez credited a combination of community engagement, population growth and sustained public-safety investment, including staffing levels. He also suggested the heavy law-enforcement presence associated with immigration enforcement might play some role. Researchers interviewed for the report cautioned that it is too early to draw a causal connection between immigration enforcement and the crime decline.

That caution is worth emphasizing. Crime rates are influenced by many overlapping factors: demographics, policing strategies, economic conditions, incarceration patterns, social services, technology, changes in reporting and longer national trends. A decline that appears in cities with very different local policies usually cannot be attributed to a single intervention. Researchers also note a separate measurement concern in immigrant communities: fear of immigration consequences can make some victims or witnesses less willing to report crimes. That possibility has to be considered when interpreting local statistics.

The broader national context supports the idea that Texas is part of a wider downward movement. The Tribune cited criminologists who pointed to substantial homicide declines across major U.S. cities since the pandemic-era peak. That does not make the Texas trend less meaningful; it simply changes the question. Instead of asking which one Texas policy caused the decline, policymakers should ask which local practices appear to be reinforcing the national improvement and how those practices can be sustained without distorting statistics or discouraging victims from contacting police.

For local governments, falling crime creates an opportunity to study what is working before conditions change again. Departments can compare clearance rates, repeat-offender patterns, response times, staffing, neighborhood hot spots and community reporting. A city that simply celebrates a lower top-line number may miss important differences among violent crime, property crime and other categories. A city that uses the decline as a baseline for deeper analysis can identify which neighborhoods still need attention even while the citywide picture improves.

The political implications are obvious because border security and public safety remain central issues in Texas. McAllen and Brownsville sit in the Rio Grande Valley, where national political rhetoric often portrays the border as uniquely dangerous. Local crime data complicate simplistic versions of that argument. Researchers cited in the Tribune also pointed to studies finding that immigrant populations, including undocumented immigrants, are not responsible for the majority of crime and often have lower offending rates than U.S.-born populations. Those findings do not eliminate border-security concerns, but they do demand precision when crime statistics are used in political debate.

For residents, the most useful measure is whether the decline is durable and visible in daily life. Lower rates should eventually translate into fewer burglaries, assaults, vehicle thefts and other victimization, not just a better number in an annual report. Public confidence may lag until people personally see safer commercial districts, neighborhoods and parks. Police departments can help close that gap by publishing data in a form residents can understand and by explaining both successes and remaining problem areas.

Texas should also be careful not to become complacent. Crime trends can reverse, and agencies need enough capacity to investigate offenses even during periods of improvement. Sustaining lower crime may require continuing the boring work that rarely makes headlines: recruiting and retaining officers, improving evidence processing, targeting repeat violence, maintaining youth programs and building trust so witnesses report what they see. Falling numbers are a reason to evaluate and reinforce effective systems, not a reason to stop paying attention.

This article is an independent Keep TX Red rewrite based on reporting published by The Texas Tribune on July 23, 2026, and the state crime data discussed in that report. The Tribune reported a 13% statewide crime-rate decline from 2024 to 2025 and 21% declines in both McAllen and Brownsville during 2025.$body$::text body), prepared AS (SELECT *,jsonb_build_object('updated','2026-08-09','intro',jsonb_build_array(split_part(body,E'\n\n',1)),'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),'faq',jsonb_build_array(),'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — original report','url',source_url)),'keyTakeaways',jsonb_build_array(dek)) body_json FROM item) INSERT INTO public.daily_articles(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text) SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text FROM prepared ON CONFLICT(slug) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,is_breaking=EXCLUDED.is_breaking,body=EXCLUDED.body,body_json=EXCLUDED.body_json,featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;