-- Daily Texas news batch for 2026-08-08 afternoon. Original Keep TX Red rewrites with unique hero images.

WITH items(slug,category,title,dek,source_name,source_url,published_at,score,is_breaking,image_url,image_alt_text,body) AS (VALUES
('2026-08-08-texas-data-center-pause-grid-deposits','Business','Texas Data Center Pause Leaves Hundreds of Millions in Grid Deposits in Limbo','Gov. Greg Abbott’s audit of proposed data centers has frozen a fast-track grid process, leaving developers with large deposits at risk and Texas regulators facing pressure for clearer rules.','Reuters','https://www.reuters.com/legal/litigation/hundreds-millions-grid-deposits-linger-uncertainty-following-texas-data-center-2026-08-07/','2026-08-08T17:35:00Z'::timestamptz,38,TRUE,'/images/news/generated/2026-08-08/texas-data-center-grid-pause.svg','Illustration of a Texas power grid and data center paused behind a review checkpoint.','Texas’ rapid data-center buildout has hit a regulatory bottleneck, and the financial stakes are now measured in hundreds of millions of dollars. Gov. Greg Abbott ordered state regulators and ERCOT to audit large proposed data-center projects before allowing additional grid connections to advance, putting the state’s Batch Zero interconnection process on hold while officials examine whether the projects are realistic and whether the power system can support them.

The pause has created an immediate problem for developers that already posted deposits to reserve a place in the process. Reuters reports that Batch Zero required deposits of $50,000 per megawatt, meaning the largest projects could have more than $100 million committed. Developers now face uncertainty over how long the audit will take, whether projects will survive the review and how much of those deposits could be lost if a company withdraws.

The review comes as Texas confronts an extraordinary queue of proposed electricity demand. Abbott has said data centers account for the overwhelming majority of hundreds of gigawatts of large-load requests under consideration. State officials want applicants to disclose ownership, expected power and water use, tax incentives and community-impact plans before receiving approval. Supporters of the audit argue that speculative projects should not distort grid planning or shift infrastructure costs to ordinary customers. Industry groups counter that developers need predictable timelines and rules if Texas wants to remain competitive for technology investment.

A pending Public Utility Commission proposal adds another layer of risk. The commission has considered making a larger share of grid deposits nonrefundable, which could increase the cost of walking away from a project that is delayed or rejected. That makes the timing of the state audit especially important for companies deciding whether to keep capital tied up in Texas.

The larger policy question is no longer whether Texas will attract data centers, but how many the grid and local communities can absorb without compromising reliability, water supplies or household costs. The audit gives state leaders a chance to separate serious projects from speculative requests, but the longer the process remains undefined, the more uncertainty it creates for utilities, developers and communities planning around proposed facilities.'),
('2026-08-08-cruz-college-sports-bill-september','Sports','Ted Cruz’s College Sports Bill Misses August Vote, Moves to September Senate Calendar','The Protect College Sports Act will wait until the Senate returns in September, extending uncertainty over NIL rules, revenue sharing and conference realignment for Texas universities.','Associated Press','https://apnews.com/article/f90c11932844ed7b15ed5f05681c3406','2026-08-08T17:36:00Z'::timestamptz,34,TRUE,'/images/news/generated/2026-08-08/cruz-college-sports-bill.svg','Illustration of a college football field beside the U.S. Capitol representing federal college-sports legislation.','A federal bill led by Texas Sen. Ted Cruz that could reshape college athletics will have to wait until September. The U.S. Senate left for its summer recess without voting on the Protect College Sports Act, but the measure was placed on the chamber’s September calendar, keeping alive a bipartisan effort to create national rules for athlete compensation and other issues that have transformed college sports.

The proposal, negotiated by Cruz and Washington Sen. Maria Cantwell with other senators, would establish federal standards for name, image and likeness deals, revenue sharing, transfers and conference realignment. Supporters say a national framework is needed because schools now operate under a mix of court settlements, NCAA rules and state laws. The Senate Commerce Committee advanced the bill 19-9 in June.

Texas schools have a direct stake in the outcome. The University of Texas and Texas A&M compete in the SEC, while Baylor, TCU, Texas Tech and Houston are members of the Big 12. Their athletic departments are navigating rapidly rising athlete-compensation costs, booster-funded NIL arrangements and the possibility that future conference moves could carry new federal restrictions.

The bill has changed substantially as senators and conferences negotiated over its details. The Big Ten and SEC, which had resisted earlier versions, moved toward support after revisions. Opposition remains from labor groups, some lawmakers and athlete advocates who argue that Congress should not limit players’ economic rights or shield the NCAA and conferences from legal challenges too broadly.

The delay means the current system stays in place through the opening weeks of football season. When the Senate returns, the bill will still need enough support to overcome procedural hurdles and then would face a difficult path in the House. For Texas universities, the September debate could determine whether college sports continue evolving through lawsuits and individual state policies or shift toward a single federal rulebook.'),
('2026-08-08-texas-judge-national-firearms-act-ruling','Politics','Texas Federal Judge Strikes Down Key National Firearms Act Rules After Tax Repeal','A federal judge in Texas ruled that registration rules for suppressors and certain short-barreled firearms can no longer rest on Congress’s taxing power after the underlying federal tax was eliminated.','Associated Press','https://apnews.com/article/7a29ec3b20d9a4ee36e04eb1b276e372','2026-08-08T17:37:00Z'::timestamptz,36,FALSE,'/images/news/generated/2026-08-08/texas-nfa-ruling.svg','Illustration of a federal courthouse in Texas with legal documents representing a firearms regulation ruling.','A federal judge in Texas has issued a major ruling against portions of the National Firearms Act, finding that registration requirements for suppressors and certain short-barreled firearms cannot continue to rely on Congress’ taxing authority after lawmakers eliminated the tax that historically supported the law.

U.S. District Judge James Hendrix concluded that the federal government’s old tax-and-registration structure lost its constitutional foundation when Congress removed the tax on covered items. The National Firearms Act dates to the 1930s and has long required owners of suppressors, short-barreled rifles and shotguns, and several other categories of weapons to register them with the federal government.

The ruling does not eliminate ordinary federal background-check requirements for firearm purchases, and it does not automatically erase every federal or state restriction that might apply to a particular weapon. Its significance is narrower but potentially far-reaching: it challenges whether the federal government can preserve the NFA’s registration system when the tax used to justify that system no longer exists.

Gun-rights organizations welcomed the decision as a correction to a regulatory system they have argued burdens lawful ownership. Gun-control advocates warned that the registration process provided an additional layer of scrutiny for weapons Congress historically treated differently from ordinary firearms. The federal government can appeal, and the case could eventually become part of a broader Supreme Court fight over the scope of federal firearms authority.

For Texans, the immediate practical effect will depend on how the ruling is implemented and whether higher courts pause or reverse it. Firearm owners should not assume every existing requirement disappeared overnight. But the decision is important because it links a recent act of Congress eliminating a tax to a constitutional challenge against the regulatory system built around that tax, potentially forcing federal lawmakers or courts to define a new legal basis for those rules.'),
('2026-08-08-texas-tv-radio-layoffs','Business','Layoffs Hit Texas TV and Radio Stations From Austin to Corpus Christi and Houston','Broadcasters across several Texas markets are cutting anchors, producers and radio staff as national media companies restructure local operations and experiment with more centralized technology.','Chron','https://www.chron.com/news/houston-texas/article/texas-tv-radio-layoffs-22378894.php','2026-08-08T17:38:00Z'::timestamptz,29,FALSE,'/images/news/generated/2026-08-08/texas-media-layoffs.svg','Illustration of television and radio broadcast towers across a Texas skyline during media-industry layoffs.','A new round of layoffs is reshaping local television and radio across Texas, affecting stations in Austin, Corpus Christi, Waco, Houston and Amarillo. The cuts involve multiple national broadcasting companies and are landing at a time when local newsrooms are under pressure to reduce costs while adopting more centralized production systems and new automation tools.

In Austin, CBS affiliate KEYE cut familiar morning-show staff as the station prepares a revised format. E.W. Scripps reductions have affected employees at KRIS 6 in Corpus Christi and KXXV in Central Texas. In radio, Cumulus Media has made another round of national cuts that reached Houston’s 104.1 KRBE and stations in Amarillo.

The Corpus Christi changes have drawn particular attention because longtime married co-anchors Bryan and Michelle Hofmann are among those leaving KRIS 6. Their final on-air date is expected later this month. The pair said publicly that the company’s broader technology strategy should not be interpreted as an artificial-intelligence replacement for their specific on-air roles, an important distinction as viewers debate how automation is changing local news.

The cuts reflect a larger business problem for local broadcasting. Traditional television and radio outlets compete with streaming services, podcasts, social media and digital advertising platforms while maintaining the expense of reporters, studios, transmitters and around-the-clock operations. Companies increasingly share production resources across markets, automate routine tasks and concentrate staff in fewer locations.

For Texas communities, the concern is not simply whether a familiar anchor disappears from a screen. Local stations often provide the fastest reporting during hurricanes, floods, tornadoes, wildfires, elections and city emergencies. Fewer journalists can mean less capacity for courthouse reporting, school-board coverage and neighborhood stories that do not attract national attention. The latest layoffs will test whether broadcasters can modernize their operations without hollowing out the local reporting that gives those stations their public value.'),
('2026-08-08-lake-corpus-christi-water-rebound','Texas News','Lake Corpus Christi Jumps Above 85% Full After Rains Transform Coastal Bend Water Outlook','A reservoir that fell into single-digit territory this spring has surged to its highest level in years, giving Corpus Christi more breathing room after a prolonged water-supply crisis.','MySA','https://www.mysanantonio.com/news/local/article/lake-corpus-christi-levels-22375516.php','2026-08-08T17:39:00Z'::timestamptz,33,FALSE,'/images/news/generated/2026-08-08/lake-corpus-christi-rebound.svg','Illustration of a Texas reservoir filling after heavy rain with a rising water gauge.','Lake Corpus Christi has climbed above 85% full after weeks of heavy rain sent water surging through South Texas rivers, a dramatic turnaround for a reservoir that was in single digits only a few months ago. The improvement is giving Corpus Christi and surrounding communities meaningful relief after years of drought and increasingly urgent warnings about the region’s long-term water supply.

According to figures cited from the Texas Water Development Board, Lake Corpus Christi reached about 85.5% capacity on August 7, its highest level in nearly four years. The reservoir had fallen below 9% this spring. Water arriving through the Nueces River system has rapidly refilled storage that residents had watched disappear during a prolonged dry period.

The broader Coastal Bend system is healthier but not fully recovered. Choke Canyon Reservoir remains much lower than Lake Corpus Christi, meaning the region still cannot treat the recent rains as a permanent solution. Combined storage has nevertheless risen sharply since winter, and Corpus Christi has been able to ease some restrictions while pushing back the timeline for a potential emergency in which projected demand would exceed available supply.

The turnaround illustrates both the benefit and the danger of relying on rainfall in a drought-prone region. A few weeks of major upstream flooding can transform reservoir levels, but another extended dry period could reverse those gains. Corpus Christi also serves major industrial users and a large port complex, so water planning affects households, employers and statewide economic activity.

The new water gives officials time to advance supply projects and conservation plans without the immediate pressure of an approaching “day zero.” It should not end the debate over desalination, reuse, pipeline capacity or industrial demand. Instead, the reservoir rebound gives the Coastal Bend something it badly needed: time. How local leaders use that time will determine whether the next drought produces another emergency countdown.'),
('2026-08-08-bucees-san-marcos-opening','Viral','Buc-ee’s Sets August 12 Opening for Massive New San Marcos Travel Center','The new I-35 stop will span roughly 74,000 square feet with 128 fueling positions, adding another giant Buc-ee’s between Austin and San Antonio.','Buc-ee''s','https://www.newswire.com/news/buc-ees-to-debut-new-travel-center-in-san-marcos-tx','2026-08-08T17:40:00Z'::timestamptz,27,FALSE,'/images/news/generated/2026-08-08/bucees-san-marcos-opening.svg','Illustration of a large Texas travel center along Interstate 35 representing the new Buc-ee''s in San Marcos.','Buc-ee’s is preparing to open one of its largest travel centers in San Marcos, adding a major new stop to the busy Interstate 35 corridor between Austin and San Antonio. The company says doors will open at 6 a.m. on Wednesday, August 12, followed by a ribbon-cutting ceremony later that morning.

The new store at 3245 N. IH 35 will cover roughly 74,000 square feet and include 128 fueling positions. That puts the San Marcos location in the same supersized category as the chain’s newest destination stores, built to handle heavy interstate traffic while offering the barbecue, jerky, fudge, kolaches, pastries and Beaver Nuggets that have turned Buc-ee’s into a Texas road-trip institution.

San Marcos is a logical location for the expansion. The city sits almost halfway between two of the state’s fastest-growing metropolitan areas, and I-35 carries a constant mix of commuters, college students, tourists and commercial traffic. The store is expected to employ more than 200 people and will give travelers another large-capacity stop on a stretch of highway where congestion can make even a fuel break a strategic decision.

The opening also highlights how far the company has expanded beyond its Texas roots. Buc-ee’s now operates travel centers across a growing list of states, yet new Texas openings still draw unusual attention because the brand remains closely tied to the state’s roadside culture.

For anyone planning an opening-day visit, Buc-ee’s says the public opening is scheduled for August 12 at 6 a.m. The company’s own website has also listed San Marcos among its August 2026 openings. Given the size of the store and the brand’s devoted following, travelers should expect the first few days to look more like an event than an ordinary gas-station opening.'),
('2026-08-08-perseids-texas-viewing-guide','Viral','Perseids Are Coming: Where Texans Can Get the Best View of August’s Meteor Shower','The annual Perseid meteor shower peaks in mid-August, and Texas dark-sky parks offer some of the best places to escape city light and watch the show.','San Antonio Express-News','https://www.expressnews.com/news/texas/article/when-where-to-view-perseids-meteor-shower-in-texas-22379416.php','2026-08-08T17:41:00Z'::timestamptz,25,FALSE,'/images/news/generated/2026-08-08/perseids-texas-night-sky.svg','Illustration of Perseid meteors streaking above a dark Texas desert landscape.','One of the year’s most reliable sky shows is approaching its peak, and Texans who can get away from city lights should have a strong chance to see it. The Perseid meteor shower reaches maximum activity in mid-August as Earth passes through debris left behind by Comet 109P/Swift-Tuttle.

The Perseids are popular because their meteors are fast, bright and often leave visible trails across the sky. Under genuinely dark conditions, observers can see dozens of meteors in an hour during the most active period. The exact number visible from any one place depends on cloud cover, moonlight, local light pollution and how long a viewer gives their eyes to adjust.

Texas has an advantage: large areas of the state remain far from major metropolitan light domes. Big Bend country is the obvious destination, but Enchanted Rock, Caprock Canyons and other state parks with dark-sky programs can also provide excellent viewing. Even outside a designated park, a safe rural location with a broad view of the sky can be dramatically better than a suburban backyard.

You do not need a telescope. In fact, binoculars and telescopes narrow the field of view too much for meteor watching. Find a dark place, give your eyes 20 to 30 minutes to adjust, lie back and look at as much sky as possible. Meteors can appear anywhere, even though their paths seem to trace back toward the constellation Perseus.

NASA identifies the Perseids as one of the most popular annual meteor showers, produced by small pieces of Swift-Tuttle burning high in Earth’s atmosphere. For Texans, the hardest part is often not knowing where to look but finding a clear, dark horizon in August. Check the forecast, avoid unnecessary phone light and give the sky time. The best meteor may arrive after everyone else has decided nothing is happening.'),
('2026-08-08-james-harden-gun-charge-dismissed','Viral','James Harden’s Houston Gun Charge Dismissed After Alternative Resolution Program','A Harris County judge dismissed the former Rockets star’s misdemeanor case after prosecutors said he completed an alternative resolution program.','Associated Press','https://apnews.com/article/ac857042ffc47105a616fa5853abc174','2026-08-08T17:42:00Z'::timestamptz,28,FALSE,'/images/news/generated/2026-08-08/james-harden-houston-case.svg','Illustration of a basketball and Houston courthouse representing the dismissal of James Harden''s misdemeanor gun case.','A Harris County judge has dismissed the misdemeanor gun charge filed against former Houston Rockets star James Harden, closing a case that began with a June traffic encounter in downtown Houston. Prosecutors asked for the dismissal after Harden completed an alternative resolution program.

Houston police arrested Harden on June 13 after officers found a handgun in plain view inside his vehicle. Texas law generally allows adults who may legally possess a firearm to carry a handgun in a vehicle, but an unholstered handgun cannot be displayed in plain view. The case was filed as a misdemeanor.

Court records did not publicly spell out every condition Harden completed. Harris County alternative-resolution programs can include requirements such as community service and are designed to resolve eligible cases without a traditional conviction when prosecutors determine that diversion is appropriate. Judge Alex Salgado approved the dismissal at the district attorney’s request.

The case drew outsized attention because Harden remains one of the most recognizable athletes associated with Houston. He won the NBA’s Most Valuable Player award while playing for the Rockets and spent the most productive stretch of his career in the city before playing for several other teams.

The dismissal means the June arrest will not result in a conviction on this charge. It also offers a useful reminder about Texas vehicle-carry rules: constitutional carry did not eliminate every restriction on how a handgun may be displayed or stored. The details of location, visibility and holster use can still matter. Harden’s case ended through a prosecutor-approved program, not through a ruling that the underlying law was invalid.'),
('2026-08-08-texas-reserve-officer-mexico-homicides','Viral','Texas Reserve Officer Arrested After Three Killings in Mexico During Custody Dispute','A reserve officer from Santa Anna, Texas, is jailed in Coahuila after Mexican authorities accused him of killing three people and critically wounding his former partner before fleeing with their child.','The Guardian','https://www.theguardian.com/us-news/2026/aug/07/chad-eberle-arrested-police-killings','2026-08-08T17:43:00Z'::timestamptz,32,TRUE,'/images/news/generated/2026-08-08/texas-officer-mexico-arrest.svg','Illustration of the Texas-Mexico border and police lights representing a cross-border homicide investigation.','A Texas reserve police officer is in custody in Mexico after authorities accused him of killing three people and critically wounding his former partner during a custody dispute in Saltillo, Coahuila. The case has drawn attention on both sides of the border because the suspect held a volunteer law-enforcement position in the small Central Texas city of Santa Anna.

Mexican authorities identified the suspect as 35-year-old Chad Eberle. Investigators allege that he traveled to Saltillo during a dispute involving his three-year-old son, opened fire on members of the child’s family and then fled with the boy. Three people were killed and the child’s mother was critically wounded, according to authorities cited by multiple news organizations.

Eberle was later taken into custody while attempting to return toward Texas through the Piedras Negras border area. The child was found unharmed and placed in protective care. Mexican authorities are pursuing charges that include femicide and aggravated or qualified homicide under Coahuila law.

Santa Anna officials confirmed that Eberle had served as an unpaid reserve officer and said he was on personal leave at the time of the alleged crimes. The city said it was coordinating with U.S. and Mexican authorities while declining to discuss details that could interfere with the investigation. Reporting also describes Eberle as a military veteran who previously worked in other Texas law-enforcement roles.

The allegations remain to be proven in court, and the legal process will proceed under Mexican law. The case is likely to generate additional scrutiny of how reserve officers are screened and supervised in small Texas departments, while also raising complicated cross-border questions involving custody, criminal jurisdiction and the treatment of a U.S. law-enforcement officer accused of violent crimes abroad.'),
('2026-08-08-whataburger-76-birthday-bogo','Viral','Whataburger Turns 76 Today With a Buy-One-Get-One Burger Deal','The Texas-born chain is marking its August 8 anniversary with an app-only BOGO Whataburger offer and a month of 76-cent specials.','Whataburger','https://stories.whataburger.com/press-room','2026-08-08T17:44:00Z'::timestamptz,26,FALSE,'/images/news/generated/2026-08-08/whataburger-76-birthday.svg','Illustration of a Texas burger stand with birthday decorations celebrating Whataburger''s 76th anniversary.','Whataburger turns 76 on August 8, and the Texas-born chain is celebrating with the kind of promotion almost guaranteed to crowd drive-through lanes: buy one Whataburger and get another free through the company’s app during the announced promotional window.

The anniversary traces back to August 8, 1950, when Harmon Dobson opened the first Whataburger on Ayers Street in Corpus Christi. His original idea was straightforward: build a hamburger large enough to require two hands and memorable enough to make customers say the restaurant’s name after the first bite. The small roadside stand eventually became one of the most recognizable food brands associated with Texas.

This year’s birthday promotion extends beyond a single day. Whataburger announced a month-long series of app-only offers built around the number 76, including selected menu items priced at 76 cents on Wednesdays. The August 8 centerpiece is the buy-one-get-one Whataburger offer.

The chain is now headquartered in San Antonio and has expanded well beyond Texas, operating more than 1,100 restaurants across 17 states according to company materials. Even with that national growth, its orange-and-white A-frame imagery, Fancy Ketchup and late-night dining culture remain strongly connected to Texas.

As with most app promotions, customers should check the offer terms before ordering, including the eligible hours, participating locations and account requirements. For Texans who treat Whataburger anniversaries as unofficial state holidays, today’s deal is less about saving the price of one burger than participating in a 76-year tradition that started in Corpus Christi.')
), prepared AS (
SELECT *, jsonb_build_object(
  'updated','2026-08-08',
  'intro',jsonb_build_array(split_part(body,E'\n\n',1)),
  'sections',jsonb_build_array(jsonb_build_object('heading','The story','paragraphs',jsonb_build_array(body))),
  'faq',jsonb_build_array(),
  'sources',jsonb_build_array(jsonb_build_object('label',source_name||' — original report','url',source_url)),
  'keyTakeaways',jsonb_build_array(dek)
) AS body_json FROM items
)
INSERT INTO public.daily_articles
(slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text)
SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text
FROM prepared
ON CONFLICT (slug) DO UPDATE SET
internal_url=EXCLUDED.internal_url,
is_ingested=EXCLUDED.is_ingested,
category=EXCLUDED.category,
title=EXCLUDED.title,
dek=EXCLUDED.dek,
source_name=EXCLUDED.source_name,
source_url=EXCLUDED.source_url,
published_at=EXCLUDED.published_at,
score=EXCLUDED.score,
is_breaking=EXCLUDED.is_breaking,
kind=EXCLUDED.kind,
body=EXCLUDED.body,
body_json=EXCLUDED.body_json,
featured_image_url=EXCLUDED.featured_image_url,
image_url=EXCLUDED.image_url,
image_alt_text=EXCLUDED.image_alt_text;
