-- Daily Texas news batch: five major Texas stories and five viral Texas stories.
-- Original Keep TX Red rewrites, deduplicated against existing published migrations.

WITH items(slug,category,title,dek,source_name,source_url,published_at,score,is_breaking,image_url,image_alt_text,body) AS (VALUES
('2026-08-08-tesla-fort-bend-solar-plant','Business','Tesla Weighs $10.1 Billion Solar Cell Plant in Fort Bend County','A state tax-incentive filing shows Tesla is considering a major solar manufacturing complex southwest of Houston that could create more than 1,000 construction jobs.','Houston Chronicle','https://www.houstonchronicle.com/business/article/tesla-musk-solar-fortbend-22379432.php','2026-08-08T21:30:00Z'::timestamptz,38,TRUE,'/images/news/generated/2026-08-08/tesla-fort-bend-solar-plant.svg','Texas solar manufacturing facility editorial illustration','Tesla is considering a $10.1 billion solar-cell manufacturing project in Fort Bend County, adding another potential piece to the advanced-manufacturing investment reshaping the Houston region. The proposal appears in a Texas tax-incentive filing and is not yet a final site commitment, but its scale would make it one of the largest industrial projects now under consideration in the state.

Tesla filed for property-tax relief under Texas'' Jobs, Energy, Technology and Innovation program for a site in Lamar Consolidated ISD. The company says construction would support about 1,150 jobs over three years, with operations targeted for 2029. Tesla also disclosed that it is evaluating at least one competing site, making the incentive process part of the location decision.

Fort Bend sits inside a fast-growing Houston-area industrial corridor with access to highways, ports, engineering talent and a large workforce. A solar-cell facility would broaden the region''s manufacturing base beyond petrochemicals and logistics while tying into Texas'' expanding technology and energy supply chains.

The project is still proposed, so the headline investment number should not be treated as money already committed. Texans should watch the final incentive package, the job and investment requirements attached to it, and how roads, utilities and schools would absorb a project of this scale. If Tesla chooses Fort Bend, the plant would reinforce Texas'' strategy of using tax policy and infrastructure to compete for capital-intensive manufacturing.'),
('2026-08-08-paxton-senate-campaign-pressure','Politics','Pressure Builds on Ken Paxton to Step Up Texas Senate Campaign','Republican allies are publicly questioning the GOP nominee''s campaign visibility as Democrat James Talarico presses a competitive statewide race.','Houston Chronicle','https://www.houstonchronicle.com/politics/texas-take/article/ken-paxton-working-hard-senate-talarico-22379162.php','2026-08-08T21:32:00Z'::timestamptz,36,TRUE,'/images/news/generated/2026-08-08/paxton-senate-campaign-pressure.svg','Texas Senate campaign editorial illustration','Texas Attorney General Ken Paxton is facing unusual public pressure from Republican voices to increase his campaign activity in the U.S. Senate race against Democrat James Talarico. The criticism matters because the contest is drawing national attention and recent polling has shown a race close enough to force both parties to treat Texas as competitive rather than automatic.

Conservative media figures and activists have questioned Paxton''s public visibility during a period when Talarico has been campaigning aggressively. Paxton has pushed back, saying he is working long days and that his campaign is accelerating after a bruising Republican primary season.

The seat could help determine control of the U.S. Senate, turning decisions about travel, advertising, debates and field organization into national political news. Republicans still benefit from Texas'' long statewide winning streak, but a close race would force the party to spend time and money it might otherwise deploy elsewhere.

Paxton''s task is to reunite Republican voters after a divisive nomination fight while keeping independents and suburban conservatives from drifting away. Talarico is trying to make the election a referendum on Paxton''s record while presenting himself as a credible statewide alternative. Watch for a heavier schedule of rallies, interviews, paid advertising and endorsements as the campaigns move into the fall turnout phase.'),
('2026-08-08-hormuz-oil-texas-energy-impact','Business','Hormuz Uncertainty Pushes Oil Higher, Putting Texas Energy Back in Focus','WTI rose as negotiations over reopening the Strait of Hormuz remained uncertain, a reminder that global shipping disruptions can quickly reach Texas producers, refiners and drivers.','Reuters','https://www.reuters.com/business/energy/oil-rises-concerns-over-strait-hormuz-reopening-plans-2026-08-07/','2026-08-08T21:34:00Z'::timestamptz,37,TRUE,'/images/news/generated/2026-08-08/hormuz-oil-texas-energy-impact.svg','Texas oil market and shipping editorial illustration','Oil prices moved higher as traders weighed whether the Strait of Hormuz can reopen reliably, putting a global security crisis directly back onto the Texas economic dashboard. West Texas Intermediate settled at $78.18 a barrel on Friday while Brent finished at $83.55, according to Reuters, as uncertainty persisted over shipping access and the terms of any arrangement involving Iran and Oman.

Texas is both a major oil-producing state and the center of the nation''s largest refining and petrochemical complex. Higher crude prices can improve cash flow for producers in the Permian Basin while raising feedstock costs for refiners and eventually putting upward pressure on fuel and transportation costs.

The immediate issue is not simply whether negotiators announce a deal. Traders are watching whether commercial vessels can move safely and consistently, what restrictions would apply and whether insurers and shipping companies consider the route usable. Each new attack or diplomatic setback can add a risk premium to crude.

Different Texans feel the move differently. Oil-field operators generally benefit from stronger prices, while consumers, airlines, trucking companies and other fuel-intensive businesses face higher costs. A sustained reopening could pull the risk premium back out of oil; continued disruption could keep global events at the center of Texas inflation, drilling budgets and gasoline prices.'),
('2026-08-08-somos-votantes-texas-latino-campaign','Politics','Progressive Group Commits $6 Million to Latino Voter Push in Texas','Somos Votantes is targeting statewide outreach and three South Texas congressional districts as both parties fight over a decisive bloc of Latino voters.','Associated Press','https://apnews.com/article/9b7d42755c9b8ab098e7c1caa522be0d','2026-08-08T21:36:00Z'::timestamptz,34,FALSE,'/images/news/generated/2026-08-08/somos-votantes-texas-latino-campaign.svg','South Texas voter outreach editorial illustration','A progressive organization is putting $6 million into a Texas campaign aimed at Latino voters, signaling how heavily national groups are investing in South Texas and other communities where voting patterns have shifted in recent elections. Somos Votantes says the effort will combine voter education with paid advertising intended to move voters toward Democratic candidates.

The plan includes roughly $2 million for statewide voter education and outreach and about $4 million in advertising through an affiliated political action committee. The paid effort is focused on three Republican-leaning congressional districts in South Texas, where narrow changes in turnout or persuasion could matter.

Latino voters are not a single ideological bloc, and recent elections have shown meaningful movement toward Republicans in parts of Texas. Democrats are trying to rebuild support by emphasizing household economics and community organizing, while Republicans are seeking to hold gains made on immigration, cultural issues and dissatisfaction with national Democrats.

South Texas has moved from being treated as safely Democratic to one of the country''s most closely watched political laboratories. Outside spending can buy television, digital ads and organizers, but it cannot guarantee turnout. The effectiveness of the campaign will depend on whether its messages fit local concerns and whether either party can turn political attention into votes in November.'),
('2026-08-08-texas-tax-free-weekend-2026','Texas News','Texas Tax-Free Weekend Is Underway: What Shoppers Can Buy Without Sales Tax','The annual back-to-school sales-tax holiday runs through Sunday, covering many clothing, footwear, backpacks and school supplies priced below $100.','MySA','https://www.mysanantonio.com/news/local/article/tax-free-weekend-texas-2026-22373312.php','2026-08-08T21:38:00Z'::timestamptz,31,FALSE,'/images/news/generated/2026-08-08/texas-tax-free-weekend-2026.svg','Texas tax-free weekend shopping editorial illustration','Texas'' annual sales-tax holiday is underway through Sunday, giving families a short window to buy many back-to-school items without state or local sales tax. The practical savings can reach 8.25% in communities that levy the maximum combined rate, making the weekend especially relevant for households buying clothes, shoes, backpacks and classroom supplies for multiple children.

Most clothing, footwear, school supplies and backpacks priced below $100 per item qualify. The exemption can apply to purchases made in stores and through eligible online or catalog orders placed during the holiday window, subject to the state''s pricing and transaction rules.

Computers, software, textbooks, jewelry, watches and many specialized athletic items do not qualify. Shoppers should also pay attention to shipping charges because added delivery costs can affect whether an item remains below the qualifying price threshold.

Back-to-school costs arrive all at once for many Texas families. The holiday does not erase those expenses, but removing sales tax from a large basket of qualifying purchases can produce a noticeable reduction. Shoppers should check the Texas Comptroller''s current eligibility list before a large purchase and keep receipts in case sales tax is charged incorrectly.'),
('2026-08-08-joes-truck-stop-bucees-trademark','Viral','Indie Musician Says Buc-ee''s Trademark Threat Turned a Joke Shirt Into a Bigger Fight','Joe Macheret says he stopped selling parody merchandise after a cease-and-desist letter, then went public as Buc-ee''s trademark tactics drew renewed national attention.','Chron','https://www.chron.com/culture/article/bucees-joes-truck-stop-letter-22377299.php','2026-08-08T21:40:00Z'::timestamptz,28,FALSE,'/images/news/generated/2026-08-08/joes-truck-stop-bucees-trademark.svg','Buc-ee''s trademark parody dispute editorial illustration','A touring country musician''s joke about Buc-ee''s has become the latest viral chapter in the Texas travel-center chain''s aggressive trademark protection. Joe Macheret, who performs as Joe''s Truck Stop, says Buc-ee''s sent him a cease-and-desist letter over parody shirts comparing his act to the chain and using altered beaver imagery.

Macheret says the shirt grew out of a fan joke and was sold as tour merchandise, not as branding for a competing convenience store. Buc-ee''s nevertheless argued that the design infringed its intellectual property and demanded that sales and promotional use stop.

The musician says he complied, stopped selling the merchandise and removed the disputed material. He later criticized the company publicly after comedian John Oliver brought national attention to Buc-ee''s history of trademark enforcement against smaller businesses.

The story is spreading because Buc-ee''s has a massive fan culture and because parody disputes invite a broader argument about corporate power, humor and brand protection. The legal question is narrower: trademark cases generally turn on issues such as likelihood of consumer confusion and the strength of protected marks, not simply whether a joke makes fun of a company.'),
('2026-08-08-dj-screw-day-houston','Viral','Houston Marks DJ Screw Day With Music, Cars and a Celebration of a Hometown Sound','Fans are gathering at the George R. Brown Convention Center for a day built around the influential Houston DJ''s music and cultural legacy.','Eventbrite','https://www.eventbrite.com/e/dj-screw-day-2026-tickets-1983796350286','2026-08-08T21:42:00Z'::timestamptz,26,FALSE,'/images/news/generated/2026-08-08/dj-screw-day-houston.svg','DJ Screw Day Houston editorial illustration','Houston is celebrating DJ Screw Day with a six-hour gathering at the George R. Brown Convention Center, bringing together music, cars, art and fans of the sound that helped define the city''s hip-hop identity. The event is designed as both a concert-style celebration and a tribute to Robert Earl Davis Jr., better known as DJ Screw.

DJ Screw''s slowed-down, tape-based style became inseparable from Houston rap and influenced artists far beyond Texas. His mixtapes documented a scene, a set of neighborhoods and a musical vocabulary that later reached national audiences.

Organizers are promoting live performances, DJ sets, special guests, art and custom-car culture. That combination reflects the broader Houston scene around Screw''s music rather than treating the day as a conventional concert.

The chopped-and-screwed sound has been sampled, imitated and referenced for decades. For Houston, however, Screw remains more than a production technique: his work is tied to the city''s cultural memory and to the rise of an independent music ecosystem that succeeded without waiting for coastal gatekeepers. That cross-generational legacy is why the tribute is spreading well beyond the people in the room.'),
('2026-08-08-harry-potter-drone-show-sugar-land','Viral','1,200 Drones Turn Sugar Land Sky Into a Harry Potter Show','Constellation Field is hosting an official Harry Potter drone production with synchronized lights, live music and familiar Wizarding World imagery.','Houston Chronicle','https://www.houstonchronicle.com/news/houston-texas/trending/article/harry-potter-drone-show-sugar-land-22377584.php','2026-08-08T21:44:00Z'::timestamptz,27,FALSE,'/images/news/generated/2026-08-08/harry-potter-drone-show-sugar-land.svg','Sugar Land Harry Potter drone show editorial illustration','The night sky over Sugar Land is becoming a giant screen this weekend as more than 1,200 synchronized drones recreate characters and scenes inspired by the Harry Potter films. The outdoor production at Constellation Field combines programmed aerial lights with a live electric violin performance built around music associated with the movies.

The drones launch in coordinated formations and assemble into large illuminated images above the ballpark. The show is designed around motion, scale and recognizable silhouettes rather than a traditional fireworks display.

Large drone productions can create detailed moving images while avoiding some of the smoke and debris associated with fireworks. The technology has become increasingly common at sporting events, holiday celebrations and branded entertainment productions.

The August 7 and 8 performances bring the touring concept to the Houston area, with themed merchandise and food adding to the franchise experience. Drone art is almost designed for short-form video: a recognizable shape materializing over a stadium gives attendees an immediate clip to share, helping the spectacle travel far beyond the ticketed audience.'),
('2026-08-08-ringling-houston-return','Viral','Ringling Is Back in Houston With a Reimagined, Animal-Free Circus','The Greatest Show on Earth is playing NRG Stadium through Sunday with acrobatics, stunts, music and a format rebuilt for a new generation.','Ringling Bros. and Barnum & Bailey','https://www.ringling.com/show/houston-tx-2026-nrg-stadium/','2026-08-08T21:46:00Z'::timestamptz,25,FALSE,'/images/news/generated/2026-08-08/ringling-houston-return.svg','Ringling Houston return editorial illustration','Ringling Bros. and Barnum & Bailey is back in Houston with a version of the circus that looks very different from the one many Texans remember. The production is playing NRG Stadium through Sunday and centers on human performers, acrobatics, stunts, comedy and music rather than animal acts.

Ringling returned after a multiyear shutdown with a redesigned show intended to keep the spectacle while leaving behind the animal-centered model that defined earlier generations. The Houston run is part of that national reinvention.

The production emphasizes high-wire skills, aerial performances, physical comedy and large-scale stunts. A music-driven pre-show and audience participation are also part of the current format.

The brand has deep nostalgia value for families who grew up attending arena circuses. Bringing it back to NRG gives parents and grandparents a chance to compare the new production with their own memories while introducing the name to children who never saw the older show. Multiple weekend performances are driving local family-event chatter and making the return one of Houston''s most visible live-entertainment stories.'),
('2026-08-08-bucees-texas-am-merch','Viral','Buc-ee''s and Texas A&M Put Two Texas Icons on the Same Shirt','The first co-branded merchandise from Buc-ee''s and Texas A&M is rolling out at selected travel centers and the university bookstore.','San Antonio Express-News','https://www.expressnews.com/news/texas/article/texas-am-university-buc-ees-co-branded-merch-line-22373344.php','2026-08-08T21:48:00Z'::timestamptz,26,FALSE,'/images/news/generated/2026-08-08/bucees-texas-am-merch.svg','Buc-ee''s and Texas A&M merchandise editorial illustration','Buc-ee''s and Texas A&M have launched their first co-branded merchandise, pairing two brands with unusually devoted Texas followings. The initial product is a T-shirt available at selected Buc-ee''s locations and the Texas A&M campus bookstore, with additional collaboration expected as the relationship develops.

Buc-ee''s founder Arch Aplin III is a Texas A&M alumnus, and the company already has a growing relationship with the university. Buc-ee''s products have been sold on campus, giving the school a direct retail connection to the travel-center brand.

The partnership is tied to broader work between the company and university, including hospitality, retail and marketing education. Aplin has made a major philanthropic commitment to Texas A&M, which is developing an academic center bearing his name.

Both brands inspire the kind of loyalty that turns ordinary merchandise into identity signaling. Combining the beaver with Aggie branding creates an obvious collector item for alumni, students and road-trip regulars. The first shirt appears to be an opening move rather than the entire collaboration, with additional co-branded merchandise expected as the partnership grows.')
), prepared AS (
 SELECT items.*,
   jsonb_build_object(
     'updated','2026-08-08',
     'intro',jsonb_build_array(body),
     'sections','[]'::jsonb,
     'faq','[]'::jsonb,
     'sources',jsonb_build_array(jsonb_build_object('label',source_name || ' — source report','url',source_url)),
     'keyTakeaways',jsonb_build_array(dek)
   ) AS body_json
 FROM items
)
INSERT INTO public.daily_articles
 (slug,internal_url,is_ingested,category,title,dek,source_name,source_url,published_at,score,is_breaking,kind,body,body_json,featured_image_url,image_url,image_alt_text)
SELECT slug,'/news/'||slug,FALSE,category,title,dek,source_name,source_url,published_at,score,is_breaking,'news',body,body_json,image_url,image_url,image_alt_text
FROM prepared
ON CONFLICT (slug) DO UPDATE SET
 internal_url=EXCLUDED.internal_url,is_ingested=EXCLUDED.is_ingested,category=EXCLUDED.category,title=EXCLUDED.title,dek=EXCLUDED.dek,
 source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,published_at=EXCLUDED.published_at,score=EXCLUDED.score,
 is_breaking=EXCLUDED.is_breaking,kind=EXCLUDED.kind,body=EXCLUDED.body,body_json=EXCLUDED.body_json,
 featured_image_url=EXCLUDED.featured_image_url,image_url=EXCLUDED.image_url,image_alt_text=EXCLUDED.image_alt_text;
