-- Activate the shared TexasDefined live-article channel on the KeepTXRed-owned
-- Supabase backend and prove the routed queue can publish a real article.
-- Idempotent: safe if the TexasDefined-side migration already ran.

ALTER TABLE public.texas_news_feed
  ADD COLUMN IF NOT EXISTS texasdefined_slug text;

CREATE TABLE IF NOT EXISTS public.texasdefined_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_feed_id bigint UNIQUE REFERENCES public.texas_news_feed(id) ON DELETE SET NULL,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  dek text NOT NULL,
  category text NOT NULL,
  region text,
  hero_url text NOT NULL,
  hero_alt text NOT NULL,
  author_id text NOT NULL DEFAULT 'a-hollis',
  published_at timestamptz NOT NULL DEFAULT now(),
  tags text[] NOT NULL DEFAULT '{}',
  body_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  related_collections text[] NOT NULL DEFAULT '{}',
  related_destinations text[] NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
  source_name text,
  source_url text,
  canonical_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_texasdefined_articles_status_published
  ON public.texasdefined_articles(status, published_at DESC);

CREATE OR REPLACE VIEW public.texasdefined_ready_queue AS
SELECT f.*
FROM public.texasdefined_story_queue f
WHERE f.texasdefined_slug IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.texasdefined_articles a WHERE a.source_feed_id = f.id
  );

CREATE OR REPLACE FUNCTION public.publish_texasdefined_queue_item(
  p_feed_id bigint,
  p_slug text,
  p_title text,
  p_dek text,
  p_category text,
  p_region text,
  p_hero_url text,
  p_hero_alt text,
  p_author_id text,
  p_tags text[],
  p_body_json jsonb,
  p_related_collections text[] DEFAULT '{}',
  p_related_destinations text[] DEFAULT '{}'
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_feed public.texas_news_feed%ROWTYPE;
BEGIN
  SELECT * INTO v_feed FROM public.texas_news_feed WHERE id = p_feed_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Feed item % not found', p_feed_id; END IF;
  IF v_feed.target_site IS DISTINCT FROM 'texasdefined' THEN
    RAISE EXCEPTION 'Feed item % is routed to %, not TexasDefined', p_feed_id, coalesce(v_feed.target_site,'unrouted');
  END IF;
  IF length(trim(coalesce(p_title,''))) < 20 OR length(trim(coalesce(p_dek,''))) < 80 THEN
    RAISE EXCEPTION 'TexasDefined article title/dek is too thin';
  END IF;
  IF jsonb_typeof(p_body_json) <> 'array' OR length(p_body_json::text) < 2500 THEN
    RAISE EXCEPTION 'TexasDefined article body is too thin';
  END IF;
  IF coalesce(p_hero_url,'') = '' OR coalesce(p_hero_alt,'') = '' THEN
    RAISE EXCEPTION 'TexasDefined article requires a hero image and alt text';
  END IF;

  INSERT INTO public.texasdefined_articles(
    source_feed_id,slug,title,dek,category,region,hero_url,hero_alt,author_id,
    tags,body_json,related_collections,related_destinations,status,source_name,
    source_url,canonical_url,published_at,updated_at
  ) VALUES (
    p_feed_id,p_slug,p_title,p_dek,p_category,nullif(p_region,''),p_hero_url,p_hero_alt,
    coalesce(nullif(p_author_id,''),'a-hollis'),coalesce(p_tags,'{}'),p_body_json,
    coalesce(p_related_collections,'{}'),coalesce(p_related_destinations,'{}'),'published',
    v_feed.source,v_feed.link,'https://texasdefined.com/news/'||p_slug,now(),now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    source_feed_id=excluded.source_feed_id,title=excluded.title,dek=excluded.dek,
    category=excluded.category,region=excluded.region,hero_url=excluded.hero_url,
    hero_alt=excluded.hero_alt,author_id=excluded.author_id,tags=excluded.tags,
    body_json=excluded.body_json,related_collections=excluded.related_collections,
    related_destinations=excluded.related_destinations,status='published',
    source_name=excluded.source_name,source_url=excluded.source_url,
    canonical_url=excluded.canonical_url,updated_at=now();

  UPDATE public.texas_news_feed SET texasdefined_slug = p_slug WHERE id = p_feed_id;
  RETURN p_slug;
END;
$$;

ALTER TABLE public.texasdefined_articles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS texasdefined_articles_public_read ON public.texasdefined_articles;
CREATE POLICY texasdefined_articles_public_read
ON public.texasdefined_articles FOR SELECT
USING (status = 'published');

GRANT SELECT ON public.texasdefined_articles TO anon, authenticated;
GRANT SELECT ON public.texasdefined_ready_queue TO authenticated;
REVOKE ALL ON FUNCTION public.publish_texasdefined_queue_item(bigint,text,text,text,text,text,text,text,text,text[],jsonb,text[],text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.publish_texasdefined_queue_item(bigint,text,text,text,text,text,text,text,text,text[],jsonb,text[],text[]) TO service_role;

DO $$
DECLARE
  v_feed_id bigint;
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.texasdefined_articles
    WHERE slug = '2026-08-10-canyon-lake-full-capacity-recovery'
      AND status = 'published'
  ) THEN
    RETURN;
  END IF;

  SELECT id INTO v_feed_id
  FROM public.texasdefined_ready_queue
  WHERE lower(coalesce(title,'')) LIKE '%canyon lake%'
     OR lower(coalesce(description,'')) LIKE '%canyon lake%'
  ORDER BY pub_date DESC NULLS LAST, id DESC
  LIMIT 1;

  IF v_feed_id IS NULL THEN
    RAISE NOTICE 'No routed Canyon Lake feed item is ready yet; channel is active but smoke article was not published.';
    RETURN;
  END IF;

  PERFORM public.publish_texasdefined_queue_item(
    v_feed_id,
    '2026-08-10-canyon-lake-full-capacity-recovery',
    'Canyon Lake Reaches Full Capacity After a Dramatic Summer Refill',
    'After starting July at roughly 61% full, Canyon Lake has held near full capacity since late July following mid-month storms that added about 157,000 acre-feet of water.',
    'lakes-rivers',
    'hill-country',
    'https://texasdefined.com/images/explore/lakes-rivers/guadalupe-river-state-park.jpg',
    'Clear Hill Country water along the Guadalupe River watershed in Central Texas',
    'a-hollis',
    ARRAY['Canyon Lake','Hill Country','Texas lakes','reservoirs','Guadalupe River'],
    jsonb_build_array(
      jsonb_build_object('type','paragraph','text',$p$Canyon Lake has reached a milestone that would have seemed distant at the beginning of July. The reservoir has held at full capacity since late July, its first sustained stretch at that level in nearly five years. The turnaround followed a sequence of mid-July storms that sent a large volume of water into the reservoir and changed the picture in a matter of weeks.$p$),
      jsonb_build_object('type','paragraph','text',$p$On July 7, Canyon Lake was reported at about 61% full. By the end of the month, the lake had climbed to full capacity. The storms added roughly 157,000 acre-feet of water, a volume large enough to make the recovery visible not just on a reservoir chart but around shorelines, ramps and coves that had spent years reflecting lower-water conditions.$p$),
      jsonb_build_object('type','heading','text','Why the refill stands out'),
      jsonb_build_object('type','paragraph','text',$p$Reservoir levels naturally rise and fall with rainfall, inflows, releases and water demand, but the speed of this rebound makes the summer change especially notable. A lake that began the month well below full moved through a major refill cycle in only a few weeks. For people who have watched Central Texas water levels through the recent dry years, the return to full pool is a striking marker of how quickly conditions can change when heavy rain falls in the right part of a watershed.$p$),
      jsonb_build_object('type','paragraph','text',$p$The number also matters beyond the simple satisfaction of seeing a lake marked “100%.” Canyon Lake is part of a larger Hill Country water system, and changes in storage affect the way residents, visitors and water managers think about the months ahead. Full capacity does not erase the effects of drought across the region, and it does not guarantee that every nearby river reach, access point or recreation area will have identical conditions. It does, however, provide a very different starting point than the one the lake had in early July.$p$),
      jsonb_build_object('type','heading','text','What visitors should keep in mind'),
      jsonb_build_object('type','paragraph','text',$p$People heading to Canyon Lake should still check current conditions before a trip. A full reservoir can bring its own operational changes, and local conditions may vary by park, boat ramp, shoreline area and downstream release schedule. Water levels can also move after storms as inflows taper and reservoir operations continue. The useful takeaway is that the lake has made an unusually strong recovery, not that every recreation or access question is automatically settled.$p$),
      jsonb_build_object('type','paragraph','text',$p$For Texas travelers, the refill is also a reminder that familiar destinations can look very different from one season to the next. A shoreline visited during a low-water year may now have water in places that had been dry for months or years. That can change views, paddling routes and the feel of a day on the lake. It is worth approaching the reservoir as it is now rather than relying on memories or photos from the recent drought period.$p$),
      jsonb_build_object('type','heading','text','A sharp reversal in one month'),
      jsonb_build_object('type','paragraph','text',$p$The most remarkable part of the story is the contrast: roughly 61% full on July 7, then full by late July after storms delivered about 157,000 acre-feet. Those figures capture one of the clearest examples this summer of how dramatically Texas water conditions can shift. Canyon Lake’s recovery does not end the need to watch rainfall, storage and releases, but it gives the Hill Country reservoir something it has not had for years — a sustained return to full capacity.$p$)
    ),
    ARRAY['hill-country-water'],
    ARRAY['canyon-lake']
  );
END;
$$;
