import { useEffect, useState } from "react";
import type { AdditionalCalculatorResult } from "@/types/calculators/additionalCalculator";

interface CalculatorScenarioActionsProps {
  calculatorKey: string;
  title: string;
  inputs: Record<string, number>;
  results: AdditionalCalculatorResult[];
  onLoad: (inputs: Record<string, number>) => void;
}

const storageKey = (calculatorKey: string) => `keeptxred:calculator:${calculatorKey}:scenario`;

function formatResult(result: AdditionalCalculatorResult) {
  if (result.type === "percent") return `${result.value.toFixed(result.decimals ?? 1)}%`;
  if (result.type === "currency") return result.value.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: result.decimals ?? 0 });
  return result.value.toLocaleString("en-US", { maximumFractionDigits: result.decimals ?? 2 });
}

export default function CalculatorScenarioActions({ calculatorKey, title, inputs, results, onLoad }: CalculatorScenarioActionsProps) {
  const [hasSaved, setHasSaved] = useState(false);
  const [message, setMessage] = useState("");

  useEffect(() => {
    setHasSaved(typeof window !== "undefined" && Boolean(window.localStorage.getItem(storageKey(calculatorKey))));
  }, [calculatorKey]);

  const save = () => {
    window.localStorage.setItem(storageKey(calculatorKey), JSON.stringify({ version: 1, savedAt: new Date().toISOString(), inputs }));
    setHasSaved(true);
    setMessage("Scenario saved on this device.");
  };

  const load = () => {
    const raw = window.localStorage.getItem(storageKey(calculatorKey));
    if (!raw) return;
    try {
      const saved = JSON.parse(raw) as { inputs?: Record<string, number> };
      if (saved.inputs) onLoad(saved.inputs);
      setMessage("Saved scenario loaded.");
    } catch {
      window.localStorage.removeItem(storageKey(calculatorKey));
      setHasSaved(false);
      setMessage("The saved scenario could not be read and was removed.");
    }
  };

  const copy = async () => {
    const text = [title, ...results.map((result) => `${result.label}: ${formatResult(result)}`), "Educational estimate generated by Keep TX Red."].join("\n");
    await navigator.clipboard.writeText(text);
    setMessage("Results copied without including your input values.");
  };

  return (
    <section className="mt-6 rounded-xl border bg-gray-50 p-4 print:hidden" aria-label="Scenario and result actions">
      <div className="flex flex-wrap gap-2">
        <button type="button" onClick={save} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold hover:bg-gray-100">Save on this device</button>
        <button type="button" onClick={load} disabled={!hasSaved} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-50">Load saved scenario</button>
        <button type="button" onClick={copy} disabled={!results.length} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold hover:bg-gray-100 disabled:opacity-50">Copy results</button>
        <button type="button" onClick={() => window.print()} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold hover:bg-gray-100">Print summary</button>
      </div>
      <p className="mt-3 text-xs text-gray-600">Saved scenarios stay in this browser. Input values are not added to the public URL or copied with the result summary.</p>
      {message ? <p role="status" className="mt-2 text-sm font-medium text-gray-800">{message}</p> : null}
    </section>
  );
}
